### ISSUE TITLE
C-level Spectrum1 contructor

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#100]
Quick question - it seems that when using the C-level `Spectrum1` constructor, there is not validity check. Is this correct? If so, it would be interesting to compare timings of this C-level constructor with and without checking the validity of the spectrum, and the call to `new("Spectrum1")`. 

Do you have any benchmarking data comparing `new` and your C-level constructor? Would be useful to have (in this issue, for example).

**Comment by jotsetung** [comment]
Yes, I did the benchmarking; I just have to dig out the numbers and will post.

**Comment by jotsetung** [comment]
The code for benchmarking is in the test_OnDiskMSnExp.R, ".compareCconstructorPerformance" function (should be at the very end).The timinigs below are from one of my test files with quite some MS1 spectra:

* With the `new("Spectrum1")` constructor (which is used in the `.applyFun2SpectraOfFileSlow` function):  24.2 seconds.
* With the C constructor creating a single Spectrum1 (which is used in the `.applyFun2SpectraOfFile`): 4.2 seconds.
* With the C constructor creating a list of Spectrum1 instances (i.e. does the for loop in C, `.applyFun2SpectraOfFileMulti`): 3.1 seconds.

**Comment by lgatto** [comment]
@jotsetung - and regarding validity?

**Comment by jotsetung** [comment]
That's a good point; the C-constructors don't do a validity check. As we discussed in Stanford it might be better to have a dedicated `validateOnDiskMSnExp` method that can be called by the user and that will do the validation on all spectra; this will take quite some time.

**Comment by lgatto** [comment]
Ok. Have marked this issue `enhancement`, so as to not forget to write the `validateOnDiskMSnExp` method. 

This however doesn't resolve the fact that the on-the-fly objects are not validated, which might not be a big problem as they are most of the time used transiently. Also, I think that it we create a unit test that test the validity of a couple of MS1 and MS2 spectra, we should be fine.

**Comment by jotsetung** [comment]
`validateOnDiskMSnExp` method is now included: https://github.com/lgatto/MSnbase/commit/5f6a9c39da5922edf4ca61e6996b330cf56a1ede

**Comment by lgatto** [comment]
> `validateOnDiskMSnExp` method is now included

Thanks - I would however suggest to make this a plain function, rather than having a generic and a single function. There won't ever be, at least in the foreseeable future any other method, warranting the extra OO complexity. I can do that now.

**Comment by jotsetung** [comment]
I've included now also a C-level constructor for `Spectrum2`. It's in commit https://github.com/lgatto/MSnbase/commit/abfe7c59a436cf7351f8b9643224569cdf67e856 . I have also added a unit test, but thus needs some more comparisons.

**Comment by lgatto** [comment]
Great, thanks. I have done a systematic comparison of `MSnExp` and `OnDiskMSnExp` accessors/methods in `tests/testthat/test_OnDiskMSnExp2.R` for MS2 data. A lot of these methods are actually exactly the same for the 2 classes, but I better safe than sorry.
