### ISSUE TITLE
TODO file

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#101]
Hi @jotsetung - would you mind pushing your TODO file (org-mode format is welcome, of course) to github, so that we can synchronise efforts.

**Comment by jotsetung** [comment]
It's already there: vignettes/NOTES.org but if we're going to remove the `OnDiskMSnExp` class in future and add the on-disk functionality for  `MSnExp` it is becoming obsolete.

**Comment by jotsetung** [comment]
Added the last TODOs.

**Comment by lgatto** [comment]
> if we're going to remove the OnDiskMSnExp class in future

That's not the immediate plan. First, I would like to keep both in parallel for at least one full release. In addition, keeping the in memory version, to be produced by `inMemory(.)` (discussed in #94) is useful to serialise the data. May be, in the longer term, we can get rid of it completely.
