### ISSUE TITLE
Spectrum on-the-fly construction

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#103]
Hi @jotsetung 

I am referring to this code chunk in `.applyFun2SpectraOfFileSlow` and the equivalent one in `applyFun2SpectraOfFile` and `.applyFun2SpectraOfFileMulti`

```r
      res <- lapply(split(fData[, c("fileIdx", "spIdx", "centroided", "acquisitionNum",
                                  "peaksCount", "totIonCurrent", "retentionTime",
                                  "polarity")], rownames(fData)),
                  FUN=function(z, theQ, fh, APPLYFUN){
                      ## Read the data.
                      spD <- mzR::peaks(fh, z[1, 2])
                      sp <- new("Spectrum1",
                                fromFile=z[1,1],
                                scanIndex=z[1, 2],
                                centroided=z[1,3],
                                acquisitionNum=z[1,4],
                                peaksCount=z[1,5],
                                tic=z[1,6],
                                rt=z[1,7],
                                polarity=z[1,8],
                                mz=spD[, 1],
                                intensity=spD[, 2])
```

It seems that you are extracting spectra based on the *spectrum index*, rather than *acquisition number*. I don't remember the difference between these two, but I don't think that are necessarily always the same. I am wondering if you shouldn't use the latter. It's at least the acquisition number that is used to match raw and identification data. 

Cc'ing @sgibb, who did check how exactly to match raw and id based on the mzIdentML specs and might know.

**Comment by lgatto** [comment]
Another question for @jotsetung:

In `.applyFun2SpectraOfFileMulti`, when `Spectrum1` is called to create the object (originally called `toReturn`, renamed `res` in the current code), it always returns a `list`. I don't understand why, as it seems as far as I have tested, that this code is executed when only a single spectrum is accessed.  Could you clarify - thanks.

**Comment by lgatto** [comment]
Bug is [here](https://github.com/lgatto/MSnbase/blob/master/R/methods-OnDiskMSnExp.R#L700-L741).

**Comment by jotsetung** [comment]
Related to the first issue: OK, I'll use acquisition num.

for `.applyFun2SpectraOfFileMulti`: that's a tricky one; it is supposed to apply a function to a single, or to multiple spectra. This depends essentially on the `fData` argument. If that one contains feature data for a single spectrum, then it will apply the function to a single spectrum, but in most instances it will be called on all spectra in a file (i.e. `fData` is then the full feature data `data.frame`). This function should be called via the `spectrapply` method, and that method does, using the `.subsetFeatureDataBy` function, a subsetting of the feature data.

Does this make sense?

**Comment by jotsetung** [comment]
We should consider adding some logic above, i.e. into the `spectrapply` method that ensures that a function is applied either only on ms level 1 or > 1.

**Comment by jotsetung** [comment]
Think I fixed the Spectrum2 on-the-fly construction with the latest commit; haven't tested due to the lack of an appropriate test file.

**Comment by sgibb** [comment]
As far as I remember the `aquisitionNum` is a general numeric ID generated by `mzR` from various vendor-specific IDs (see https://github.com/lgatto/msidmatching/issues/2#issuecomment-38047074 for the corresponding C++ code). In contrast the `spectrumID` is the number of the spectrum in the mzML/mzIdentML file. Often both IDs are identical but there is not any warranty that this is always the case. We decided to use the `aquisitionNum` for the matching because we assume that the order of spectra in the file could change (e.g. alphabetical vs. natural sorting) and that the corrected vendor-IDs are the most robust IDs.

**Comment by lgatto** [comment]
@jotsetung - for some data:

```r
library("RforProteomics")
url <- "http://proteome.sysbiol.cam.ac.uk/lgatto/files/Thermo-HELA-PRT/"
f1 <- downloadData(file.path(url, "Thermo_Hela_PRTC_1.mzML"))
```
or 
```r
library("rpx")
px <- PXDataset("PXD000001")
mzf <- pxget(px, pxfiles(px)[6])
```

**Comment by lgatto** [comment]
Thanks @sgibb

**Comment by lgatto** [comment]
> Think I fixed the Spectrum2 on-the-fly construction with the latest commit; haven't tested due to the lack of an appropriate test file.

Just had to fix a minor but, but works now, I think. Once we get a more functional version, I will add unit tests to compare `MSnExp` and `OnDiskMSnExp` for MS2 level.

**Comment by lgatto** [comment]
C-level constructor committed in abfe7c59a436cf7351f8b9643224569cdf67e856

**Comment by jotsetung** [comment]
Just changed the spectrum extraction method to use acquisition num instead of spectrum index (commit https://github.com/lgatto/MSnbase/commit/c1ebc93e0e6a7718a663087a06570ec2694cf09b).

**Comment by lgatto** [comment]
Thanks!
