### ISSUE TITLE
Update data in fData

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#105]
Some methods, such as `removePeaks`, `clean`, `trimMz`, ... modify data that is recorded in the `featureData` (for example `tic`, `peaksCount`). 

Need to check (and test) that the feature data is updated accordingly.

**Comment by jotsetung** [comment]
for the `peaksCount`, I've implemented that slightly different. If `removePeaks` is called the feature data is not altered. A call to `peaksCount` first checks in the `spectraProcessingQueue` if a `removePeaks` step is present, and if so, it applies it and returns the peak count after it. Thus, the `featureData` always contains the original peak count.

The advantage of this is, that it would allow to _undo_ a processing step by simply removing it from the processing queue. The disadvantage is that the `peaksCount` in the `featureData` and the values returned by the `featureCount` method can be different. Solution: rename `peaksCount` in the `featureData` to `originalPeakCount`?

Regarding the `tic`, I haven't seen any method that changes the `tic` thus far. Is there one?

**Comment by lgatto** [comment]
Ok, let me think about your `peaksCount` implementation a bit. May be your `originalPeakCount` suggestion is the best compromise, here; I have already done a few related updates to keep things consistent.

> Regarding the tic, I haven't seen any method that changes the tic thus far. Is there one?

Yes, if you call `removePeaks`, then tic changes. 
```r
> tic(sp)
[1] 512661.5
> tic(removePeaks(sp, t = 1e4))
[1] 358986.1
```

**Comment by lgatto** [comment]
Actually, it looks like to `totIonCurrent` in the header should be stored and renamed as you suggest, as it does not necessarily match the sum of intensities. Shall we go with `originalPeakCount` and `originalTotIonCurrent` in the head, and the `peakscount` and `tic` are calculated on the fly.

**Comment by jotsetung** [comment]
Yes, I think that would be great.

**Comment by lgatto** [comment]
TODO: update `tic` so that it applies any relevant processing in the `spectraProcessingQueue`.

**Comment by lgatto** [comment]
Update on `tic`. When reviewing the code, it seem that `tic` should indeed return `totIonCount`, which is in the `featureData` and that it is `ionCount` that sums all intensities. I will update accordingly, and revert `originalTotIonCurrent` to `totIonCurrent`.
