### ISSUE TITLE
Filtering when using the spectra accessor vs. dedicated MSnExp filters

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#106]
Hi @jotsetung - I am wondering if it is a good idea to have the `rtlim` argument to the `spectra` accessor for the following reasons

- Currently, you have implemented the `rtlim` and `scans` arguments/filters. There could also be `msLevel`, and possibly others, which would lead to a long list of arguments.
- `spectra` returns the spectra as a `list`; it is an accessor and shouldn't do anything else than accessing and returning the data.
- Given the 2 points above, I would prefer to do all the filtering and the `[OnDisk]MSnExp` level, and then access the spectra as a list.

My suggestion (as already alluded to in issue #94) would be to have dedicated filtering functions (not methods), for the most common filtering operations: 

- `filterMsLevel`
- `filterRt`
- No need to have a filter for the scan index, as that works directly with `[`
- `filterFile` (see #107)
- ...

**Comment by lgatto** [comment]
And, by the way, this would lend itself to some funky piping:
```r
x %>% filterFile("myfirsfile.mzML") %>%
      filterMsLevel(1) %>% 
      filterRt(c(30, 50)) 
```

**Comment by jotsetung** [comment]
I agree that long lists of arguments are not ideal. For performance reasons the filtering should however be done before extraction of the data. I see there two options:

* The approach that you suggest to have filtering methods that return an `[OnDisk]MSnExp`; this could lead to quite some long commands like `sub <- spectra(filterMz(filterRt(filterMsLevel(odmse, 1), rtlim = c(30, 50)), mzlim = c(300, 400)))`.

* A filtering like in `ensembldb`, i.e. have an argument `filter` in `spectra` which allows to pass one or more filters, e.g. a `MzFilter`, an `RtFilter` etc.

**Comment by lgatto** [comment]
Both options, i.e. individual functions or a single `filter` function with multiple arguments are fine by me. I would favour the option that results in the simplest code, and I suspect it would be the former. 

Regarding the `filterMz`, we could add a `minMz` and `maxMz` (these are actually called `lowMz` and `highMz` in the raw data header and feature data) to have a lazy and fast filter on M/Z.

**Comment by lgatto** [comment]
Now that I think about it, we would probably want a second argument to some of functions that specifies on what level to operate; something like
```r
filterMz(x, c(20,  50), msLevel = 1)
```
I still need to think about this issue of handling different  spectra independently.

**Comment by jotsetung** [comment]
Yes, individual filter methods would result in simpler code as it doesn't require additional classes etc. So, let's go for that.

I find a second argument (`msLevel`) to the `filterMz` method however a little counter intuitive. To be consistent it would be better to keep filter methods for individual arguments. The only reason I can see for such a method would be if you would like to have a `MSnExp` with M/Z filtered MS1 spectra and all unfiltered MS2 spectra; is this something that you would need for MSn data?

**Comment by lgatto** [comment]
> I find a second argument (msLevel) to the filterMz method however a little counter intuitive. To be consistent it would be better to keep filter methods for individual arguments. The only reason I can see for such a method would be if you would like to have a MSnExp with M/Z filtered MS1 spectra and all unfiltered MS2 spectra; is this something that you would need for MSn data?

The reason is that filtering MZ (and `removePeaks` would be another example) would probably require different outputs for different levels. The MZ range for MS1 and MS2 spectra is different anyway. 

I think it is a good thing to keep MS1 and MS>1 together, in one experiment. but this is probably going to come up again, which is why I think we need more time to think about it.

**Comment by jotsetung** [comment]
Makes sense. We could add then, as you suggest, add an `msLevel` parameter to (some? all?) filter functions and if it's not specified it will filter on all levels.

By the way: there will be two classes of filters: 

* The *immediate* filters: those that will just work on the `featureData` (subsetting by file, retention time, scan index, spectrum name etc). These can be applied directly and will be very fast. Part of the basic functionality is already implemented in the `.subsetFeatureDataBy` function.

* The *lazy* filters: such as `trimMz`: these will be added to the processing queue and only be executed on demand.

**Comment by lgatto** [comment]
See issue #114 for a discussion on how/when to set the MS level.
