### ISSUE TITLE
Clarify semantic of column subsetting in [,OnDiskMSnExp

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#107]
Hi @jotsetung - could you clarify the semantic here
```r
setMethod("[", signature(x="OnDiskMSnExp", i="logicalOrNumeric",
                         j="logicalOrNumeric", drop="missing"),
          function(x, i, j, drop){ ...
```
While there is a `pData`, the notion of sample is not defined at this stage. The data could have been acquired from a single sample (label-free) but also from multiple samples (multiplexing). I assume to use `j` subsetting for files, but I think this obscures the normal rows/columns semantics. 

This could be replaced by an ad hoc file filter, as discussed in #106.

**Comment by lgatto** [comment]
In addition, this leads to 
```r
>      subs <- odmse[rtime(odmse) >= 2 & rtime(odmse) <= 20, 1]
Error in validObject(x) (from methods-OnDiskMSnExp.R#344) : 
  invalid class “OnDiskMSnExp” object: Object is not 'onDisk'!
```
since I updated the validity, that requires the assay data to be empty.

**Comment by jotsetung** [comment]
Idea was to extract spectra by index (i) and file (j).

**Comment by lgatto** [comment]
But that's confusing. The `[i, j]` typically refers to rows (features) and columns (samples), which is not the case here. I suggest we use the `filterFile` function (discussed in issue #106) for that.
