### ISSUE TITLE
methods signature

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#109]
As an example, the `peaksCount` generic is defined in `mzR` as 
```r
setGeneric("peaksCount", function(object,scans,...) standardGeneric("peaksCount"))
```
I would suggest to only implement methods for `object = "OnDiskMSnExp", scans = "missing"` (and ignore `scans = "numeric"`). If only some peaks count needs to be computer, it seems more consistent to subset prior to calling the methods, like
```r
peaksCount(x[scans])
```

**Comment by lgatto** [comment]
Done in 08385eda905895e18b85b9232a668a0ecb307a2c.

**Comment by lgatto** [comment]
NB: I will keep the 2 in memory methods for now and might, as the one with numeric scans should be deprecated prior to defunct.

**Comment by lgatto** [comment]
And by the way, the performance is hardly different:
```r
> f <- proteomics(full = TRUE)[1]
> suppressMessages(xx <- MSnbase:::readMSData2(f))
> microbenchmark(suppressMessages(spectra(xx[1:2])), 
+                suppressMessages(spectra(xx, scans = 1:2)))
Unit: milliseconds
                                       expr      min       lq     mean   median
         suppressMessages(spectra(xx[1:2])) 187.1789 191.2811 200.8911 197.4171
 suppressMessages(spectra(xx, scans = 1:2)) 183.9336 186.9881 198.0007 192.6416
       uq      max neval
 203.5280 250.7263   100
 199.1815 256.3811   100
```

**Comment by jotsetung** [comment]
I just added some additional functionality to `peaksCount` that prevents the full data to be imported and peak counts being calculated if the data was not processed (returning the `originalPeaksCount` in that case).
Pushed in https://github.com/lgatto/MSnbase/commit/617c477c6dbe83f9e5c71e9da1129476915039ef

**Comment by lgatto** [comment]
Ok, thanks.

Regarding you comment here

```r
## @lgatto: I suppose we will do the subsetting all on the object itself, thus
## we don't need the subsetting code below, right?
## Sub-set the feature data based on the arguments.
+    fd <- .subsetFeatureDataBy(fData(object), index=index, scanIdx=scanIdx,
+                               name=name, rtlim=rtlim)
```
Indeed, I think we can remove this. Will do after pulling/merging.
