### ISSUE TITLE
Favour functions over generics/methods

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#111]
As mentioned in issue #100 regarding the `validateOnDiskMSnExp`, I would suggest we favour functions over generics/methods, at least in the first option. If we realise that we need multiple implementations, then the additional complexity is possibly worth the effort. 

Current candidates (which are note exported, by the way) are 
- `execute` (only 1 method for `OnDiskMSnExp`, although this verb is very generic, and if exported, could be made more specific)
- `processingQueue` (only 1 method for `OnDiskMSnExp`)
- `spectrapply`(only 1 method for `OnDiskMSnExp`)

I know that this comment also applies to quite a few methods that already exist in `MSnbase`, but the favour function over generic/method rule of thumb is something I learned with experience over time. Back in the `MSnbase` beginning, I systematically defined generics and methods when functions would have been a better, more lightweight solution.

**Comment by jotsetung** [comment]
I agree that functions would be more lightweight; an advantage would however be that the same-named method could have two different implementations, one for `MSnExp` and one for `OnDiskMSnExp`, so the methods could be developed independently and kept separate. 
For example, filter functions/methods for `MSnExp` would need to remove certain spectra from the `assayData` slot, while for `OnDiskMSnExp` only the `featureData` would be manipulated and, for the *lazy* methods, processing steps would be added.

**Comment by lgatto** [comment]
The situation you describe is exactly the one where methods are needed, such as all the filtering and processing methods and accessors, that need to work on `MSnExp` and `OnDiskMSnExp` objects (and, in some cases, on classes defined in other packages, such as `mzR` and, even more so in the future, `xcms`). 

The examples above are only applied to `OnDiskMSnExp`'s for now, and are not imported, and I can't see any immediate use case for any of them in `MSnExp` objects. If there were any in the future, it would be easy enough to update them to generics/methods. 

Anyway, it's not an urgent matter at this stage.
