### ISSUE TITLE
processingQuene and processingData

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#115]
The `processingData` slots stores a short summary of each processing step that is applied on the `MSnExp` object. The `processingQueue` stores processing step to be applied on the spectrum data when they are accessed. When an `OnDiskMSnExp` is converted to an `MSnExp`, the steps in the `processingQueue` will be transferred to the `processingData`. 

A few thoughts:
- It would be possible to undo lazy steps, while immediate step can't be undone. 
- It might be good to think about execution order and some heuristics to minimise the filtering/processing time.
- I also thought about the fact that repeating the processing steps could be a huge waste of time. In general, this repetition would only be done a few spectra, to explore and visualise the effect of the processing on the data, and that code could be implemented in C to minimise execution time. But I was wondering if we couldn't store processed spectra on disk (as an `rds` for example), or a SQLite database. I suppose the next step would be to have a `SQLiteMSnExp` class.

**Comment by jotsetung** [comment]
Yes, I agree. While it's nice to *undo* processing steps at some stage it would be better to actually apply them. For now I would however like to focus on the `OnDiskMSnExp` (or rather `MSnExpOnDisk`) object and evaluate its performance on actual analyses. The `MSnExpSQLite` is then the next logical step. I'm however wondering what would be better:

* A single SQLite database for one experiment.
* One SQLite database per mzML file.

At present the first option seems to be more promising.

**Comment by lgatto** [comment]
> For now I would however like to focus on the `OnDiskMSnExp` (or rather `MSnExpOnDisk`) object and evaluate its performance on actual analyses.

+1

> At present the first option seems to be more promising.

Yes, I think so too. But that's for later.
