### ISSUE TITLE
Bug is OnDiskMSnExp spetrum access

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#118]
@jotsetung - any idea? I will look into it asap, but you might have a clearer idea.

```r
> f <- msdata::proteomics(full=T)
> f
[1] "/home/lg390/R/x86_64-pc-linux-gnu-library/3.3rel/msdata/proteomics/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz"
> x <- MSnbase:::readMSData2(f)
Reading 509 spectra from file TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz
> x
Object of class "MSnExp" (on disk)
Object size in memory: 0.12 Mb
- - - Spectra data - - -
 MS level(s): 1 2 
 Number of spectra: 509 
 MSn retention times: 18:28 - 22:3 minutes
- - - Processing information - - -
Data loaded: Sun Jul  3 19:21:31 2016 
 MSnbase version: 1.21.8 
- - - Meta data  - - -
phenoData
  rowNames:
    TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz 
protocolData: none
featureData
  featureNames: X001.1 X002.1 ... X509.1 (509 total)
  fvarLabels: fileIdx spIdx ... spectrum (25 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
> x[[1]]
Read data from file TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz.
Index whichScan out of bounds [1 ... 509].
Error in Spectra1(peaksCount = nValues, scanIndex = ms1fd$spIdx, rt = ms1fd$retentionTime,  : 
  Arguments 'mz', 'intensity' and 'nvalues' are required!
```

**Comment by jotsetung** [comment]
I'll look into that tomorrow morning.

**Comment by lgatto** [comment]
I found what causes this error. I happens because the file I use, `msdata::proteomics(full.names = TRUE)`, is a subset of a full file. It contains acquisition numbers 1003 to 1511. But, when the peaks are extracted from the file, this is not taken into account:
```r
        allSpect <- mzR::peaks(fileh, msnfd$acquisitionNum)
```
and so calling `x[[1]]` tries to extract the 1003th spectrum, when there are only 509 in the file. The workaround is to do the following

```r
hd <- header(fileh)
k <- match(msnfd$acquisitionNum, hd$acquisitionNum)
allSpect <- mzR::peaks(fileh, k)
```
It is a shame to do this extra matching for this specific case, but we can't rule out something like this. I will commit this fix (and only this) as a commit so that we can more easily roll back if we can identify a better way.

**Comment by lgatto** [comment]
See commit e0dea901bba200afd4d0e65f1fc0a16f735bf6fa.

**Comment by jotsetung** [comment]
I suggest the following change to ensure that `acquisitionNum` is used as the primary ID but still there is no need to read also the header when spectra are loaded on the fly:
+ In `readMSData2`, sort the feature data (after adding the index of the spectrum in the file as column `spIdx`) by `acquisitionNum`. That way e.g. the 3rd row in the `featureData` corresponds to the 3rd measured spectrum, no matter what it's index in the mzML file is.
+ When the spectra are imported on the fly, the `spIdx` column is used. This corresponds to the index of the spectrum in the file.

@lgatto that OK with you?

I've pushed these changes in commit https://github.com/lgatto/MSnbase/commit/55c6415e09224f2dd173893513e8fa698f5a7023.

**Comment by lgatto** [comment]
How do you do the ordering when there are multiple files: by `spIdx` first, then by file number?

**Comment by jotsetung** [comment]
The ordering is done within the loop over the files, thus, the `data.frame` is ordered by `acquisitionNum` for each file and the `data.frame`s per file are then concatenated to the ultimate `featureData`. This would correspond to an ordering by `acquisitionNum` followed by an ordering by file number.

**Comment by lgatto** [comment]
Just to make sure I understand:
```
spIdx   fileNum ...
1       1
2       1
3       1
...
1       2
2       2
...
```

**Comment by jotsetung** [comment]
Correct; just that I'm sorting by `acquisitionNum`, so it could be something like:
```
spIdx    acquisitionNum    fileNum ...
2        1                 1
1        2                 1
3        3                 1
...
1        1001              2
2        1002              2
...
```
For file 1 the `acquisitionNum` is not completely identical to the order of the scans in the file (as described in issue #103). File 2 exemplifies this issue (i.e. the mzML file containing only a sub-set of scans, from 1001 to ...).

**Comment by jotsetung** [comment]
@lgatto actually, that's not correct. I've just seen that the feature data is sorted by the `fullhdorder` variable (which is in fact the `X001.1` etc, i.e. the feature names). Thus, features are in the order: first acquisition num in file 1, first acquisition num in file 2, second acquisition num in file 1 and so on (for two files).
In the end I don't think that's a problem, because what really counts is that `spIdx` (index in the file) and `acquisitionNum` match in the data frame.
