### ISSUE TITLE
Error in `readMSData`: `Error in is(x, "classRepresentation") : object 'tmp' not found`

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#119]
Seems to be related to both `MSnExp` and `OnDiskMSnExp`.
Will investigate.

**Comment by lgatto** [comment]
Could you check again, I think it was a misspelled var name in `isOnDisk`.

**Comment by jotsetung** [comment]
Yes, fixed that. in `isOnDisk` the variable was named `tmp`. Now `MSnExp` and `readMSData` works again, but I have a bug in `readMSData2`.

**Comment by jotsetung** [comment]
I get the following error in `readMSData2`:
```{r}
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘msLevel’ for signature ‘"NULL"’
```
after digging into the code I think I found the reason: when the `OnDiskMSnExp` object is created, R creates first its base class `pSet` and calls the `validity` method on this object and that's the problem:
the `isOnDisk` function returns always `FALSE` for that object (since the `pSet` class doesn't have a `spectraProcessingQueue` slot) and the `validity` call tries to check the validity of each spectrum in the `assayData` slot and throws an error.

Possible solutions:
* Add again the `onDisk` slot to the `pSet` class. Only a slot in the `pSet` will be considered/evaluated when the `validity` of the `pSet` is called (which is always done before the validity of the `OnDiskMSnExp`).
* Add an additional condition to the `pSet` validity.

I don't really like option 1, but I don't see an alternative (and I don't like option 2).
Any suggestions?

**Comment by jotsetung** [comment]
Actually, thinking it over, for option 1 above, it might make more sense to add a slot `backend` to the `pSet` class (with values `memory`, `disk` etc). This would keep us save for future implementations of the `MSnExpSQLite` class, for which we might want to have spectrum checks again.

**Comment by lgatto** [comment]
The error above can be fixed by changing 

```r
 if (!isOnDisk(object)) {
   ...
}
```
to
```r
 if (length(object)) {
  ...
```

I am not sure why at this stage the object is not yet an `OnDiskMSnExp` (it is an `MSnExp`) - the intricacies of initialisation are convoluted - but here we go. For now, let's use this as a fix. I am going to open an issue with your suggestion. I have to think about it a but more. The only thing that stops me for now is that it will break backwards compatibility (all `MSnExp` objects will become invalid as they miss that new slot).
