### ISSUE TITLE
Add backend slot to pSet

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#120]
Add a `backend` slot to `pSet`, defining if the object in `onDisk`, `inMemory` or, later, `SQL`, ... See issue #119 for some background.

**Comment by jotsetung** [comment]
I agree that such a slot is not ideal in the `pSet` as objects of this class shouldn't be aware that there is something like a on-disk or SQLite access.
Regarding the validity check in https://github.com/lgatto/MSnbase/issues/119 I'm fine with that.
