### ISSUE TITLE
Subset experimentData in filterFile?

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#122]
I was wondering if and how the `experimentData` should also be sub-setted in `filterFile`. In its present implementation it's not done and I think that might be a pretty tricky one (?).

**Comment by lgatto** [comment]
It looks like the order in which the metadata is added in `experimentData` is the same as the files, so I suppose it would be possible to selectively keep the correct information.

**Comment by jotsetung** [comment]
Yes, it's doable; it only affects slots `instrumentManufacturer`, `instrumentModel`, `ionSource`, `analyser` and `detectorType`, and these will contain only one value if the same instrument/setup was used in the different files. In that case there is no need to sub-setting the `experimentData` as far as I can see. 
It's different if different setups were used in the different files. In that case the values are concatenated with a `, `. Now, splitting by `, ` might be problematic, thus I suggest to use `| ` to collapse the different fields, so that it's easier to split and process them again. Any objections?

**Comment by lgatto** [comment]
Instead of pasting the data into a character of length 1, the info should probably be concatenated (keeping duplicates), so that it becomes straightforward to subset.

**Comment by jotsetung** [comment]
Agree, concatenating the instrument info would be great; if the `experimentData` supports that.
I didn't touch the code since my last commit; let me know if you did find time to start working/work on that issue; if you didn't find the time I'll go at this tomorrow morning. R-coding is relaxing while being in the train ;)

**Comment by lgatto** [comment]
Done in d3a1ec36a3d1608f35d4b97029aee35c44ff4535. 

I haven't updated the `filterFile` though - will leave it to you, as you have written the method.

**Comment by jotsetung** [comment]
Done in https://github.com/lgatto/MSnbase/commit/46447afab397b7797e4ea70e30d54268992ddd45
