### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#123]
- [ ] I think that, once we get closer to a stable code base, the documentation for `MSnExp` and `OnDiskMSnExp` should be merged, because (1) the APIs should be as close as possible, if not identical, and (2) it shouldn't really matter for the user which one they happen to use and migrating from on disk to in memory should be transparent. 
- [x] Prepare a benchmarking/timing vignette 
- [x] Update `MSnbase-demo` for `MSnbase2`
- [x] Update `MSnbase-devel` for `MSnbase2`

**Comment by jotsetung** [comment]
Suggestion: split the documentation into 3 files:
* *MSnExp-class.Rd*: just describe the class and the slots, no methods.
* *OnDiskMSnExp-class.Rd*: just describe the class/concept.
* *MSnExp-methods.Rd*: list all of the methods, eventually separated into sections *Accessor methods*, *Filtering and sub-setting* and *Analysis methods*.
