### ISSUE TITLE
precursorIntensity: re-calculate the value after e.g. normalization?

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#124]
I'm not at all familiar with MS2 data, so probably that's no problem at all... still:
The `precursorIntensity` method for `OnDiskMSnExp` does simply return the value from the `featureData`'s _precursorIntensity_ column (which was read from the mzML file header). Also for `MSnExp` objects it is not much different. But when e.g. a normalization or baseline adjustment is applied to MS1 data, the intensity of the precursor might also change; should this be calculated on the fly (if that's possible at all)?

**Comment by lgatto** [comment]
I suppose we could, but on the other hand, it's also useful to keep to original value. I don't think this is important for now, but we could consider a function `recalculatePrecursorIntensity` at some point.
