### ISSUE TITLE
Subsetting problem: subset to spectra present only in some (not all) files of an experiment

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#125]
Just stumbled over the following problem: I was sub-setting an `OnDiskMSnExp` by `filterAcquisitionNum` using acquisition numbers that are present only in one of the two files in the experiment.
```{r}
mzfiles <- c(system.file("microtofq/MM14.mzML", package = "msdata"),
                    system.file("microtofq/MM8.mzML", package = "msdata"))
onDisk <- readMSData2(files = mzf, msLevel = 1, centroided=TRUE,
                          verbose = FALSE)
filterAcquisitionNum(onDisk, n = 180:190)
```
this throws the error:
```{r}
Error in validObject(object) : 
  invalid class “OnDiskMSnExp” object: Spectra files in assayData does not match files in processinData.
```

In this case the specified acquisition numbers are only present in the second file, so only these are returned, while still two file names are reported etc. 
While this might only be a theoretical problem not arising in *real world* experiments I still would like to tackle it.

**Comment by lgatto** [comment]
Good point - I think `filterAcquisitionNum` should also have a `file` argument, then, to specify from which file to filter out. These numbers are relevant for a specific file only anyway.

**Comment by lgatto** [comment]
Actually, giving this a second thought, I am wondering if `filterAcquisitionNum` is really a function we need/want. In a multi-file experiment (which is really most real-life cases), or even single-file set-up, how relevant is this? When I do this, it is to create a small test data, but I have never done anything like that as part of a actual data analysis pipeline. And, in such cases, a simple `smallx <- x[fData(x)acquisitionNum > n & fData(x)acquisitionNum < m]` would work.

Or maybe, `filterAcquisitionNum` should only work for single-file `MSnExp`s?

**Comment by jotsetung** [comment]
I did now move the code from the `filterFile` method relevant to the eventual sub-setting of `phenoData`, `experimentData` and `processingData` to the `[` (where it also makes more sense). Now, however the `OnDiskMSnExp` is sub-setted, it will always ensure that e.g. `fromFile` does not point to a non-existing file or similar.
I'm just adding some more test cases and will push then.
Regarding the `filterAcquisitionNum` method, I added an optional argument `file`; for now I would like to keep the method, just in case we'll need it later (I think somewhere in `xcms` I've seen a case were data is sub-setted by spectrum index).

**Comment by jotsetung** [comment]
I've added the above described functionality to `[` of `OnDiskMSnExp` in commit https://github.com/lgatto/MSnbase/commit/8223c340bf210e255de3878b8b7521c38ad6f17c . Now, if you call e.g. `onDisk[1]` it will return an `OnDiskMSnExp` with a single spectrum and also a single file, ensuring that the pheno data and the `experimentData` matches that one file/spectrum.
Problem is it breaks now some tests with `MSnExp` since an `inMem[1]` returns a `MSnExp` with a single spectrum, but all files, all pheno data and all experiment data. Wanted to get your feedback on that before I start changing the `[` of the `MSnExp` too.

**Comment by lgatto** [comment]
Just to make sure I understand: when sub-setting by `[` (or ``[``, I assume), only the appropriate files, i.e. those the spectra/spectrum they originated from, will be kept. I think this is very nice indeed, as it keep the semantics valid. 

I will apply the same modifications I did to `readMSData2` to `readMSData`, so that the same behaviour can then be implemented for (in memory) `MSnExp`s.

**Comment by jotsetung** [comment]
Exactly, subsetting by `[` now ensures that just the `phenoData`, `experimentData` and `processingData` relevant to the spectra to which the data set was subsetted are included.

I did add the respective code to `readMSData` and to the `[` for `pSet` (commit https://github.com/lgatto/MSnbase/commit/35303bb6b0926fa32479650c8b9d9efd9d48a1bb ). Unit tests for `[` are in *test_OnDiskMSnExp.R*.
