### ISSUE TITLE
Centroided and smoothed setters

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#126]
Need to create `centroided` and `smoothed` setters for `OnDiskMSnExp` that take an `msLevel` argument.

**Comment by lgatto** [comment]
See 16d4b69e5e5abb38370455bdcf0e90ef4c2cd88c for `centroided<-`.

**Comment by lgatto** [comment]
@jotsetung - the `Spectrum` class doesn't define a `smoothed` slots, like it has a `centroided`. Is this something you would need?

**Comment by jotsetung** [comment]
Hm, haven't used the `smooth` method yet. If it has implications on other processing steps whether a spectrum was smoothed or not it might be good to have that info ready in a slot. If it's just for the user to know that smoothing was performed I think it would be enough to add that info into `@processing`.

**Comment by lgatto** [comment]
Ok, will add it and make sure all data remain valid.
