### ISSUE TITLE
Implement additional `OnDiskMSnExp` methods

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#127]
Implement (or just re-use where possible) the remaining methods for `OnDiskMSnExp`:
- [ ] `plot`
- [ ] `plot2d`
- [ ] `plotDensity`
- [ ] `plotMzDelta`
- [x] `trimMz` (`filterMz`) in commit https://github.com/lgatto/MSnbase/commit/cd503512d697a2b42f8468f8c773084cbfdbc2f7
- [x] `normalise, normalize`
- [x] `bin` in commit https://github.com/lgatto/MSnbase/commit/b961a6b82802ee4e6bfcaf0b9c08e9488fc2f826
- [x] `compareSpectra` in commit https://github.com/lgatto/MSnbase/commit/5f44eab4cbebda67761d2c3ae50dc25544676602
- [x] `pickPeaks` in commit https://github.com/lgatto/MSnbase/commit/076c1527d9c9b159014f471cfe9019f5bb68dcca
- [x] `estimateNoise` in commit https://github.com/lgatto/MSnbase/commit/076c1527d9c9b159014f471cfe9019f5bb68dcca
- [x] `smooth` in commit https://github.com/lgatto/MSnbase/commit/c00ac4054fe042c267bd021468d1703f0c498a71
- [x] `extractPrecSpectra` in commit https://github.com/lgatto/MSnbase/commit/de2a967c28d34791f9f7d20012a3221de8936a6d
- [x] `precursorMz`, `precursorIntensity`, `precursorCharge`, `precScanNum` in commit https://github.com/lgatto/MSnbase/commit/de2a967c28d34791f9f7d20012a3221de8936a6d

**Comment by lgatto** [comment]
See also #114. 

* Several of these will work out of the box because the extract spectrum information, such as `plot`, `plotMzDelta` (although this one should probably be rewritten to access the data at the C level).
* Others, such as `pickPeaks`, `smooth`, `normalise` ... will create an entry in the `spectraProcessingQueue` and will ultimately require a `inMemory` function.

**Comment by jotsetung** [comment]
`compareSpectra` for `OnDiskMSnExp` first loads all the spectra in memory and performs then the comparison. This might become quite memory demanding on large data sets, but the alternative (i.e. load the 2 spectra that will be compared from disk in each iteration) is really slow.
