### ISSUE TITLE
Rewrite plot method using base graphics

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#129]
- `plot(, type = "h")` _just_ works for centroided data
- `ggplot2` is nice to further customise the plot afterwards 
- Or, possible, have an option to defined which plotting system to use.

**Comment by yafeng** [comment]
Hi, @lgatto @sgibb  
The plot spectrum functions are really useful, but  I would like to have more plotting options to customize the pictures.
Using the current plotting function, i can already produce a nice figure! (attached here)

This is a typical mirror image of two experimental MS2 spectrum of same peptide, however one is endogenous, one is synthetic. Synthetic peptides are quite often used when one wants to validate their peptide identifications from certain biological samples.

[Peptide.MS2.mirrorImage.pdf](https://github.com/lgatto/MSnbase/files/415382/Peptide.MS2.mirrorImage.pdf)

Here is the command how i generated the figure.
plot(endopep_spectrum,synpep_spectrum,tolerance=0.02,relative=FALSE,
     sequences=c(peptide,peptide),modifications=c(M=15.995,C=57.021,Nterm=229.163, K=229.163),z=c(1,2))

To make the figure nicer, i want to do the following small changes.
draw all peaks in grey, color the peaks that can be annotated as b, y ions (b ions blue, y ions red if possible)
For matched peaks, can we adjust the size of circle? It looks a bit too big now :)

In the end, it seems not possible to pass neutralLoss options 
neutralLoss=defaultNeutralLoss(disableAmmoniaLoss=c("K", "R","N","Q"))
 to the plotting functions. Can it be fixed?

One last nice feature to have is 
precursor ions can also be annotated if found in MS2 spectrum.

**Comment by sgibb** [comment]
@yafeng Thanks for your feedback. I split your bug report/feature request into multiple issues to keep this one clean.

**Comment by yafeng** [comment]
@sgibb , thanks for the quick response!
