### ISSUE TITLE
precursorMz and extractPrecSpectra on mixed MS 1 and 2 objects

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#132]
`precursorMz` is only defined for `Spectrum2` objects and `extractPrecSpectra` does only work for MS2 only `MSnExp` objects.
I was wondering, wouldn't it be better that `precursorMz` returns `NA` for `Spectrum1` objects? That way, if `precursorMz` is called on a mixed MS 1 and 2 object it would return a (named) numeric vector with `NA` if the corresponding spectrum is of MS level 1, and the actual precursor MZ otherwise. Don't know if that would break code elsewhere...

**Comment by jotsetung** [comment]
Actually, I realized that this would apply to more methods:
`precScanNum`, `precursorCharge` `precursorIntensity`

**Comment by lgatto** [comment]
Yes, good idea for all `precursor*` methods.

**Comment by jotsetung** [comment]
Methods implemented for `OnDiskMSnExp`: commit https://github.com/lgatto/MSnbase/commit/de2a967c28d34791f9f7d20012a3221de8936a6d .

The methods throw and error if the `OnDiskMSnExp` object contains only MS1 spectra (just like the implementation for `MSnExp`), otherwise they return the actual values, with `NA` for eventually present MS1 spectra (in case it's a mixed MS1 MS2 `OnDiskMSnExp`).

I think we can close this issue if you are OK with that.

**Comment by lgatto** [comment]
Sure.
