### ISSUE TITLE
Returning empty spectrum when filterMz doesn't select any mz points  

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#134]
Currently, `filterMz` returns the spectrum as it was when no data points are within `minmz` and `maxmz`. I think it would be better to return an empty spectrum, or one with 0 intensity at  `minmz` and `maxmz`.

**Comment by lgatto** [comment]
Checking with @jotsetung that this is fine

**Comment by lgatto** [comment]
See 137f7d8bab27570d0c61fafa0e6abc5c88f679b0.

**Comment by jotsetung** [comment]
Agree
