### ISSUE TITLE
Use only public data for testing

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#140]
@jotsetung - some tests test for the `HOST` and conditionally use local data for testing. Could we either use publicly available data or add these or other adequate data be added to `msdata`?

**Comment by jotsetung** [comment]
They will be pretty large to be added to `msdata` and the tests would run very slowly. These were mostly to test performances and stuff. I could remove all these `HOST` tests and use only the files already in `msdata`.

**Comment by lgatto** [comment]
> I could remove all these `HOST` tests and use only the files already in `msdata`.

If the others don't are adequate, then yes, please. If you want additional local tests, put them in inst/scripts or add these test files in .gitignore.
