### ISSUE TITLE
Export execute processing steps function

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#141]
I would suggest to renames `execute` to something more specific (for exampe `executeProcessingSteps` or `processSteps`), document it in `ProcessingStep-class.Rd` and export it. That way, we will also get rid of the note that complains about using `MSnbase:::execute`.

**Comment by jotsetung** [comment]
Done in https://github.com/lgatto/MSnbase/commit/a556e6add2f192808a19d805cf767edf214b510e
