### ISSUE TITLE
Spectrum2 constructor throws an error if peaksCount is given

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#145]
Using the current master branch I get the following error when creating an `Spectrum2` object (maybe this is also true for `Spectrum` and `Spectrum1`):

MWE:
```r
new("Spectrum2", mz=1:5, intensity=1:5)
# Object of class "Spectrum2"
#  Precursor:  
#  Retention time: : 
#  Charge:  
#  MSn level: 2 
#  Peaks count: 5 
#  Total ion count: 15 

new("Spectrum2", mz=1:5, intensity=1:5, peaksCount=5L)
# Error in validObject(.Object) : 
#   invalid class “Spectrum2” object: Peaks count does not match up with number of MZ values.
```

**Comment by jotsetung** [comment]
I think this boils down to the same issue that causes some of the yet to be fixed problems in issue #138. My hottest guess is the `initialize` method from the `Spectrum` class.

**Comment by lgatto** [comment]
Yes, I'm working on this right now. But the problem is more troubling, as if occurs randomly when no `peaksCount` it provided...

**Comment by lgatto** [comment]
Done in 00cbb6e4fb56e51132be8880db245c06289075a1 and 464fc787a0af81c80d8dfdc90e754cb446b3b7ad.

**Comment by sgibb** [comment]
Sorry but I didn't follow the issue #138 because I thought it was only present in the MSnbase2 branch. Thanks for fixing it so quickly.
