### ISSUE TITLE
Don't use fix "cex" for points (matched peaks) in `.plotSingleSpectrum`

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#148]
cf. title; extracted from #129 

CC: @yafeng

**Comment by sgibb** [comment]
There is a bunch of arguments now:

- legend.cex
- fragments.cex
- peaks.cex
- peaks.pch
- peaks.lwd

All work as described in `?par` or `?plot.Spectrum.Spectrum`.

Not the prettiest example but it shows the new functionality:
```r
plot(msexp[[1]], msexp[[2]], 
     sequences=c("VESITARHGEVLQLRPK", "IDGQWVTHQWLKK"), 
     peaks.lwd=2, peaks.pch=18, peaks.cex=2, fragments.cex=2)
```
![rplot001](https://cloud.githubusercontent.com/assets/1828443/17630646/78aad09e-60c0-11e6-8107-a72f3d6d613d.png)

**Comment by yafeng** [comment]
@sgibb, thanks!  How do I update MSnbase to try this new feature?

**Comment by lgatto** [comment]
This will install the development version from github.
```r
library(devtools)
install_github("lgatto/MSnbase")
```
But, you might end into trouble. Ideally, you would also want to move the Bioconductor devel:
```r
library(BiocInstaller)
useDevel()
biocLite()
```
then the above.

**Comment by yafeng** [comment]
I tried the above command, which didn't work. Looked up on internet, added this command,  options(buildtools.check = function(action) TRUE ) . Now it works.
