### ISSUE TITLE
M/Z values are outside of lowMZ and highMZ.

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#153]
I am testing the latest `MSnbase` `master` branch and suddenly get 

```r
Error in validateOnDiskMSnExp(onDisk2) : 
  M/Z values of spectrum 2 are outside of lowMZ and highMZ.
```

This is very strange - @jotsetung, any idea if this could be related to some issue in your latest updates?

But I would suggest to change the following in `validateOnDiskMSnExp`

```r
       if (!(res[[i]][1] >= (fd$lowMZ[i] - mzTolerance) &
              res[[i]][2] <= (fd$highMZ[i] + mzTolerance)))
            stop("M/Z values of spectrum ", i, " are outside of ",
                 "lowMZ and highMZ.")
```

to use `base::all.equal(res[[i]][1], fd$lowMZ[i], tolerance = mzTolerance)` and `base::all.equal(res[[i]][2], fd$highMZ[i], tolerance = mzTolerance)`, because what we really want are those values to be equal, rather than being inside the low/high MZ values. Any comments?

**Comment by lgatto** [comment]
Note that I have changed that unit test to use 
```r
    onDisk2 <- multiMsOnDisk
```
rather than 
```r
    onDisk2 <- onDisk
```

I think the latter was an error, as it only contains MS1 data, and the last test, where MS2 were filtered, did not make sense. Having said that, I have added a new test to check the validity of empty `OnDiskMSnExp` objects (and fixed `validateOnDiskMSnExp` accordingly).

My questions above are still open.

**Comment by jotsetung** [comment]
@lgatto I'll check into this issue; could be that this is related to the recently introduced ordering of the `featureData` by `acquisitionNum` (although I believe it is unlikely). on what file did you test this, or in which unit test?

**Comment by lgatto** [comment]
Failing unit test is `test_OnDiskMSnExp.R`, first test. To reproduce

```r
library(msdata)
mzf <- c(system.file("microtofq/MM14.mzML", package = "msdata"),
         system.file("microtofq/MM8.mzML", package = "msdata"))
onDisk <- readMSData2(files = mzf, msLevel. = 1, centroided. = TRUE)
> validateOnDiskMSnExp(onDisk)
Error in validateOnDiskMSnExp(onDisk) (from functions-OnDiskMSnExp.R!265762K2#26) : 
  M/Z values of spectrum 2 are outside of lowMZ and highMZ.
```

**Comment by lgatto** [comment]
By the way, I just pushed some changes involving that and related files to `master`. Please pull first.

**Comment by jotsetung** [comment]
got it. the problem is the mzML file, not any changes in the code. the MM14.mzML file apparently lacks the highMZ and lowMZ values, as the fData has a 0.000 in these columns.
check `head(fData(onDisk))`.

**Comment by lgatto** [comment]
Ok, yes. What should we do in such cases? 
- Ignore this test with a waring when `lowMZ` and `highMZ` are 0?
- Update the `lowMZ` and `highMZ` when reading the data in?
- Leave it as invalid?

And what do you think of using `all.eqall`?

**Comment by jotsetung** [comment]
Reading the `lowMZ` and `highMZ`nfrom the data in such cases would be quite an overhead; the simplest solution would be to skip the test in such cases. but this depends whether these valies would be used at all, which I don't know. So, if `lowMZ` and `highMZ` are not urgently needed I woul opt to skip the testin these cases.

to the `all.equal`, yes, that would be better Than the comparison as it is now.

**Comment by lgatto** [comment]
Ok, will take care of it.

**Comment by lgatto** [comment]
Actually, the test for zero low and high MZ is already there

```r
        if (identical(fd$lowMZ[i], 0) & identical(fd$highMZ[i], 0)) {
            emptyMz <- TRUE
            next
        }
 [...]
    if (emptyMz)
        warning("Header value lowMZ and highMZ is 0 for one or more spectra.")
```
but somehow, the check later still failed and produced the error, and the warning was not thrown. Will make sure this works an commit.
