### ISSUE TITLE
Spectral counting question

### ISSUE THREAD

**Issue by Thys3Potgieter** [lgatto/MSnbase#156]
Hi,
Please excuse if this is not a bug!

Im assuming the number of psms in an msnid object should sum to the spectral counts at the peptide level?

Here is an example from my data that I find confusing:

> show(m)                                                                                              
MSnID object
Working directory: "."
#Spectrum Files:  16 
#PSMs: 7739191 at 0.22 % FDR
#peptides: 47758 at 1.6 % FDR
#accessions: 114904 at 4.3 % FDR
> ms <- as( m, "MSnSet")                                                                               
> rs <- rowSums(exprs(ms))    
> sum(rs)
[1] 327980

So summing the spectral counts across replicates for each peptide (rs) and summing the total counts (sum(rs)) does not give me a number that equals to the total number of PSMs.
If you can tell me what I am doing wrong I will be very greateful :)
Thanks
Thys

**Comment by lgatto** [comment]
It would probably be useful to see how `m` was created. Also, could you clarify what `dim(ms)` returns and show `head(exprs(ms))` - I am a bit confused about the mention of replicates and your calculation of `rowSums`. 

Cc'ing @vladpetyuk - he is the author of [`MSnID`](https://github.com/vladpetyuk/MSnID), (which would actually be the more relevant place to ask the question), but let's carry on here.

**Comment by vladpetyuk** [comment]
Not diving into details yet, but this mess is likely due to not-perfectly-solved (if solved at all) problem of peptide to protein assignment redundancy.  Double check that you are using MSnID version >= 1.7.3
See the difference for this version in the [NEWS file](https://github.com/Bioconductor-mirror/MSnID/blob/master/NEWS).
If this persists then we'll look further.

**Comment by Thys3Potgieter** [comment]
Thanks guys, I believe you have answered my question, I have an old version of MsnID. It does seem that a single PSM gets multiple entries in the psms(msnid) table in the case of peptides mapping to more than one protein, such that the accession column always contains only a single accession. I do believe that the show(msnid) PSM number may then not be the same as the total number of psm's obtained from spectral counting using MSnbase, and am satisfied as to why that is.

I include the details requested by Igatto but please don't worry too much about it,  as I still need to install the latest version of MsnID. Thanks guys!

> dim(ms)
[1] 47758    16

> head(exprs(ms))                                                                                                                                                                                           
                           150614_Diluted_Repeat_Dionex_QE_Andrew_AdultStool_FASP_AE_recalibrated.mgf
A.AAAAEEEKTEFDVILVEAGAGK.M                                                                          0
A.AAAGDNYQAVVLEK.S                                                                                  0
A.AAALQPGEALLLENLR.F                                                                                0
A.AAAYLGTVIGK.K                                                                                     0
A.AADLAAGSDAVILRHPESVK.T                                                                            0
A.AAEEKDEFDVELTEVGPNKVK.V                                                                           0
                           150614_Diluted_Repeat_Dionex_QE_Andrew_AdultStool_FASP_A_recalibrated.mgf
A.AAAAEEEKTEFDVILVEAGAGK.M                                                                         0
A.AAAGDNYQAVVLEK.S                                                                                 0
A.AAALQPGEALLLENLR.F                                                                               1
A.AAAYLGTVIGK.K                                                                                    0
A.AADLAAGSDAVILRHPESVK.T                                                                           0
A.AAEEKDEFDVELTEVGPNKVK.V                                                                          0
                           150614_Diluted_Repeat_Dionex_QE_Andrew_AdultStool_FASP_BE_recalibrated.mgf
A.AAAAEEEKTEFDVILVEAGAGK.M                                                                          0
A.AAAGDNYQAVVLEK.S                                                                                  0
A.AAALQPGEALLLENLR.F                                                                                0
A.AAAYLGTVIGK.K                                                                                     0
A.AADLAAGSDAVILRHPESVK.T                                                                            0
A.AAEEKDEFDVELTEVGPNKVK.V                                                                           0
                           150614_Diluted_Repeat_Dionex_QE_Andrew_AdultStool_FASP_B_recalibrated.mgf
A.AAAAEEEKTEFDVILVEAGAGK.M                                                                         0
A.AAAGDNYQAVVLEK.S                                                                                 0
A.AAALQPGEALLLENLR.F                                                                               0
A.AAAYLGTVIGK.K                                                                                    0
A.AADLAAGSDAVILRHPESVK.T                                                                           0
A.AAEEKDEFDVELTEVGPNKVK.V                                                                          0
                           150614_Diluted_Repeat_Dionex_QE_Andrew_AdultStool_FASP_CE_recalibrated.mgf
A.AAAAEEEKTEFDVILVEAGAGK.M                                                                          0
A.AAAGDNYQAVVLEK.S                                                                                  0
A.AAALQPGEALLLENLR.F                                                                                0
A.AAAYLGTVIGK.K                                                                                     0
A.AADLAAGSDAVILRHPESVK.T                                                                            0
A.AAEEKDEFDVELTEVGPNKVK.V                                                                           0
                           150614_Diluted_Repeat_Dionex_QE_Andrew_AdultStool_FASP_C_recalibrated.mgf
A.AAAAEEEKTEFDVILVEAGAGK.M                                                                         0
A.AAAGDNYQAVVLEK.S                                                                                 0
A.AAALQPGEALLLENLR.F                                                                               0
A.AAAYLGTVIGK.K                                                                                    0
A.AADLAAGSDAVILRHPESVK.T                                                                           0
A.AAEEKDEFDVELTEVGPNKVK.V                                                                          0
...

> head(rowSums(exprs(ms)))
A.AAAAEEEKTEFDVILVEAGAGK.M         A.AAAGDNYQAVVLEK.S 
                         5                          1 
      A.AAALQPGEALLLENLR.F            A.AAAYLGTVIGK.K 
                         1                          1 
  A.AADLAAGSDAVILRHPESVK.T  A.AAEEKDEFDVELTEVGPNKVK.V 
                         9                          3 
#then...I used the sum of all the counts for each peptide to get the total number of psms included in the spectral counts, I hope my reasoning is correct!

By replicates I meant sample results stored in separate mzIdentML files that were combined into a single msnid object for FDR control and spectral count analysis.

Kind regards
Thys

**Comment by lgatto** [comment]
Closing the issue for now, but @Thys3Potgieter, don't hesitate to open it again if the problem persists.
