### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#157]
As part of the `MSnbase2` testing, it would be interesting to benchmark SSD and hard-drive disk access.

**Comment by jotsetung** [comment]
Good idea; I have a SSD build-in, but no HD (except an external USB3 one). I could test there, since USB3 should also provide fast enough throughput - similar to SATA (?).

**Comment by lgatto** [comment]
I have SSD on my laptop, and planned to use a desktop in the lab for hard-drive. It's probably better to use the same computer, indeed. Feel free to add to the `benchmarking` vignette.

**Comment by jotsetung** [comment]
Just as an information since I started using the `OnDiskMSnExp` in one of our projects - reading the full data from 690 mzML files, each with 1720 spectra took 1236 seconds - not too bad I feel, it's size in memory is also only 235MB.
