### ISSUE TITLE
ion injection time feature extraction from mzML file

### ISSUE THREAD

**Issue by mchiapello** [lgatto/MSnbase#159]
Dear Laurent,
I'd like to ask for a new feature in MSnbase: 
Is it possible to add in "readMSData" function, to ability to read the ion injection time feature?

I used the following code for my analysis:

```r
# Library
library(MSnbase)
library("XML")

# Read raw data
Rep1 <- "/path/to/file/*.mzML"
rawdata <- readMSData(Rep1)

# Prepare xml file
doc <- xmlInternalTreeParse(Rep1)
namespaceDef <- getDefaultNamespace(doc)
ns <- c(x=namespaceDef[[1]]$uri)

# Read "ion injection time"
x2 <- xpathApply(doc, "//x:cvParam[@accession = 'MS:1000927']", namespaces = ns, xmlAttrs)

# Extract the values
xvals2 <- sapply(x2, "[", "value")

# Validity check
length(xvals2) == nrow(fData(rawdata))

# Add ion injection time to MSnExp object
fData(rawdata)$inj2 <- as.numeric(xvals2)
```

**Comment by lgatto** [comment]
There is a new `addInjectionTime` method. It is a bit more complex than the code above because it needs to handle `MSnExp` objects build from multiple files and with different MS levels.

**Comment by lgatto** [comment]
Form commit #7aab7fe79d26c4c0f1ff018a8a522b1fc0ef05d0, injection time is now added by default in `readMSData2`. (The method that added it has been removed)
