### ISSUE TITLE
Ordering based on acquisition number

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#160]
In `readMSData2`, there is a [line](https://github.com/lgatto/MSnbase/blob/master/R/readMSData2.R#L56) that reorders the spectra based on the acquisition number:
```r
        ## Order the fdData by acquisitionNum to force use of acquisitionNum
        ## as unique ID for the spectrum (issue #103). That way we can use
        ## the spIdx (is the index of the spectrum within the file) for
        ## subsetting and extracting.
        fdData <- fdData[order(fdData$acquisitionNum), ] ## not sure this is needed
```
@jotsetung - is this really needed? Are the spectra not always ordered by acquisition number? It checked the package after adding a test 
```r
stopifnot(all(sort(fdData$acquisitionNum) == dData$acquisitionNum))
```
and there were no errors with the files we use.

**Comment by jotsetung** [comment]
It is not needed if the header is always ordered by `acquisitionNum`; I didn't know and wanted to ensure that it is.
