### ISSUE TITLE
C-level constructor breaks RMassBank

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#163]
Emma reported the following error on the [bioc-devel mailing list](https://stat.ethz.ch/pipermail/bioc-devel/2016-October/009844.html).
```r
> new("RmbSpectrum2")
Error in initialize(value, ...) : 
  'initialize' method returned an object of class “Spectrum2” instead of
  the required class “RmbSpectrum2”
```
As discussed on the email thread, this seems to be the result of calling the C-level constructors in the `Spectrum2` (and `Spectrum1`) `initialize` methods. As a consequence, will probably revert back to the old `initialize,Spectrum` method.

**Comment by jotsetung** [comment]
First run of tests went OK:
```{r}
library(MSnbase)
library(msdata)
mzf <- c(system.file("microtofq/MM14.mzML", package = "msdata"),
         system.file("microtofq/MM8.mzML", package = "msdata"))
f <- msdata::proteomics(full.names = TRUE, pattern = "TMT_Erwinia")

## readMSData2
for (i in 1:7500) {
    if (i %% 200 == 0)
        cat(i, "\n")
    res <- readMSData2(f, verbose = FALSE)
    sp <- spectra(res)
    sp <- res[[12]]
    res <- readMSData2(mzf, verbose = FALSE)
    sp <- spectra(res)
    sp <- res[[12]]
}
```
Next I'll check the `readMSData`.

**Comment by lgatto** [comment]
Would you mind using both files in
```r
f <- msdata::proteomics(full.names = TRUE)
```
The new one has MS1, 2, and 3 spectra.

**Comment by jotsetung** [comment]
No, not again!
With 
```{r}
library(MSnbase)
library(msdata)
f <- msdata::proteomics(full.names = TRUE, pattern = "TMT_Erwinia")
## readMSData
for (i in 1:10000) {
    if (i %% 200 == 0)
        cat(i, "\n")
    res <- readMSData(f)
    sp <- spectra(res)
    sp <- res[[12]]
}
```
I get agani randomly:
```{r}
Reading 451 MS2 spectra from file TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz
  |============================================================          |  86%Error in (function (x)  : attempt to apply non-function
  |======================================================================| 100%
Creating 'MSnExp' object
```

I'll try again `readMSData2` on the new test file.

**Comment by jotsetung** [comment]
OK, I found a workaround:
I've removed the `contains = "Versioned"` from `Spectrum` along with the `prototype(new("Versioned")...` from `Spectrum`, `Spectrum1` and `Spectrum2` as well and it runs without errors - strange indeed.

I also run the `readMSData2` with the two test files you suggested and it run without errors.

**Comment by lgatto** [comment]
But we need the versions - see `R/methods-updateObjectTo.R`

**Comment by jotsetung** [comment]
Agree, it's just strange that this solves these random errors

**Comment by lgatto** [comment]
Do you the `Spectrum1`/`Spectrum2` classes in `xcms3`? If so, do you use them directly or do you create other classes that contain them (as in the example at the origin of this issue)?

I would be compelled to use the C constructor in `MSnbase`, because we can't really ship code that fails so often, and I doubt we will figure out what happens any time soon. I would then submit a patch to `RMassBank` that basically copies the relevant code from `Spectrum2` into `RmbSpectrum2`, getting rid of the `contains = "Spectrum2"`.  This would be fine because, as far as I see, they don't rely on any methods.

**Comment by jotsetung** [comment]
No, I don't use `Spectrum1` classes yet in `xcms3`.

I also prefer the C-constructors, but I would really like to know what's going on there. I'll try some more stuff, e.g. removing the `new` calls in the `prototype` as Kasper suggested, but I'm afraid that that won't help.

**Comment by lgatto** [comment]
In an email, you mentioned positive results with moving `new("Versioned, ...)` out of the prototype into `initialize` (it would really be fantastic if that was the culprit). Could you push this, so that we can sort out `RMassBank` without patches.

**Comment by jotsetung** [comment]
Yes I will, just want to run more tests on that.
A problem that comes along with this is that the C-constructors lack the version information as the prototype does no longer set the version. I'll have to add that to the C-constructor.

**Comment by lgatto** [comment]
I suggest we create a variable in `.MSnbaseEnv` where we document the class versions (`MSnExpVersion`, `OnDiskMSnExpVersion`, `Spectrum1Version`, ...) and then re-use these in the various `initialize`/constructors. Do you want me to do that, or is it just easier for you to do it?

**Comment by jotsetung** [comment]
I would prefer you do that; you've got the better overview  over all classes. In the meantime I'll try also a different approach; let's hope that that works as it would be much easier (no hacks in C).

**Comment by jotsetung** [comment]
The alternative approach didn't work; I thought bypassing the `new("Versioned")` call in `prototype` with a direct assignment of `new("Versions")` to the `.__classVersion__` slot would do it... unfortunately not.

So, it will be the C-hack. The tracking of class versions in `.MSnbaseEnv` would then really help there.

**Comment by lgatto** [comment]
> So, it will be the C-hack. The tracking of class versions in .MSnbaseEnv would then really help there.

Versions in `.MSnbaseEnv` is not that different from versions hard-coded in the class definitions. We must just remember to change them.

It's not only a C-level hack. We also need to set them in the R-level constructors. May be it's worth updating the validity method of all classes to make sure the `.__classVersion__` has a proper version (i.e. is not whatever a default/empty `Versioned` slot it). Do you want me to take care of this?

**Comment by jotsetung** [comment]
Yes, that would be great. Can you then push the changes as soon as you have the `.MSnbaseEnv` in place? I'll grab then the version numbers from there and pass them down to C.

**Comment by lgatto** [comment]
Will have to pickup my F1 from school soon, but will get started tonight.

**Comment by lgatto** [comment]
Things do become a bit messy - defining the version in the `initialize` method when this one is long can be tricky. I have started to do so (see `MSnProcess` and `MIAPE` classes and new code at the top of `environment.R` for details, especially the latter to grep the class version numbers).

**Comment by lgatto** [comment]
I don't think we can check in the `validity` method for a version number, because the prototype and/or a call to any `callNextMethod` won't be valid. I might have to drop this check in the validity.

**Comment by jotsetung** [comment]
It depends when the `validity` method is called, I guess after all `initialize` methods are called. In that case it should be OK, because we're setting the `classVersion` in the `initialize` methods.

**Comment by lgatto** [comment]
But, from R Programming for Bioinformatics (R Gentleman):
> [...] validity is checked when the default initialize method is *called*; so if there is a user-defined initialize method that does not call `callNextMethod`, then validity will not be checked.

As in the [example of `NAnnotatedDataFrame`](https://github.com/lgatto/MSnbase/blob/master/R/methods-NAnnotatedDataFrame.R#L3-L9), which depends on `AnnotatedDataFrame`, I have to `callNextMethod`, which in turn throws the error that my object-to-be doesn't have a class version.

**Comment by lgatto** [comment]
But, once set in the `initialize` methods, the class version will be present. I don't think it is a huge issue not to test it in the validity (or at least in some cases, where validity can't be met).

**Comment by jotsetung** [comment]
Agree.

**Comment by lgatto** [comment]
There are now many unexpected side effects and errors that creep up since I did this last change. I am going to revert back, setting the version in the prototype (I don't want to break everything now), and proceed with setting the version in the `initialize` where is doesn't lead to a cascade of new issues.

**Comment by jotsetung** [comment]
That's strange. I'll add it to the `initialize` of `Spectrum1`, `Spectrum2` and `Spectrum`. There it worked nicely. I'm now adding some more unit tests to ensure that also the C-constructors return the correct versions and then I'll push the changes.

**Comment by lgatto** [comment]
I'm on it. Yes, spectra classes are the most important, and they don't rely on any other classes.

**Comment by lgatto** [comment]
Just pushed

**Comment by jotsetung** [comment]
I've pushed now the fixes for `Spectrum1` and `Spectrum2` setting class versions in the C-level constructors and in their `initialize` methods. Still, `R CMD check` produces lots of errors now, but they seem to be unrelated to my changes. 
@lgatto are you on them? 

I'm running the torture tests on the new code. I'll update once that's done.

**Comment by lgatto** [comment]
These errors are completely crazy - I get one complaining about `[,MSnSet`. What I will do is revert back all versions to the prototype except for `Spectrum` and that it from there.

**Comment by lgatto** [comment]
One error was in `.versionToNum`
```r
> odmse[[1]]
Error in strsplit(z, split = ".", fixed = TRUE) : non-character argument
Calls: [[ ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```
Changing it to 
```r
.versionToNum <- function(z) z@.Data
```
seems to fix it. Moving on to others...

**Comment by lgatto** [comment]
Quite a few errors because
```r
> classVersion(aa[[1]])
Spectrum2  Spectrum 
  "0.3.0"   "0.4.0" 
> classVersion(msx[[1]])
 Spectrum Spectrum2 
  "0.4.0"   "0.2.0" 
```

**Comment by jotsetung** [comment]
Ah, sorry. The `.versionToNum` was my fault. Yes, the ordering of the version; I thought calling `classVersion(.Object)` in the `initialize` *before* `callNectMethod` results always in the ordering `Spectrum1`, `Spectrum` or `Spectrum2`,`Spectrum`.

**Comment by lgatto** [comment]
> I thought calling `classVersion(.Object)` in the initialize before `callNextMethod` results always in the ordering `Spectrum1`, `Spectrum` or `Spectrum2`, `Spectrum`.

I would have thought so too, but after some testing, it doesn't look like it. I now set both `Spectrum` and `Spectrum[1|2]` in `initialize,Spectrum[1|2]` in the right order.

**Comment by lgatto** [comment]
I think we not opened a whole new can of worms:
```r
> classVersion("Spectrum1")
[1] "Versioned; no version string"
```
which breaks `updateObject`.

**Comment by jotsetung** [comment]
I didn't knew that `classVersion` can be called on a class name, I always thought it is called on class instances:
```{r}
> classVersion(new("Spectrum1"))
Spectrum1  Spectrum 
  "0.3.0"   "0.4.0" 
```
It would make more sense to me, although in the `classVersion` man page it is described differently - but we know that that man page also described using `new("Versioned")` in the `prototype` which apparently is not a good thing to do...

**Comment by lgatto** [comment]
The only way out I see now it to replace `expect_identical` by `expect_equivalent` in out using tests, to ignore attributes (i.e. class versions, but I don't know what else is ignored!)

**Comment by lgatto** [comment]
Actually, easiest is no to bump class version number - pathetic, but that's what I am going to do now :-(

**Comment by lgatto** [comment]
@jotsetung - there's a problem with C-level constructed class versions 
```r
> f <- msdata::proteomics(full.names = TRUE, pattern = "TMT_Erwinia_1")
> inmem2 <- readMSData(f, centroided = NA, verbose = FALSE)  ## That's the MS 2 data.
> ondisk2 <- readMSData2(f, msLevel = 2, verbose = FALSE)
> all.equal(inmem2[[1]], ondisk2[[1]])
[1] "Attributes: < Component “.__classVersion__”: Names: 2 string mismatches >"                     
[2] "Attributes: < Component “.__classVersion__”: Component 1: Modes: numeric, list >"              
[3] "Attributes: < Component “.__classVersion__”: Component 1: Lengths: 3, 1 >"                     
[4] "Attributes: < Component “.__classVersion__”: Component 1: target is numeric, current is list >"
[5] "Attributes: < Component “.__classVersion__”: Component 2: Modes: numeric, list >"              
[6] "Attributes: < Component “.__classVersion__”: Component 2: Lengths: 3, 1 >"                     
[7] "Attributes: < Component “.__classVersion__”: Component 2: target is numeric, current is list >"
> classVersion(inmem2[[1]])
 Spectrum Spectrum2 
  "0.4.0"   "0.2.0" 
> classVersion(ondisk2[[1]])
   Spectrum2     Spectrum 
"c(0, 2, 0)" "c(0, 4, 0)" 
```
Could you have a look?

**Comment by jotsetung** [comment]
Fixed in https://github.com/lgatto/MSnbase/commit/cc9ee4e1079328c037bc5df2f31c12eb0acd105b.

**Comment by lgatto** [comment]
Checking package now - hoping to be able to close soon. Where all your torture tests positive?

**Comment by jotsetung** [comment]
Torture tests look good. they are at iteration 3000 for `readMSData` and `readMSData2` and no problem thus far.

**Comment by lgatto** [comment]
I have added a `inst/scripts/torture. R` script based on your code above 79372e8dc1e84d7cdad5d5f2a0124b6449b1a8ee

**Comment by jotsetung** [comment]
well, I still get one error in the `test_updateObjects.R`; this must be related to the one you reported on the Bioc-devel I guess.

**Comment by lgatto** [comment]
Yes - I will comment that unit test for now and document this in a new issue, so that we can tackle it if/when we hear back for the Bioc experts.

**Comment by jotsetung** [comment]
Just an update on the torture test:
+ No error in 10,000 iterations for the `readMSData2`.
+ No error in 10,000 iterations for the `readMSData`.

**Comment by lgatto** [comment]
And yet... 
![2016-10-12-212639_744x795_scrot](https://cloud.githubusercontent.com/assets/384198/19326477/97dce5f6-90c2-11e6-8167-de7dc82b58c6.png)
Today's (2016-10-12) [check report](https://bioconductor.org/checkResults/3.4/bioc-LATEST/MSnbase/malbec1-checksrc.html)

**Comment by jotsetung** [comment]
Well, that calls for more torture tests... I'll run some more.

**Comment by lgatto** [comment]
At least, it seems that the errors are becoming much rarer. It might also be dependent on the environment - I can imaging the Bioc servers being heavily loaded during these checks.

**Comment by lgatto** [comment]
Have you seen this [error report](https://stat.ethz.ch/pipermail/bioc-devel/2016-October/009893.html) in unit tests:

```
I get an error that is coming from either xcms::xcmsSet or xcms::group, see
the bottom of the message for full error.

-------------------------------------------------------------------------------------------------------------
Error in signalCondition(e) :
  no function to return from, jumping to top level
Calls: <Anonymous> -> .handleSimpleError -> h -> signalCondition
-------------------------------------------------------------------------------------------------------------
```
Looks familiar! The package doesn't depend on `MSnbase` though, but on `mzR`.

**Comment by jotsetung** [comment]
well, yes. `mzR` seems to be quite problematic; also because we had to call `gc` after closing the filehandles in `mzR`, otherwise we got these strange random errors. I spent a week in August trying to tackle the problem in `mzR`(most likely somewhere in the C-code) but couldn't find anything. Eventually we'll find the problem someday...
