### ISSUE TITLE
Add a bpc,MSnExp and bpc,OnDiskMSnExp method

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#168]
Would be nice to have, along with the `tic` method, also a `bpc` method that extracts the _base peak chromatogram_ from an `MSnExp` and `OnDiskMSnExp`, i.e. the maximum intensity from each spectrum.

If you would agree I could implement that.

**Comment by lgatto** [comment]
Do you mean a method that extract the `basePeakIntensity` feature data? Note that this data isn't available from (in memory) `MSnExp` objects (i.e. in the `Spectrum1`/`Spectrum2` objects). It would need to be calculated on the fly, and I wouldn't be surprised if they didn't match `fData` values, or would not be after some processing. We already had this discussion, I think, of such data that would not be correct after some processing, and agreed to rename it as *original* or *initial*.

**Comment by jotsetung** [comment]
I guess yes, extract the `basePeakIntensity` feature data - haven't looked at that yet. That might however be like the `totIonCurrent` feature data, that represents the _raw_ data from the MS-machine and does not match - at least for our files - the value of the centroided mzML file.

I didn't check the `chromatogram` method yet, eventually that does what I want. In the end would be nice to have some method to extract `sum` or `max` of intensities of a spectrum. 
Actually, thinking it over an implementation of the `chromatogram` method might be it, with a parameter `type` that can be either `"tic"` or `"bpc"` and eventually a logical parameter `initial` to specify whether the values should be extracted from the feature data.

**Comment by lgatto** [comment]
> I guess yes, extract the `basePeakIntensity` feature data - haven't looked at that yet. That might however be like the `totIonCurrent` feature data, that represents the raw data from the MS-machine and does not match - at least for our files - the value of the centroided mzML file.

Yes, same situation - I'm fine with having a `bpi,OnDiskMSnExp` method that returns that feature data, and document that these are the values are reported in the raw data. Not sure if we need `bpi,MSnExp`, that iterates over all spectra. If so, then we could have a parameter in `bpi,OnDiskMSnExp` that forces to recalculate the values. What do you think?

> I didn't check the `chromatogram` method yet

There's also `xic`, for extracted ion chromatograms.

`chromatogram` and `xic` would be very easy to implement for `OnDiskMSnExp`, as they operate on an `mzRramp` object, that we can create (and close) from `fileNames(.)`.

> In the end would be nice to have some method to extract sum or max of intensities of a spectrum. 

Could you clarify what you mean? The max or sum of all intensities in a spectrum? That would be easy to add - something along the lines of 

- `quantify(sp, method = "max")` would return `max(intensity(sp))`
- `quantify(sp, method = "sum")` would return `sum(intensity(sp))`

(There's already a `method = "sum" with `reporters` defined)

**Comment by jotsetung** [comment]
Done. The `bpi` method has an additional parameter `initial` that, when `TRUE` returns the values extracted from the mzML header and when `FALSE` calculates it from the actual data. I have modified the `tic,OnDiskMSnExp` method the same way (i.e. parameter `initial`) and modified the documentation accordingly.
