### ISSUE TITLE
Add a method to extract the intensity and mz pairs

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#169]
I was thinking of adding a method `intensityMzPair` for `OnDiskMSnExp` and `MSnExp` objects to return a `list` of two-columns matrices with the intensity-mz duplets. This might be useful specifically for `OnDiskMSnExp` where separate calls to `intensity` and `mz` would require the data to be read twice, while on the other hand calling `spectra,OnDiskMSnExp` first and then extracting the corresponding data with `lapply` and `intensity`, `mz` is in my opinion too cumbersome (and more memory demanding).

@lgatto what you think?

**Comment by lgatto** [comment]
There is `as(sp, "data.frame")`. So it would be more along the lines of `lapply(spectra(x), as, "data,frame"). Is the operation you suggest one that is expected to be heavily used? Then, a specific function that goes straight at the C level could be useful, indeed.

I am wondering if it wouldn't be interesting to have a `msapply` function. It would make the above shorter (`msapply(x, as, "data,frame")) and would make it more natural to iterate on all spectra. To iterate along all MS level 2 spectra, we would get `msapply(filterMsLevel(x, 2), ...)`.

**Comment by jotsetung** [comment]
I'll check the `as(sp, "data.frame")`, that might do it indeed. An implementation in `C` or one that bypasses the `Spectrum` generation might indeed be faster, but that way we can no longer use the lazy processing queue, so that's a no-go for `OnDiskMSnExp`.

Yep, the `msapply` might be an interesting one, I've already implemented an `spectrapply` function for `OnDiskMSnExp` that does exactly that - iterates over all spectra. Actually, every `OnDiskMSnExp` method requiring the spectrum data uses this function (also the `spectra` method).

**Comment by lgatto** [comment]
Ah, yes, `spectrapply` had slipped of my mind. It is not exported; may be it should? I would then suggest to implement one for (in memory) `MSnSet` objects too.

**Comment by jotsetung** [comment]
OK, I'll export it and implement it for `MSnExp`/`pSet`.

**Comment by jotsetung** [comment]
Done
