### ISSUE TITLE
Creating Spectrum2 objects is slower than it was in MSnbase1

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#171]
While running the new `synpater2` pipeline we recognized a speed reduction in creating in-memory `Spectrum2` objects. This is a huge problem for creating >100000 spectra (which took ages but is now at least 2x slower). Please find a MWE that compares `master` against `48950cc5`. E.g. creating 1000 spectra takes nearly 8 seconds on my laptop (4 seconds in MSnbase1):
```bash
# in your shell
git branch 1.21.8 48950cc5
```
```r
install_github("sgibb/benchgit") 
# It changes branches automatically and
# runs each function multiple times.
# No random execution order, no prewarming etc. supported.
library("benchgit")

createSpectra <- function(n) {
l <- lapply(1:n, function(x) {
  new("Spectrum2",
      precScanNum=1L,
      precursorMz=1000,
      precursorIntensity=500,
      precursorCharge=2L,
      rt=120,
      centroided=TRUE,
      peaksCount=10,
      mz=1:10,
      intensity=1:10,
      fromFile=1L)
})}

N <- 1e3

benchgit(createSpectra(N), packagePath=".",
         branches=c("master", "1.21.8"), replications=3)

#        elapsed    avg relative
# 1.21.8  17.432 3.4864     1.00
# master  39.583 7.9166     2.27
```
The relative time difference is independent of the number of spectra generated.

**Comment by jotsetung** [comment]
As far as I know we didn't change too much of `Spectrum2` related code, apart from the new `initialize` method that sets the class version. I also realized that spectrum generation using `new` is quite slow - I thought it's mainly due to validity checks etc.
If you want a speedup of the spectrum creation you could try the `MSnbase:::Spectrum2_mz_sorted` constructor function that creates the `Spectrum2` directly in C. I'm using that one in `OnDiskMSnExp`.

**Comment by lgatto** [comment]
The real drawback of this C-level constructor is that it doesn't validate the `Spectrum` objects. As the spectra created as part of the new `synapter` are (or can be) special compared to spectra extracted from mzML/mzXML files, I would suggest to run a few tests and systematically check their validity to start with.

**Comment by sgibb** [comment]
@jotsetung `MSnbase:::Spectrum2_mz_sorted` is indeed faster (same setting as above 0.2 seconds (vs. 4 and 8)). Even if I call `validObject` on each spectrum manually it is finished after 1 second.
Are there any caveats beside the missing validity checks mentioned by @lgatto ?

@lgatto Is the following enough verify the spectra?
```r
lapply(stupidPlgsSpectrumXmlData, function(x) { 
  # do crazy conversion
  # ...
  s <- MSnbase:::Spectrum2_mz_sorted(...)
  if (validObject(s)) {
    s
  }
})
```

BTW: there is no validity method for `MSnExp` objects. Is that intended?

**Comment by lgatto** [comment]
>  Are there any caveats beside the missing validity checks mentioned by @lgatto ?

Not that I can think of. This is really motivated by the new -on-disk implementation of the `MSnExp` class, called `OnDiskMSnExp`. They have the same API, but are much faster and small (see `benchmarking` vignette), support multiple MS levels, ... and will eventually be used in proteomics and metabolomics. 

> Is the following enough verify the spectra?

Yes, that is how I would do it. If you use fast/on-disk `MSnExp`s, that use the C-level spectrum constructor on the fly, then there's a `validateOnDiskMSnExp` that will that (among other things).

> BTW: there is no validity method for MSnExp objects. Is that intended?

There should be one for the super class `pSet`.

**Comment by jotsetung** [comment]
The returned spectra are the same, and I perform a lot of input parameter checking in R - should be save to use it - it even sets the version correctly.

**Comment by sgibb** [comment]
@lgatto I can't use `OnDiskMSnExp` because I don't want to convert the crazy spectrum.xml files and fragment.csv into mzML files. 

@jotsetung thanks, great work!
