### ISSUE TITLE
netCDF support?

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#173]
I'm now including support for `OnDiskMSnExp` and `MSnExp` into `xcms`. The plan is that raw data is loaded and represented by these classes which enables to perform some initial data inspection, quality control, filtering etc. Users can then call `detectFeatures` method to identify peaks in chromatographic space (results are thus far returned as `xcmsSet` objects but I'll implement an other result object later). `xcms` has also *netCDF* support and it would be crucial to bring that also to `MSnbase`. I would thus implement the corresponding functionality to the `readMSData` and `readMSData2` functions (shouldn't be too difficult since `mzR` supports netCDF - we might just miss some data here and there). I'll do that in a *playgroung*  branch.

**Comment by lgatto** [comment]
Unless the branch is already created, could you rather call it `netCDF`, please.

I think netCDF support for `readMSData` and in-memory `MSnSet`s is not essential. While I don't think they will be dropped any time soon, on-disk is the preferred route.

**Comment by jotsetung** [comment]
ah, sorry - did already create it. think we can it delete anyway afterwards

**Comment by jotsetung** [comment]
ah, sorry - did already create it. think we can it delete anyway afterwards

**Comment by jotsetung** [comment]
Looks good - @lgatto could you eventually check if your'e OK with the changes and if so, merge with the master branch?

**Comment by jotsetung** [comment]
Just merged *master* into *playground*, so the only difference now should be the check whether the file to be read is a CDF file (based on file ending), and if so, use the `"netCDF"` backend from `mzR`. Also, some header information can not be extracted from CDF files, thus I had to ensure that they don't cause an error when the `Spectrum` objects are created.

**Comment by lgatto** [comment]
I just pulled locally at run a check. There are no warning/errors, but the checking takes 30 minutes! It probably too more than the expected 5 minutes in the past, but 30 is a bit of a stretch. I haven't has time yet to investigate; do you have an idea, is it netCDF related?

**Comment by jotsetung** [comment]
That's strange - eventually you could try to remove the `test_that("readMSData and readMSData2 reading CDF", {` in the *test_readMSData2.R* file - indeed, reading the spectra from the CDF takes some time, but only around 30 seconds on my computer.

**Comment by lgatto** [comment]
Will try later, as soon as I have time.

**Comment by lgatto** [comment]
Now down to 13 minutes. High but more in line with what I anticipated. My computer was probably playing silly last night.

As a general rule, it would be good to try to keep an eye on the checking times.

Going to merge into `master` - closing now.

**Comment by jotsetung** [comment]
@lgatto could you eventually commit to BioC svn too? I need netCDF support in xcms (3).

**Comment by lgatto** [comment]
done
