### ISSUE TITLE
travis build fails

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#175]
I fixed some dependencies on travis. Now all build dependencies build successfully. But building `MSnbase` fails with the following error:
```
Quitting from lines 188-193 (benchmarking.Rmd) 
Error: processing vignette 'benchmarking.Rmd' failed with diagnostics:
setting worker timeout:
  error reading from connection
Execution halted
```
https://travis-ci.org/lgatto/MSnbase/builds/183582212#L6627-L6631

Removing `benchmarking.Rmd` results in
```
Quitting from lines 903-910 (MSnbase-demo.Rnw) 
Error: processing vignette 'MSnbase-demo.Rnw' failed with diagnostics:
setting worker timeout:
  error reading from connection
Execution halted
```

Both chunks contain `quantify` calls but I don't think that is the reason for the error.

Any other ideas?

**Comment by lgatto** [comment]
Everything builds/checks fine locally. I guess it might be something related to parallel code on the travis server.

**Comment by jotsetung** [comment]
I sometimes get these messages on my mac too - eventually you could try:
```{r}
options(bphost = "localhost")
library(BiocParallel)
register(MulticoreParam())
```
or alternatively use `SnowParam` by default - I don't know what the default on linux machines is.

**Comment by lgatto** [comment]
Or just use `SerialParams()`, but I would prefer to first see if we can't address it on the travis side.

**Comment by sgibb** [comment]
@lgatto Should we ask the r-travis folks about the parallel problem? Is there a environment variable we could use to use `SerialParams()` on travis and `MulticoreParams()` everywhere else?

BTW: sry for removing the texlive packages, I thought all of these packages where present in texlive-extra-font etc. (but ubuntu 12.04 is very old ...)

**Comment by lgatto** [comment]
I haven't had time to follow up, but yes, I think we need to check with r-travis folks. Please, go ahead if you have time.

**Comment by lgatto** [comment]
See https://github.com/travis-ci/travis-ci/issues/7052

**Comment by lgatto** [comment]
It's a miracle, it builds!

Important config to avoid timeouts:

```script: 
  - | 
    R CMD build .
    travis_wait 30 R CMD check MSnbase*tar.gz
```
and
```
after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
```
But using serial processing. See [this issue](https://github.com/travis-ci/travis-ci/issues/7052).

**Comment by sgibb** [comment]
travis claims that MSnbase could be build successfully (we get a green badge) but in fact it fails with exactly the same error, e.g. https://travis-ci.org/lgatto/MSnbase/builds/200311060
```
$ R CMD build .
travis_wait 30 R CMD check MSnbase*tar.gz
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘MSnbase’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... ERROR
Quitting from lines 187-192 (benchmarking.Rmd) 
Error: processing vignette 'benchmarking.Rmd' failed with diagnostics:
setting worker timeout:
  error reading from connection

Execution halted

Still running (1 of 30): R CMD check MSnbase*tar.gz

The command R CMD check MSnbase*tar.gz exited with 0.
```
The script should not exit with exit code `0`

**Comment by lgatto** [comment]
I have cleaned the cache and restart a build - let's see how it goes.

**Comment by sgibb** [comment]
@lgatto did you close this issue intentionally? While showing a green badge and returning exit code 0, travis still fails to build *MSnbase* with exactly the same error as above: https://travis-ci.org/lgatto/MSnbase/builds/224609389
```
Quitting from lines 187-192 (benchmarking.Rmd) 
Error: processing vignette 'benchmarking.Rmd' failed with diagnostics:
setting worker timeout:
  error reading from connection
```

**Comment by lgatto** [comment]
This works again now. Just for the record, it only works with `dist:precise`, otherwise building R runs out of time.
