### ISSUE TITLE
Vignettes format

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#176]
@sgibb @jotsetung - I am wondering if it's not worth switching to Rmd/html using the new `BiocStyle::html_document2` style. Any thoughts?

**Comment by jotsetung** [comment]
I would very much like to switch to the new format. Also using the floating toc.

**Comment by lgatto** [comment]
I have converted all but the big `MSnbase-demo` vignette. Hope to tackle that one at some point. Closing for now.
