### ISSUE TITLE
New XCMSnSet slot [was: Proposed change to validity method of pSet]

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#177]
I'm going to extend the `OnDiskMSnExp` object in `xcms` (`XCMSnExp` object) to represent results from a feature detection and alignment in a metabolomics workflow. I've planned to put all the data into the `assayData` slot since that's empty for `OnDiskMSnExp` objects anyway - the problem is that the validity from the `pSet` class starts checking its content once something is put into the `assayData` resulting in all sorts of error messages.

My suggestion would be to amend the `if (length(object)) {` to `if (length(ls(object@assayData, pattern = "^X"))) {`.

@lgatto any thoughts/concerns?

**Comment by lgatto** [comment]
What are you going to store in the `assayData`?

I don't really like your suggestion, but I'm not sure mine is better, but here I go. What about having `validateAssayData` methods that are called within `validObject`. 
- The default `pSet` method just returns `TRUE`.
- The `MSnExp` method does all the current checking. 
- The `OnDiskMSnExp` method again returns `TRUE`.
- The `XCMSnExp` method does whatever it needs to.

Would this work?

**Comment by jotsetung** [comment]
That's going to work perfectly! Like it. Going to hack right away.

**Comment by jotsetung** [comment]
Heck - doesn't work. `OnDiskMSnExp` extends `MSnExp` directly, thus, the validity method on `OnDiskMSnExp` calls first the validity method from `MSnExp` which checks all spectra in `assayData`. No way that `validObject,OnDiskMSnExp` does not call `validObject,MSnExp` (at least none that I know of).
Seems I have to add an additional slot in the `XCMSnExp` to hold that result data - well makes sense, since it is not _really_ an assay data.

**Comment by lgatto** [comment]
Too bad :-(

Slot name? `msFeatureData`, or any variation thereof?

**Comment by jotsetung** [comment]
That might be a good name. I'll have features, adjusted retention time and feature alignment information (`matrix`, `numeric` and `DataFrame`). I'm not yet sure whether I should create 3 separate slots or put all of them into an `environment` and that into a single slot. 
Thinking it over I think I'll opt for the first approach (dedicated slots). What you think?

**Comment by lgatto** [comment]
I would rather suggest a single slot, because all these related data are contained. An environment or even an object of class `MsFeatureData` defined as 
```r
setClass("MsFeatureData", contains = "environment")
```
that has it's own API (not necessarily generics/methods, unless we also defined them for the `XCMSnExp` class; could just a documented set of functions) and validity method.

**Comment by jotsetung** [comment]
Nice idea. 
Have to rethink it, however. The 3 different data types, _features_ (`matrix`), _adjusted retention time_ (`numeric`) and _feature alignment_ (`DataFrame`) are related and linked, but come from 3 different analysis steps. So, while it's possible to have only features, it's not possible to have any of the other two without the features. Now, having all these in a single environment sounds nice to me - only, putting that even inside its own class might be a little too much of an encapsulation since validation etc can be done at the `XCMSnExp` level - although I find it very elegant.

**Comment by lgatto** [comment]
> validation etc can be done at the `XCMSnExp` level 

I can also be a simple `validateMsFeatureData` that is called within `XCMSnExp`'s validity. It still think that, even without it's class, formalising the API for the `MsFeatureData` environment and implementing (internal) functions that respect the API will structure the code, make it more maintainable, and easier to re-use the environment if necessary. 

The dedicated class essentially allows to be able to formally ask `inherits(., "MsFeatureData")`.

**Comment by jotsetung** [comment]
Makes sense. Thanks for the suggestion.

**Comment by jotsetung** [comment]
Oh yes, this was a nice suggestion, thanks! Makes everything much easier (specifically validation of the data).
