### ISSUE TITLE
sort(method="radix") -> provide backward compatible fallback

### ISSUE THREAD

**Issue by sneumann** [lgatto/MSnbase#180]
Hi, the `sort(method="radix")` implementation bumps the minimum R version 
to 3.3. Not all R installations have that, or require non-distribution-standard 
package downloads etc. Since MSnbase is a fairly important infrastructure package, 
it shouldn't force new installations unless the missing functionality is critical,
#136 showed around 10% speed improvement, which is not critical.

It would be great if there was a fallback to shell sorting for R < 3.3.0.

**Comment by lgatto** [comment]
As @jotsetung provided the patch, I'll wait for his input. 

I would suggest to use shell sorting as the default and switch to radix for R >= 3.3, as long as that doesn't make things slower again. It that's the case, we could have a default `sort` method in the `MSnbase` options set in `onLoad` that would be set based on the R version.

**Comment by jotsetung** [comment]
Wasn't aware `radix` was not available on R < 3.3, sorry for that (have to check xcms too then).
I found that radix sorting was considerably faster for the test files I used, so, where available I would like to use radix sorting. 
Adding an option for the sort method that falls back to `method = "auto"` on R < 3.3 makes sense to me.
I'll hack it right away.

**Comment by jotsetung** [comment]
Done in master - what about release 3.4? Can you do that @lgatto or which branch matches that release?

**Comment by lgatto** [comment]
Thanks!

> Done in master - what about release 3.4? Can you do that @lgatto or which branch matches that release?

Yes, I'll look into this tonight or tomorrow morning.

**Comment by lgatto** [comment]
Done in Bioc devel and release-3.4.

**Comment by jotsetung** [comment]
As @sneumann pointed out `sort` does not have a `method` argument in R < 3.3. Have to fix the issue differently.

**Comment by jotsetung** [comment]
Now, thinking it all over I'm almost thinking of just calling `order` without specifying the method. might eventually be slightly slower, but would make things simpler - no additional option, no version checking. @lgatto what do you think?

**Comment by lgatto** [comment]
Yes, it seems code simplicity/readability would be the better option here (over minimal optimisation for a subset of users).

**Comment by jotsetung** [comment]
OK, done - tests run without errors - @lgatto could you eventually push to BioC? thanks!

**Comment by jotsetung** [comment]
@lgatto sorry to bug again - could you, when you have time, dcommit to BioC svn please?

**Comment by lgatto** [comment]
Done.
