### ISSUE TITLE
R CMD check error for version 2.1.8 on BioC

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#185]
Just realized that the 2.1.8 version on Bioconductor fails the `R CMD check`: http://bioconductor.org/checkResults/devel/bioc-LATEST/MSnbase/

**Comment by jotsetung** [comment]
These `R CMD check` errors seem to be fixed in the current version on github (2.1.9).

**Comment by lgatto** [comment]
Yes, and it's a strange error - somehow the verbose option is not set. I'm going to push 2.1.9 to sort that out.
