### ISSUE TITLE
split method for MSnExp, pSet, OnDiskMSnExp

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#186]
I'm working currently with the `XCMSnExp` object in `xcms` that extends `OnDiskMSnExp` and I have a scenario in which I would like to split this object by sample/files.

Now, before implementing such a method I was wondering what you would expect from a `split` function for e.g. the `pSet`. In `xcms` I'm always thinking *sample-wise*, so splitting an object by sample makes sense to me, what do you think @lgatto @sgibb ?

**Comment by jotsetung** [comment]
To explain a little more:
assume you have an `MSnExp` `a` with spectra from 4 files, a `split` like `L <- split(a, f = factor(c("a", "b", "a", "b")))` would return you a `list` of length 2, `L[[1]]` being an `MSnExp` with all spectra from files 1 and 3 and `L[[2]]` with those from files 2 and 4.

**Comment by lgatto** [comment]
If I understand correctly, you are thinking about something like
```r
> a
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 0.24 Mb
- - - Spectra data - - -
 MS level(s): 1 2 3 
 Number of spectra: 1074 
 MSn retention times: 18:28 - 74:54 minutes
- - - Processing information - - -
Data loaded [Thu Jan 26 09:13:11 2017] 
 MSnbase version: 2.1.9 
- - - Meta data  - - -
phenoData
  rowNames: MS3TMT10_01022016_32917-33481.mzML.gz
    TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  MS3TMT10_01022016_32917-33481.mzML.gz,   TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz 
protocolData: none
featureData
  featureNames: X001.1 X001.2 ... X565.1 (1074 total)
  fvarLabels: fileIdx spIdx ... spectrum (27 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
> fileNames(a)
[1] "/home/lg390/R/x86_64-pc-linux-gnu-library/3.4/msdata/proteomics/MS3TMT10_01022016_32917-33481.mzML.gz"                        
[2] "/home/lg390/R/x86_64-pc-linux-gnu-library/3.4/msdata/proteomics/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz"
> lapply(seq_along(fileNames(a)), function(i) filterFile(a, i))
[[1]]
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 0.14 Mb
- - - Spectra data - - -
 MS level(s): 1 2 3 
 Number of spectra: 565 
 MSn retention times: 73:43 - 74:54 minutes
- - - Processing information - - -
Data loaded [Thu Jan 26 09:13:11 2017] 
Filter: select file(s) 1. [Thu Jan 26 09:17:25 2017] 
 MSnbase version: 2.1.9 
- - - Meta data  - - -
phenoData
  rowNames: MS3TMT10_01022016_32917-33481.mzML.gz
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  MS3TMT10_01022016_32917-33481.mzML.gz 
protocolData: none
featureData
  featureNames: X001.1 X002.1 ... X565.1 (565 total)
  fvarLabels: fileIdx spIdx ... spectrum (27 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'

[[2]]
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 0.13 Mb
- - - Spectra data - - -
 MS level(s): 1 2 
 Number of spectra: 509 
 MSn retention times: 18:28 - 22:3 minutes
- - - Processing information - - -
Data loaded [Thu Jan 26 09:13:11 2017] 
Filter: select file(s) 2. [Thu Jan 26 09:17:25 2017] 
 MSnbase version: 2.1.9 
- - - Meta data  - - -
phenoData
  rowNames:
    TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz 
protocolData: none
featureData
  featureNames: X001.2 X002.2 ... X509.2 (509 total)
  fvarLabels: fileIdx spIdx ... spectrum (27 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
```

I think this is a rather limited scope for such a generic function like `split`. Also, sample and files don't necessarily match - in proteomics, we used labelling to combine multiple samples per acquisition/file; one sample can be fractionated over multiple acquisitions/files.

My understanding of splitting would rather be along the native MS dimensions,  i.e. retention time and M/Z; not sure if that would be any useful, though.

**Comment by jotsetung** [comment]
No, that wouldn't help in my case. OK, so I'll just implement a small helper function to split the `XCMSnExp` by file.

**Comment by lgatto** [comment]
I think it would be useful to have that helper function for `pSet` *et al.*. 

I have implemented these kind of splitting operations and relevant classes multiple times in the past: `MSnSet` and `MSnSetList`, `FeaturesOfInterest` and `FoICollections`, ... where the latter simply have a `list` slot containing the list (also, possibly a `log` or `metadata` `list` for some basic annotation) and `show`, `[` and `[[` methods.

**Comment by jotsetung** [comment]
OK, so let's reopen ;)

But then, when it's supposed to work on `pSet`, `MSnExp` etc, a method, e.g. `splitByFile` might be better than just a simple function, don't you think?

Regarding the dedicated class, for now I would like to keep it simple (also because use cases might be limited) and just return a simple `list`.

**Comment by lgatto** [comment]
A `splitByFile` method would be great. 

I agree with keeping things simple. A main driver for a simple class is to have a nice print-out rather than a long and useless list that spans several screens. Bit that can wait.

**Comment by jotsetung** [comment]
Just one note, the function should not split the object into a list of single-file objects (as in your example above), but should allow to e.g. split it into 2 objects each containing the data of 2 files.

Still OK with that?

**Comment by jotsetung** [comment]
Let me know if you're OK with https://github.com/lgatto/MSnbase/commit/8a4ea39697e534ef1fcc16ebfda3f4460037a7b0 or if I should change something.

**Comment by lgatto** [comment]
Looks good to me.
