### ISSUE TITLE
Errors due to new file in msdata::proteomics?

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#187]
I was puzzled by the failing `R CMD check` lately on MSnbase (also on the BioC build machines) and was wondering whether that might be due to changed in the `msdata` package. In version 0.15.1:
```r
> msdata::proteomics()
[1] "MRM-standmix-5.mzML.gz"                                       
[2] "MS3TMT10_01022016_32917-33481.mzML.gz"                        
[3] "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz"
```
Now, there seem to be problems reading the first one with `readMSData2`.

So, there seems to be a problem with the first file. I would suggest as a quick fix to ensure in the failing examples and unit tests that not just the first file returned by `msdata::proteomics` is used, but one is specifically selected.

**Comment by lgatto** [comment]
Strange, as I had run checks locally to look for this specifically. Anyway, it is somehow to be expected that some things fail with that file (it's missing MS data altogether). I will fix it.

**Comment by jotsetung** [comment]
I did already, am just running the checks.

**Comment by lgatto** [comment]
Ok, thanks!

**Comment by jotsetung** [comment]
Done. Are you going to commit to Bioc-svn soon? I'm asking because I'm waiting with xcms, since it depends now on MSnbase 2.1.10.

**Comment by lgatto** [comment]
I'll do now.
