### ISSUE TITLE
bin_Spectrum is not working if the largest break is smaller than max(mz) - mean(diff(breaks))

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#191]
While investigating #190 I came across another bug introduced in #137. If the largest break is smaller than `max(mz) - mean(diff(breaks))` `bin_Spectrum` fails with the following error:
```r
s1 <- new("Spectrum2", mz=1:4, intensity=1:4)
bin_Spectrum(s1, breaks=c(1,2))
# Error in validSpectrum(object) :
#   Unequal number of MZ and intensity values.
```
While this is working:
```r
bin_Spectrum(s1, breaks=c(1,3))
# Object of class "Spectrum2"
#  Precursor:
#  Retention time: :
#  Charge:
#  MSn level: 2
#  Peaks count: 2
#  Total ion count: 10
```
This happens because of the (too small) expansion of the breaks in https://github.com/lgatto/MSnbase/blob/a942daa309c5f65180556c8d5399fe33b2e1fd68/R/functions-Spectrum.R#L311-L315.

**Comment by sgibb** [comment]
Now we use: `ceiling(max(mz) + mean(diff(breaks)))` instead of `max(breaks) + mean(diff(breaks)))`, that could result in different breaks on the RHS/upper *m/z* end.:
https://github.com/lgatto/MSnbase/blob/1295aaae934d551803889ebbfa1e19b2b1c5e848/R/functions-Spectrum.R#L301-L303

**Comment by jotsetung** [comment]
Reopening this, because I'm not entirely happy with the solution to add `. IMHO this generates an unnecessarily large last bin, which then results in the last midpoint being shifted (i.e. higher than expected).

example:
```r
mz <- 1:20
brks <- seq(1, 20, by = 3)
brks
[1]  1  4  7 10 13 16 19

## Largest mz is thus larger than the largest break
## @sgibb's solution results in the following breaks
if (mz[length(mz)] >= brks[length(brks)])
    brks <- c(brks, ceiling(mz[length(mz)]) + mean(diff(brks)))
brks
[1]  1  4  7 10 13 16 19 23

## Which results then in the following mid points:
(brks[-length(brks)] + brks[-1L]) / 2L
[1]  2.5  5.5  8.5 11.5 14.5 17.5 21.0
## With the last mid point being by 0.5 higher than what would be expected.

## My suggestion would be to use:
brks <- seq(1, 20, by = 3)
if (mz[length(mz)] >= brks[length(brks)])
    brks <- c(brks, max(ceiling(mz[length(mz)] + 1e-6), brks[length(brks)] + mean(diff(brks))))
brks
[1]  1  4  7 10 13 16 19 22

## This ensures that the maximum value is always included AND that the size of the last bin 
## (and related midpoint) is (in most cases) identical to the size of all other bins. 
```

@sgibb , is that something you could live with?

**Comment by jotsetung** [comment]
Update: the `ceiling` above is not necessary (and not helpful at all). Adding
`max((rng[2] + 1e-6), brks[length(brks)] + mean(diff(brks)))` is sufficient to ensure that the largest values is definitely within the bin.

**Comment by jotsetung** [comment]
The difference between `breaks_Spectrum` and `.fix_breaks` on the unit tests for `breaks_Spectrum`:
```r
s1 <- new("Spectrum2", mz = 1:4, intensity = 1:4)
## issue 191
> MSnbase:::breaks_Spectrum(s1)
[1] 1 2 3 4 5
> MSnbase:::breaks_Spectrum(s1, breaks = 1:2)
[1] 1 2 5
> MSnbase:::breaks_Spectrum(s1, binSize = 2)
[1] 1 3 6
```

```r
> ints <- 1:4
> brks <- seq(min(ints), max(ints), by = 1)
> MSnbase:::.fix_breaks(brks, range(ints))
[1] 1 2 3 4 5
> MSnbase:::.fix_breaks(1:2, range(ints))
[1] 1.000000 2.000000 4.000001
> MSnbase:::.fix_breaks(seq(1, 4, by = 2), range(ints))
[1] 1 3 5

```

**Comment by sgibb** [comment]
@jotsetung sorry for the late response. Your solution with `max((rng[2] + 1e-6), brks[length(brks)] + mean(diff(brks)))` is great. (The `ceiling` was indeed not helpful.)
