### ISSUE TITLE
MSnbase sticker?

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#196]
Sorry for filing this as an issue... I was just wondering whether we should make a MSnbase sticker. I have a template Gimp xcf file on which we could work. I could add that to the git repo so all of you can work on it too.

**Comment by lgatto** [comment]
I wanted to create stickers since the last EuroBioc conference, but didn't get a chance. 

What about creating a sticker repo that we can fork and/or contribute to?

**Comment by lgatto** [comment]
Followed-up [here](https://github.com/jotsetung/BioC-stickers).

**Comment by lgatto** [comment]
Followed-up [here](https://github.com/jotsetung/BioC-stickers).
