### ISSUE TITLE
Parallel processing for OnDiskMSnExp not efficient

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#197]
I saw some performance issues working with `OnDiskMSnExp` objects from large experiments (many files). The setting in `getBpParam` is too conservative skipping parallel processing at all if the average number of spectra per file is lower than 1000. I'd like to skip the specific condition for `OnDiskMSnExp` objects and just drop parallel processing if the length of the object is less than 1000. 
@lgatto any objections?

**Comment by lgatto** [comment]
> if the length of the object is less than 1000.

Is this a typo? Did you mean a value smaller than 1000?

**Comment by sgibb** [comment]
I think he meant  skip parallel processing just if the `OnDiskMSnExp` contains less than 1000 spectra.

**Comment by jotsetung** [comment]
Yup, @sgibb is right. No parallel processing if there are less than 1000 spectra in the object (i.e. its length is < 1000).

**Comment by lgatto** [comment]
Is that not what we have?
```r
> MSnbaseOptions()
$PARALLEL_THRESH
[1] 1000

$verbose
[1] FALSE
```
Or is that on a file basis, and you want it on a total object basis?

**Comment by jotsetung** [comment]
Eventually easier to just look at the code. I removed the special case for `OnDiskMSnExp`. @lgatto , OK for you?

**Comment by lgatto** [comment]
Yep, fine by me.
