### ISSUE TITLE
speed up package load time

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#201]
The loading time for `MSnbase` is quite long. I was wondering if we could reduce the package loading time (about 3.3 secs on my computer). This would be specifically helpful for parallel processing using `SnowParam` (only parallel processing available in Windows).

I guess the loading time is a combination of time spent on the imports and on the exports - so I guess there is not much that can be done.

**Comment by lgatto** [comment]
It would be great if we could to that. Maybe worth exploring:
- move some packages from depends to imports in the description
- reduce import to importFrom in the namespace

**Comment by jotsetung** [comment]
I'll play a little around with that and what speed improvement we could get.

**Comment by sgibb** [comment]
We could also review all Depends and Suggests. E.g. `reshape2` is just used for `melt` (which could easily replaced), see #202 for example. (I am not sure whether @lgatto want to merge this now, or want to wait for the next release cycle).

**Comment by lgatto** [comment]
As long as changes are relatively minor, like #202, I am happy to merge now.

**Comment by jotsetung** [comment]
I would rather like to change stuff later - don't want to break things again ;)
