### ISSUE TITLE
Direct accessor to fData 

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#209]
From #203 

> It would be useful to be able to change the behaviour of `$` or have another operator (`$$` and `@` where discusses) to access `fData` columns, like `$` does for `pData`. Accessing `fData`columns is much more useful in our spatial proteomics work in pRoloc, where we so often need to access feature variables in our `MSnSets` and close to never anything in `pData`.

Implementeding `$$` or `@` hasn't proved easy, and the latter would be confusing anyway. Any comments and suggestions are welcome.

**Comment by lgatto** [comment]
Some suggestions from a discussion with Martin:

- Make `$` dispatch (and autocomplete) on both `fData` and `pData` columns
- Use `x$fd$` and `x$pd$` to dispatch and autocomplete on `fData` and `pData` respectively. Will this not break old code? The big limitation is that none of the feature/pheno data columns can be named `pd` or `fd`, which is not viable, as `pd` is used as shortcut for *phenoDisco*.

**Comment by lgatto** [comment]
Coming back to my option example, what it the option supported dispatching on both (point 1 above; that would be the default) and also could be set to dispatch only on `fData` or `pData`? 
@sgibb @jotsetung - what would you think of that?

**Comment by sgibb** [comment]
While I have no solution I am against an option to switch dispatching because it would be too confusing. If you read some others code you never know whether he access `fData` (rows) or `pData` (columns) (at least without knowing the `fvarLabels` by heart).

**Comment by lgatto** [comment]
Ok, no option then.

**Comment by jotsetung** [comment]
Agree with @sgibb
