### ISSUE TITLE
Reading mzData in readMSData2() broken with default mzR:pwiz backend

### ISSUE THREAD

**Issue by sneumann** [lgatto/MSnbase#214]
Hi, 
the new default backend in mzR is pwiz, but mzXML and mzData are only handled 
by the mzR:RAMP backend:

```
> fticr <- readMSData2(list.files(system.file("fticr", package = "msdata"), recursive = TRUE, full.names = TRUE)[1], msLevel. = 1)
Error in pwizModule$open(filename) : 
  [MSDataFile::readFile()] Unsupported file format.
```

In XCMS we check the required backend like this:
https://github.com/sneumann/xcms/blob/ed8945662d82612911bcdbf4be3333ea750d1ef6/R/xcmsSource.R#L9
and use the corresponding backend:
https://github.com/sneumann/xcms/blob/ed8945662d82612911bcdbf4be3333ea750d1ef6/R/xcmsSource.R#L9
Yours, Steffen

**Comment by jotsetung** [comment]
Fixing this results in a log of unit test failures in `MSnbase` - have to check that. Possible reason: if `pwiz` is used as backend stuff like `polarity` is correctly read, while `Ramp` doesn't.

**Comment by sneumann** [comment]
Hi, I can conform that the xcms `R CMD check` passes with
```
other attached packages:
[1] xcms_2.99.2         MSnbase_2.3.4       ProtGenerics_1.6.0 
[4] mzR_2.11.3          Rcpp_0.12.10        BiocParallel_1.8.2 
[7] Biobase_2.34.0      BiocGenerics_0.20.0
```
all pulled tonight from github. Well done everyone ! Yours, Steffen

**Comment by sneumann** [comment]
Hi, I can conform that the xcms `R CMD check` passes with
```
other attached packages:
[1] xcms_2.99.2         MSnbase_2.3.4       ProtGenerics_1.6.0 
[4] mzR_2.11.3          Rcpp_0.12.10        BiocParallel_1.8.2 
[7] Biobase_2.34.0      BiocGenerics_0.20.0
```
all pulled tonight from github. Well done everyone ! Yours, Steffen
