### ISSUE TITLE
Spectrum2 C level constructor fails for empty spectra

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#215]
The C-constructor for Spectrum2 classes fails if a spectrum does not contain any values. Data from
https://github.com/crmclean/Reproducible_Examples/tree/master/xcms
```r
library(MSnbase)

raw_data <- readMSData2("mtab_mmetsp_ft_120815_01.mzML")

ms1 <- raw_data[[1]]

ms2 <- raw_data[[2]]

Error in Spectra2_mz_sorted(msLevel = msnfd$msLevel, peaksCount = nValues,  : 
  Arguments 'mz', 'intensity' and 'nvalues' are required!

```

**Comment by jotsetung** [comment]
Note, reading just the MS2 spectra using `readMSData` works:
```r
raw_data2 <- readMSData("mtab_mmetsp_ft_120815_01.mzML")
ms2 <- raw_data2[[1]]
mz(ms2)
numeric(0)
```

**Comment by lgatto** [comment]
`Spetra2_mz_sorted` fails as expected [here](https://github.com/lgatto/MSnbase/blob/master/R/functions-Spectrum2.R#L97-L98)

```r
    if (length(mz) == 0 | length(intensity) == 0 | length(nvalues) == 0) {
        stop("Arguments 'mz', 'intensity' and 'nvalues' are required!")
```

I think it would be good to change this so that when `nvalues` is 0 (which is the case above), empty `mz` and `intensity` are allowed, and return a spectrum that is equivalent that the one with the R constructor and `readMSData`.

**Comment by jotsetung** [comment]
Agree. Will do as soon as I find the time for it.

**Comment by jotsetung** [comment]
Fixed. Just removing the check above worked:
```r
library(MSnbase)
raw_data <- readMSData2("mtab_mmetsp_ft_120815_01.mzML")
ms1 <- raw_data[[1]]
ms2 <- raw_data[[2]]
mz(ms2)
numeric(0)

only_ms2 <- filterMsLevel(raw_data, msLevel = 2)
all_ms2 <- spectra(only_ms2)
all_ms2_2 <- spectra(readMSData("mtab_mmetsp_ft_120815_01.mzML", msLevel. = 2))
expect_equal(unname(all_ms2), unname(all_ms2_2))
## Works
```

**Comment by jotsetung** [comment]
Made pull request https://github.com/lgatto/MSnbase/pull/219
