### ISSUE TITLE
unit test runtime

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#216]
The runtime of the unit tests is very long now (`MSnbase` version 2.3.3 and `mzR` 2.11.1). This might have to do something with recent changes to `mzR` (?)

**Comment by jotsetung** [comment]
Yes, indeed - this is related to the default backend in `mzR`. The code that is most affected is code for `OnDiskMSnExp`. I build a modified `mzR` (based on 2.11.1) that allows to switch the backend using an option:

```r
library(mzR)
library(msdata)
f <- msdata::proteomics(full.names = TRUE, pattern = "TMT_Erwinia")

options(mzR = list(default_backend = "Ramp"))

onDisk_ramp <- readMSData2(f)

system.time(spct_ramp <- onDisk_ramp[[4]])
## mzR: using backend  Ramp 
##    user  system elapsed 
##   0.315   0.015   0.328 

system.time(spct_ramp_all <- spectra(onDisk_ramp))
## mzR: using backend  Ramp 
##    user  system elapsed 
##   1.647   0.101   1.748 

options(mzR = list(default_backend = "pwiz"))

onDisk_pwiz <- readMSData2(f)

system.time(spct_pwiz <- onDisk_pwiz[[4]])
## mzR: using backend  pwiz 
##    user  system elapsed 
##   0.487   0.036   0.518 
system.time(spct_pwiz_all <- spectra(onDisk_pwiz))
## mzR: using backend  pwiz 
##    user  system elapsed 
##  86.432   8.979  92.879 

```
The difference between the `spectra` calls on `pwiz` and `Ramp` backends is unacceptable.

I'll dig a little deeper into this.

**Comment by jotsetung** [comment]
OK, it's all in `mzR`:
```r
fpw <- openMSfile(f, backend = "pwiz")
framp <- openMSfile(f, backend = "Ramp")
idx <- 1:509   ## That's the number of spectra we've got in the file.

## Read all header
system.time(
    fpw_hdr <- mzR::header(fpw)
)
##  user  system elapsed 
## 1.027   0.054   1.083 
system.time(
    framp_hdr <- mzR::header(framp)
)
##  user  system elapsed 
## 0.446   0.009   0.455 
```
Reading all header is comparable, but slower with `pwiz`.

```r
## Read all header providing the index
system.time(
    fpw_hdr_2 <- mzR::header(fpw, idx)
)
##   user  system elapsed 
## 84.447   8.387  90.556 

system.time(
    framp_hdr_2 <- mzR::header(framp, idx)
)
##  user  system elapsed 
## 0.471   0.009   0.481 
```
`pwiz` fails completely to read headers efficiently when indices are provided! That's the reason for the slow performance when switching to `pwiz`!

The data is almost similar, `pwiz` does read polarity info which `Ramp` doesn't.
```r
library(testthat)
expect_equal(fpw_hdr, fpw_hdr_2)
expect_equal(framp_hdr, framp_hdr_2)
expect_equal(framp_hdr, fpw_hdr)
Error: `framp_hdr` not equal to `fpw_hdr`.
Component “polarity”: Mean absolute difference: 1
```
Also for single header access, `pwiz` is slower:
```r
## Read a single header
system.time(
    fpw_hdr_2 <- mzR::header(fpw, 5)
)
##  user  system elapsed 
## 0.190   0.020   0.204 

system.time(
    framp_hdr_2 <- mzR::header(framp, 5)
)
##  user  system elapsed 
## 0.006   0.001   0.006 
```

With spectra access both methods are again comparable:
```r
## Same tests for spectra:
system.time(
    fpw_pks <- mzR::peaks(fpw)
)
##  user  system elapsed 
## 0.439   0.028   0.467 
system.time(
    framp_pks <- mzR::peaks(framp)
)
##  user  system elapsed 
## 0.465   0.025   0.491 

## All spectra with index
system.time(
    fpw_pks_2 <- mzR::peaks(fpw, idx)
)
##  user  system elapsed 
## 0.456   0.026   0.483 

system.time(
    framp_pks_2 <- mzR::peaks(framp, idx)
)
##  user  system elapsed 
## 0.450   0.022   0.472 

```

**Comment by jotsetung** [comment]
The `spectrapply` method is incredibly slow for `pwiz` backend, reason being the fix for issue #170, i.e. the addition of a `hd_spectra <- mzR::header(fileh, fData$spIdx)` call to the `.applyFun2SpectraOfFileMulti` function although that would not be needed at all.

I'll check if I could remove that line again and still don't get the problems reported in #170.

**Comment by jotsetung** [comment]
Nope - after removing this line I get again the same errors as described in issue #170.

**Comment by jotsetung** [comment]
OK, once the PR in `mzR` is accepted, unit tests and performance should be restored again.

**Comment by lgatto** [comment]
The package builds and checks fine again on travis-ci. Note that the testing is done using parallel processing again.
