### ISSUE TITLE
xic and chromatogram methods not implemented for mzRpwiz

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#218]
The `xic` and `chromatogram` methods are implemented for `mzRamp`, but not for `mzRpwiz`.

**Comment by lgatto** [comment]
- The problem, which I just realised today, is that `MSnbase::chromatogram,mzRramp`, and `mzR::chromatogram,mzRpwiz` do different things. I plan to deprecate the former, as all development is not done using the `pwiz` backend
- Re `xic`, it is slow and needs to be improved (it was used more as testing ground), not really meant for large scale utilisation. It will also `deprecate` it and a proper implementation should probably live in `mzR` for `mzRpiz`, that is then reused in `MSnbase`.

**Comment by lgatto** [comment]
By the way, how is the `Chromatogram` class doing? Is this not what would need to be returned by `chromatogram`?

**Comment by jotsetung** [comment]
Was to slow to answer - `extractChromatograms` from the `xcms` looks to be redundant to the `xic`. It returns a `Chromatogram` object (actually a `list` of them, one per file/sample in an `OnDiskMSnExp`.

**Comment by lgatto** [comment]
See #222
