### ISSUE TITLE
Note: MSnbase in svn is older than on github

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#220]
Hi @lgatto, probably you know that already, but the MSnbase version in Bioconductor's svn is 2.3.2 and the version here on github is 2.3.4.
Note that the `R CMD check` errors for 2.3.2 currently occurring in Bioc's build machines are also fixed in 2.3.4.

**Comment by lgatto** [comment]
Thanks. There was a version mismatch in DESCRIPTION and NEWS.md. Fixed and committed to svn. Now we have 2.3.3 on Bioc and 2.3.4 in github.
