### ISSUE TITLE
Use Chromatogram[s] in MSnbase

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#222]
As discussed with @jotsetung, the `Chromatogram` and new `Chromatograms` classes will be moved to `MSnbase`.

**Comment by lgatto** [comment]
Coming back to the discussion and how combining extracted `Chromatogram`objects for multiple files into a rectangular object (`DataFrame` or `matrix`). How are the `rt` by `mz` ranges defined or named? Are they actual ranges, so that one could ask for all those that overlap with `[300, 500]` M/Z, for example?

**Comment by lgatto** [comment]
Thanks - let's may be wait and see what looks the most useful.

In the end, are you going for the `matrix` or `DataFrame` of `Chromatogram` objects?

**Comment by jotsetung** [comment]
I'm going for `matrix`:
```r
> ch <- Chromatogram()
> chl <- list(ch, ch, ch, ch)
> mat <- matrix(chl, ncol = 1)
> mat
     [,1]
[1,] ?   
[2,] ?   
[3,] ?   
[4,] ?   

> mat[1, 1]
[[1]]
Object of class: Chromatogram
length of object: 0
from file: 
mz range: [NA, NA]
```

While `data.frame`:
```r
> ch <- Chromatogram()
> chl <- list(ch, ch, ch, ch)
> as.data.frame(chl)
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class "structure("Chromatogram", package = "MSnbase")" to a data.frame
> data.frame(chl)
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class "structure("Chromatogram", package = "MSnbase")" to a data.frame
```
