### ISSUE TITLE
spectra ordering for multiple files

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#225]
This issue is the same as #68 (PR #69) was for spectra located in a single file but for multiple files. If I read multiple files the order is now: spectrum1.file1, spectrum1.file10, spectrum1.file11, ... , spectrum1. file2, ... , spectrum2.file1, ... (`X001.1`, `X001.10`, `X001.11`, ... `X001.2`, ... `X002.1`).

Wouldn't it be more useful to swap the order: file.spectrum and apply natural sorting to files as well?

So, e.g. file1.spectrum1, file1.spectrum2, ..., file2.spectrum1, ... (`X01.001`, `X01.002`, ... `X02.001`).

from `readMSData2.R`:
```r
fullhdorder <- c(fullhdorder,
                     sprintf(paste0("X%0",
                                    ceiling(log10(length(spidx) + 1L)),
                                    "d.%s"), 1:length(spidx), filen))
```
should be:
```r
nDigitsSpIdx <- ceiling(log10(length(spidx) + 1L))
nDigitsFileIdx <- ceiling(log10(length(files) + 1L))

fullhdorder <- c(fullhdorder,
                     sprintf(paste0("X%0", nDigitsFileIdx, "d.",
                                     "%0", nDigitsSpIdx, "d"), 
                                     filen, seq_along(spidx))
```

BTW: I am not sure how this would effect existing code/objects.

CC: @pavel-shliaha

**Comment by pavel-shliaha** [comment]
according to Laurent it is impossible to reorder spectra in MSnBase object. This is a huge inconvinience, since it means that the table with frgmentation parameters needs to be reordered instead

**Comment by lgatto** [comment]
> according to Laurent it is impossible to reorder spectra in MSnBase object. This is a huge inconvinience, since it means that the table with frgmentation parameters needs to be reordered instead

There is no fixed order of spectra in an `MSnExp` or an `OnDiskMSnExp`. You can define the order that suites you best.

**Comment by lgatto** [comment]
I am currently testing, and have found at least one example that needs updating. 

@sgibb, could you elaborate on the need for a specific order, and how, this particular naming scheme is needed in addition to `filterFile`. I'm fine with renaming the features as you suggest, but would appreciate a bit more discussion to see beyond the case where a very fast `filterFile` would work too.

**Comment by sgibb** [comment]
In fact there is no important reason but convenience. (I am afraid I have not any strong argument.) 

1. If you want to add additional information (that are generated in the same order as the mzML files) to the `featureData` slot  you have to do `merge(x, y, by=c("fileIdx", "spIdx"))` instead of simply call `cbind`.
2. If the user wants to access the second spectrum of the first file, he has to call `filterFile(msnexp, 1)[[2]]` instead of just `msnexp[[2]]`.
3. IMHO `F01.S0001`, `F01.S0002`, `F02.S0001`, ... are better (row) name thans `X0001.1`, `X0001.2`, `X0002.1`, ...
4. I like sorted lists 😄.

But I understand that we should not do this more or less cosmetic change if it breaks anything.

**Comment by lgatto** [comment]
OK, thanks. It makes sense. I wanted to make sure I didn't miss a more profound reason.
