### ISSUE TITLE
Add Chromatogram[s] section in MSnbase vignette.

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#227]
See [here](https://github.com/lgatto/MSnbase/pull/224#issuecomment-310891243)

**Comment by jotsetung** [comment]
I added a section to *MSnbase-demo.Rmd*. Let me know if you want me to expand it.

**Comment by lgatto** [comment]
I have 2 suggestions
- Maybe a figures
- You will be describing much more in the xcms vignette, so may be you could add a link or footnote referring to xcms.

**Comment by jotsetung** [comment]
With figures you mean to add a plot/subsection to the *Plotting raw data* section I guess.

**Comment by jotsetung** [comment]
Done in https://github.com/lgatto/MSnbase/commit/a46ece5df45c8717627e41ef7213a0e6037d3814
