### ISSUE TITLE
Bug in nav example?

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#228]
While checking the latest MSnbase master I get the follwing error:
```
* checking examples ... ERROR
> f <- msdata::proteomics(full.names = TRUE)[2]
> x <- readMSData2(f, centroided = c(FALSE, TRUE, FALSE))
> (sp <- which(msLevel(x) == 3)[2]) ## 2nd MS3 spectrum
<NA> 
  NA 
> x[[sp]] ## curent MS3
Error in .local(x, i, j, ...) : subscript out of bounds
Calls: [[ -> [[ -> .local
Execution halted
```

Change happend in the latest commit https://github.com/lgatto/MSnbase/commit/28d770604058aa1b4264c167c49797057a37d524

Are there any MS3 spectra in this selected mzML?

**Comment by lgatto** [comment]
Thank you for the bug report.
