### ISSUE TITLE
Issues with chromatogram constructor

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#229]
```r
 > f
[1] "ML_2017-05-23_J1-21.mzML" "ML_2017-05-23_J2-21.mzML"
[3] "ML_2017-05-23_J3-21.mzML"
> rw <- readMSData2(f, verbose = TRUE)
Reading 51034 spectra from file ML_2017-05-23_J1-21.mzML
Reading 50039 spectra from file ML_2017-05-23_J2-21.mzML
Reading 47029 spectra from file ML_2017-05-23_J3-21.mzML
> rw
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 30.54 Mb
- - - Spectra data - - -
 MS level(s): 1 2 
 Number of spectra: 148102 
 MSn retention times: 10:0 - 100:0 minutes
- - - Processing information - - -
Data loaded [Tue Jul 11 15:51:50 2017] 
 MSnbase version: 2.3.9 
- - - Meta data  - - -
phenoData
  rowNames: ML_2017-05-23_J1-21.mzML ML_2017-05-23_J2-21.mzML
    ML_2017-05-23_J3-21.mzML
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  [1] ML_2017-05-23_J1-21.mzML...  [3] ML_2017-05-23_J3-21.mzML
  Use 'fileNames(.)' to see all files.
protocolData: none
featureData
  featureNames: F1.S00001 F1.S00002 ... F3.S47029 (148102 total)
  fvarLabels: fileIdx spIdx ... spectrum (27 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
> chrom <- chromatogram(rw)
Error: 'bplapply' receive data failed:
  error reading from connection
```

I then tried to avoid parallel processing. This required some code changes (see 9fc6c8d5e0b0d65a966b733b93669db3943045a5), which however resulting in another error (or errors, but the first one can be ignores, I think).

```r
> chrom <- chromatogram(rw, BPPARAM = bpparam("SerialParam"))
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Error: cannot allocate vector of size 1.7 Gb
```

Cc: @jotsetung

**Comment by lgatto** [comment]
I also tried with a single file:
```r
> fileNames(rw)
[1] "ML_2017-05-23_J1-21.mzML"
> chrom <- chromatogram(rw)
Error: cannot allocate vector of size 3.1 Gb
```

**Comment by lgatto** [comment]
Following up with some more testing. If I centroid the MS1 data (which is recommended, but of interest for a test):
```r
> f
[1] "centr/ML_2017-05-23_J1-21.mzML"
> rw <- readMSData2(f, centroided = TRUE, verbose = TRUE)
Reading 51034 spectra from file ML_2017-05-23_J1-21.mzML
> chrom <- chromatogram(rw)
> chrom
Chromatograms with 1 row and 1 column
     ML_2017-05-23_J1-21.mzML
               <Chromatogram>
[1,]             length: 6042
```

**Comment by lgatto** [comment]
And, when aggregating:
```r
> f <- list.files(pattern = "mzML$")[1]
> f
[1] "ML_2017-05-23_J1-21.mzML"
> rw <- readMSData2(f, centroided = c(FALSE, TRUE), verbose = TRUE)
Reading 51034 spectra from file ML_2017-05-23_J1-21.mzML
> chrom <- chromatogram(rw, aggregationFun = "max")
> chrom
Chromatograms with 1 row and 1 column
     ML_2017-05-23_J1-21.mzML
               <Chromatogram>
[1,]             length: 6042
```

**Comment by lgatto** [comment]
I also observe that `chromatogram` is extremely memory greedy in my examples.

**Comment by jotsetung** [comment]
> I then tried to avoid parallel processing. This required some code changes

Parallel processing could also be *switched off* using `register(SerialParam())`, that's how I usually do it. All functions use by default the (default) registered parallel settings.

Re memory greedy: this could well be. `chromatogram` reads all spectra of a file to aggregate its intensities. This is performed on a per-file basis (one file after the other is processed), to be memory friendly - as good as it can be.
So, in principle you should get the same error if you try to read one of the (not centroided) files using `readMSData`.

**Comment by lgatto** [comment]
Re-running tests this morning are more promising. I've had *strange things* happening with my laptop since CSAMA, including becoming at times very slow. I will report back or close depending on how things turn out.

**Comment by jotsetung** [comment]
Still, I can imagine that, depending on the resolution, reading `mzML` files in profile mode can be quite memory demanding.

**Comment by lgatto** [comment]
Closing for now as things work well on a server.

**Comment by jotsetung** [comment]
I will investigate a little to see if I could reduce the memory demand (and eventually improve the performance) of the `spectrapply,OnDiskMSnExp` method (core of all data accessing methods of `OnDiskMSnExp` objects).
