### ISSUE TITLE
Reading MS and ID files is taking too long 

### ISSUE THREAD

**Issue by prvst** [lgatto/MSnbase#231]
Hey Laurent;

I'm experimenting with the MSnbase package, following some of the examples described on the vignette and I'm having some issues with mzid and mzml loading/parsing, I have here a 930 MB mzml and a 310 MB mzid file.

My code is pretty much the same you have on the section 4, subsection 4.1, the mzml file takes about 5 minutes to load and the mzid loading died after > 20 minutes of processing with the following error:

`Error in split.default(x, g) : first argument must be a vector`

I think the error could be something else, but my only concern here is about the time necessary to load and prepare the files. These are kinda deep sequencing data and I have dozens of those to read.

Am I doing something wrong here ? Is there a way to speed the loading functions ? Some external pipelines I have take less than a minute to read those files, so I imagine this can be improved somehow.

Thanks

**Comment by lgatto** [comment]
Regarding the raw data, use `readMSData2` rather than `readMSData`. The former is for the new backend (see the `benchmarking` vignette for details), and that's where all development is geared towards. 

I am not sure about the error you see. Could you copy the code in the issue, please.

Regarding parsing the id data, there is room for improvement. The current implementation uses the `mzID` package (because it was the first one out there), but the similar functionality in `mzR` is much faster. I can try to work on that in the coming day (would be a fun holiday project).

**Comment by prvst** [comment]
This is what I have :

`quantFile <- ("raw/b1906_293T_proteinID_01A_QE3_122212.mzML")`
`identFile <- ("id/b1906_293T_proteinID_01A_QE3_122212.mzid")`

`msexp <- readMSData(quantFile, verbose = FALSE)`
`head(fData(msexp), n = 2)`

`msexp <- addIdentificationData(msexp, id = identFile, verbose = FALSE)`
`head(fData(msexp), n = 2)`

output: `Error in split.default(x, g) : first argument must be a vector`

**Comment by prvst** [comment]
sorry misclicked...

I also tried the mzR package, like this : 

`x <- openIDfile(file)`

After about 10 minutes, I got a fatal erro from Rstudio saying " R Session aborted - R encountered a fatal error"

no further explanation, just a button to close everything.

**Comment by sgibb** [comment]
@lgatto this old PR comes to my mind: https://github.com/lgatto/MSnbase/pull/48; Adding `mzR` support for `addIdentificationData` should be really simple now, e.g.:
```r
id <- openIDfile("msdata.mzid")
addIdentificationData(m, psms(id), icol=c("spectrumID", "acquisitionNum"))
```

but this fails with the error mentioned above:

```
Error in split.default(x, g) : first argument must be a vector
> traceback()
8: split.default(x, g)
7: split(x, g)
6: lapply(split(x, g), FUN)
5: ave(id$accession, id[, icol], FUN = utils.vec2ssv) at utils.R#792
4: utils.mergeSpectraAndIdentificationData(fd, id, fcol = fcol, 
       icol = icol) at methods-MSnExp.R#298
3: .local(object, id, ...)
2: addIdentificationData(m, psms(p), icol = c("spectrumID", "acquisitionNum")) at AllGenerics.R#96
1: addIdentificationData(m, psms(p), icol = c("spectrumID", "acquisitionNum"))
```

**Comment by lgatto** [comment]
Thanks @sgibb, will look into it.

**Comment by lgatto** [comment]
@prvst -  how did you create that mzid file? Could you share it?

**Comment by prvst** [comment]
The spectra files are from [this study](http://www.nature.com/nbt/journal/v33/n7/full/nbt.3267.html?foxtrotcallback=true). I used the latest stable Comet version to generate a pepXML file and idconvert from pwiz to generate the mzid file. The search parameters are pretty much default, nothing exceptional.

Comet also generates a tab-delimited file, but the columns are different from those described by the mzID package (nothing that can't be adjusted though). I'm not using MSGFp or Tandem, as suggested on the vignette, because I want to see how the results will look like when comparing with my current pipeline, here I'm using Comet followed by a tool of mine called Philosopher that runs PeptideProphet, ProteinProphet  and also calculates the FDR levels.

**Comment by lgatto** [comment]
The search engine shouldn't matter, as long as the `mzid` files are valid - the only reason I mention these two programs is because they can be used with R/Bioc. It could be related to `pepXML` that results in limited `mzid` files though. Could you share one of these `mzid` files?

**Comment by prvst** [comment]
sure, where should I post the file ?

**Comment by sgibb** [comment]
@lgatto maybe we should open another issue. I am not sure the problems are related.
The error `Error in split.default(x, g) : first argument must be a vector` on my *mzR* example happens because we rely on some column names (that are maybe different in the @prvst' ID file as well): https://github.com/lgatto/MSnbase/blob/master/R/utils.R#L791-L793

`mzR` renames the accession attribute into `DatabaseAccession` (and description into `DatabaseDescription`, and `pepseq` into `sequence`). The following works: 
```r
m <- readMSData2("Thermo_Hela_PRTC_1_MS2cent-5000-6000.mzML")
idHandle<- openIDfile("Thermo_Hela_PRTC_1_MS2cent-5000-6000.mzid")
id <- psms(idHandle)
colnames(id)[c(7, 14, 17)] <- c("pepseq", "accession", "description")
# convert from "factor"
id$accession <- as.character(id$accession)
id$description <- as.character(id$description)
id$spectrumFile <- basename(sourceInfo(idHandle)[1])
addIdentificationData(m, id, icol=c("spectrumFile", "acquisitionNum"))
```
We have to provide a method `addIdentificationData,MSnExp,mzIdent` and ensure in `addIdentification,MSnExp,data.frame` that all the columns are present (or given as an argument).

So maybe the XML arguments like accession, description, pepseq etc. are named differently in @prvst's mzIdent file, because a wrong column name in one of these 3 yield the error he mentioned.

**Comment by lgatto** [comment]
@sgibb - yes, that's what I am working on now. We need to be able to specify all these in the `addIdentificationData` methods, and set the values accordingly. Thanks for your input. But @prvst might have another issue, as he mentioned that he got an error when calling `openIDfile`.

@prvst - upload it where you want and give me a link to download it. I don't have a public server for you to upload data.

**Comment by prvst** [comment]
@lgatto here is the file:
https://drive.google.com/file/d/0B7dAMrTk0FbaWkZacUUyRm9lQlk/view?usp=sharing
Let me know when you get it, so I can drop the link.

**Comment by lgatto** [comment]
@prvst - do you know how to download that file on the command line? I have to connect to a server and use `wget`, as my local connection is patchy at best. I tried using a text browser, but it seems I need to connect to my google account to access the file.

**Comment by lgatto** [comment]
@prvst - could you install the latest version from github and try again. Now, `addIdenticationData` uses `mzR` and uses the correct columns names (`DatabaseAccess` instead of `accession`, ...).

**Comment by prvst** [comment]
@lgatto 

I installed the new version with this `biocLite("lgatto/MSnbase")`. My session shows the following:

`other attached packages:
[1] MSnbase_2.3.9       ProtGenerics_1.6.0  BiocParallel_1.8.2  mzR_2.8.1           Rcpp_0.12.12        Biobase_2.34.0      BiocGenerics_0.20.0`

I tried the snippet again but the same fatal error shows up and crashes my R session.

Regarding the file: Can we try [wormhole](https://github.com/warner/magic-wormhole) ?

**Comment by lgatto** [comment]
> Regarding the file: Can we try wormhole ?

Yes, it's now installed on the server.

**Comment by prvst** [comment]
9-congregate-woodlark

**Comment by lgatto** [comment]
Receiving file now, thanks.

**Comment by lgatto** [comment]
So, here's what I have:
```r
> library(mzR)
 Loading required package: Rcpp
 > x = openIDfile("b1906_293T_proteinID_01A_QE3_122212.mzid")
 > x
 Identification file handle.
 Filename:  b1906_293T_proteinID_01A_QE3_122212.mzid
 Number of psms:  207048
```
This is with
```r
> sessionInfo()
 R version 3.4.1 RC (2017-06-22 r72854)
 Platform: x86_64-pc-linux-gnu (64-bit)
 Running under: Ubuntu 14.04.1 LTS

 Matrix products: default
 BLAS: /usr/lib/libblas/libblas.so.3.0
 LAPACK: /usr/lib/lapack/liblapack.so.3.0

 locale:
  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
  [9] LC_ADDRESS=C               LC_TELEPHONE=C
 [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

 attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   base

 other attached packages:
 [1] mzR_2.11.4           Rcpp_0.12.12         BiocInstaller_1.27.2

 loaded via a namespace (and not attached):
  [1] codetools_0.2-15    digest_0.6.12       withr_2.0.0
  [4] R6_2.2.2            git2r_0.19.0        httr_1.2.1
  [7] curl_2.8.1          devtools_1.13.2     tools_3.4.1
 [10] Biobase_2.37.2      ProtGenerics_1.9.0  parallel_3.4.1
 [13] compiler_3.4.1      BiocGenerics_0.23.0 memoise_1.1.0
 [16] knitr_1.16
```
@prvst - could you try the above in a new R session and report back, please.

**Comment by prvst** [comment]
@lgatto It works when I run on the terminal, but not on Rstudio, I still have a session crash when running the `openIDfile` function

**Comment by lgatto** [comment]
Could you also try with this file:
```r
> f <- msdata::ident(full.names = TRUE)
> f
[1] "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid"
```
which works on my laptop in RStudio. I can't try RStudio with your file as it's on a server.

**Comment by prvst** [comment]
I tried the same snippet above with the TMT file as well and the result was the same, the session crashes

**Comment by lgatto** [comment]
What is your RStudio version? Could you try with the latest one, in case that's not the one you are using.

**Comment by prvst** [comment]
I was using v1.0.143, so I just updated to v1.0.153. Unfortunately, the error persists

**Comment by lgatto** [comment]
I tried to following in R studio on my GNU/Linux laptop
```r
> library("mzR")
> x <- openIDfile("b1906_293T_proteinID_01A_QE3_122212.mzid")
> x
Identification file handle.
Filename:  b1906_293T_proteinID_01A_QE3_122212.mzid 
Number of psms:  207048 
> dim(psms(x))
[1] 207048     18
> library("MSnbase")
> iddf <- readMzIdData("b1906_293T_proteinID_01A_QE3_122212.mzid") ## new in latest MSnbase
> dim(iddf)
[1] 250989     34
```

I have RStudio Version 1.0.143 and 

```r
> sessionInfo()
R version 3.4.0 Patched (2017-06-12 r72786)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/libf77blas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
[1] MSnbase_2.3.9       ProtGenerics_1.9.0  BiocParallel_1.11.4
[4] mzR_2.11.4          Rcpp_0.12.11        Biobase_2.37.2     
[7] BiocGenerics_0.23.0

loaded via a namespace (and not attached):
 [1] IRanges_2.11.6        zlibbioc_1.23.0      
 [3] doParallel_1.0.10     munsell_0.4.3        
 [5] colorspace_1.3-2      impute_1.51.0        
 [7] lattice_0.20-35       rlang_0.1.1.9000     
 [9] foreach_1.4.3         msdata_0.17.1        
[11] plyr_1.8.4            tools_3.4.0          
[13] mzID_1.15.0           grid_3.4.0           
[15] gtable_0.2.0          affy_1.55.0          
[17] iterators_1.0.8       digest_0.6.12        
[19] lazyeval_0.2.0        tibble_1.3.3         
[21] preprocessCore_1.39.0 affyio_1.47.0        
[23] ggplot2_2.2.1         S4Vectors_0.15.5     
[25] codetools_0.2-15      MALDIquant_1.16.2    
[27] limma_3.33.3          BiocInstaller_1.27.2 
[29] compiler_3.4.0        pcaMethods_1.69.0    
[31] scales_0.4.1          stats4_3.4.0         
[33] XML_3.98-1.9          vsn_3.45.0 
```

I don't think I can do much at this stage. 

By the way, @prvst, what OS are you running?

**Comment by prvst** [comment]
@lgatto thanks for all the help anyways. I'm running a Ubuntu 17.04, but I'll try on a different system and let you know the outcome.

Thanks for all
