### ISSUE TITLE
Add phenoData to Chromatograms class

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#236]
What about adding a `pdata` slot to the `Chromatograms` object?
If we add that:
+ Ensure that subsetting also correctly sub-sets the pheno data.
+ Implement all getters and setters (i.e. `$`, `$<-`, `pData`, `pData<-`.

**Comment by lgatto** [comment]
Yes, excellent idea. Will there be an explicit relation between the dimensions of the `Chromatograms` and `phenoData` objects?

**Comment by jotsetung** [comment]
Yup, `nrow(phenoData)` has to be the same than `ncol(Chromatograms)`. I'll ensure that for all subsetting operations etc.

**Comment by jotsetung** [comment]
Made pull request https://github.com/lgatto/MSnbase/pull/239
