### ISSUE TITLE
scan number in Chromatogram object

### ISSUE THREAD

**Issue by stanstrup** [lgatto/MSnbase#238]
Would it be possible to have the scan number in the chromatogram object?
When you subset it can be useful to be able to trace back the original scan.

**Comment by jotsetung** [comment]
I thought the retention time is enough - is the scan number required? Note that the names of the individual values actually are the spectrum IDs:
```r
> rtime(chr)
F001.S0603 F001.S0604 F001.S0605 F001.S0606 F001.S0607 F001.S0608 F001.S0609 
   168.236    168.515    168.794    169.073    169.352    169.631    169.910 
F001.S0610 F001.S0611 F001.S0612 F001.S0613 F001.S0614 F001.S0615 F001.S0616 
   170.189    170.468    170.747    171.026    171.305    171.584    171.863 
F001.S0617 F001.S0618 F001.S0619 F001.S0620 F001.S0621 F001.S0622 F001.S0623 
   172.142    172.421    172.700    172.979    173.258    173.537    173.816 
F001.S0624 F001.S0625 F001.S0626 F001.S0627 F001.S0628 F001.S0629 F001.S0630 
   174.095    174.374    174.653    174.932    175.211    175.490    175.769 
F001.S0631 F001.S0632 F001.S0633 F001.S0634 
   176.048    176.327    176.606    176.885 
> intensity(chr)
F001.S0603 F001.S0604 F001.S0605 F001.S0606 F001.S0607 F001.S0608 F001.S0609 
        NA         NA         NA         NA         NA         NA         NA 
F001.S0610 F001.S0611 F001.S0612 F001.S0613 F001.S0614 F001.S0615 F001.S0616 
        NA        120        176        539        792       1040       1038 
F001.S0617 F001.S0618 F001.S0619 F001.S0620 F001.S0621 F001.S0622 F001.S0623 
       878        748        541        294        254        161        136 
F001.S0624 F001.S0625 F001.S0626 F001.S0627 F001.S0628 F001.S0629 F001.S0630 
       117         87         47         49         56         44         36 
F001.S0631 F001.S0632 F001.S0633 F001.S0634 
        46         31         NA         32 

```

These could be used to track exactly the spectrum from which the value derived:
```r
> met_pilot[["F001.S0603"]]
Object of class "Spectrum1"
 Retention time: 2:48 
 MSn level: 1 
 Total ion count: 3572 
 Polarity: 1 
```

I'm just a bit reluctant to add more slots to the `Chromatogram` object.

**Comment by stanstrup** [comment]
Ah. Thanks. I didn't notice the names. Yes that will do.

**Comment by lgatto** [comment]
Wouldn't it be useful to have an `acquisionNum` method, like we have for `Spectrum`, `MSnExp` (and now also) `MSnExp`?

**Comment by jotsetung** [comment]
In that case I have to add the a `acquisitionNum` slot to the `Chromatogram` object. I thought having the retention time is enough and wanted to keep the object as *lean* as possible. @stanstrup ?

**Comment by lgatto** [comment]
The method could also only parse the names to keep the actual object lightweight. It wouldn't be as fast as if it did access the actual acquisition numbers, but that might not matter if it isn't used too heavily.

**Comment by jotsetung** [comment]
That might do. Only, for `Chromatogram` objects without the correct names it would have to return `1:length(chr)` and show a warning.

**Comment by jotsetung** [comment]
Actually I think the spectrum ID is not always 1:1 related to the `acquisitionNum`:
according to *RcppPwiz*, the acquisitionNum is defined as the "scan number as declared in File (may be gaps)" (proteowizard is inferring this info from the id of the spectrum in the file), the spectrum ID is however build using an index from 1:number of spectra in file:
```r
        fullhdorder <- c(fullhdorder,
                          formatFileSpectrumNames(fileIds=filen,
                                                  spectrumIds=seq_along(spidx),
                                                  nSpectra=length(spidx),
                                                  nFiles=length(files)))
```
What if we used:
```r
        fullhdorder <- c(fullhdorder,
                          formatFileSpectrumNames(fileIds=filen,
                                                  spectrumIds=fData$acquisitionNum,
                                                  nSpectra=length(spidx),
                                                  nFiles=length(files)))

```
instead?
@lgatto @sgibb ?

**Comment by lgatto** [comment]
> for `Chromatogram` objects without the correct names it would have to return 1:length(chr) and show a warning.

Why would there be `Chromatogram` objects without correct names? 

I think I'm fine with what you suggest. But where (function, method?) do you suggest to apply this change?

**Comment by jotsetung** [comment]
When `Chromatogram` objects are extracted from an `MSnExp` or `OnDiskMSnExp` object they will always have *correct* names. But you can also create `Chromatogram` objects using the constructor:
```r
> chr <- Chromatogram(rt = 1:10, intensity = 1:10)
## Then they will not have names assigned
> intensity(chr)
 [1]  1  2  3  4  5  6  7  8  9 10
```
`Chromatogram` objects don't have to be necessarily linked to `MSnExp` or `OnDiskMSnExp` objects.

As far as I've seen the `formatFileSpectrumNames` is called in `readMSData` and `readMSData2`.

**Comment by lgatto** [comment]
Ok, makes sense. Thanks for the clarification.

**Comment by lgatto** [comment]
Closing; feel free to re-open if necessary.

**Comment by jotsetung** [comment]
Re-opening, because I'll still have to implement the `acquisitionNum` method for `Chromatogram` objects - depending whether `formatFileSpectrumNames` uses `acquisitionNum` instead of spectrum index.
