### ISSUE TITLE
Extracting MS level > 1 chromatogram

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#246]
`chromatogram,MSnExp` does not allow to extract `Chromatograms` for MS level > 1 yet. I didn't anticipate that this will be needed, but with SWATH data it is (see https://github.com/sneumann/xcms/issues/205).
The required code is ready in `.extractMultipleChromatograms` but I didn't add the `msLevel` argument to `chromatograms,MSnExp` (yet). 
@lgatto: OK if I add that and push to master?

**Comment by lgatto** [comment]
Yes, of course. Will `msLevel` be limited to a single level (a `numeric` of length 1) or will it support multiple levels?

**Comment by jotsetung** [comment]
good point - as of now it supports length > 1. But I'm not sure whether that's clever. Never done anything with MS level > 1. What do you think? restrict to single level?

**Comment by lgatto** [comment]
I can't think of a use case with more than on level, but I don't think that's a reason to restrict it to one level. Maybe it's good to support it, as long as it's easy to get the levels back from an `Chromatograms` object.

**Comment by jotsetung** [comment]
OK, so I'll have to add a slot `msLevel` to the `Chromatogram` class. That will then be an `integer` of length > 0.
