### ISSUE TITLE
"Error in plot.window(...) : need finite 'ylim' values" plot,Chromatograms

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#249]
`Error in plot.window(...) : need finite 'ylim' values` is thrown in `plot,Chromatograms` if none of the `Chromatogram` objects contain valid values (i.e. only `NA` intensities for the provided `rtime`).

I would like to catch this error and draw an empty plot with `ylim = c(1, 0)`. That OK with you @lgatto ?

Note: this applies also to `plot,Chromatogram`.

**Comment by lgatto** [comment]
What about an `isEmpty,Chromatogram[s]` to test the data in the plot method, and return either a message or a warning before producing an empty plot?

**Comment by jotsetung** [comment]
Good point. I'll implement `isEmpty,Chromatogram[s]`. So, the approach would be to check if the chromatogram is empty and if it is show a warning and still produce the plot (but with `ylim = c(0, 1)`.
IMHO a `plot` call should, in case there is e.g. no data, show a plot (and a warning) but not stop with an `error`.

**Comment by lgatto** [comment]
Yes, I agree that an empty plot after a warning is more friendly than an error. The plot could even have `empty chromatogram` text on it, to make it obvious.

**Comment by jotsetung** [comment]
Done - are you also pushing to Bioc at some point?

**Comment by lgatto** [comment]
Will do as I have a bit of time - tonight or tomorrow morning.

**Comment by jotsetung** [comment]
no hurry, was just asking.

**Comment by lgatto** [comment]
Well, I thought I would merge, but upstreams vs origin is a f****ing mess. No idea how it got there, and how to sort it out. It will take some time, I'm afraid...

**Comment by lgatto** [comment]
On bioc now.
