### ISSUE TITLE
Unable to find inherited method for function 'chromatogram' for signature 'MSnEXP'

### ISSUE THREAD

**Issue by NebuchadnezzaraHardrada** [lgatto/MSnbase#251]
There seems to be a problem with the chromatogram function. In some cases, the problem lies with subscripts being out of bounds and in some, the inherited method cannot be found. 
![unabletofindinheritedmethod](https://user-images.githubusercontent.com/29667095/30165467-7971490a-93e0-11e7-880e-08af84997256.PNG)
![chromatogramerror](https://user-images.githubusercontent.com/29667095/30165462-745044b2-93e0-11e7-8b1c-30cda2db59cb.PNG)

**Comment by lgatto** [comment]
We won't be able to help without your `sessionInfo()`, but the most likely explanation is that some packages are out of date. Here's some code that shows that it is supposed to work:
```r
> library("msdata")
> f <- c(system.file("microtofq/MM14.mzML", package = "msdata"),
+           system.file("microtofq/MM8.mzML", package = "msdata"))
> msd <- readMSData(f, msLevel = 1, mode = "inMemory")
> tic <- chromatogram(msd)
> tic
Chromatograms with 1 row and 2 columns
          MM14.mzML       MM8.mzML
     <Chromatogram> <Chromatogram>
[1,]    length: 112    length: 198
phenoData with 1 variables
> ## with an onDisk object, as you have above
> msd <- readMSData(f, msLevel = 1, mode = "onDisk")
> tic <- chromatogram(msd)
> tic
Chromatograms with 1 row and 2 columns
          MM14.mzML       MM8.mzML
     <Chromatogram> <Chromatogram>
[1,]    length: 112    length: 198
phenoData with 1 variables
```

**Comment by lgatto** [comment]
@NebuchadnezzaraHardrada - closing this issue for now, but please feel free to re-open it you still hit any issue.

**Comment by NebuchadnezzaraHardrada** [comment]
[XCMSErrors.txt](https://github.com/lgatto/MSnbase/files/1289854/XCMSErrors.txt)
I am using XCMS which uses some of your MSnBase functions. Maybe the problems lie with XCMS or with me as I have to admit that I am not a professional in R. Please find attached these two txt files that details the errors that I have received and also the session info that you asked for.
[SessionInfo.txt](https://github.com/lgatto/MSnbase/files/1289853/SessionInfo.txt)

**Comment by lgatto** [comment]
(Next time, please cut and past the output in the issue within code chunks, it's easier to read).

You session information seems to indicate that your system is up-to-date. It's difficult to say for sure what is wrong from your error, but looks like like you are trying to read one or more files in, one of which is `Eta6`, which is not found. 

Please, start a new console, create your `f` variable, display its content, then try to read the data in using whatever function you are using (could be `readMSData`, but it's not shown) and cut/paste everything in the issue, not only the error.

**Comment by jotsetung** [comment]
I guess this issue is related to https://github.com/sneumann/xcms/issues/218 over in `xcms`. To me it looks like you have to switch to the new developmental versions of the packages if you want to use the functionality such as `chromatogram` etc.
