### ISSUE TITLE
chromatogram performance

### ISSUE THREAD

**Issue by mjhelf** [lgatto/MSnbase#258]
Hi,

I have been playing around with the `chromatogram `function for a bit, and noticed a few things that I did not quite understand:

1. it seems like the "old" `rawEIC `function (xcms) is a lot quicker in getting EICs. The comparison may not be entirely fair because there is more information in the `Chromatogram` class than in the rawEIC- produced lists, but I am surprised at how different they are. Is `chromatogram `meant to be the replacement for `rawEIC`, or is there a different function for that (this may be a question for the xcms repository?)

2. I like that the reported intensities are the same as with the `rawEIC`, and the last scan inside the rt range is no longer missing when using `chromatogram`!

3. The biggest surprise to me, is this: `chromatogram `takes longer on `MSnExp `objects than on `OnDiskMSnExp `objects. I thought the `chromatogram `method on an `MSnExp `object would be quicker, and be more or less on par with the `rawEIC, xcmsRaw` method since both should use data from memory?

I don't know how much the performance, especially for the onDisk object, depends on the performance of the file storage? This is run on a fairly fast SSD (Samsung SSD 960 Pro), so I wonder if the performance of the `chromatogram, OnDiskMSnExp` would be much worse on, say, a HDD.

Sorry if the code is clunky & thank you! 

This is what I ran (using a single mzXML file as input, and looking for EICs for 100 features). Same behavior without  `MSnbase::` :

```
library(devtools)

dev_mode(on = T)
library(xcms)

centroidFiles <- list.files(".",
                            full.names = T,
                            pattern = ".mzXML",
                            recursive = T)

system.time({
xcmsRawObj <- lapply(centroidFiles, xcmsRaw, profstep = 0)
})

system.time({
centroidFilesObj <- readMSData(centroidFiles, pdata = NULL, verbose = isMSnbaseVerbose(),
                          centroided. = T,
                          smoothed. = NA, mode = "onDisk")
})

system.time({
centroidFilesObjMem <- readMSData(centroidFiles, pdata = NULL, verbose = isMSnbaseVerbose(),
                               centroided. = T,
                               msLevel. = 1,
                               smoothed. = NA, mode = "inMemory")
})

testpeaks <- data.frame(mz = rep(c(201:300),1),#abs(rnorm(100,500,10)),
                        rt = rep(c(201:300),1))
rts <- matrix(c(testpeaks$rt-5, testpeaks$rt+5), ncol = 2)
mzs <- matrix(c(testpeaks$rt-5, testpeaks$rt+5), ncol = 2)



pt_xcmsRaw <- proc.time()
##make lists for mapply to work correctly  
rtl <- unname(as.list(data.frame(t(rts))))
mzl <- unname(as.list(data.frame(t(mzs))))

rawEICresult = list()
for(i in 1:length(xcmsRawObj)){
rawEICresult[[i]] <- mapply(rawEIC, mzrange = mzl, rtrange = rtl, MoreArgs = list(object = xcmsRawObj[[i]]), SIMPLIFY = F)
}

pt_xcmsRaw <- proc.time() - pt_xcmsRaw

pt_onDisk <- proc.time()
#This works:
centroidOndiskchrom <- MSnbase::chromatogram(centroidFilesObj,
                                          rt = rts,
                                          mz = mzs, 
                                          BPPARAM = SerialParam(),#SnowParam(workers = 1),
                                          missing = 0,
                                          aggregationFun = "sum")
pt_onDisk <- proc.time() - pt_onDisk

pt_inMem <- proc.time()
centroidInmemchrom <- MSnbase::chromatogram(centroidFilesObjMem,
                                          rt = rts,
                                          mz = mzs, 
                                          BPPARAM = SerialParam(),#SnowParam(workers = 1),
                                          missing = 0,
                                          aggregationFun = "sum")

pt_inMem <- proc.time() - pt_inMem

pt_xcmsRaw
pt_onDisk
pt_inMem
```

Times to generate the EIC or chomatogram outputs (typically in this range when repeated):
```
pt_xcmsRaw
   user  system elapsed 
   0.04    0.00    0.05 
d> pt_onDisk
   user  system elapsed 
   0.36    0.00    0.39 
d> pt_inMem
   user  system elapsed 
   1.09    0.00    1.12 
```
Extracting from two files (for 100 features) roughly doubles times for running both `chromatogram` s, while the time for rawEIC is not much different:

```
pt_xcmsRaw
   user  system elapsed 
   0.03    0.00    0.05 
d> pt_onDisk
   user  system elapsed 
   0.63    0.02    0.69 
d> pt_inMem
   user  system elapsed 
   2.12    0.00    2.16 
```

This is the result with 1000 features from one file (instead of 100) (more or less stable when rerun a couple times):

```
pt_xcmsRaw
   user  system elapsed 
   0.06    0.00    0.07 
d> pt_onDisk
   user  system elapsed 
   1.97    0.02    1.98 
d> pt_inMem
   user  system elapsed 
   2.66    0.01    2.72 
```

Loading the files was also relatively slow for the `MSnExp` (inMemory) object (here: loading only one file):
```
system.time({
+xcmsRawObj <- lapply(centroidFiles[1], xcmsRaw, profstep = 0)
+})
   user  system elapsed 
   2.83    0.12    2.95 
d> 
d> system.time({
+ centroidFilesObj <- readMSData(centroidFiles[1], pdata = NULL, verbose = isMSnbaseVerbose(),
+                           centroided. = T,
+                           smoothed. = NA, mode = "onDisk")
+ })
   user  system elapsed 
   0.75    0.08    0.83 
d> 
d> system.time({
+ centroidFilesObjMem <- readMSData(centroidFiles[1], pdata = NULL, verbose = isMSnbaseVerbose(),
+                                centroided. = T,
+                                msLevel. = 1,
+                                smoothed. = NA, mode = "inMemory")
+ })
   user  system elapsed 
  14.95    0.11   15.09 
```

Here is the printout for `centroidFilesObjMem`. Other reported memory usages: 54 MB for `xcmsRawObj` and 0.71 MB for `centroidFilesObj`

```
MSn experiment data ("MSnExp")
Object size in memory: 61.41 Mb
- - - Spectra data - - -
 MS level(s): 1 
 Number of spectra: 2290 
 MSn retention times: 0:0 - 20:1 minutes
- - - Processing information - - -
Data loaded: Mon Sep 18 17:30:40 2017 
 MSnbase version: 2.3.11 
- - - Meta data  - - -
phenoData
  rowNames: 170811AA27.mzXML
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  170811AA27.mzXML 
protocolData: none
featureData
  featureNames: F1.S0001 F1.S0002 ... F1.S2290 (2290 total)
  fvarLabels: spectrum
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)
```

sessionInfo():
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xcms_2.99.7         MSnbase_2.3.11      ProtGenerics_1.9.0  mzR_2.11.8          Rcpp_0.12.12        BiocParallel_1.11.8
[7] Biobase_2.37.2      BiocGenerics_0.23.1 devtools_1.13.3    

loaded via a namespace (and not attached):
 [1] compiler_3.4.1         BiocInstaller_1.27.4   RColorBrewer_1.1-2     plyr_1.8.4             iterators_1.0.8       
 [6] tools_3.4.1            zlibbioc_1.23.0        MALDIquant_1.16.4      digest_0.6.12          memoise_1.1.0         
[11] tibble_1.3.4           preprocessCore_1.39.3  gtable_0.2.0           lattice_0.20-35        rlang_0.1.2           
[16] Matrix_1.2-10          foreach_1.4.3          withr_2.0.0            S4Vectors_0.14.4       IRanges_2.11.15       
[21] multtest_2.33.0        stats4_3.4.1           grid_3.4.1             impute_1.51.0          survival_2.41-3       
[26] XML_3.98-1.9           RANN_2.5.1             limma_3.33.9           ggplot2_2.2.1          MASS_7.3-47           
[31] splines_3.4.1          scales_0.5.0           pcaMethods_1.69.0      codetools_0.2-15       MassSpecWavelet_1.43.0
[36] mzID_1.15.0            colorspace_1.3-2       affy_1.55.0            lazyeval_0.2.0         munsell_0.4.3         
[41] doParallel_1.0.10      vsn_3.45.2             affyio_1.47.1         
```

**Comment by lgatto** [comment]
Thank you for this thorough issue. 

I can't really comment on the comparison with `rawEIC`, and how current code in `MSnbase` is going to influence `xmcs` in the future. @jotsetung will be the right person to chime in.

Regarding `MSnExp` and `OnDiskMSnExp`, the latter is the object that is going to be developed in the future. The former is very slow, and doesn't scale for many files when MS1 data is needed. It is a viable route for MS2 only (which is relevant for proteomics, the first use case that it was meant to address).

I am not that surprised that `OnDiskMSnExp` is faster than `MSnExp` (in memory) for `chromatogram`. `OnDiskMSnExp` is written in a way to be fast and supports parallel processing whenever possible. For example, looking at the `chromatograms` code, there's only one place where `OnDiskMSnExp` will take a hit in terms of speed (while still being better in terms of memory); that's when calling `spectra(...)`. That function creates a list of spectra, either from memory, or from disk. The latter is of course slower, but all the processing is then done in parallel. 

I am not sure one can predict when on disk is faster then in memory. It depends on the number of spectra (at some point, on disk will become slower), although the memory footprint might also, at some point, counterbalance that. The important point is that for modern experiments, with many files, in memory just doesn't scale, or requires hardware that most users don't have access to.

Finally, in terms of SSD performance, we didn't see any major difference with hard drives (see the [`benchmaking` vignette](https://lgatto.github.io/MSnbase/articles/benchmarking.html) and search for SSD or HDD), although more tests with bigger data would probably be useful.

We could set up more thorough tests with bigger data and more use cases to explore the impact of on disk access, if desirable.

**Comment by jotsetung** [comment]
Nice observation @mjhelf !
Regarding 1) yes, the idea is that the `chromatogram` function replaces the `rawEIC,xcmsRaw`. While it has a lower performance than the `rawEIC` we put some brainwork in designing the `Chromatogram` and `Chromatograms` classes that I think make them superior despite the potentially lower speed. Also, the `chromatogram` method is supposed to replace the `getEIC,xcmsSet` method (that did extract chromatograms from the *profile* matrix). So, we have now one method in place instead of two, and this one does extract ion chromatograms from multiple files at once and returns them in a two-dimensional array (`Chromatograms` object) that is easy to handle/subset and contains also the phenodata from the originating object.

Regarding the observation that `chromatogram` is slow for `MSnExp`:
The `chromatogram` method was tuned for `OnDiskMSnExp` objects and the same function is called for `MSnExp` too. I could implement a faster version for `MSnExp`-only that takes more advantage of the data being stored in memory but so far I have focused more on the `OnDiskMSnExp` objects.

`rawEIC` is really fast as it is implemented in `C` and directly accesses the data stored in the `xcmsRaw` (which is somewhat comparable to a `MSnExp` - at least I'll replace the `xcmsRaw` by he `MSnExp`/`OnDiskMSnExp` in the new `xcms` user interface). Also, it does return a simple R `list`. One reason we're slower is that we're creating `S4` classes instead of basic R data types, but that should have only a smaller impact on performance.

I repeated the speed tests again with a more realistic example: for LCMS experiments with many samples you don't want to keep the raw data in memory, thus I'm forcing below also the raw data to be read using `xcmsRaw` **within** the function that calls `rawEIC`:
```r
library(xcms)
library(microbenchmark)
file <- system.file(package = "msdata", "microtofq/MM8.mzML")

in_mem <- readMSData(file, mode = "inMem", msLevel = 1)
on_disk <- readMSData(file, mode = "onDisk")
xraw <- xcmsRaw(file, profstep = 0)

## Define MS slices - 20 in total
mzr <- matrix(c(201:220 - 0.2, 201:220 + 0.2), ncol = 2)
rtr <- matrix(c(11:30 - 5, 11:30 + 5), ncol = 2)

mzl <- split.data.frame(mzr, 1:nrow(mzr))
rtl <- split.data.frame(rtr, 1:nrow(rtr))

onDiskRawEIC <- function(file, rt, mz) {
    xr <- xcmsRaw(file, profstep = 0)
    mapply(FUN = rawEIC, mzrange = mz, rtrange = rt, MoreArgs = list(object = xr), SIMPLIFY = FALSE)
}

microbenchmark(chromatogram(in_mem, rt = rtr, mz = mzr), chromatogram(on_disk, rt = rtr, mz = mzr), onDiskRawEIC(file, rt = rtl, mz = mzl), times = 5)

Unit: milliseconds
                                      expr      min       lq     mean   median
  chromatogram(in_mem, rt = rtr, mz = mzr) 554.0659 555.2493 558.8991 560.5340
 chromatogram(on_disk, rt = rtr, mz = mzr) 165.1105 169.1875 169.8773 169.6301
    onDiskRawEIC(file, rt = rtl, mz = mzl) 559.4036 565.8325 568.5937 567.9948
       uq      max neval cld
 561.0386 563.6077     5  b 
 171.7850 173.6731     5 a  
 571.8093 577.9286     5   c

```

This actually illustrates when `chromatogram,OnDiskMSnExp` can outperform all others: the method first identifies the spectra that contain the data for any of the provided `rt` ranges, then it loads just these spectra from the files and processes them (i.e. filters on the `mz` ranges). In other words, the function first filters the `OnDiskMSnExp` object by the retention time ranges, then it loads the raw data for the corresponding spectra as `Spectrum` objects and filters them by the provided mz ranges. This reading of selected spectra is much faster than loading the full raw data and processing from there.
The `C` code running on already pre-loaded raw data would however beat all.

**Comment by jotsetung** [comment]
Do you need any more information or is anything unclear @mjhelf ? 
If not, can I proceed to close the issue?

**Comment by jotsetung** [comment]
Closing issue. Feel free to re-open if anything is unclear/missing @mjhelf
