### ISSUE TITLE
Writing/exporting raw data objects 

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#259]
This discusses naming the function in PR #257, also discussed [here](https://stat.ethz.ch/pipermail/bioc-devel/2017-September/011671.html). Current suggestions are

1. `write` - Jo's first choice
2. `writeMSData` as a generic with methods in `mzR` and `MSnbase`
3. `export` - suggested on bioc-devel

Please share you opinions/votes below.

**Comment by lgatto** [comment]
Given the feedback on bioc-devel, I suggest we drop `write`. 

From a user's perspective, I think `writeMSData` fits well with `readMSData`. Also, the equivalent of `export`, would be `import`, which we don't use. I think having `writeMSData` in `mzR` makes me want this option even more, as we would keep the naming consistent across packages. 

So my vote would go for 2.

Quick question - what would be the difference in writing an `MSnExp` object and an `mzRpwiz` object?

**Comment by jotsetung** [comment]
Jup, let's drop `write`. I tend to 3 (`export`) - for 2 we have to make `writeMSData` a generic with arguments becoming potentially tricky:
+ `writeMSData` in `mzR` needs: `files` (`character`), `header` (`data.frame`) and `data` (`list`).
+ `writeMSData` in `MSnbase` does not have a `header`. We would need to make the generic as `writeMSData` `signature(data = "MSnExp", file = "character")`... thinking it over its doable. So OK for me to go for that.

**Comment by lgatto** [comment]
We could have 
```r
setGeneric("writeMSData", function(object, file, ...) standardGeneric("writeMSData"))
```
and then in `mzR`
```r
setMethod("writeMSData", 
           c("list", ## list of spectra
             "character", ## file name 
             "data.frame", ## header 
             ...) 
   function(object, filenames, header) { ... })
```
and in `MSnbase`
```r
setMethod("writeMSData", 
           c("MSnExp", ## list of spectra
             "character", ## file name 
             ...) { 
  function(object, files) {
    header <- fData(object)
     ...
})
```

By the way, I would prefer `filename` rather than `filenames`, given #257.

**Comment by jotsetung** [comment]
OK, let's go for that - do you add the generic to `ProtGenerics` @lgatto ?

**Comment by jotsetung** [comment]
Made a pull request in `ProtGenerics`: https://github.com/lgatto/ProtGenerics/pull/5

**Comment by lgatto** [comment]
Merged. Will push to bioc asap (but I'm at a meeting whole day).

**Comment by lgatto** [comment]
Done
