### ISSUE TITLE
processingData slot is overwritten by initialize,MSnSet 

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#264]
Currently `initialize` overwrites the `processingData` slot of `MSnSet` objects (inherit from `pSet`). Is that expected?

https://github.com/lgatto/MSnbase/blob/69d68e68afdb3cb07513aa24937e6cfddc10f1e5/R/methods-MSnSet.R#L43

That's why something like this is necessary:

https://github.com/lgatto/MSnbase/blob/69d68e68afdb3cb07513aa24937e6cfddc10f1e5/R/quantitation-MS2-isobaric.R#L58-L67

IMHO the following should work:
```r
new("MSnSet", processingData=new("MSnProcess", processing="Created"))
```

Is there any reason for overwriting the `processingData` slot?

**Comment by lgatto** [comment]
No, there isn't any good reason indeed, and a patch would be welcome.
