### ISSUE TITLE
protocolData in quantify_MSnExp are always dropped

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#265]
While looking through the code to fix #264 I found the following:

https://github.com/lgatto/MSnbase/blob/edcf4bd972faebfa9663101e89a35b9f6d66cf0f/R/quantitation-MS2-isobaric.R#L69-L76

As far as I understand the `protocolData` are always dropped? I suppose that should not be the case.

**Comment by lgatto** [comment]
No, I don't think it's always dropped. It is only of its dimensions don't  match any more. For example if one starts with one raw files, there's a `protocolData` slot documenting one sample/file, but then quantifies with iTRAQ4-plex, which produces quantitation data for 4 samples. In such a case, the `protocolData` will only be retrained if it had 4 rows. 

To be honest, I don't think this slot is used much.

**Comment by sgibb** [comment]
If the dimensions match `protocolData` are assigned to `.protocolData`. But `.protocolData` is never used, so in fact the information is lost.

> To be honest, I don't think this slot is used much.

Me, neither.

**Comment by lgatto** [comment]
Indeed, something like this is missing 
```r
msnset@protocolData <- .protocolData
```
Thank you for spotting! Feel free to send a PR, or I can quickly do it.

**Comment by lgatto** [comment]
Thank you.
