### ISSUE TITLE
Write support in Bioconductor 3.6 release

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#267]
I was wondering what features should all go into the Bioconductor 3.6 release?

Should the write support be added? If yes, I see only little chance to implement a stable version of the *save multiple input file into a single mzML* file in the next weeks. See also https://github.com/lgatto/MSnbase/issues/257.

**Comment by lgatto** [comment]
I think we should have a vote about this. My preference would probably be to be able to write everything back into a single file, but that is only personal and I think that we probably want both options if, among 3 developers, both solutions are preferred. 

My main question is whether providing official/stable write support for only one option is the best approach, or aren't we incurring a risk of providing the ~~wrong~~ less popular option (you know how it is, users will always ask for the other one, whichever is available ;-). On the other hand, providing one option will provide wider exposure and testing to write support. 

So here we go, if you, as a developer or user have a opinion, please vote for 

- we release write support for multiple file now an for a single file later: upvote this comment +1 (thumps up)
- we wait and release both write support options at once: downvote this comment -1 (thumps down)

**Comment by jotsetung** [comment]
Although it's not a very large number of votes (4) it seems we agree all on option 👍 
In the meantime I fixed the merge conflicts in the https://github.com/lgatto/MSnbase/pull/253 PR

**Comment by lgatto** [comment]
Yes, 4 is one more than the 3 core developers, so that's good. I will continue my review and do a couple of tests in the coming days.
