### ISSUE TITLE
Force absolute file paths for OnDiskMSnExp

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#270]
I would suggest to call `normalizePath(files)` in the `readOnDiskMSData` function to replace relative file paths with absolute paths (in addition to replace `~` with the user's home directory).
Reason: on Windows it can happen with SNOW parallel processing that the spawned R process is executed in a different folder and the process will not find the file.
On Unix systems it can also happen that some calls to proteowizard fails because it can not find the file/does not understand the path (happened to me with `~`).

**Comment by lgatto** [comment]
Yes, good suggestion. If you have time, feel free to amend and push immediately to master. This is probably something to do for other `read*` functions too.

**Comment by jotsetung** [comment]
I pushed to master. I think the other `read*` functions should be OK, it is however critical for `OnDiskMSnExp` since the raw data will be read multiple times (in parallel) from the original files during an analysis.

**Comment by lgatto** [comment]
Ok, thanks. Feel free to close then.
