### ISSUE TITLE
Reading files depends on filename extension

### ISSUE THREAD

**Issue by sneumann** [lgatto/MSnbase#275]
Hi, determining the file type depends on the filename extension. 
In galaxy workflows, input data is unfortunately passed as "something.dat":
```
> MS2RawFile<-readMSData("MM8.mzML", msLevel=1)
> MS2RawFile<-readMSData("MM8.dat", msLevel=1)
Error in .mzRBackend(x) : Could not determine file type for MM8.dat
```
We had the same issue in xcms: 
https://github.com/sneumann/xcms/issues/188 
and @jotsetung implemented a fix in https://github.com/sneumann/xcms/commit/7ef70598754cffc9e896ddb3358f62471e0d16cb

It might even make sense to move the implementation 
of `mzRBackendFromFilename` etc. into mzR itself.

Yours, Steffen

**Comment by jotsetung** [comment]
The trick was to read the first few lines of input if the extension was not recognized and look for some keywords there. I can make a pull request for that.

**Comment by sgibb** [comment]
IMHO @sneumann is right. The whole `mzRBackendFrom*` stuff should be part of `mzR`.

**Comment by lgatto** [comment]
Yes, fine by me to move it to `mzR`; it does make sense indeed.

**Comment by jotsetung** [comment]
Reopening because support is not yet in `MSnbase`
