### ISSUE TITLE
question: orbitrap scans information from scanList XML node

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/MSnbase#278]
I am looking at the mzML of an Orbitrap scan and it seems there is a whole XML node that contains the information on ion injection time, mz range and the filter string, as shown below 

         <scanList count="1">
            <cvParam cvRef="MS" accession="MS:1000795" name="no combination" value=""/>
            <scan>
              <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="0.001043266933" unitCvRef="UO" unitAccession="UO:0000031" unitName="minute"/>
              <cvParam cvRef="MS" accession="MS:1000512" name="filter string" value="FTMS + p NSI Full ms [380.0000-1400.0000]"/>
              <cvParam cvRef="MS" accession="MS:1000927" name="ion injection time" value="4.575656414032" unitCvRef="UO" unitAccession="UO:0000028" unitName="millisecond"/>
              <scanWindowList count="1">
                <scanWindow>
                  <cvParam cvRef="MS" accession="MS:1000501" name="scan window lower limit" value="380.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                  <cvParam cvRef="MS" accession="MS:1000500" name="scan window upper limit" value="1400.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </scanWindow>
              </scanWindowList>
            </scan>
          </scanList>

This is extremely valuable information, but does it get loaded into the spectrum?

**Comment by sgibb** [comment]
I have no file to test it but I guess *"filter string"* isn't part of the `data.frame` returned by `mzR::header`.

If I am correct it has to be added to `mzR` (if the `mzR` developers like this feature, CC: @sneumann, @jotsetung)

As workaround we could use some kind of XPath extraction as we did with ion injection time before (see e.g.: https://github.com/sneumann/mzR/issues/29#issuecomment-179979357 and https://github.com/lgatto/MSnbase/commit/7aab7fe79d26c4c0f1ff018a8a522b1fc0ef05d0).

**Comment by sneumann** [comment]
Indeed, pwiz extracts these as part of the SpectrumInfo:
https://github.com/sneumann/mzR/search?utf8=%E2%9C%93&q=filterString&type=

The `filterString` handling would have to be added to https://github.com/sneumann/mzR/blob/9fcdcb46cd792acfa474ba85775d918adbc0ceb3/src/RcppRamp.cpp#L137
What about other vendor files ? Include `filterString` only for Thermo, or leave empty for other instruments ?

An Orbitrap file for the unit test is in R package `msdata/proteomics/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz`

Yours,
Steffen

**Comment by lgatto** [comment]
I won't have time to add this myself, but would consider a PR with a quick XPath-based hack in `MSnbase` or, preferably, an update to `mzR`.

**Comment by jotsetung** [comment]
An update to `mzR` wouldn't be that difficult. We are already extracting the *MS_ion_injection_time*, we could extract in addition also the *filter string* (as a `character`). So, return the string if it's there and `NA` otherwise.

**Comment by sgibb** [comment]
I am willing to implement this. Unfortunately I have no experience with Rcpp, so I will need some help. I started a WIP PR: https://github.com/sneumann/mzR/pull/140
