### ISSUE TITLE
Required fvarLabels

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#283]
Allow to only create a subset of required feature variables from the header. this should be possible on object construction (as an argument to `readMSData` and as a function).

**Comment by jotsetung** [comment]
Extending on it:
+ `readMSData` allows to manually specify wanted `fvarLabels` - by default use all columns returned by `mzR::header`.
+ `reduceFvarLabels` (or `reduceFeatureData`) to remove eventually un-necessary columns from the `featureData`.

**Comment by jotsetung** [comment]
Note: this will only work for `OnDiskMSnExp`.

**Comment by jotsetung** [comment]
I would define a variable with the absolutely necessary column names for the `featureData`:
```r
.OnDiskMSnExpReqFvarLabels <- c("fileIdx", "spIdx", "acquisitionNum",
                                "retentionTime", "msLevel")
```
Is there anything missing from your side @lgatto @sgibb ?

**Comment by lgatto** [comment]
> Note: this will only work for `OnDiskMSnExp`.

Yes, that makes sense, but could we name the vector `.MSnExpReqFvarLabels`.

Regarding the function name to do this, what about `filterFvarData`/`filterFeatureData` (it does filtering along the feature variable columns, just like other filter functions do along the lines) or `keepFvarData`/`keepFeatureData`, or `selectFeatureData`. I am not convinced about *reduce*, that already has a meaning in the package. 

There happen to already exist a [`selectFeatureData` function](https://github.com/lgatto/MSnbase/blob/master/R/functions-MSnSet.R#L237), which allows the user to select which ones to keep if no `fcol` is missing (default). This function could probably be moved out of the `functions-MSnSet` file it currently lives in (`utils.R` is probably a good place), and amended so that if `object` is an `MSnExp` and `fcol` is missing, `fcol` is set to `MSnExpReqFvarLabels`.

**Comment by sgibb** [comment]
Considering #282 I would also like to keep `precursorScanNum` per default (especially for `OnDiskMSnExp` objects).

> Note: this will only work for OnDiskMSnExp.

But the function `filterFeatureData` should work for `MSnExp` as well. Because at least `FilterString` etc. will be part of the `featureData` of an `MSnExp` object, or?

**Comment by jotsetung** [comment]
OK, added `precursorScanNum` to the required `fvarLabels`.

Fun thing is that the `selectFeatureData` function did already work for `OnDiskMSnExp` as it is completely class-agnostic and works with any object with `featureData` and `featureData<-`. I did only implement a `requiredFvarLabels` function and subsetting to the minimal required `fvarLabels` is now as simple as:
```r
selectFeatureData(on_disk, fcol = requiredFvarLabels(class(on_disk)))
```
alternatively, one can use @lgatto's awesome interfaces to pick the columns.


> But the function filterFeatureData should work for MSnExp as well. Because at least FilterString etc. will be part of the featureData of an MSnExp object, or?

Nope, the `readMSData(mode = "inMem"` does not add additional columns returned by `mzR::header` to the `fData`. This means also that any additional columns such as `FilterString` are currently **only** available/returned for `OnDiskMSnExp`.

**Comment by sgibb** [comment]
> Nope, the readMSData(mode = "inMem" does not add additional columns returned by mzR::header to the fData. This means also that any additional columns such as FilterString are currently only available/returned for OnDiskMSnExp.

Thanks for the clarification. I didn't remember the code anymore.
