### ISSUE TITLE
Extend pickPeaks method/improve centroiding

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#291]
That's something we (@SiggiSmara and me) are currently working on. On our (UP)LC-MC we get after centroiding quite some scattering of the m/z values for the same ions in consecutive scans. This can be seen e.g. in the plot below, which represents the signal for histidine after doing a simple `pickPeaks` on the profile mode data. From one to the next scan, the centroid jumps between discrete values (lower panel), some of them being close to the theoretical m/z (the red dashed line), some not.
![untitled](https://user-images.githubusercontent.com/5506112/34102072-149202c4-e3e8-11e7-8c8b-cbf9c576a3d9.png)

Centroiding using the manufacturer's software is no option for us, since that's even worse (we have an AB Sciex instrument). Also Proteowizard's mass spec wavelet-based approach isn't working either.

Taking simply the maximum signal for each mass peak might not be ideal, so that's why I've started adding functionality to the `pickPeaks` method (`centroiding` branch) that does some *m/z refinement* of the reported centroid (and indeed improves accuracy of our data). Currently it refines the m/z by reporting an intensity-weighted average m/z value based on multiple signals close to the centroid/maximum value per mass peak.

Currently I've implemented this with an additional parameter `refineMz` to the `pickPeaks` method that allows to specify the name of a function to apply for m/z refinement, with additional arguments being passed using `...`. This is however not ideal, since, e.g. typos like `refineMZ` instead of `refineMz` are silently accepted by `pickPeaks`.

@lgatto , @sgibb , any thoughts on that?

**Comment by lgatto** [comment]
If I understand, the `refineMz` function is called after peak picking. 

I am not sure what you mean by silently accepted - do you rather mean silently ignored without informing the user that they misnamed a named parameter. I don't think there's anything to be done about this, and it is a known annoyance. 

One option I can think of would be to have a `refineMz` method. It is a different operation than purely peak picking, so conflating both is a source of confusion.  

Also, in your code, while you are at it, could you add a call to `logging` in `prickPeak,MSnExp`, to log the processing (it even seems to be missing now).

**Comment by jotsetung** [comment]
Sorry, I didn't explain it properly:
The m/z refinement has to be done during the peak picking, because it needs the full profile mode data (m/z values and intensities). See https://github.com/lgatto/MSnbase/blob/centroiding/R/functions-Spectrum.R#L404:L460, with `refineMz` being a a parameter to the `pickPeaks` method and taking the name of a *refinement function* (such as `kNeighbors`, https://github.com/lgatto/MSnbase/blob/centroiding/R/functions-Spectrum.R#L655:L666).

> I am not sure what you mean by silently accepted
Exactly, I meant what you described.

Re `logging`, I'll do. 
Btw, I like your typo, we should also implement a `prickPeaks` 😄

**Comment by lgatto** [comment]
I looked at the code and saw it was called at the end of the function, but failed to see that it uses unaltered peak data. 

The silent `...` passing is annoying, but I am unsure we can (or should) really guard against typos. Maybe an option would be to have `refineMzArgs = list()` argument, and you would then call 
```r
pks <- do.call(refineMz, args = append(list(mz, int, peakIdx), refineMzArgs))
```
This would also allow to have dedicated parameters for other parts of the peak picking.

PS: stupid typo fixed now :-)

**Comment by jotsetung** [comment]
> I looked at the code and saw it was called at the end of the function, but failed to see that it uses unaltered peak data.

The `pickPeaks_Spectrum` is supposed to take a `Spectrum` object with profile data and return a `Spectrum` object with only the centroids reported for each mass peak (i.e. it's m/z and intensity value). What the `refineMz` functions do is to take the same data (profile m/z, intensity) as well as the positions of the centroids in the spectrum and calculate a *refined* m/z for each centroid based on m/z and intensity values of neighboring signals to the centroid. The refined m/z is simply an intensity-weighted averaged m/z . Because it needs the profile intensity and m/z values it can not be called after `pickPeaks`. It complicates the `pickPeaks` method a little, but I think we could live with that.

Yes the `refineMzArgs` approach might do it. It definitely helps to separate arguments.

**Comment by SiggiSmara** [comment]
I would then also do the same (i.e. SNRArgs = list() )  for the signal to noise arguments for pickPeaks_spectrum. That would also encourage users to think about what arguments are going to be used in which context.

**Comment by lgatto** [comment]
But I would also like to emphasise that have such a list of arguments is an additional burden for users. Instead of 
```r
pickPeaks(x, refineMz = "kNeighbors", arg1 = 1, arg2 = 2)
```
they will end up typing
```r
pickPeaks(x, refineMz = "kNeighbors", refineArgs = list(arg1 = 1, arg2 = 2))
```
which is, considering that what triggered the discussion was user typos, possibly counterproductive. 

(And, by the way, I have followed the convention to use either UK spelling, or support UK and US - would you consider `kNeighbours` and `kNeighbors`?)

**Comment by jotsetung** [comment]
OK, having a `list` encapsulating arguments might indeed not be that user friendly. I will check if I can come up with some crazy checking of the `...`.

And yes, I'll do a `kNeighbours` and `kNeighbors` 👍

**Comment by SiggiSmara** [comment]
I see your point @lgatto. The function is growing complicated. There are optional parameters passed to both estimateNoise_Spectrum as well as related to the refineMz addition. But your example simplifies the problem of calling the function since there are other parameters to pass to it as well. 
My suggestion to simplify things would be to move even more of the parameters into lists. I find something like the following quite readable and also clear in terms of what you are wanting to get out of the function.:

```
my_snrArgs = list (SNR=3, method="SuperSmoother", arg1_snr=1, arg2_snr=2)
my_refineArgs = list (method="kNeighbors", arg1_refine = 1, arg2_refine = 2)
pickPeaks(x, halfWindowSize =2, snrArgs = my_snrArgs,  refineArgs= my_refineArgs)
```

**Comment by jotsetung** [comment]
IMHO the lack of defaults for the parameters might be another problem/complication with the approach to encapsulate parameters into `list`s.

In the end, even if we have many parameters, users will usually not change many or all of them. So, after first favoring the `list` encapsulation I'm no longer convinced it improves usability.

**Comment by SiggiSmara** [comment]
You guys, @jotsetung and @lgatto,  are the experts in how things works better in R, I trust your judgement. Just have some hankies ready when I come crying and my script is not working :wink:

**Comment by lgatto** [comment]
It might be useful to reformulate the question in the following way

> Peak picking can be a difficult operation involving actual peak picking, and also m/z refining, and might even be influenced by prior smoothing. There is a need for users to identify an appropriate set of methods and parameters.

This essentially points to the need for a way to sensibly optimise the signal processing and peak picking pipeline. If you have a way to tell good from bad sets of parameters, then the question above could be framed and implemented in proper code. In other words, we could have something along the lines of
```r
p <- MsProcessingParams() ## sensible sets of default params
p <- testMsProcessingParams(msnexp, p)
summary(p) 
plot(p)
px <- getParams(p)
msexp <- smooth(msexp, px)
msexp <- pickPeak(msexp, px)
```

**Comment by sgibb** [comment]
@lgatto Prior testing/optimizing of the processing arguments would be great!

@jotsetung / @SiggiSmara : Maybe we could circumvent the current problem by avoiding `...` for `estimateNoise`. `estimateNoise` currently supports just two methods: MAD, SuperSmoother. The MAD method has no additional arguments and the only one that is useful/used for SuperSmoother (`supsmu`) is the `span` argument. So we could set a default `span` that is removed if `method == "MAD"`. That would allow you to use `...` for `refineMz`.

BTW: you could use `pmatch` to allow partial matching on `...` in your `dots <- list(...); dots <- dots[!names(dots) %in% c("k", "signalPercentage", "stopAtTwo")]` evaluation.

**Comment by jotsetung** [comment]
Agree that prior testing would be great - is doable if one knows what to expect in the data. For our data where I know what ions to expect and what m/z they should have it could be done. I'm just not sure if that can be generalized. The `IPO` Bioconductor package does parameter optimization for `xcms` settings.

Re removing `...` from the `estimateNoise`: that would be a possibility @sgibb 
And thanks for the hint with the `pmatch`

**Comment by lgatto** [comment]
Ah yes, I had forgotten about `IPO`! Is this something we could emulate, re-use or improve, but make it applicable to `[OnDisk]MSnExp` as well al metabolomics and proteomics?

**Comment by jotsetung** [comment]
The principle is simple - so emulating/re-using the concepts might be possible. Point is that there is the need of positive controls in each experiment/file, being it ions being present or similar (internal controls). No idea if that can be generalized to proteomics experiments, for metabolomics it seems to be possible - for certain types of samples.

Another thing to keep in mind is that optimizations like performed in `IPO` try to optimize the recovery/detection of known ions (optimize the *true positives*) but do not control the *false positives*.

**Comment by lgatto** [comment]
Defining a set of true positives/control ions (and false negatives, i.e. missing control ions) will also work for proteomics (or at least some experiments); false positives and true negatives will always be more difficult. An additional point with the current infrastructure, is that we will be able to design a nice graphical (shiny) interface to visualise the control ions at the raw data in addition to the usual performance metrics.

This might just be an idea for the future, and not the right thing at the moment.

**Comment by jotsetung** [comment]
I like the idea very much and I think it will be highly appreciated by users both from the metabolomics and proteomics world but you're right, we should first focus on implementing all the infrastructure (`smooth` is already there, `pickPeaks` too, and some initial m/z refinement options too) and gain a little experience (ideally on different data sets) to derive good measures to compare settings.

We could also ping here @stanstrup - he did also test some approaches to perform centroiding in R/MSnbase.

**Comment by SiggiSmara** [comment]
Well there are databases of common background ions such as the [maconda](http://www.maconda.bham.ac.uk/about.php) that we can explore using for this purpose. Not every mass spec is going to see the same ones but every mass spec should see enough of them to use as template for evaluating the various settings.

**Comment by SiggiSmara** [comment]
Another approach is to first figure out how to detect background ions in the profile data (based on percent presence in all spectra for instance). You would not know the accurate mass of those unless they are in the known background ion lists/databases but assuming that your instrument is calibrated and behaves in a stable manner (no great mass fluctuations on the time scale of a single run) you can also develop statistics on centroided m/z values for all background ions and use that to compare the results of different setting. The challenge here would be how to detect background ions in profile spectra.

But I agree with the rest of you, better to first focus on laying the foundation for this by finalizing the underlying functions for processing spectra and then layer something like optimization on top of that in a second moment.

**Comment by Tony-II** [comment]
Would it be possible to have the rectangle as shown by jorainer  (https://github.com/lgatto/MSnbase/issues/291#issue-282838271) always included and plotted in the function MSnbase::plotXIC_MSnExp?

We also facing the centroidisation issue on a AB Sciex 5600 TripleToF instrument, and compared the non-centroiding, proteowizard centroiding and the MSnbase-centroiding functions ... 
This visualisation function here is for exploratory purposes extremely useful (for both the R-users as well as the analytical experts) to see/recognize their substances via these wonderful plots (RT of chromatographic peak at the top, m/z behaviour and the borders rectangle at the bottom).

I also posted this to the metabolomics forum, where I got a putative workaround, but was suggested to place a _feature request_ to the maintainers (http://www.metabolomics-forum.com/index.php?topic=1313.0). So I did ...

**Comment by jorainer** [comment]
The problem is that the rectangle shown in the plot can not be estimated from the data but has to be provided externally - and that is a problem. We would have to add an additional parameter that would allow to specify an m/z and/or rt range to highlight in each plot... I'll think of it and try to come to a solution.

**Comment by Tony-II** [comment]
Many thanks for this indeed. Please allow an additional remark on this which came up to me ...
When there are multiple files present, than only the last file has the abline(..) for the m/z value available, not all the other samples:

peak <- raw_data %>%
  filterRt(rtr) %>%
  filterMz(mzr)

plot(x = peak, type = "XIC")  
abline(v = peak_rtmmed, col = "red", lty = 2)

A very minor thing I encountered today is that the documentation for _dirname_ is maybe inprecise, as it says:

dirname(path)
dirname(path) <- value

I think, it should say: 

dirname(object)
dirname(object) <- path
