### ISSUE TITLE
MZ axis inversion with plot3D

### ISSUE THREAD

**Issue by sdechaumet** [lgatto/MSnbase#292]
Hello,

Thank you for the amazing work done on this package, I'm currently using MSnbase to explore data acquired on an LC-Orbitrap system and assess data quality. When I used MSmap object to plot 2D and 3D chromatograms with 'plot' and 'plot3D' function, I had a strange feel when comparing the two outputs from the same MSmap object. Indeed the mz axis is inverted (not reversed) on the 3D plot. For example, with mz from 550 to 600, 550 spectrum are on the 600 side and 600 spectra are on the 550 side of the axis on the 3D plot. (See picture below. Intensities from m/z 595 to 600 were replaced by 5e07 to clearly show the differences between the two plots)

![image](https://user-images.githubusercontent.com/29856567/34153535-b71ef7a2-e4b2-11e7-8f5a-b2e04990b5e4.png)

I used MSnbase 2.4.0 with R 3.4.0 via Rstudio 1.1.383

Thank you again for your work.

**Comment by lgatto** [comment]
Thank you for your report. I have pushed a fix on github, in the devel branch on Bioconductor, and will do in the release branch too. The updates on Bioconductor should become available in 24 hours or so. You could install from github, but that would lead to a mix of devel/release versions, which is not ideal.
