### ISSUE TITLE
Syntax for setting directories in readMSData

### ISSUE THREAD

**Issue by R-retard** [lgatto/MSnbase#296]
Please can someone give me the correct syntax to use to define directories and paths to a directory containing either mzxML or mzML files.

I am trying the following: file <- dir(system.file(package = "MSnbase", dir = "phenolics"),
             full.names = TRUE, pattern = "mzML$")
 rawdata <- readMSData(file, msLevel = 1, verbose = FALSE)

​where I have several mzML files in a directory "phenolics" on my C drive.  I get the error saying that at least one function per file needs to be defined. The data was collected using a Waters Synapt G2 and converted using msConvert (gui version) - it contains MS1 and MS2 data as well as lockmass and UV data (4 functions).

 

I cannot get this to work even if I use mzML files off the web.  Please advise.  Thanks Malcolm Taylor

**Comment by jotsetung** [comment]
Have a look at the help page of the `system.file` function (by calling `?system.file`). There you see that `system.file` is supposed to find files within R packages installed on your system. To get the list of mzML files within a directory phenolics you need would do something like `dir("C:/phenolics", full.names = TRUE, pattern = "mzML$")`.

**Comment by R-retard** [comment]
Thanks.  Much appreciated.
