### ISSUE TITLE
Use an AnnotatedDataFrame as NAnnotatedDataFrame in pData()

### ISSUE THREAD

**Issue by sneumann** [lgatto/MSnbase#298]
Hi, from Risa and an ISA-Tab file I get an `AnnotatedDataFrame`
through `getAnnotatedDataFrameAssay()`, and I'd like to assign 
that as pData:
```
adf <- new("AnnotatedDataFrame")
omse <- new("OnDiskMSnExp")
pData(omse) <- adf
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘pData<-’ for signature ‘"NAnnotatedDataFrame", "AnnotatedDataFrame"’
```
so it would be great to either have sth like `nadf <- as.NAnnotatedDataFrame(adf)` or 
a function ‘pData<-’ for signature ‘"NAnnotatedDataFrame", "AnnotatedDataFrame"’.
Or did I miss sth. easier ? Yours, Steffen

**Comment by lgatto** [comment]
You can assign a `data.frame` directly:
```r
> omse <- new("OnDiskMSnExp")
> adf <- new("AnnotatedDataFrame", data = data.frame(x = 1:3))
> pData(omse) <- pData(adf) ## extract and assign the data.frame
> pData(omse) 
  x
1 1
2 2
3 3
> phenoData(omse) 
An object of class 'NAnnotatedDataFrame'
  sampleNames: 1 2 3
  varLabels: x
  varMetadata: labelDescription
  Multiplexing: 1 - Single run 
```

**Comment by sneumann** [comment]
Excellent, that closed the gap I had. Thx and have a nice evening! Yours, Steffen

**Comment by jotsetung** [comment]
I've added a `phenoData<-` method (pull request https://github.com/lgatto/MSnbase/pull/301).
