### ISSUE TITLE
validation method for pSet does not check phenoData slot

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#300]
Just realized that the validation method for `pSet` does not check `@phenoData`. I would have expected that it validates whether the number of rows matches the number of files or something along these lines. Is there a reason for not checking this @lgatto ?

**Comment by lgatto** [comment]
A raw data file can represent a single sample (label-free) or several (labelled, such as isobaric tagging). Hence, one can't know how many rows the `phenoData` slot should have.
