### ISSUE TITLE
PD MS3 quantitation

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#302]
This is a follow up from #282, that compares the data and quantitation values that you provided in a separate csv file. Below is an MS2 spectrum, acquisition number 21951:
```r
Object of class "Spectrum2"
 Precursor: 464.135 
 Retention time: 45:28 
 Charge: 0 
 MSn level: 3 
 Peaks count: 154 
 Total ion count: 13179064 
```
and here are the TMT11 reporter ions
![rplot001](https://user-images.githubusercontent.com/384198/35220620-0456ba2e-ff6f-11e7-9332-ac802b5b51e8.png)

If I compare the max of these centroided peaks and the quantitation values from PD, here's what I get:

|                |     data|       PD|     ratio|
|:---------------|--------:|--------:|---------:|
|Abundance..126  | 747962.4| 21440000| 0.0348863|
|Abundance..127N | 728301.1| 20760000| 0.0350819|
|Abundance..127C | 738639.2| 21050000| 0.0350898|
|Abundance..128N | 702737.8| 19920000| 0.0352780|
|Abundance..128C | 719996.6| 20400000| 0.0352939|
|Abundance..129N | 708870.3| 19980000| 0.0354790|
|Abundance..129C | 714436.9| 20130000| 0.0354912|
|Abundance..130N | 651039.9| 18240000| 0.0356930|
|Abundance..130C | 738367.9| 20690000| 0.0356872|
|Abundance..131N | 676327.1| 18850000| 0.0358794|
|Abundance..131C | 735835.1| 20510000| 0.0358769|

They are substantially different, but at least with a constant ratio.

@pavel-shliaha - do you know why this is? Could it be that the `raw` file has MS3 data in profile mode which got centroided in the `mzML`?

**Comment by pavel-shliaha** [comment]
The exact intensities of the reporters are irrelevant if the reporter ratios are consistent (afterall TMT is a relative quantitation technique). What exactly PD does to transform the intensities is irrelevant, as long as it is by the same factor.

**Comment by lgatto** [comment]
@pavel-shliaha - you are not helpful here. I am not asking whether it is relevant or not, I want to know why such a discrepancy. If you don't know, just say so.

**Comment by lgatto** [comment]
Note to self: the MS3 data is also centroided in the raw file, with means that no additional processing was done during the conversion to mzML. It thus means that PD does *something else*.

**Comment by sgibb** [comment]
I am absolutely not familiar with PD. But maybe PD isn't doing anything here and msconvert is modify the data? Because the counts in PD are integers and in your exported data double values. Does msconvert do some averaging or some kind of normalisation? Is the ratio of `0.03` similar across different spectra?

**Comment by lgatto** [comment]
The `data` column above is what is in the `mzML` data. That is also what it in the `raw` data, as far as I remember - it is definitely centroided. But there's no reason for these values to be integers, certainly not if centroided. Re ratio, they are different for different spectra, for they consistent within spectra.

The PD data was actually produced from `LUM2_01407_KS.raw` - it would be good to have that file to get to the bottom of this issue.

**Comment by lgatto** [comment]
@pavel-shliaha - what's the difference between `LUM2_01407_KS.raw` and `SP_newer_software.raw`?
