### ISSUE TITLE
Conflicting feature variable names when using combineFeatures twice with CV

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#303]
See [this question](https://support.bioconductor.org/p/105314/) for details:

1. calling `combineFeatures` (with `CV = TRUE`) to combine spectra to peptides generates fvarLabels `CV.TMT6.126` ...
2. calling `combineFeatures` (with `CV = TRUE`) to combine peptides to proteins tries to generate fvarLabels `CV.TMT6.126` ... and fails with error

```
Error in value[[3L]](cond) : duplicate 'row.names' are not allowed
  AnnotatedDataFrame 'initialize' could not update varMetadata:
  perhaps pData and varMetadata are inconsistent?
In addition: Warning message:
non-unique values when setting 'row.names': ‘CV.TMT6.126’, ‘CV.TMT6.127’, ‘CV.TMT6.128’, ‘CV.TMT6.129’, ‘CV.TMT6.130’, ‘CV.TMT6.131’
```

### TODO

1. better error message
2. if `CV` fvarLabels are already present, add a suffix.

**Comment by PDiracDelta** [comment]
For me, putting `CV = FALSE` does not resolve the issue. However, solution #2 mentioned in your answer to [the mentioned question](https://support.bioconductor.org/p/105314/) does work.

**Comment by lgatto** [comment]
As noted on the support site, it should be `cv` in lower case:

```r
> 
> library("MSnbase")
> library("rpx")
> px1 <- PXDataset("PXD000001")
> mztab <- pxget(px1, "PXD000001_mztab.txt")
Downloading 1 file
/home/lg390/tmp/PXD000001_mztab.txt already present.
> spec <- readMzTabData(mztab, what = "PEP", version = "0.9")
Warning message:
Version 0.9 is deprecated. Please see '?readMzTabData' and '?MzTab' for details. 
> pep <- combineFeatures(spec, groupBy = fData(spec)$sequence, fun = sum)
> prot <- combineFeatures(pep, groupBy = fData(pep)$accession, fun = sum)
Error in value[[3L]](cond) : duplicate 'row.names' are not allowed
  AnnotatedDataFrame 'initialize' could not update varMetadata:
  perhaps pData and varMetadata are inconsistent?
In addition: Warning message:
non-unique values when setting 'row.names': ‘CV.sub[1]’, ‘CV.sub[2]’, ‘CV.sub[3]’, ‘CV.sub[4]’, ‘CV.sub[5]’, ‘CV.sub[6]’ 
> prot <- combineFeatures(pep, groupBy = fData(pep)$accession, fun = sum, cv = FALSE)
```

I'll still see to make some changes in the package to avoid this, or at least make it explicit why the error happens.

**Comment by lgatto** [comment]
This is now properly addressed. If there is already a set of CV feature variables, the new set will be suffixed with a `.1` (or `.2`, ... if the previous index already exists).
