### ISSUE TITLE
pData disapears after call to combineFeatures() call.

### ISSUE THREAD

**Issue by adder** [lgatto/MSnbase#304]
Hi 

When I reduce the data from peptide to protein level with combineFeatures() I noticed that the pData in the returned MSnSet is empty.
I have to add it back manually.
Is this a bug or is there a reason for this?

thanks

**Comment by lgatto** [comment]
What's your version? 

I have 2.5.6 (the latest in devel):
```r
> library("MSnbase")
> library("rpx")
> px1 <- PXDataset("PXD000001")
> mztab <- pxget(px1, "PXD000001_mztab.txt")
Downloading 1 file
/home/lg390/tmp/PXD000001_mztab.txt already present.
> x <- readMzTabData(mztab, what = "PEP", version = "0.9")
Warning message:
Version 0.9 is deprecated. Please see '?readMzTabData' and '?MzTab' for details. 
> pData(x)$foo <- 1:6
> pData(x)
                      abundance foo
sub[1] peptide_abundance_sub[1]   1
sub[2] peptide_abundance_sub[2]   2
sub[3] peptide_abundance_sub[3]   3
sub[4] peptide_abundance_sub[4]   4
sub[5] peptide_abundance_sub[5]   5
sub[6] peptide_abundance_sub[6]   6
> x2 <- combineFeatures(x, groupBy = fData(x)$sequence, fun = sum)
> pData(x2)
                      abundance foo
sub[1] peptide_abundance_sub[1]   1
sub[2] peptide_abundance_sub[2]   2
sub[3] peptide_abundance_sub[3]   3
sub[4] peptide_abundance_sub[4]   4
sub[5] peptide_abundance_sub[5]   5
sub[6] peptide_abundance_sub[6]   6
```
If your version is recent, could you show your code and give more details about what you pass as `groupBy` - there are different internal functions, so there might be one execution path that missed retaining `pData`.

**Comment by adder** [comment]
Hey
You're right. There were some dependeny issues with my development version of MSnbase and the latest stable bioconductor version was loaded instead (2.4).
I can confirm that my issue is fixed in the latest development version.
Thanks a lot!
