### ISSUE TITLE
writeMSData not available

### ISSUE THREAD

**Issue by PDiracDelta** [lgatto/MSnbase#306]
The writeMSData function for creating MZ(X)ML files is not available in MSnbase, although the [documentation](http://bioconductor.org/packages/release/bioc/vignettes/MSnbase/inst/doc/MSnbase-demo.html#22_exporting_experimentsms_data) suggests it should be.
```
> source("https://bioconductor.org/biocLite.R")
Bioconductor version 3.6 (BiocInstaller 1.28.0), ?biocLite for help
> library(MSnbase)
> writeMSData()
Error in writeMSData() : could not find function "writeMSData"
```

**Comment by jotsetung** [comment]
Could you please show the output of your `sessionInfo()`? With `MSnbase` version 2.4.1 I get:
```r
> library(MSnbase)
> showMethods("writeMSData")
Function: writeMSData (package ProtGenerics)
object="list", file="character"
object="MSnExp", file="character"
```
So, the method is there.

**Comment by lgatto** [comment]
The online documentation you refer to is for the very latest development version. That feature should also be available in the stable Bioconductor release though (which is, I believe, what you use). Could you first update your packages 
```r
library("BiocInstaller")
biocLite()
```
then, `writeMSData` is still missing, post the output of `sessionInfo`.

**Comment by PDiracDelta** [comment]
OK, something went wrong during my last BioConductor update and MSnBase was amongst the un-updated packages. I suppose I should fix my update process first.

**Comment by lgatto** [comment]
Yes please, update first and follow-up here if you still have issues. 

Note that it's `MSnbase` (lowercase b).
