### ISSUE TITLE
How can I remove a feature from an MSnSet?

### ISSUE THREAD

**Issue by PDiracDelta** [lgatto/MSnbase#307]
The idea is simple: I would like to remove some features from an MSnSet (corresponding to specific rows in the fData object) by retaining only the complement of those rows.
I tried doing
`fData(myMSnSet) <- fData(myMSnSet)[some_rows_to_keep,]`
but when afterwards I want to filter NA values, I get (update: slightly different error):
`filterNA(myMSnSet)`
`Error in validObject(.Object) : 
  invalid class “MSnSet” object: featureNames differ between assayData and featureData`
I cannot access assayData to manually remove any rows there, and I can't seem to find any way to remove features by passing their row names/indices in the documentation.

How can I remove a feature ('row' in the fData dataframe) from an MSnSet?

**Comment by lgatto** [comment]
When doing the following, you only remove row from the feature data, which leads to a faulty object
```r
fData(myMSnSet) <- fData(myMSnSet)[some_rows_to_keep,]
```
You need to do the following to keep it consistent.
```r
myMSnSet <- myMSnSet)some_rows_to_keep, ]
```

**Comment by PDiracDelta** [comment]
That was actually my first hunch, but that throws another Error:
`myMSnSet <- myMSnSet[some_rows_to_keep,]
Error in orig[[nm]][i, , ..., drop = drop] : subscript out of bounds`

Also I copied the wrong error in the question, I'll quickly fix it.

**Comment by PDiracDelta** [comment]
I tried to simplify my workflow a little and came up with a slightly different (though I think inherently the same) Error:
`myMSnSet <- myMSnSet[!fData(myMSnSet)$isdecoy,]
Error in orig[[nm]][i, , ..., drop = drop] : 
  (subscript) logical subscript too long`

**Comment by lgatto** [comment]
Are you sure your `myMSnSet` is valid? Look what happens if I try to subset with a vector of logicals that is too long:
```r
> dim(msnset)
[1] 55  4
> sel <- rep(c(TRUE, FALSE), 30)
> length(sel)
[1] 60
> msnset[sel, ]
Error in orig[[nm]][i, , ..., drop = drop] : 
  (subscript) logical subscript too long
```

**Comment by PDiracDelta** [comment]
Well I updated my BioConductor packages, and suddenly everything works. I don't know why it didn't at first, since if I called filterNA on the original MSnSet (without removing certain rows) it worked just fine.

Anyway, thanks for the help!
