### ISSUE TITLE
Adding data file to msdata?

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#310]
I know this issue is not directly related to `MSnbase` - but I would like to add two files (about 20MB each). I'd like to use them for unit tests of the *new* stuff on the `centroiding` branch.

**Comment by lgatto** [comment]
Yes, no problem at all. How do you want to proceed? `msdata` isn't on github, so you could clone it from Bioc, add files, check and send me either the tarball or the new/modified files.

**Comment by jotsetung** [comment]
For me the easiest would be to send you simply the files. would that be OK?

**Comment by lgatto** [comment]
Do you want to document the files? I do so for the proteomics data files in `?proteomics`, but it's up to you.

**Comment by lgatto** [comment]
Oh, and in what directory do you want me to add them?
```
cdf
fticr
ident
iontrap
lockmass
microtofq
mzid
proteomics
threonine
```

**Comment by jotsetung** [comment]
I guess I should document them - in what format can I do that? would it be OK to provide an R file with a function, say `sciexdata`, and roxygen documentation?

subfolder could be `sciex`.

**Comment by lgatto** [comment]
I don't think you need a function. Just an `Rd` file that gives some information about the files in the `sciexdata` directory is useful. Have a look in `man/proteomics.Rd`for an example.

**Comment by jotsetung** [comment]
OK the man page would be that below. Thanks for your help!

```
\name{sciexdata}
\alias{sciexdata}

\title{AB Sciex LC-MS data files}

\description{
  The mzML files in the \code{sciex} directory in the \code{msdata}
  package represent profile-mode LC-MS data of pooled human serum
  samples (the same pool being measured). The samples were analyzed by
  ultra high-performance liquid chromatography (UHPLC; Agilent 1290)
  coupled to a Q-TOF mass spectrometer (TripleTOF 5600+ AB Sciex). The
  chromatographic separation was based in hydrophilic interaction liquid
  chromatography (HILIC) and performed using an Waters Acquity BEH
  Amide, 100 x 2.1 mm column.

  The mass specctrometer was operated in full scan mode in the mass
  range from 50 to 1000 m/z and with an accumulation time of 250 ms. The
  files represent a subset of spectra/scans from m/z 105 to 134 and from
  retention time 0 to 260 seconds. The files were generated in the same
  LC-MS run, but from different injections. Details on the individual
  files are provided below.
}

\details{
  \itemize{
    \item{20171016_POOL_POS_1_105-134.mzML}{
      profile-mode LC-MS data of pooled human serum samples. Injection
      index: 1.
    }

    \item{20171016_POOL_POS_3_105-134.mzML}{
      profile-mode LC-MS data of pooled human serum samples. Injection
      index: 19.
    }
  }
}

\author{
  Sigurdur Smarason, Giuseppe Paglia and Johannes Rainer
}

\examples{
## List the files in the sciex folder
dir(system.file("sciex", package = "msdata"))

}

\keyword{datasets}
```

**Comment by lgatto** [comment]
Done in `msdata` version 0.19.3. Just pushed it to Bioconductor, but it will take some time to propagate (I think experiment packages are built Wednesdays and Saturdays).

**Comment by jotsetung** [comment]
Thanks!

**Comment by jotsetung** [comment]
Hi @lgatto sorry to bother again. I've now checked version `msdata` 0.19.3, the help file is there, but the new mzML files not - could you please add the files to a folder `"sciex"`?

**Comment by jotsetung** [comment]
Just to confirm that all is OK. Thanks again.
