### ISSUE TITLE
Missing passed argument when calling filterIdentificationDataFrame in addDataFrameIdentificationData

### ISSUE THREAD

**Issue by veitveit** [lgatto/MSnbase#316]
There should also be a ```spectrumID``` argument when calling the function, as otherwise only the default ```spectrumID=spectrumID``` will work. The same case might apply for the other instances of ```filterIdentificationData...```

**Comment by lgatto** [comment]
Could you give me an example code to help me track down exactly what is happening. 

There's a `...` in `filterIdentificationDataFrame` that is called inside `.addDataFrameIdentificationData`, so I think it should work. The `...` are however missing from other `add*IdentificaitonData` functions, so I would like to track down if there's more missing.

**Comment by veitveit** [comment]
OK, I think I got it now. Probably confused the ```icol``` argument with with ```spectrumID```. The identification data did not have a ```spectrumID``` column.

But you are right that the  ```... ``` might be missing in other functions, such as ```.addCharacterIdentificationData```.

The code was something like 
```addIdentificationData(myExp1,ident_file,fcol=c("spectrumID"), icol=c("differentID"))```
with ```ident_file``` as data.frame (and missing the ```spectrumID``` column)

**Comment by lgatto** [comment]
There were a couple of `...` missing that I have added now. Thank you for highlighting this, and feel free to re-open the issue if you detect any other issues.
