### ISSUE TITLE
Disable CV parameter "MS:-1" for writeMSData

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#321]
This is related to https://github.com/sneumann/mzR/issues/151 . Apparently, while `proteowizard` allows to use `MS:-1` for an unknown CV this seems not to be allowed in an mzML file.

Amend thus the `.guesSoftwareProcessing` to not return a CV param if it is unknown.

**Comment by jotsetung** [comment]
That was a little too fast - I need the `"MS:-1"` for know to differentiate between MS CV IDs for the software and the processings (we can change this to use the *real* MS CV term for `MSnbase` once that is included).

Will have to revert this -

**Comment by lgatto** [comment]
Ok, go ahead.

**Comment by jotsetung** [comment]
I made a pull request addressing this. 

We should keep the issue open until the `MSnbase` has its own MS CV term ID and the replace `"MS:-1"` with that.

**Comment by lgatto** [comment]
I think this can be closed now, right?
