### ISSUE TITLE
bpc or tic with relative intensity

### ISSUE THREAD

**Issue by waleadebayo** [lgatto/MSnbase#323]
Hi, all. I am new to using MSnBase. I am trying to do a BPC or a TIC with relative intensity values rather than total intensity, so that my y axis will be 0 to 100 only rather than actual intensity. I am getting errors. Pls help. This is what I have tried in plot and ggplot functions.

```r
> xrMB <- readMSData("U_16_2.mzXML", msLevel = 1, centroided = TRUE,)
> bpc <- chromatogram(xrMB, aggregationFun = "max")
> plot(bpc) # this gave actual intensity
> library(ggplot2)
> library(scales)
> ggplot(bpc, aes(x = factor(retention_time))) +  
+     geom_bar(aes(y = (..intensity..)/sum(..intensity..))) + 
+     scale_y_continuous(labels = percent, limits = c(0,1))
Error: ggplot2 doesn't know how to deal with data of class Chromatograms
```

**Comment by SiggiSmara** [comment]
The plot function is overridden within MSnbase classes which is why you get a  plot of a chromatogram. 
To plot using your code you could call as.data.frame() on the chromatogram object before passing it to ggplot. 
‘’’

**Comment by lgatto** [comment]
You are confused with how `plot` and `ggplot` work. The latter only works with dataframes, while the former will display different behaviour depending on its input. In particular, in your example, `plot` knows how to visualise a `Chromatograms` object.

Here's what you could do:

```r
> library("MSnbase")
> library("msdata")
> f <- system.file("microtofq/MM14.mzML", package = "msdata")
> msd <- readMSData(f, msLevel = 1)
> bpc <- chromatogram(msd, aggregationFun = "max")
> bpc <- bpc[[1]]
> dfr <- data.frame(rtime = rtime(bpc), intensity = intensity(bpc))
> head(dfr)
          rtime intensity
F1.S001 270.334      1685
F1.S002 270.671      1694
F1.S003 271.007      4403
F1.S004 271.343     11692
F1.S005 271.680     26379
F1.S006 272.016     41575
> ggplot(dfr, aes(x = rtime, y = intensity)) + geom_line() ## and customise accordingly
```
![rplot001](https://user-images.githubusercontent.com/384198/37793740-6b562554-2e07-11e8-96e2-e2883c3b32f0.png)

**Comment by waleadebayo** [comment]
Thank you for your response. will tweak the rest to customise

**Comment by lgatto** [comment]
Actually, if what you want to do is to rescale the y-axis (rather then necessarily using `ggplot2`), you can use the following hack:
```r
bpc@intensity <- intensity(bpc)/max(intensity(bpc))
plot(bpc)
```
![rplot001](https://user-images.githubusercontent.com/384198/37799204-e65ab6de-2e16-11e8-9364-b8e140f9efa1.png)

I'll close this issue, but feel free to re-open it if necessary.
