### ISSUE TITLE
Fix for updates in mzR: read centroiding information from files

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#325]
Fix for the changes in `mzR` that add column `centroided` to the `data.frame` returned by `mzR::header` (PR https://github.com/sneumann/mzR/pull/153 in `mzR`).

Since there is also the parameter `centroided.` in `readMSData` I would suggest to use in the default case (i.e. `centroided. = NA`) the centroiding information reported in the `mzML` or `mzXML`, if `centroided. = TRUE` or `FALSE` it will overwrite the information read from the raw files.

**Comment by lgatto** [comment]
> Since there is also the parameter `centroided.` in `readMSData` I would suggest to use in the default case (i.e. `centroided. = NA`) the centroiding information reported in the `mzML` or `mzXML`, if `centroided. = TRUE` or `FALSE` it will overwrite the information read from the raw files.

Yes, excellent idea. There's already a `isCentroidedFromFile` function that might be useful.

**Comment by jotsetung** [comment]
The changes in the https://github.com/sneumann/mzR/pull/153 PR in `mzR` would make this function obsolete. `mzR`'s `pwiz` module reads centroiding information directly from the file and returns it in the `header` (column `"centroided"`).

**Comment by lgatto** [comment]
I suppose this can be closed too?
