### ISSUE TITLE
TIMEOUT on BioC build machines 

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#333]
`MSnbase` has now build TIMEOUTs on the BioC Windows build machines - if OK for you I would investigate a little how we could tune the unit tests. Some/many of them are most likely slow because of `OnDiskMSnExp` access to raw data. That can be definitely tuned by either first subsetting the object or use a test file other than the *mzML.gz* files (access to those files is considerably slower due to the additional uncompression).

**Comment by lgatto** [comment]
Yes, but I wouldn't make to many changes as the timout might be transient. 

There is value in using real files for tests. If the compression does make a big difference, maybe we could copy it to a temp location and uncompress it in `testthat.R` and use that one for the tests.

**Comment by jotsetung** [comment]
I agree. I'll have a look and check how and if I can increase speed without loosing coverage.

slow unit tests are (mostly related to `OnDiskMSnExp`):

| test | file | time |
|:----:|:----:|:----:|
| isCentroidedFromFile | test_centroided.R | 28.291 |
| MSmap from mzRpwiz and OnDiskMSnExp | test_MSmap.R | 29.890 |
| chromatogram,MSnExp works | test_MSnExp.R | 20.571 |
| pickPeaks,MSnExp works with refineMz | test_MSnExp.R | 14.695 |
| filterMz | test_MSnExpFilters.R | 26.669 |
| Compare OnDiskMSnExp and MSnExp compareSpectra | test_OnDiskMSnExp_other_methods.R | 23.287 |
| clean on OnDiskMSnExp with different MS levels | test_OnDiskMSnExp.R | 24.707 |
| removePeaks on OnDiskMSnExp with different MS levels | test_OnDiskMSnExp.R | 19.301 |
| readMSData inMemory and onDisk reading CDF | test_readMSData2.R | 20.538 |
| writeMSData works on CDF files | test_writeMSData.R | 32.915 |

**Comment by jotsetung** [comment]
With the changes from PR https://github.com/lgatto/MSnbase/pull/334 we can reduce the timings quite significantly (for most tests) without reducing the validity of the tests (I believe):

|                         test                         |               file                | real  |
|:----------------------------------------------------:|:---------------------------------:|:-----:|
|                 isCentroidedFromFile                 |         test_centroided.R         | 2.895 |
|         MSmap from mzRpwiz and OnDiskMSnExp          |           test_MSmap.R            | 0.119 |
|              chromatogram,MSnExp works               |           test_MSnExp.R           | 5.336 |
|         pickPeaks,MSnExp works with refineMz         |           test_MSnExp.R           | 2.025 |
|                       filterMz                       |       test_MSnExpFilters.R        | 11.84 |
|    Compare OnDiskMSnExp and MSnExp compareSpectra    | test_OnDiskMSnExp_other_methods.R | 1.465 |
|    clean on OnDiskMSnExp with different MS levels    |        test_OnDiskMSnExp.R        | 9.31  |
| removePeaks on OnDiskMSnExp with different MS levels |        test_OnDiskMSnExp.R        | 8.548 |
|      readMSData inMemory and onDisk reading CDF      |        test_readMSData2.R         | 18.39 |
|            writeMSData works on CDF files            |        test_writeMSData.R         | 10.15 |
