### ISSUE TITLE
Unit test "Robust summarisation" fails

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#335]
I don't know if that's just on macOS or also on other systems, but for me the unit test *Robust summarisation* in *test_robust* fails (has to do with https://github.com/lgatto/MSnbase/pull/330?):

```r
  ── 1. Failure: Robust summarisation (@test_robust.R#223)  ──────────────────────
  exprs(res1)[notENO, ] not identical to exprs(res2)[notENO, ].
  Objects equal but not identical
```
Could be fixed by replacing `expect_identical` with `expect_equal`, but I don't know if that's OK.

**Comment by lgatto** [comment]
Interesting, I have 
```r
> diffs <- exprs(res1)[notENO, ] - exprs(res2)[notENO, ]
> range(diffs)
[1] 0 0
```
Ok, I'll change it to `expect_equal`.
