### ISSUE TITLE
calculateFragments

### ISSUE THREAD

**Issue by andrewholding** [lgatto/MSnbase#337]
calculateFragments fails on the amino acid code U. U is the code for selenomethionine, and while rare is found in Uniprot. Other rare amino acids seem to be missing too e.g. O for pyrrolysine. 

e.g. calculateFragments("AUAA", modifications=c(C=57.02146), type=ionTypes,z=1, neutralLoss=neutralLoss)
         mz ion type pos z  seq
1  72.04439  b1    b   1 1    A
2        NA  b2    b   2 1   AU
3        NA  b3    b   3 1  AUA
4        NA  b4    b   4 1 AUAA
5  90.05495  y1    y   1 1    A
6 161.09206  y2    y   2 1   AA
7        NA  y3    y   3 1  UAA
8        NA  y4    y   4 1 AUAA

**Comment by lgatto** [comment]
Thank you for your post. Are there any other amino acids you would like us to add?
Ideally, it would be great to provide us with 
- single letter abbreviation
- Residue Mass
- 3 letter abbreviation
- Immonium Ion Mass
- Full Name
- Hydrophobicity
- Hydrophilicity
- SideChainMass
- pK1
- pK2
- pI

**Comment by andrewholding** [comment]
Thanks for the quick response, I'm not an expect. U (which is actually Selenocysteine) is listed on mascot's website - http://www.matrixscience.com/help/aa_help.html

**Comment by lgatto** [comment]
Ok, so we have:
- Selenocysteine (symbol Sec or U)
- Pyrrolysine (symbol Pyl or O)

(I'll try to find the other information)

@sgibb - I see that we have selenocysteine in `unimod`, not the pyrrolysine. Shall I add these two to the intermal `MSnbase` amino acids dataframe?

**Comment by sgibb** [comment]
I am afraid that the `unimod` package won't be released in the near future (it is not my highest priority). So please add both to `MSnbase`'s internal amino acids dataframe.
