### ISSUE TITLE
New combineSpectra for MSnExp objects

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#339]
Formalise the `combineSpectra` function as documented [here](https://github.com/sneumann/xcms/issues/237#issuecomment-383007195).

**Comment by carobirer** [comment]
Hi, let me know if you need some test data from me, and how I can send it to you. Thanks a lot for your help.

**Comment by lgatto** [comment]
I have some working code but still need to write unit tests. I will mention updates here.

**Comment by carobirer** [comment]
Ok, thanks.

**Comment by lgatto** [comment]
Closing this one. New functionality will be implemented in the *RforMassSpectrometry* packages.
