### ISSUE TITLE
Error "idFile" <NA> 

### ISSUE THREAD

**Issue by haripazhayath** [lgatto/MSnbase#347]
I am unable to map  mzid with mzML file. Below are the commands. I am using MSnbase version 2.4.2
```
mzids.raw         <- mzID(mzid.files)
msexp.raw         <- readMSData(mzml.files)
msexp <- addIdentificationData(msexp.raw, mzids.raw)
idSummary(msexp)
       spectrumFile idFile coverage
1 Saliva_2_new.mzML   <NA>    0.241
 msexp  <- removeNoId(msexp)
Error in utils.removeNoId(object, fcol, keep) : 
  sequence not in fvarLabels(object).
```

**Comment by haripazhayath** [comment]
Error in utils.removeNoId(object, fcol, keep) : 
  sequence not in fvarLabels(object)

**Comment by lgatto** [comment]
The `removeNoId` function removes feature that don't have any identification results. This is defined as those that have a missing value in a feature variable named `sequence`, which seems to be missing in your case, but which can be set with, for example
```r
removeNoId(msexp, fcol = "pepsequences")
```
You can find the name of all the feature variables with `fvarLabels(msexp)`.

**Comment by haripazhayath** [comment]
Thank you. I have 23 mzml files and mzid files of multiple fractions. IdSummary for some msexp shows " idFile"  field correct mzid. For many it shows <NA>. Why this happens. Does the identification result be correct?

**Comment by lgatto** [comment]
I don't know. What is your experimental design? Is this label-free or labelled data?
If it works for some files, I think we can assume that things work. Have you looked at the identification results from the pairs that don't work? Do you have any confident results?

**Comment by haripazhayath** [comment]
It's itraq data. 23 raw files .I have used uniprot fatsa for searching. I will try quantifying and see the result.

**Comment by haripazhayath** [comment]
I could find peptides using fData(msexp)$pepseq. When I am inputting id file as data frame I am getting the error 
Error in filterIdentificationDataFrame(id, accession = accession, rank = rank,  : 
  argument "decoy" is missing, with no default

**Comment by lgatto** [comment]
If it's 23 fractions from the same multiplexed samples, you can read all the data in one go, then add all the identification data. 

Re the other error you have, this is because you don't have any decoy data in your id files - did you use MSGF+? (Note that you can set it to use decoy databases). If you don't have any decoy data, you can set `decoy = NULL` to ignore it altogether. See `?filterIdentificationDataFrame` for details.

**Comment by haripazhayath** [comment]
Yes, I also ran all samples together . I used -tda 1 in MSGF+ and table(iddf$isDecoy) is showing  TRUE and FALSE numbers

**Comment by lgatto** [comment]
Then you should set `decoy = "isDecoy"` to make it work.

**Comment by haripazhayath** [comment]
ft<-filterIdentificationDataFrame(f,decoy="isdecoy",accession = "accession",spectrumID ="spectrumid").
This is what worked for me now. The header information in id file is different. Does this not influence filteration of previous set, when we input id file as mzid ?

**Comment by lgatto** [comment]
If you look at the man page available at `?filterIdentificationDataFrame`, you will see what the default header values are expected to be:
```
filterIdentificationDataFrame(x, decoy = "isDecoy", rank = "rank",
       accession = "DatabaseAccess", spectrumID = "spectrumID")
```
If they are different, you set them to match your header, as you did above, and the function will work as expected.

**Comment by haripazhayath** [comment]
Yes. This is what see asdefualt header in man page. This makes it
difficult. Headers are different with public datasets. Evertime I need to
manually check this and change the source code.

**Comment by lgatto** [comment]
Yes, headers a different because there are different ways to name stuff. Believe me, it is far more annoying for those that write software than those that use it.
