### ISSUE TITLE
Can readMSData reading more than two files be run with parallel?

### ISSUE THREAD

**Issue by wenbostar** [lgatto/MSnbase#35]
Hi Laurent,
Can readMSData reading more than two files be ran with parallel? It should be very useful to reduce the time when reading multiple files.
How do you think?
Best regards!
Bo

**Comment by lgatto** [comment]
This should be possible, although the benefits might not be that great, if disk IO is a limiting factor. Marking this as enhancement.

**Comment by kristiyanto** [comment]
I share similar concern.
As for now, my approach is to split the identification and quantification for each sample separately (across a cluster) and each process produced an R object (*.rda) containing processed (annotated and quantified) samples.

Now I don't know how to combine those samples together as a single set. Iterate through each sample will get me an error as discussed in Issue #6.

Could you enlighten me what would be the best approach?

Thanks,
Daniel

**Comment by lgatto** [comment]
Hi @kristiyanto 

Could you describe your design a little bit more - I am about to do some improvements on that front, so your input would be very valuable. 

* It is possible to read multiple raw data files into a single `MSnExp` object: `readMSData(c(f1, f2)`. This is not serially (as opposed to parallel processing - see above). This is only relevant when the same biological samples were labelled with the same isobaric tags:

```r
> file <- dir(system.file(package="MSnbase",dir="extdata"),
+             full.name=TRUE, pattern="mzXML$")
> file.copy(file, "~/tmp/f2.mzXML")
[1] TRUE
> xx <- readMSData(c(file, f2), verbose = FALSE)
> fileNames(xx)
[1] "/home/lg390/R/x86_64-pc-linux-gnu-library/3.3/MSnbase/extdata/dummyiTRAQ.mzXML"
[2] "~/tmp/dummyiTRAQ2.mzXML"                                                       
> k <- quantify(xx, reporters = iTRAQ4, verbose = FALSE)
> exprs(k)
     iTRAQ4.114 iTRAQ4.115 iTRAQ4.116 iTRAQ4.117
X1.1   4483.320   4873.996   6743.441   4601.378
X1.2   4483.320   4873.996   6743.441   4601.378
X2.1   1918.082   1418.040   1117.601   1581.954
X2.2   1918.082   1418.040   1117.601   1581.954
X3.1  15210.979  15296.256  15592.760  16550.502
X3.2  15210.979  15296.256  15592.760  16550.502
X4.1   4133.103   5069.983   4724.845   4694.801
X4.2   4133.103   5069.983   4724.845   4694.801
X5.1  11947.881  13061.875  12809.491  12911.479
X5.2  11947.881  13061.875  12809.491  12911.479
```
* It is also possibly to process the 2 files separately, then combine the quantified data:
```r
> 
> x1 <- readMSData(file, verbose = FALSE)
> k1 <- quantify(x1, reporters = iTRAQ4, verbose = FALSE)
> x2 <- readMSData(f2, verbose = FALSE)
> k2 <- quantify(x2, reporters = iTRAQ4, verbose = FALSE)
> k2 <- updateFeatureNames(k2)
> exprs(combine(k1, k2))
        iTRAQ4.114 iTRAQ4.115 iTRAQ4.116 iTRAQ4.117
X1.1      4483.320   4873.996   6743.441   4601.378
X2.1      1918.082   1418.040   1117.601   1581.954
X3.1     15210.979  15296.256  15592.760  16550.502
X4.1      4133.103   5069.983   4724.845   4694.801
X5.1     11947.881  13061.875  12809.491  12911.479
X1.1.k2   4483.320   4873.996   6743.441   4601.378
X2.1.k2   1918.082   1418.040   1117.601   1581.954
X3.1.k2  15210.979  15296.256  15592.760  16550.502
X4.1.k2   4133.103   5069.983   4724.845   4694.801
X5.1.k2  11947.881  13061.875  12809.491  12911.479
```

* If the acquisitions where from different samples but same features (as defined by `featureNames`, which would need to be updated accordingly):

```r
> x1 <- readMSData(file, verbose = FALSE)
> k1 <- quantify(x1, reporters = iTRAQ4, verbose = FALSE)
> x2 <- readMSData(f2, verbose = FALSE)
> k2 <- quantify(x2, reporters = iTRAQ4, verbose = FALSE)
> k2 <- updateSampleNames(k2)
> exprs(combine(k1, k2))
     iTRAQ4.114 iTRAQ4.115 iTRAQ4.116 iTRAQ4.117 iTRAQ4.114.k2 iTRAQ4.115.k2
X1.1   4483.320   4873.996   6743.441   4601.378      4483.320      4873.996
X2.1   1918.082   1418.040   1117.601   1581.954      1918.082      1418.040
X3.1  15210.979  15296.256  15592.760  16550.502     15210.979     15296.256
X4.1   4133.103   5069.983   4724.845   4694.801      4133.103      5069.983
X5.1  11947.881  13061.875  12809.491  12911.479     11947.881     13061.875
     iTRAQ4.116.k2 iTRAQ4.117.k2
X1.1      6743.441      4601.378
X2.1      1117.601      1581.954
X3.1     15592.760     16550.502
X4.1      4724.845      4694.801
X5.1     12809.491     12911.479
```

`combine` is essentially either a `cbind` or `rbind`, depending on matching sample or feature names.

**Comment by lgatto** [comment]
Closing this issue, as we are moving towards an onDisk mode. If there is still concern about this, please re-open.
