### ISSUE TITLE
plotDensity: error if no charge is assigned. 

### ISSUE THREAD

**Issue by sneumann** [lgatto/MSnbase#358]
Hi, I get an 
```
> plotDensity(xs, "ionCount")
Error: c("charge", z) %in% names(object) are not all TRUE
```
if the experiment has no charges annotated, which is the case 
for plain `XCMSnExp`. It would be great to just plot the ionCount density
and skip additional splitting by charge if that column is missing.
In the meantime, I'd appreciate a hint how to add/fake the Charge column 
so that I can continue here. 
Yours, Steffen

**Comment by lgatto** [comment]
Closing, but feel free to follow up.
