### ISSUE TITLE
TMT 10 plex

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/MSnbase#36]
this information is from the kit description:

http://www.piercenet.com/instructions/2162457.pdf

I have saved the description as well as a csv table I created at:

data:\CCP\LabTalks\tags (feel free to move it)

the tags have the disctribution of isotopes as shown 

![image](https://cloud.githubusercontent.com/assets/1895805/3442561/25e42092-0116-11e4-81fc-665da48aa286.png)

The table gives a very counter-intuitive explanation for purity correction

![image](https://cloud.githubusercontent.com/assets/1895805/3442492/058e71f4-0115-11e4-9bc2-633f3b6b2e99.png)

I would assume that whenever an isotope is added or substracted from the reporter it happens on C12/C13. That means that the C series can only be contaminated by other C-series, while N-series can only be contaminated by other N series (see figure above).

This is the case for -1 and -2 channels, e.g.  for 129C -1 is 128C and -2 is 127C.

On the other hand + 1 and + 2 always follow the pattern: + 1 is always from the same series, but + 2 is the next tag in the list, e.g. for 128C + 1 is 129C, but + 2 IS NOT 130C as you would expect, but 129N. 

I am not really sure whether this is a mistake and they meant 130C, but instead written 129N or they actually measured 129N, which does not make any sense to me.

**Comment by lgatto** [comment]
Support for TMT 10-plex added in version 1.15.16 (#a2295220e3552806f135e4d27421d8f0c35b7e75)

**Comment by lgatto** [comment]
The annotations reported above (see https://twitter.com/lgatt0/status/1065890025412468736) for details. This has been confirmed by Thermo.
