### ISSUE TITLE
Wrong MS OBO VC terms used

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#360]
Sorry for pushing this (https://github.com/lgatto/MSnbase/commit/6c7bdb7ea8e65b87fd12ebd2d00ebedf90e9a3d6) directly to master. I had used wrong CV terms for baseline correction and smoothing. Eventually also something to fix in *RELEASE_#_7*?

**Comment by lgatto** [comment]
backported and pushed to devel branch.

**Comment by jotsetung** [comment]
Sorry - did forget to adapt the unit test. Fixed now in the latest commit to master (again sorry).

**Comment by lgatto** [comment]
No worries. Pushed to 2.7.7 on github (bumped to 2.7.8) and Bioc devel and backported to version 2.6.4 in release.
