### ISSUE TITLE
filterPolarity

### ISSUE THREAD

**Issue by zeehio** [lgatto/MSnbase#388]
Thank you for your time and efforts on this package.

My apologies if I am overlooking something obvious (I am a newcomer here). If that is the case, feel free to tell me and I will close the issue.

 I found out I needed a `filterPolarity` function and I wonder if it would be worth including a `filterPolarity` function in your `MSnbase` package. Here is my use case and a demo implementation:

## Without polarity filtering

Loading a single sample and plotting a region, without `filterPolarity`, both polarities appear mixed:

```r
# My apologies, I don't have permissions to submit data right now :-S
MSnbase::readMSData("1.mzXML") %>%
  MSnbase::filterRt(rt = c(500, 520)) %>%
  MSnbase::filterMz(mz = c(300, 400)) %>%
  MSnbase::plot(type = "XIC")
```

![imatge](https://user-images.githubusercontent.com/75441/49731200-e26ffd80-fc7a-11e8-94ed-af9125e092e9.png)

## With polarity filtering

Based on `MSnbase::filterMsLevel` I wrote this `filterPolarity` function.

```r
filterPolarity <- function(object, polarity.) {
  if (missing(polarity.)) return(object)
  polarity. <- as.numeric(polarity.)
  object[MSnbase::polarity(object) %in% polarity.]
}
```

Filtering the polarity I can easily see the positive and negative polarities:

```r
MSnbase::readMSData("1.mzXML") %>%
  filterPolarity(polarity. = 1) %>%
  MSnbase::filterRt(rt = c(500, 520)) %>%
  MSnbase::filterMz(mz = c(300, 400)) %>%
  MSnbase::plot(type = "XIC")
```
![imatge](https://user-images.githubusercontent.com/75441/49731336-4abedf00-fc7b-11e8-81f2-e4ec2a8a4a37.png)

```r
MSnbase::readMSData("1.mzXML") %>%
  filterPolarity(polarity. = 0) %>%
  MSnbase::filterRt(rt = c(500, 520)) %>%
  MSnbase::filterMz(mz = c(300, 400)) %>%
  MSnbase::plot(type = "XIC")
```

![imatge](https://user-images.githubusercontent.com/75441/49731807-d2f1b400-fc7c-11e8-84b5-331abbc398dd.png)

Is there a reason why there is not a `filterPolarity` function in `MSnbase`? I feel I am missing something obvious, but I'd rather ask just in case...

Thanks

**Comment by lgatto** [comment]
Thank you for your report @zeehio. Firstly, I suppose we should indeed add a function `filterPolarity`. 

I will let @jotsetung also chime in, put I spotted an issue in your function (which might be a false positive though):
```r
filterPolarity <- function(object, polarity.) {
  if (missing(polarity.)) return(object)
  polarity. <- as.numeric(polarity.)
  object[MSnbase::polarity(dataset_not_dia) %in% polarity.] ## should be object, rather than dataset_no_dia
}
```
Could you confirm if that's the reason for the lack of effective filtering, or if it's only a typo.

**Comment by lgatto** [comment]
I have added the method to `MSnbase` - only on github for now. And thank you for feature request.
