### ISSUE TITLE
Rename fun as method in combineFeatures

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#389]
As `method` is used in many other functions such as `impute`, `plot2D`, ...

**Comment by jotsetung** [comment]
Makes sense. or `FUN` instead of `fun`.

**Comment by lgatto** [comment]
I suppose as this is a major API break, we need a smooth transition with a support for `fun` (with a message) and `method` for a while before, before removing the former...

**Comment by jotsetung** [comment]
are you doing this @lgatto or should I? Best is you simply assign the lucky guy implementing it ;)

**Comment by jotsetung** [comment]
Umpfh - lucky me 🎉 
well, at least we know who has to do it.

**Comment by jotsetung** [comment]
Wait - you got me. I thought it's `fun` in `combineSpectra` - wasn't aware that there's also a `combineFeatures`.

**Comment by lgatto** [comment]
Well spotted. I am wondering of we shouldn't do the same for `combineSpectra`. Now that I think about it, there's a major difference in `plot2D`, `impute`, `normalise`, ... that use `method`, and `combineSpectra` and (paritally) `combineFeatures`, that use `fun`. The former all take characters as input, and the underlying method is then applied. The two latter case actually take functions as arguments (except that `combineFeatures` takes a set of pre-defined characters, as in `methods` above and supports user-defined functions). 

My question is 
- is it better to keep `method` and `fun` to highlight the different input types
- is it better to standardise it to `method`, the type of the input being documented in the man page.

My feeling is that `fun` (or `FUN`) isn't all that useful/telling for the average user, so that a standardisation would be preferable. 

@jotsetung @sgibb - what do you think?

**Comment by lgatto** [comment]
And I only realise not that @jotsetung already submitted a PR. So I guess option 2 it is, which would imply to also do the same change in `combineSpectra`.

**Comment by jotsetung** [comment]
Yup. I changed `fun` to `method` in both `combineFeatures` **and** `combineSpectra`.

**Comment by lgatto** [comment]
You are too good!
