### ISSUE TITLE
Parallel hdf5 read/write

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#391]
Hi @grimbough - getting back you re parallel reading/writing hdf5 files. For example, I have 

```
     group     name       otype dclass       dim
0        /        1   H5I_GROUP                 
1       /1 F1.S0001 H5I_DATASET  FLOAT 25800 x 2
2       /1 F1.S0002 H5I_DATASET  FLOAT 25934 x 2
3       /1 F1.S0003 H5I_DATASET  FLOAT 26148 x 2
...
7534        /        2   H5I_GROUP                 
7535       /2 F2.S001 H5I_DATASET  FLOAT 43527 x 2
7536       /2 F2.S002 H5I_DATASET  FLOAT   211 x 2
7537       /2 F2.S003 H5I_DATASET  FLOAT   124 x 2
...
```
with potentially 10s or 100s of groups.

- Could I write these groups in parallel, and would this be faster?
- Could I read these groups in parallel, and would this be faster?

I found that there is apparently a specific parallel HDF5 implementation. Is this something that is available in the `rhdf5` package? 

- Alternatively, would if be a sensible approach to create a data directory, and in there have multiple hdf5 file instead of one file with multiple groups?

**Comment by grimbough** [comment]
Parallel reading with a single-machine multicore approach actually works quite well.  Typically, with HDF5, a reasonable amount of time is spent decompressing the data, so it takes a few threads before you saturate the disk IO.  In the past I looked into this a bit and found I was still getting improvements up to about 20 cores (http://www.msmith.de/2018/05/01/parallel-r-hdf5/).  

You can also experiment with changing the compression level you save the data at, which can have a noticeable impact on speed.  The default is GZIP level 7, and you can adjust it with the `level` argument to `h5write()`.

Below is quick example of parallel reading, which requires very little modification to what we've already discussed in #387 

```r
library(rhdf5)

## generate data and write to file
mat <- matrix(runif(n = 200000), ncol = 2)
h5f <- tempfile(fileext = ".h5")
for(i in seq_len(1000)) {
  h5write(mat, file = h5f, name = paste("dset", i, sep = "_"))
}

## read wrapper
## finds all dataset names, then reads them
## i is the number of cores to use
par_read <- function(i) {
  dsets <- h5ls(h5f)$name  
  parallel::mclapply(dsets, h5read, file = h5f, mc.cores = i)
}

## benchmark
bm1 <- microbenchmark::microbenchmark(
  par_read(1), par_read(2), par_read(3), par_read(4),
  times = 5
)
```
```
> bm1
Unit: seconds
        expr       min        lq      mean    median       uq      max neval
 par_read(1) 11.283424 11.603667 13.154608 12.305320 12.53453 18.04610     5
 par_read(2) 11.192490 11.252322 11.518428 11.262183 11.40384 12.48130     5
 par_read(3)  9.008593  9.216137  9.785845  9.818125 10.33932 10.54705     5
 par_read(4)  8.836623  9.188579  9.719818  9.520099 10.28111 10.77267     5
```
Parallel writing is trickier, so I'll add a separate post comment below.

**Comment by jotsetung** [comment]
I'm experiencing problems with parallel read access to a single hdf5 file:
```r
> h5_sps <- spectrapply(h5_sciex, BPPARAM = MulticoreParam(2))
Error: BiocParallel errors
  element index: 1
  first error: HDF5. Dataset. Can't open object.
```

Without parallel processing it actually works:
```r
> h5_sps <- spectrapply(h5_sciex, BPPARAM = SerialParam())
```

The `spectrapply` function is defined [here](https://github.com/lgatto/MSnbase/blob/hdf5_jo/R/hdf5.R#L220:L244) . In essence, I'm using the open file handle (of type `H5IdComponent`) and pass that along to the read function:

```r
.h5read_raw <- function(file, name = "") {
    did <- .Call("_H5Dopen", file@ID, name, NULL, PACKAGE = "rhdf5")
    res <- .Call("_H5Dread", did, NULL, NULL, NULL, TRUE, 0L, FALSE, FALSE,
                 PACKAGE = "rhdf5")
    invisible(.Call("_H5Dclose", did, PACKAGE = "rhdf5"))
    res
}
```

I guess it is not possible to use the same file handle in parallel processes?

**Comment by jotsetung** [comment]
Thanks for the feedback. @lgatto should we consider having one hdf5 file per mzML file? not really ideal, but that way we would definitely avoid parallel access issues like the one above.

**Comment by lgatto** [comment]
@jotsetung - yes, this is what lead me to read and ask about and parallel hdf5. Disk IO can be a bottleneck on its own, hence my preference to test and read before writing multiple hdf5 files. 

I am wondering

**Comment by lgatto** [comment]
I am wondering if the error you have seen above isn't the result of a misunderstanding or misconding somewhere - Mike has done some [tests with parallel processing](http://www.msmith.de/2018/05/01/parallel-r-hdf5/).

**Comment by jotsetung** [comment]
The error I get is because I was using the same file handle for each parallel process - and that does not work i.e. leads to the error above. If we have all data in a single hdf5 file each process has to open the file, access the data and close the file again - similar to what we do with the current `OnDiskMSnExp`/`mzR` implementation. I guess this will have an impact on performance.

**Comment by jotsetung** [comment]
In the commit above I open/close the connection to the HDF5 file for each data access (each spectrum). With that parallel access works. Some timings comparing the *onDisk* and *hdf5* implementations:

```r
library(MSnbase)
library(rhdf5)
library(BiocParallel)

sf <- dir(system.file("sciex", package = "msdata"), full.names = TRUE)
h5_sciex <- readHdf5DiskMSData(sf, hdf5file = paste0(tempfile(), ".h5"))
sciex <- readMSData(sf, mode = "onDisk")
h5closeAll()

mcp <- bpstart(MulticoreParam(2))

## Check that data is the same
sps <- spectra(sciex, BPPARAM = mcp)
h5_sps <- spectra(h5_sciex, BPPARAM = mcp)
library(testthat)
expect_equal(sps, h5_sps)

## Compare performance
library(microbenchmark)
microbenchmark(
    spectra(sciex, BPPARAM = SerialParam()),
    spectra(sciex, BPPARAM = mcp),
    spectra(h5_sciex, BPPARAM = SerialParam()),
    spectra(h5_sciex, BPPARAM = mcp),
    times = 5)
Unit: milliseconds
                                       expr       min        lq      mean
    spectra(sciex, BPPARAM = SerialParam()) 1072.3285 1143.5310 1199.4421
              spectra(sciex, BPPARAM = mcp)  661.2461  840.8027  857.1082
 spectra(h5_sciex, BPPARAM = SerialParam())  653.2791  705.5648  864.2879
           spectra(h5_sciex, BPPARAM = mcp)  597.8303  660.1449  754.9856
    median        uq      max neval cld
 1189.6966 1280.5075 1311.147     5   b
  860.5232  860.6688 1062.300     5  a 
  928.1845  960.1046 1074.307     5  a 
  731.6885  760.4157 1024.848     5  a 

``` 

So, HDF5 is slightly faster. What is puzzling is that there is almost no performance gain in the parallel access to the HDF5. Below I repeat it for 4 *real* data files.

```r
fls <- dir("/Users/jo/data/2018/", pattern = "mzML$", full.names = TRUE)[1:4]
od <- readMSData(fls, mode = "onDisk")
h5 <- readHdf5DiskMSData(fls)
h5closeAll()

sps <- spectra(od, BPPARAM = mcp)
h5_sps <- spectra(h5, BPPARAM = mcp)
expect_equal(sps, h5_sps)

mcp4 <- bpstart(MulticoreParam(4))

microbenchmark(spectra(od, BPPARAM = SerialParam()),
               spectra(od, BPPARAM = mcp),
               spectra(od, BPPARAM = mcp4),
               spectra(h5, BPPARAM = SerialParam()),
               spectra(h5, BPPARAM = mcp),
               spectra(h5, BPPARAM = mcp4),
               times = 5)
Unit: seconds
                                 expr      min       lq     mean   median
 spectra(od, BPPARAM = SerialParam()) 8.721256 8.987641 9.036292 9.038025
           spectra(od, BPPARAM = mcp) 5.553505 6.625305 7.856512 8.481469
          spectra(od, BPPARAM = mcp4) 4.524092 4.750867 5.960890 6.046666
 spectra(h5, BPPARAM = SerialParam()) 4.414138 6.115809 7.012096 6.599496
           spectra(h5, BPPARAM = mcp) 3.105068 3.187379 4.721912 3.756028
          spectra(h5, BPPARAM = mcp4) 3.596617 3.610037 5.179819 5.030838
       uq      max neval cld
 9.144085 9.290455     5   b
 9.054507 9.567774     5  ab
 6.197679 8.285149     5  ab
 8.180238 9.750798     5  ab
 5.266416 8.294667     5  a 
 6.490628 7.170975     5  a 

```

Again, the performance gain with parallel access is only small. Even more surprising is that hdf5 access with 2 or 4 parallel processes is about the same.

**Comment by grimbough** [comment]
Thanks for the benchmarks.  If anything your real datasets example gets slower when you increase the number of workers.

I'm teaching at the moment, but I'll try and find some time to look more closely.  This is not the behviour I saw previously, but that may well have been before changing from linking against HDF5 1.8 to 1.10
