### ISSUE TITLE
hdf5 read access

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#392]
- [x] `[[`
- [x] `[` (uses `OnDiskMSnExp`)
- [ ] `spectra` - see issue #391 to see if the underlying data model fits parallel mzML file/group-based access

**Comment by jotsetung** [comment]
`spectrapply,Hdf5MSnExp` (which is called/used by `spectra`, `mz` and all other data access methods) is implemented in commit https://github.com/lgatto/MSnbase/commit/0a76246992c4ac9b160ddcb84b5eab66be1cfca0 I'll however try to tweak it a little to get some better performance.
