### ISSUE TITLE
Not able to read cdf files

### ISSUE THREAD

**Issue by anupbharade09** [lgatto/MSnbase#396]
Hello,

Hope you are doing good.
I am trying to read cdf files using readMSdata , but getting below error.

According to the instrument information in the files,
the data has been acquired on different instruments!
Error in validObject(.Object) : 
  invalid class “MIAPE” object: 1: invalid object for slot "instrumentModel" in class "MIAPE": got class "matrix", should be or extend class "character"
invalid class “MIAPE” object: 2: invalid object for slot "instrumentManufacturer" in class "MIAPE": got class "matrix", should be or extend class "character"

Does cdf files must have some specific structure while using readMSdata ?
Could you please help me with this?

**Comment by lgatto** [comment]
Could you please show the exact code you ran that lead to this error. Please do copy/paste both you input code and the content of any variables you use (in this case the vector of file names provided as input to `readMSData`) as well as all the output (warnings and errors). Finally, do also provide to output of `sessionInfo`.

As far as I can tell from your report, you seem to want to read data from multiple files that, based on their content, has been acquired on different instruments. This is only a message. 
In addition, you have an error because the raw file contained metadata that was not consistent with the expected format. But without further details (see above), I can't say more.

Finally, cdf shouldn't require anything special.

**Comment by anupbharade09** [comment]
Thanks for the quick reply. 
I do want to read multiple files. But for testing purpose i am currently only using a single file.
Below are the input commands :
Input:
#raw files
all_raw_files <- list.files(path_to_raw_data, recursive=T, full.names=T)

#data frames
pd <- data.frame(sample_name=sub(basename(all_raw_files),
                                 pattern = ".CDF", 
                                   replacement = "", 
                                   fixed = TRUE),
                   sample_group = c(rep("KO", 1), rep("WT", 1)),
                   stringsAsFactors = FALSE) 

#raw data (this runs into error)
raw_data <- readMSData(files=all_raw_files, pdata=new("NAnnotatedDataFrame", pd), mode="onDisk",verbose = TRUE)

Output:

> raw_data <- readMSData(files=all_raw_files, pdata=new("NAnnotatedDataFrame", pd), mode="onDisk",verbose = TRUE)
Polarity can not be extracted from netCDF files, please set manually the polarity with the 'polarity' method.
Reading 37093 spectra from file S0.2_1.cdf
Reading 37093 spectra from file S0.2_1.cdf
According to the instrument information in the files,
the data has been acquired on different instruments!
Error in validObject(.Object) : 
  invalid class “MIAPE” object: 1: invalid object for slot "instrumentModel" in class "MIAPE": got class "matrix", should be or extend class "character"
invalid class “MIAPE” object: 2: invalid object for slot "instrumentManufacturer" in class "MIAPE": got class "matrix", should be or extend class "character"

Even i suspect that cdf files don't have consistent metadata, but i am unable to identify what exactly needs to be changed/altered. Is there anything you can suggest to make cdf files consistent with this framework (any document maybe).
Also here is the sessionInfo:

> sessionInfo
function (package = NULL) 
{
    z <- list()
    z$R.version <- R.Version()
    z$platform <- z$R.version$platform
    if (nzchar(.Platform$r_arch)) 
        z$platform <- paste(z$platform, .Platform$r_arch, sep = "/")
    z$platform <- paste0(z$platform, " (", 8 * .Machine$sizeof.pointer, 
        "-bit)")
    z$locale <- Sys.getlocale()
    if (.Platform$OS.type == "windows") {
        z$running <- win.version()
    }
    else if (nzchar(Sys.which("uname"))) {
        uname <- system("uname -a", intern = TRUE)
        os <- sub(" .*", "", uname)
        z$running <- switch(os, Linux = if (file.exists("/etc/os-release")) {
            tmp <- readLines("/etc/os-release")
            t2 <- if (any(startsWith(tmp, "PRETTY_NAME="))) sub("^PRETTY_NAME=", 
                "", grep("^PRETTY_NAME=", tmp, value = TRUE)[1L]) else if (any(startsWith(tmp, 
                "NAME"))) sub("^NAME=", "", grep("^NAME=", tmp, 
                value = TRUE)[1L]) else "Linux (unknown distro)"
            sub("\"(.*)\"", "\\1", t2)
        } else if (file.exists("/etc/system-release")) {
            readLines("/etc/system-release")
        }, Darwin = {
            ver <- readLines("/System/Library/CoreServices/SystemVersion.plist")
            ind <- grep("ProductUserVisibleVersion", ver)
            ver <- ver[ind + 1L]
            ver <- sub(".*<string>", "", ver)
            ver <- sub("</string>$", "", ver)
            ver1 <- strsplit(ver, ".", fixed = TRUE)[[1L]][2L]
            sprintf("%s %s %s", ifelse(as.numeric(ver1) < 12, 
                "OS X", "macOS"), switch(ver1, `6` = "Snow Leopard", 
                `7` = "Lion", `8` = "Mountain Lion", `9` = "Mavericks", 
                `10` = "Yosemite", `11` = "El Capitan", `12` = "Sierra", 
                `13` = "High Sierra", ""), ver)
        }, SunOS = {
            ver <- system("uname -r", intern = TRUE)
            paste("Solaris", strsplit(ver, ".", fixed = TRUE)[[1L]][2L])
        }, uname)
    }
    if (is.null(package)) {
        package <- grep("^package:", search(), value = TRUE)
        keep <- vapply(package, function(x) x == "package:base" || 
            !is.null(attr(as.environment(x), "path")), NA)
        package <- .rmpkg(package[keep])
    }
    pkgDesc <- lapply(package, packageDescription, encoding = NA)
    if (length(package) == 0) 
        stop("no valid packages were specified")
    basePkgs <- sapply(pkgDesc, function(x) !is.null(x$Priority) && 
        x$Priority == "base")
    z$basePkgs <- package[basePkgs]
    if (any(!basePkgs)) {
        z$otherPkgs <- pkgDesc[!basePkgs]
        names(z$otherPkgs) <- package[!basePkgs]
    }
    loadedOnly <- loadedNamespaces()
    loadedOnly <- loadedOnly[!(loadedOnly %in% package)]
    if (length(loadedOnly)) {
        names(loadedOnly) <- loadedOnly
        pkgDesc <- c(pkgDesc, lapply(loadedOnly, packageDescription))
        z$loadedOnly <- pkgDesc[loadedOnly]
    }
    z$matprod <- as.character(options("matprod"))
    es <- extSoftVersion()
    z$BLAS <- as.character(es["BLAS"])
    z$LAPACK <- La_library()
    class(z) <- "sessionInfo"
    z
}
<bytecode: 0x120f24370>
<environment: namespace:utils>

**Comment by anupbharade09** [comment]
sessionInfo() logs:

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xcms_3.4.1          BiocParallel_1.16.2 MSnbase_2.8.2       ProtGenerics_1.14.0 S4Vectors_0.20.1    mzR_2.16.0          Rcpp_1.0.0          Biobase_2.42.0     
[9] BiocGenerics_0.28.0

loaded via a namespace (and not attached):
 [1] RColorBrewer_1.1-2     DEoptimR_1.0-8         compiler_3.5.1         pillar_1.3.1           BiocManager_1.30.4     plyr_1.8.4             iterators_1.0.10      
 [8] tools_3.5.1            zlibbioc_1.28.0        digest_0.6.18          ncdf4_1.16             MALDIquant_1.18        tibble_1.4.2           preprocessCore_1.44.0 
[15] gtable_0.2.0           lattice_0.20-38        rlang_0.3.0.1          foreach_1.4.4          Matrix_1.2-15          IRanges_2.16.0         multtest_2.38.0       
[22] grid_3.5.1             robustbase_0.93-3      impute_1.56.0          survival_2.43-3        XML_3.98-1.16          RANN_2.6               limma_3.38.3          
[29] ggplot2_3.1.0          splines_3.5.1          scales_1.0.0           pcaMethods_1.74.0      codetools_0.2-15       MASS_7.3-51.1          MassSpecWavelet_1.48.0
[36] mzID_1.20.0            colorspace_1.3-2       affy_1.60.0            doParallel_1.0.14      lazyeval_0.2.1         munsell_0.5.0          vsn_3.50.0            
[43] crayon_1.3.4           affyio_1.52.0

**Comment by lgatto** [comment]
Thank you. Would it be possible to share one of the cdf files. It looks like some metadata either isn't parsed correctly or isn't encoded correctly in the files, leading the the `instrumentModel` and `instrumentManufacturer` errors.

**Comment by anupbharade09** [comment]
Each cdf file is little huge. Is there anyway i can share it with you ?
Meanwhile below are the Variables, dimensions and global attributes of file.

     28 variables (excluding dimension variables):
        char error_log[_64_byte_string,error_number]   
        double a_d_sampling_rate[scan_number]   
        short a_d_coaddition_factor[scan_number]   
        double scan_acquisition_time[scan_number]   
        double scan_duration[scan_number]   
        double inter_scan_time[scan_number]   
        double resolution[scan_number]   
        int actual_scan_number[scan_number]   
        double total_intensity[scan_number]   
            units: Arbitrary Intensity Units
        double mass_range_min[scan_number]   
        double mass_range_max[scan_number]   
        double time_range_min[scan_number]   
        double time_range_max[scan_number]   
        int scan_index[scan_number]   
        int point_count[scan_number]   
        int flag_count[scan_number]   
        short mass_values[point_number]   
            units: M/Z
        int intensity_values[point_number]   
            units: Arbitrary Intensity Units
        char instrument_name[instrument_number,_32_byte_string]   
        char instrument_id[instrument_number,_32_byte_string]   
        char instrument_mfr[instrument_number,_32_byte_string]   
        char instrument_model[instrument_number,_32_byte_string]   
        char instrument_serial_no[instrument_number,_32_byte_string]   
        char instrument_sw_version[instrument_number,_32_byte_string]   
        char instrument_fw_version[instrument_number,_32_byte_string]   
        char instrument_os_version[instrument_number,_32_byte_string]   
        char instrument_app_version[instrument_number,_32_byte_string]   
        char instrument_comments[instrument_number,_32_byte_string]   

     13 dimensions:
        _2_byte_string  Size:2
        _4_byte_string  Size:4
        _8_byte_string  Size:8
        _16_byte_string  Size:16
        _32_byte_string  Size:32
        _64_byte_string  Size:64
        _128_byte_string  Size:128
        _255_byte_string  Size:255
        range  Size:2
        point_number  Size:13784663   *** is unlimited ***
        error_number  Size:1
        scan_number  Size:37089
        instrument_number  Size:32

    27 global attributes:
        dataset_completeness: C1+C2
        ms_template_revision: 1.0.1
        netcdf_revision: 3.6.1
        languages: English
        netcdf_file_date_time_stamp: 20110124121906-0500
        experiment_date_time_stamp: 20110113232143-0500
        experiment_type: Centroided Mass Spectrum
        sample_state: Other State
        test_separation_type: Gas-Liquid Chromatography
        test_ms_inlet: Capillary Direct
        test_ms_inlet_temperature: 280
        test_ionization_mode: Electron Impact
        test_ionization_polarity: Positive Polarity
        test_source_temperature: 210
        test_accelerating_potential: -600
        test_detector_type: Electron Multiplier
        test_detector_potential: -1630
        test_resolution_type: Constant Resolution
        test_scan_function: Mass Scan
        test_scan_direction: Up
        test_scan_law: Linear
        test_scan_time: 0.000199999994947575
        raw_data_mass_format: Short
        raw_data_time_format: Short
        raw_data_intensity_format: Long
        units: Seconds
        starting_scan_number: 0

**Comment by anupbharade09** [comment]
Hello,

I have tried both steps as per your suggestion, but it did not help.
Structure of both faahKO files and our files are same. As we discussed earlier it seems there is some inconsistency with the metadata (experiment data) in our files.
Do you have any idea how can we check this experiment data?

**Comment by anupbharade09** [comment]
Hello,

I found the issue in our cdf files. The dimensions of the 2 variables which were there in error were incorrect. I have corrected those and able to read it using readMSData.
Thanks for your inputs.
