### ISSUE TITLE
Adding cvParams through writeMSData

### ISSUE THREAD

**Issue by mobiusklein** [lgatto/MSnbase#397]
Hello,

I'm looking for a way to add data to a `Spectrum` object so that when it passes through `writeMSData` a new `<cvParam/>` or `<userParam/>` tag is produced. So far as I can tell, the parameter tags are determined in mzR's [RcppPwiz::addSpectrumList](https://github.com/sneumann/mzR/blob/master/src/RcppPwiz.cpp#L596), but the only information it looks at come out of the columns of `spctr_header`

Additionally, is there a way to add more data arrays, like "charge array", to the object?

**Comment by jotsetung** [comment]
Unfortunately there is at present no way to add additional fields to the exported mzML. This would require some major changes in the `mzR` package - it might actually not be too bad to rewrite part of the `mzR` code - only I have no time for this at present.

**Comment by lgatto** [comment]
I suppose the exported cvParams are tuned to fit the metadata available in our `[OnDisk]MSnExp` objects. So I think it is more likely on our side to update/adapt the mzML writer if there's a reason/need from the `MSnbase` side. @mobiusklein - on the R side, where is that information stored?

**Comment by mobiusklein** [comment]
Thank you for the clarification. From tracing through the code by eye, I don't think there is a place where arbitrary parameter values are stored in memory on the R side. I wasn't certain I was correct though, because in this [post](https://twitter.com/lgatt0/status/1075446897207373824) , you claimed `MSnBase` could write mzML. From the context of the claim in the referenced abstract (note: I am the author of the abstract), that support for mzML was "complete", meaning it could represent anything defined in the specification. 

Given how often I've been wrong about a codebase using manual static analysis, I wanted to get clarification that I wasn't missing anything before I decide revise that manuscript. Those two properties, support for arbitrary parameters and arrays for other quantities than m/z and intensity were important parts of why I wrote the published library in the first place, and they're exercised in first mzML case study.

Do you still think I should revise the text to go into more detail about this?

**Comment by lgatto** [comment]
Support in `MSnbase` is that we can load mzML files (not necessary in [memory](http://lgatto.github.io/MSnbase/articles/v04-benchmarking.html)), process the data (for example raw data transformation), and write the new data back the mzML. It isn't possible to add custom cvParams - the cvParams that are written back are those that were parsed and used to create the R-side representation of the MS data. 

To get back to your specific question, mzML write support in `MSnbase` can't be considered complete (as you defined above), and was never meant to cover use cases like you describe in your `psims` (I haven't read the paper in details, I'm basing my claims on the abstract and this issue). It will most likely never cover the `psims` functionality, unless we use it under the hood :-). So no, I don't think my tweet warrants any change (in the abstract) - if anything, you could briefly mention that there is mzML write support in R through Bioconductor, albeit not as complete as in your solution. But thank you very much for enquiring.

By the way, a forward slash has been replaced by a space in `https://github.com mobiusklein/psims` in the abstract.

**Comment by mobiusklein** [comment]
Thanks for catching that typo. That's probably why the source code link in the original journal tweet didn't work. Of course, the URL in the `\href` was correct.

I'll add a note about `MSnbase`. I had originally just referred to `mzR` ([mzR #171](https://github.com/sneumann/mzR/issues/171)).
