### ISSUE TITLE
Compare single hdf5 file vs one hdf5 file per sample

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#403]
Parallel access to the same hdf5 file can cause problems (see issue #391). Having one hdf5 file for each sample/input mzML file can solve some of these problems as per file data access can be parallelized without running into data locking or similar problems.

In commit https://github.com/lgatto/MSnbase/commit/11b0f5aeed20a62d1418c170988993e7853ef392 an object, `Hdf5MSnExp2` was introduced that stores data from each sample into its own hdf5 file. 

Advantages of this object are:
- Faster loading/generating of the `Hdf5MSnExp2` object as the input files can be processed in parallel.
- No problems with per-file parallel access.

Disadvantages:
- Potentially cluttering the workspace/folder where the hdf5 files are saved with a large number of hdf5 files.
- Loosing the advantage to have all data from one experiment in one hdf5 file.

**Comment by jotsetung** [comment]
I did a comparison extracting spectra from 12 mzML files, subsetted to a small retention time range and extracting thus extracting ~ 350 spectra from each file. This subsetting ensures that reading the files in parallel does not fill up the memory and causing performance issues because the system starts to swap.

The results are:

```r
Unit: milliseconds
                                             expr       min        lq      mean
  tmp <- spectrapply(od, BPPARAM = SerialParam()) 4269.3533 4397.7689 4440.4475
           tmp <- spectrapply(od, BPPARAM = mcp2) 2755.0120 2800.1838 2866.4969
           tmp <- spectrapply(od, BPPARAM = mcp3) 1929.5308 1991.3827 2122.4681
           tmp <- spectrapply(od, BPPARAM = mcp4) 1616.4662 1622.3476 1789.9860
  tmp <- spectrapply(h5, BPPARAM = SerialParam()) 1062.0575 1195.8804 1264.8999
           tmp <- spectrapply(h5, BPPARAM = mcp2) 1094.5752 1166.2359 1569.6348
           tmp <- spectrapply(h5, BPPARAM = mcp3)  977.2817 1005.2603 1354.8524
           tmp <- spectrapply(h5, BPPARAM = mcp4)  891.2376  891.2809 1323.3015
 tmp <- spectrapply(h52, BPPARAM = SerialParam())  884.7185 1058.6976 1302.1689
          tmp <- spectrapply(h52, BPPARAM = mcp2) 1059.3127 1081.6102 1194.8125
          tmp <- spectrapply(h52, BPPARAM = mcp3) 1010.8662 1015.5434 1126.8259
          tmp <- spectrapply(h52, BPPARAM = mcp4)  826.4003  837.1282  881.5466
    median        uq      max neval   cld
 4421.4686 4488.1227 4644.503     6     e
 2819.6846 2987.2581 3017.158     6    d 
 2102.7951 2288.0489 2320.256     6   cd 
 1789.5791 1947.0665 1974.877     6  bc  
 1212.6776 1256.0029 1650.103     6 ab   
 1318.0246 1571.8862 2949.063     6 a c  
 1010.5840 1075.3788 3050.025     6 a c  
 1053.0049 1364.3050 2686.976     6 ab   
 1238.2204 1603.8389 1789.318     6 ab   
 1165.9040 1259.1898 1436.954     6 ab   
 1039.0752 1237.9833 1418.412     6 ab   
  849.2608  939.8117  987.418     6 a    
```

`od` is the `OnDiskMSnExp` object and uses `mzR` to load the data from the original mzML files, `h5` is the `Hdf5MSnExp` that reads the data from a single hdf5 file and `h52` is an `Hdf5MSnExp2` object with one hdf5 file per sample/input mzML file.

We see a nice scaling by CPU for the `od` object, quite some speed improvement if we use one of the hdf5 objects. What puzzles me is that parallel processing on hdf5 files does not scale that well. Also, when looking at the `min` timings, using 2 CPUs instead of a single one is actually worse.

Could it be that hdf5 locks connections to the file(s) such that only a single process at a time can access data @grimbough ? I did use `h5disableFileLocking()` after loading the libraries, but since I'm directly calling the C functions of the `rhdf5` package I'm afraid tht won't help... See https://github.com/lgatto/MSnbase/blob/hdf5_jo/R/hdf5_2.R#L145-L146 for the lines in which I open/close the hdf5 file - is there eventually a flag that has to be set somewhere (the `_H5Fopen` function) to explicitely disable file locking?

**Comment by grimbough** [comment]
The call to `h5disableFileLocking()` just sets an environment variable that HDF5 looks for when opening files, so it should apply irrespective of how you're accessing the C functions.

I had a quick check and using the up-to-date **rhdf5** I still see the linear performance increase I reported in http://www.msmith.de/2018/05/01/parallel-r-hdf5/ so it's not a fundamental issue, but rather something different in how we're working here compared to my previous examples.

In that case we're reading (and calculating on) a single dataset, and breaking the column index between processes.  Maybe your suspicion that opening multiple file handles is not efficient is correct.

**Comment by grimbough** [comment]
I think it's certainly plausible that the multi-process dispatch & opening is slower than the reading.  How about the following example.

```r
library(rhdf5)
library(BiocParallel)

## generate data and write to file
mat <- matrix(runif(n = 200000), ncol = 2)
h5f <- tempfile(fileext = ".h5")
for(i in seq_len(400)) {
  if(i %% 2)
    h5write(mat, file = h5f, name = paste("dset", i, sep = "_"), level = 9)
  else 
    h5write(mat, file = h5f, name = paste("dset", i, sep = "_"), level = 0)
}
```

In the above we create a 400 datasets, each with 200,000 rows and 2 columns, which I think is the right order of magnitude for you data.  Correct me if I'm wrong!  Half of these are compressed with GZIP level 9 and half with GZIP level 0.  I just want to see if 'doing work' in addition to the reading makes a difference to the timings.  

Then lets compare reading the compressed and the not-compress using multiple threads:

```r
## finds all dataset names, then reads them
## i is the number of cores to use, odd is a logical
par_read <- function(i, odd) {
  if(odd)
    dsets <- paste0('dset_', seq(1,400,2))
  else
    dsets <- paste0('dset_', seq(2,400,2))
  parallel::mclapply(dsets, h5read, file = h5f, mc.cores = i)
}

bm1 <- microbenchmark::microbenchmark(
  par_read(1, TRUE), par_read(2, TRUE), par_read(3, TRUE), par_read(4, TRUE),
  par_read(1, FALSE), par_read(2, FALSE), par_read(3, FALSE), par_read(4, FALSE),
  times = 3
)
```
```
Unit: milliseconds
               expr       min        lq      mean    median       uq       max neval
  par_read(1, TRUE) 2169.6019 2184.9682 2245.4464 2200.3346 2283.369 2366.4028     3
  par_read(2, TRUE) 2075.1646 2117.3457 2241.7324 2159.5267 2325.016 2490.5058     3
  par_read(3, TRUE) 1498.4111 1569.1251 1827.4727 1639.8390 1992.003 2344.1680     3
  par_read(4, TRUE) 1328.0208 1431.1749 1489.2176 1534.3289 1569.816 1605.3031     3
 par_read(1, FALSE)  802.2079  925.1751 1024.9134 1048.1423 1136.266 1224.3900     3
 par_read(2, FALSE) 1188.1736 1308.0537 1394.1033 1427.9337 1497.068 1566.2026     3
 par_read(3, FALSE) 1005.5267 1142.3833 1726.8768 1279.2399 2087.552 2895.8637     3
 par_read(4, FALSE)  932.5547  945.9616  957.1395  959.3685  969.432  979.4955     3
```

Looks to me like when the compression is hard we see a benefit from using multiple threads, but it's actually prohibitive to do this when there's no compression, suggesting that it's certainly possible for serial reads to be faster than trying to do it in parallel.

**Comment by lgatto** [comment]
Re your disadvantages above, @jotsetung, I think we can safely ignore these if we create one directory (possibly even hidden), something like 
```
.SHA5_of_file_names/orig_file_name_1.h5
.SHA5_of_file_names/orig_file_name_2.h5
.SHA5_of_file_names/orig_file_name_3.h5
.SHA5_of_file_names/orig_file_name_4.h5
...
```
This even makes the `mzML` to `hdf5` correspondence straightforward.

(I am also still considering `BiocCache`...)

**Comment by jotsetung** [comment]
@lgatto agree. The function to create a `Hdf5MSnExp2` (with one hdf5 file per mzML file) has an argument `hdf5path` that allows to specify a folder where to store the files.

**Comment by jotsetung** [comment]
@grimbough thanks for your input! I think we are doing extremely well. In the end it seems that reading data from one/more hdf5 files is so fast that it makes no sense to parallelize it as. If there are additional calculations performed on top of the extracted data the story is again quite different and we see a performance gain:

In the example I was reading 8 mzML files and am removing signals with an intensity < 1000 and extracting from each spectrum the mean intensity. `od` is again the object reading data from mzML files, `h5` from a single hdf5 file and `h52` from one hdf5 file per mzML file:

```r
Unit: seconds
                                                             expr       min
  a <- spectrapply(od, FUN = spctra_fun, BPPARAM = SerialParam()) 24.503728
           a <- spectrapply(od, FUN = spctra_fun, BPPARAM = mcp2) 11.631402
           a <- spectrapply(od, FUN = spctra_fun, BPPARAM = mcp3)  9.282632
           a <- spectrapply(od, FUN = spctra_fun, BPPARAM = mcp4)  6.616506
  a <- spectrapply(h5, FUN = spctra_fun, BPPARAM = SerialParam())  9.460080
           a <- spectrapply(h5, FUN = spctra_fun, BPPARAM = mcp2)  5.479902
           a <- spectrapply(h5, FUN = spctra_fun, BPPARAM = mcp3)  5.265595
           a <- spectrapply(h5, FUN = spctra_fun, BPPARAM = mcp4)  3.822537
 a <- spectrapply(h52, FUN = spctra_fun, BPPARAM = SerialParam()) 10.416272
          a <- spectrapply(h52, FUN = spctra_fun, BPPARAM = mcp2)  4.693011
          a <- spectrapply(h52, FUN = spctra_fun, BPPARAM = mcp3)  4.926477
          a <- spectrapply(h52, FUN = spctra_fun, BPPARAM = mcp4)  3.738530
        lq      mean    median        uq       max neval   cld
 24.700535 25.409394 25.806142 25.985227 26.051341     5     e
 11.730706 13.536367 12.115192 14.668586 17.535949     5    d 
  9.446768  9.941436  9.652242  9.740641 11.584895     5  b d 
  7.509027  8.957366  9.760118 10.260502 10.640678     5 abc  
 11.473220 12.095017 12.790399 13.073613 13.677775     5   cd 
  7.034111  7.862632  8.823111  8.951383  9.024654     5 ab   
  6.647311  7.512346  8.372970  8.457016  8.818835     5 ab   
  4.540544  5.528619  4.922359  6.760641  7.597015     5 a    
 11.479377 11.907134 11.532648 12.680137 13.427238     5   cd 
  6.006038  6.417964  6.171787  7.431667  7.787319     5 ab   
  5.679842  7.166995  7.282385  7.708795 10.237477     5 ab   
  3.911676  6.200978  6.780255  7.180545  9.393885     5 a    

```

I am now satisfied with the way we safe/read the data to/from hdf5 files. It's just the question if we want to use the one-hdf5-file per experiment or the one-hdf5-file per sample. The former has the advantage that everything is in a single file, the latter that subsetting, filtering and parallel writing might be easier and faster.

**Comment by lgatto** [comment]
> It's just the question if we want to use the one-hdf5-file per experiment or the one-hdf5-file per sample.

Another point is that, at some point, we will need to write data back to disk (this is another motivation for using hdf5, in addition to speed). Any idea on how parallel/multiple files vs single file writing will perform?

**Comment by jotsetung** [comment]
Seems parallel writing to a single hdf5 file does not work consistently, even after setting `h5disableFileLocking()` (see issue #405). Thus, we should opt for the one hdf5 file per mzML/sample approach.

**Comment by grimbough** [comment]
Parallel writing is not supported by HDF5 (except maybe when using MPI - never tried this myself).  I think this is because some global properties are stored in memory by the writing process, and two or more processes will essentially compete with each other and destroy the structure created by the others.  Sometimes you get a subset of the contents working, but often there will simply be an empty file created at the end.

If you want to follow the multi-file paradigm, one thing that may make life easier are external links, which allow you to link datasets between files.  You can then create a file per mzML and then have a single light-weight 'master' file that appears to contain everything.  Maybe this makes it easier to reference a group of samples, although you still end up with many files on disk.

The example below will parallel write a few files each containing a single dataset with an easy to guess name, and then create a master file and loop over the data files adding the a link to the dataset inside.

```r
## global dataset for testing
mat <- matrix(runif(n = 2000000), ncol = 2)

## creates a file containing one dataset.  File and 
## dataset names are related by argument i
simple_write <- function(i) {
  file_name <- paste0(tempdir(), .Platform$file.sep, i, ".h5")
  if(file.exists(file_name)) { file.remove(file_name) }
  dset_name <- paste0("dset_", i)
  h5write(mat, file = file_name, name = dset_name)
}

para_write <- function(i, mc.cores = 1) {
  ## write example datasets in parallel
  parallel::mclapply(seq_len(i), simple_write, mc.cores = mc.cores)
  ## identify individual files & open 'master' to store them all
  data_files <- list.files(tempdir(), pattern = "[0-9].h5$")
  master_file <- paste0(tempdir(), .Platform$file.sep, "master.h5")
  fid <- H5Fcreate(master_file)
  ## loop through data file, creating a link to the dataset
  ## in each one
  for(f in data_files) {
    dset_name <- paste0("dset_", gsub(x = f, ".h5", ""))
    H5Lcreate_external(target_file_name = f, 
                       target_obj_name = dset_name,
                       link_loc = fid,
                       link_name = dset_name)
  }
  H5Fclose(fid)
}
``` 

*You could do something nicer where the writing process returns the name of the file and the datasets it includes so you don't need to construct them.*

This seems to scale nicely with more cores:

```r
> bm1 <- microbenchmark::microbenchmark(
+   para_write(20, 1), para_write(20, 2), para_write(20, 3), para_write(20, 4), 
+   times = 10
+ )
> bm1
Unit: seconds
              expr      min       lq     mean   median        uq       max neval
 para_write(20, 1) 5.357794 6.019130 8.503277 9.250356 10.458790 10.892386    10
 para_write(20, 2) 3.063265 3.206872 4.681616 5.464361  5.587954  6.345717    10
 para_write(20, 3) 2.155480 2.867874 3.540354 3.794196  4.215897  4.710625    10
 para_write(20, 4) 1.568722 1.651583 2.426993 2.360672  3.205947  3.322449    10
```

and here's how the master file presents itself:

```r
> h5ls(master_file)
   group    name       otype dclass        dim
0      /  dset_1 H5I_DATASET  FLOAT 100000 x 2
1      / dset_10 H5I_DATASET  FLOAT 100000 x 2
2      / dset_11 H5I_DATASET  FLOAT 100000 x 2
3      / dset_12 H5I_DATASET  FLOAT 100000 x 2
4      / dset_13 H5I_DATASET  FLOAT 100000 x 2
5      / dset_14 H5I_DATASET  FLOAT 100000 x 2
6      / dset_15 H5I_DATASET  FLOAT 100000 x 2
7      /  dset_2 H5I_DATASET  FLOAT 100000 x 2
8      /  dset_3 H5I_DATASET  FLOAT 100000 x 2
9      /  dset_4 H5I_DATASET  FLOAT 100000 x 2
10     /  dset_5 H5I_DATASET  FLOAT 100000 x 2
11     /  dset_6 H5I_DATASET  FLOAT 100000 x 2
12     /  dset_7 H5I_DATASET  FLOAT 100000 x 2
13     /  dset_8 H5I_DATASET  FLOAT 100000 x 2
14     /  dset_9 H5I_DATASET  FLOAT 100000 x 2
```

**Comment by jotsetung** [comment]
Thanks @grimbough for your input. I think we will stick to the one-hdf5-file-per sample approach. This makes also sub-setting and filtering the data simpler. Closing this issue now as the changes have been implemented in commit  https://github.com/lgatto/MSnbase/commit/b8de4d85b166ee68ad0bb8746a72c1d31f88757e
