### ISSUE TITLE
Implement a new data reading function

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#411]
For the new backends we need a new reader. I'd suggest something like `readMSData3 <- function(files, sampleData, backend)`. We should change the name then later...

**Comment by jotsetung** [comment]
So far we're not reading instrument information or similar stuff. Feel free to add that functionality if you think it's important/required @lgatto @sgibb .

Also, I think we should call `backendInitialize` and `backendImportData` on the `backend`.

**Comment by lgatto** [comment]
> So far we're not reading instrument information or similar stuff.

Quick comment on that - all the MIAME/MIAPE business never really caught up, so I suggest we ignore it for now. I will discuss further in another issue.

**Comment by jotsetung** [comment]
Agree - if needed we can add it later. I'd like to keep the `MSnExperiment` as simple and lightweight as possible.
