### ISSUE TITLE
Copy and modify S4 objects without the underlying file

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#412]
As @jotsetung mentioned in https://github.com/lgatto/MSnbase/issues/405#issuecomment-455159654 we will get into trouble if someone copies **and** modifies S4 objects (e.g. `Hdf5MSnExp`) without copying the underlying file.

@lgatto mentioned using checksum to at least recognize the problem and inform the user. We should definitely implement this in the `Backend` class.

I would also suggest a `deepCopy` method for all file base backends (that are writeable) that copies the underlying file if the user really want a copy (e.g. to compare different steps in a pipeline).

**Comment by jotsetung** [comment]
Yes, for the (outdated) *hdf5* backend in branch `hdf5` I'm now keeping an md5 sum of the spectra data of one file in the object **and** am writing it to the hdf5. Whenever data is read from the hdf5 file the check sums are compared and an error is thrown if they don't match (see e.g. https://github.com/lgatto/MSnbase/blob/hdf5/R/hdf5.R#L325-L335).

As you suggested, this should be managed by the backend class, so the `MSnExperiment` doesn't have to care about it.

**Comment by sgibb** [comment]
Do we really need a `backendDeepCopy` method? 
Currently it will just return the object. For `BackendHdf5` it has to be implemented (I guess we would use `file.copy` with a newly generated filename for all `@h5files`).
`setBackend` offers us a solution for this problem already:
```r
sf <- dir(system.file("sciex", package = "msdata"), full.names = TRUE)
sciex_h5 <- readMSnExperiment(sf, backend = BackendHdf5(),
                              path = file.path(tempdir(), "sciex_h5"))
sciex_h5_copy <- setBackend(sciex_h5, BackendHdf5(), path = ".")
```
(of course this has to be documented)
There is at least one problem with this solution: I guess `file.copy` is much faster than reading and writing all spectra to new files.

**Comment by sgibb** [comment]
Currently we don't need this. We may implement this if some user really want to use it.
