### ISSUE TITLE
Synchronize documentation efforts

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#413]
I'd say we should synchronize the documentation efforts, specifically for the backends. I guess we will simply have a single documentation file for all backends and the roxygen code for that should go to the *Backend-class.R*.

**Comment by sgibb** [comment]
I would suggest an .R file per backend that just adds its specific documentation (using the `@describeIn` roxygen tag), so it results in one large manual page for all backends.

**Comment by jotsetung** [comment]
Agree. Wasn't aware of the `@describeIn` tag - have to look it up.

**Comment by jotsetung** [comment]
I did that with `XChromatogram` and `XChromatograms` classes in `xcms`. I'm using a single rd file for all methods, functions and the classes (always using `@rdname XChromatogram`). To keep it somehow organized I'm using `@section` tags grouping description of functions and methods by topic.

**Comment by sgibb** [comment]
Ok, that's possible but you don't really document the class (would require `\docType{class}` and the slots have to be documented). In fact you misuse the method documentation (`\docType{method}`) and add an alias for `Chromatogram(s)-class` to it. :wink:

**Comment by jotsetung** [comment]
That's right. But that's also something that Martin Morgan did in the `AnnotationFilter` package, so, from that perspective it seems to be acceptable - and users should not use the slots anyway directly.

**Comment by sgibb** [comment]
Ok, if Martin did it, it is more or less official. Let's do it that way.

**Comment by jotsetung** [comment]
Suggestion: we use the same documentation concept for the `MSnExperiment` class (one documentation, method descriptions grouped into sections). 
Also, I'd propose to not export any of the `backend...` methods (and hence documenting them also only internally). The user should not have to deal with these methods.

**Comment by sgibb** [comment]
I agree with both suggestions (same documentation concept for `MSnExperiment`, don't export and document (for the user) the `backend...` methods).
