### ISSUE TITLE
backendReadSpectra on a single or multiple files?

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#419]
based on the discussion https://github.com/lgatto/MSnbase/commit/f7673703420ff9b365723495b4509958dd918e50#r32063917 I think we agreed that parallelization should be done on a per-file basis in `MSnExperiment`. Now, implementing `backendReadSpectra,BackendMzR` I'm a little struggling whether I should expect parameter `file` to be always of length 1 (would fit the above) or whether I should also support `length(file) > 1`. @sgibb any opinion?

**Comment by sgibb** [comment]
You are right: the backend reader should just work on single files. I guess I could remove all the `BPPARAM` arguments again (except from `backendImportData`).

**Comment by sgibb** [comment]
Or we do the parallelisation in the backend: https://github.com/lgatto/MSnbase/pull/418#discussion_r251442014

**Comment by jotsetung** [comment]
With https://github.com/lgatto/MSnbase/commit/23fd27eb308486f367e816b890aac3a04f46e266 I've now added the `spectrapply,MSnExperiment` method. If we move now the parallelization into the backend I'd propose to drop the `backendReadSpectra` method and make a `backendSpectrapply` method that does exactly what the `spectrapply` does:
- if `FUN = NULL` return a `list` of `Spectrum` objects.
- if `FUN` is a function, apply that function to each spectrum and return a `list` of it's result.

Also the processing queue should then be passed to this method.

**Comment by jotsetung** [comment]
Allowing the `backendReadSpectra` to read only data from a single file sounds somehow strange. So, from that point of view I'd go to move the `spectrapply` to the backend. 

Writing spectra is however a completely different story. For in-mem all is fine, but we will run into troubles if we require to pass **all** spectra to the `writeSpectraData`. There we would have to find a clever solution to allow writing the data in chunks (ideally per file, again).

**Comment by jotsetung** [comment]
I'd say the `backendReadSpectra` should support reading spectra from one or multiple files. It's up to the `MSnExperiment` to decide what's best.
