### ISSUE TITLE
Redifinition of Backend classes

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#422]
Based on some comments/discussions (see e.g. issue #419) I'd propose to re-define the `Backend` classes:

- add `@files` slot to hold the original file names.
- all spectra access should be purely handled by the `Backend` class, including parallelization etc.

The classes should have the additional methods:
```r
setMethod("backendSpectrapply", "Backend", function(object, FUN = NULL, queue = list(), BPPARAM = bpparam(), ...) { ... })
```
 With `queue` being the `@processingQueue` of the `MSnExperiment` object and `FUN` an (optional) function to applied to each `Spectrum`.

In addition we would need a `backendWriteSpectra` or similar function that does not require that the list of spectra to be written has to be passed as an argument. That should anyway not be required, as the spectra data is anyway handled by the backend. So it should suffice that the `spectraData` is passed to the function as well as the processing queue.

**Comment by jotsetung** [comment]
We might also want to move the `processingQueue` slot to the `Backend` class (issue #423).

**Comment by jotsetung** [comment]
I'm currently adding also the `@processingQueue` to the backend and fixing methods and unit tests for `BackendMzR` and `BackendMemory`.

**Comment by sgibb** [comment]
Just add a link because it is related to the `@processingQueue` part: https://github.com/lgatto/MSnbase/issues/423#issuecomment-458722366

**Comment by jotsetung** [comment]
With the commits above I changed the `Backend` class again to its original definition (except that it has also the `@files` slot). So, the purpose of the `Backend` is exclusively on handling spectrum data i/o as suggested in https://github.com/lgatto/MSnbase/issues/423#issuecomment-458722366

In addition I removed the `backendSpectrapply` method again - all this functionality (parallelization by file, applying the lazy evaluation queue) is done in the `MSnExperiment` class. Only thing we have to check is how we can efficiently write/update spectrum data to the backend **without** having to read the full spectrum data first. In principle this should however be possible in a similar way than `spectrapply,MSnExperiment` works now.

**Comment by sgibb** [comment]
Sorry for all this confusion and back and forth. Now we are (again) more in line with my initial idea.

> Only thing we have to check is how we can efficiently write/update spectrum data to the backend without having to read the full spectrum data first.

Currently (and in your PR) all spectra from one file are read at once and subsequently processed. We just have to ensure that `backendWriteSpectra` is called in the `bplappy`. Should be easy enough:
```r
    res <- bplapply(split(object@spectraData, file_f), function(z, queue, bknd) {
        backendWriteSpectra(bknd, z, .apply_processing_queue(backendReadSpectra(bknd, z), queue))
    }, queue = pqueue, bknd = object@backend, BPPARAM = BPPARAM)
```
Because `BackendMzR` doesn't provide write support `BackendMzR,backendWriteSpectra` could just swap the backend to `BackendMemory`.

BTW: We could add an `fcol="fileIdx"` argument to the `MSnExperiment,spectrapply` (or we call it `scol`/`sdcol` for `spectraData`) to control the split. Maybe you have even larger files and want to parallelize on a combination of file and spectra indicies.

**Comment by jotsetung** [comment]
> Sorry for all this confusion and back and forth. Now we are (again) more in line with my initial idea.

well, it was my fault. But now I feel it really makes much sense! And yes, writing data should be doable, just as you described.

> Because BackendMzR doesn't provide write support BackendMzR,backendWriteSpectra could just swap the backend to BackendMemory.

I would rather show a message that the backend does not support writing. It actually doesn't have to. But converting to a `BackendMemory` automatically might not be a good idea - once the user realizes what happens the memory will already get full... I would leave the decision up to the user: do you want low memory footprint: use an mzR backend, do you want on-disk with write support and have plenty of free disk space: use hdf5 backend, do you have enough memory or your experiment is small: use in memory.

Regarding the `fcol`. It's a nice idea. I just have to think over it.

**Comment by jotsetung** [comment]
Closing the issue because I think the present definition of the `Backend` class works well.
