### ISSUE TITLE
MSnbase style guide

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#427]
I have added a section in the MSnbase development vignette. Currently, there's

- Do not use `.` when naming symbols.
- A leading `.` can be used for hidden/local functions or variables.
- Use `##` to start full-line comments.
- Use spaces between `=` in function arguments or class definition.
- Always use a space after a comma. This: `a, b, c`.
- Always use spaces around binary operators.

I would also like to suggest 

- Use `##'` for `roxygen` headers (**fixed** typo)

To be discussed:

- do we use/accept `snake_case_style` for functions?

@sgibb @jotsetung - comments, suggestions?

**Comment by jotsetung** [comment]
All OK.

> Use ##@ for roxygen headers

Do you mean using `##' ` for roxygen instead of `#'`? Honestly, I like `#'` more because it looks cleaner - I feel.

> do we use/accept snake_case_style for functions?

I would say yes, if it's an internal function. Exported functions should not use snake case.

**Comment by sgibb** [comment]
What about https://www.bioconductor.org/developers/how-to/coding-style/ ?
At least this *Use spaces between = in function arguments or class definition* differs: 
> No space around “=” when using named arguments to functions. This: `somefunc(a=1, b=2)`

And of course, I am against user-visible `snake_case_style` :wink:

**Comment by lgatto** [comment]
> *Use spaces between = in function arguments or class definition* differs.

Yes, I know, that's my personal style :-)

**Comment by jotsetung** [comment]
Actually I prefer `somefunc(a = 1, b = 2)` over `somefunc(a=1, b=2)`, it's simply easier to read - and I would have to change a lot of code as I use this by default...

**Comment by sgibb** [comment]
I could agree with `somefunc(a = 1)`. What about indentation code lines that are longer than 78/80 characters?

**Comment by sgibb** [comment]
BTW: @lgatto you are writing a `lintr` settings file for the style, aren't you? :wink:

**Comment by lgatto** [comment]
Unfortunately I don't have a `lintr`. Not sure I'll find time to write one.

> What about indentation code lines that are longer than 78/80 characters?

What do you mean? Line length includes indentation. 80 should be a (soft) limit indeed.

**Comment by lgatto** [comment]
By the way, feel free to update the style guide section in the development vignette directly, or send a PR so we can discuss and merge directly.

**Comment by sgibb** [comment]
I meant something like this:
```r
# no wrap at 80
someVeryLongVariableName <- someVeryLongFunctionName(withSomeEvenLongerFunctionArgumentA = 1, withSomeEvenLongerFunctionArgumentB = 2)

# alternative 1
someVeryLongVariableName <- 
    someVeryLongFunctionName(withSomeEvenLongerFunctionArgumentA = 1, 
                             withSomeEvenLongerFunctionArgumentB = 2)

# alternative 2
someVeryLongVariableName <- someVeryLongFunctionName(
    withSomeEvenLongerFunctionArgumentA = 1, 
    withSomeEvenLongerFunctionArgumentB = 2
)
```

I prefer alternative 2.

**Comment by lgatto** [comment]
@sgibb - I definitely agree that your first example needs to be wrapped on multiple lines. I don't really mind about alternative 1 or 2, to be honest. I am not keen on the lonely closing parenthesis at the end, though. I would probably prefer 2b below to 2. 
```r 
# alternative 2b
someVeryLongVariableName <- someVeryLongFunctionName(
    withSomeEvenLongerFunctionArgumentA = 1, 
    withSomeEvenLongerFunctionArgumentB = 2)
```
I think we should definitely add a guideline to guard against the first option.
