### ISSUE TITLE
xtandem results in MSexp?

### ISSUE THREAD

**Issue by adder** [lgatto/MSnbase#43]
Hi, 
You are probably aware that xtandem does not use the mzid output format for its result. The xtandem XML can thus not be loaded directly into MSexp. It is possible to read the results with rtandem package. Is there some way to get your xtandem results  or the rtandem result class into MSexp without using external tools like http://www.psidev.info/mzidentml to convert the xml to mzid (which didn't work btw when I tried is, some nulpointerexecption)

greetz

**Comment by lgatto** [comment]
> You are probably aware that xtandem does not use the mzid output format for its result. 
> The xtandem XML can thus not be loaded directly into MSexp. 

Yes, I know that. We prefer to focus our effort on community-wide standards although, to be fair, xTANDEM's format has been out there for longer.

> It is possible to read the results  with rtandem package. Is there some way to get your 
> xtandem results or the rtandem result class into MSexp without using external tools like 
> http://www.psidev.info/mzidentml to convert the xml to mzid (which didn't work btw when I 
> tried is, some nulpointerexecption)

Once you have the xTANDEM results in R, as a `data.frame` for example, and you can match the identification results and the spectra in the `MSnExp`, you will have to re-order the identification `data.frame` and then do the following to add these data to the existing feature/spectra annotation:

```r
fd <- fData(msexp) 
## merge or cbind fd and your id data, keeping
## the original row order; for example using dplyr::left_join
## fd <- left_join(fd, id)
fData(msexp) <- fd
``` 

(You might want to send a bug report re the conversion error.)

**Comment by sgibb** [comment]
I am not familiar with the `rTANDEM` package. Do we get a `data.frame` with all necessary information? If this is the case we could think about a function similar to our current `addIdentificationData` method that accept a `data.frame` as input. That should be not too much work because we currently convert mzIdentML into a `data.frame` and do the merging via `utils.mergeSpectraAndIdentificationData` (hidden by `NAMESPACE`). `utils.mergeSpectraAndIdentificationData` needs both the feature and identification data as `data.frame` and returns a merged feature `data.frame`.

**Comment by lgatto** [comment]
`rTANDEM`'s output is a bit convoluted, IMHO. It would be possible to get a peptide `data.frame` by first extracting all proteins, then all peptides. But I haven't used it enough to make sure this would work for sure and that the matching with the original data, whether `mgf` or `mzML` would be straightforward. 

However, I think supporting identification data as a `data.frame` would actually enable to generalise it enough at little cost. That would be great!

**Comment by sgibb** [comment]
If #45 is merged we could provide a `addIdentificationData` method with the signature: `c("MSnExp", "rTANDEM")` but I never used `rTANDEM`.

**Comment by lgatto** [comment]
Let's investigate that later. AFAIK, there is no direct way to get the full identification data as a `data.frame` from `rTANDEM`. I think `c("MSnExp", "mzRident")` and all the existing with `MSnSet` instead of `MSnExp` are are better bet.

**Comment by lgatto** [comment]
Closing for now. Re-open if still relevant.
