### ISSUE TITLE
Implement filter methods for `MSnExperiment`

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#433]
Implement data subsettings and filtering methods:

- [X] `[`
- [X] `[[`
- [X] `filterFile`
- [x] `filterMsLevel`
- [x] `filterPolarity`
- [x] `filterRt`
- [x] `filterMz`
- [x] `filterAcquisitionNum`
- [x] `filterEmptySpectra`
- [x] `filterPrecursorScan`

**Comment by jotsetung** [comment]
All done in the *spectra_jo* branch.

**Comment by jorainer** [comment]
Obsolete
