### ISSUE TITLE
Method to switch backends

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#434]
I think it's now time to think also about the best way to switch backends.

The most intuitive approach would be to have a simple `as` method to coerce one into the other object. This will however not work as switching backends will also need the `spectraData` and eventual additional arguments that are specific to the backend (such as `path` for `BackendHdf5`). Keeping our naming scheme we could implement a `backendAs` method that supports additional parameters.

Any other ideas/comments @lgatto @sgibb?

**Comment by lgatto** [comment]
Sounds good. To make sure I understand, you are thinking of something along the lines of
```r
setGeneric("backendAs", function(object, backend, ...) standardGeneric("backendAs"))

setMethod("backendAs", c("MSnExperiment", "BackendMzR"), ...)
setMethod("backendAs", c("MSnExperiment", "BackendMemory"), ...)
setMethod("backendAs", c("MSnExperiment", "BackendHdf5"), ...)
```

**Comment by jotsetung** [comment]
I thought more of 
```r
setMethod("backendAs", c("BackendMzR", "BackendMemory"), ...)
```

but you are right, because we need also the `spectraData` it should involve the `MSnExperiment` (as you suggest). But then I would call the method `switchBackend` instead.

**Comment by lgatto** [comment]
Ok, let's vote:
- :+1:  for `backendAs`
- :-1: for `switchBackend`

**Comment by lgatto** [comment]
the suspense is unbearable... it all lies into @sgibb's hands to decide :-D

**Comment by jotsetung** [comment]
Yes :)
I can also live with `backendAs`. My reasoning for not using `backendAs` was that all (internal) methods for `Backend` classes start with `backend`, so it could be confusing to have a method following that naming scheme that is not a `Backend` class.

**Comment by jotsetung** [comment]
Switching the backend is surprisingly simple (just used `switchBackend` here, but we can change that):
```r
#' @rdname MSnExperiment
setGeneric("switchBackend", function(object, backend, ..., BPPARAM = bpparam())
    standardGeneric("switchBackend"))
#' @rdname hidden_aliases
setMethod("switchBackend", c("MSnExperiment", "Backend"), function(object,
                                                                   backend,
                                                                   ...) {
    backend <- backendInitialize(backend, fileNames(object),
                                 object@spectraData, ...)
    ## Would have to check modification counter if the data was
    ## changed...
    backend <- backendWriteSpectra(
        backend, backendReadSpectra(object@backend, object@spectraData),
        object@spectraData)
    object@backend <- backend
    validObject(object)
    object
})
```

This works unfortunately **not** for larger experiments as the full data is first read into memory by `backendReadSpectra`. I have to think of a better solution here... any suggestions welcome.

**Comment by jotsetung** [comment]
I'm afraid we have to go for `Backend`-specific solutions (i.e. one for each `Backend` class). Too bad, thought we cound use a general-purpose one.

**Comment by lgatto** [comment]
Actually, we will need (n² - n)/2 for n backend implementations, if we want to be able to switch between any backends. Not sure we really need all pairs though.

**Comment by jotsetung** [comment]
I think we should get away with at max n implementations. It's more the `backendWriteSpectra` that is tricky. The `backendReadSpectra` is simple and easily parallelizable. `backendWriteSpectra` returns however a `Backend` class. So we have to cheat a little to enable parallel processing.

**Comment by lgatto** [comment]
I'm worried about the *cheat a little*. I mean about *cheat*, not little.

**Comment by jotsetung** [comment]
:) it's not really cheating. That was the wrong formulation. We just have to consider object-specific properties. 
Converting any `Backend` to `BackendMemory` is no problem, for that we use the implementation above. To `BackendMzR` is even easier: there is no need for the `backendReadSpectra` and `backendWriteSpectra` calls. `BackendHdf5` is a little tricky because of the checksum/modification counter. But I am currently testing something.

**Comment by jotsetung** [comment]
It's better to discuss this if I have the code committed - then we can discuss if that's the way to go or if we need to rethink.

**Comment by jotsetung** [comment]
It's in https://github.com/lgatto/MSnbase/commit/d03094e763ae2014019563cb102ac2f7f7f9abb1 . We can continue the discussion on the actual code.

**Comment by sgibb** [comment]
I haven't look at the code yet. But we could provide a general method that loads everything in memory as default and implement a few specifics for e.g. the conversion from/to `BackendHdf5` for speed and memory saving.

I had `switchBackend` in my initial gist. I don't really like `backendAs` because of the reason @jotsetung mentioned (`backend` prefix for all non-exported backend methods). 
@lgatto if you don't like `switchBackend`, what about `setBackend("MSnExperiment", "NewBackend")` ?

**Comment by lgatto** [comment]
Mhh, yes, I prefer `setBackend`, not sure why though. And yes, the reason mentioned by @jotsetung rules anything starting with `backend` out. I'll let you choose which name is best.

**Comment by jotsetung** [comment]
> I haven't look at the code yet. But we could provide a general method that loads everything in memory as default and implement a few specifics for e.g. the conversion from/to `BackendHdf5` for speed and memory saving.

@sgibb, you're reading my mind. That's what I've implemented - so this pull request will then be easier 😉 

And `setBackend` sounds nice. Yes, I like that. I'll rename.

**Comment by jotsetung** [comment]
It's now implemented and in the *backends* branch.
