### ISSUE TITLE
Chromatogram experiments

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#437]
This issue is a follow-up from a discussion from #436 that notes some changes that could be implemented to the current `Chromatogram` class:

- re-same the `phenoData` slot `sampleData` and implement it as a `DataFrame`, to be consistent with `MSnExperiment`
- the feature data should also be encoded as a `DataFrame`
- `MSnExperiment` and `Chromatogram` could have equally named feature meta-data. This is also true for quantitative data (i.e. `MSnSet`). My suggestion would be to call these `featureData`, have a generic accessor `featureData` (or `mcols`, both, ... to be discussed), and possibly also a `spectraData` for `MSnExperiment`, `chrom[atogram]Data` for `Chromatogram`, ...
 
- `Chromatogram` objects should also get a `metadata` list and `version`/`processing` characters, in line with the `MSnExperiment` class.
- Later, they will probably more to a backend structure. This could also lead to a lazy evaluation feature and a `processingQueue` list.

The point here is to have equivalent experiment-level classes for MS and chromatographic data.

**Comment by sgibb** [comment]
I never used the `Chromatogram(s)` class myself and never analysed SWATH data. But reading @jotsetung comment on #436:

> I need to find and extract MS2 spectra that are associated with chromatographic peaks, and for these I want to add additional metadata to each `Spectrum` class (i.e. what the current `Spectra` object allows).

it could be useful to provide a container class that could store both spectra and chromatograms. 
For the classical `MSnExp` replacement (currently named `MSnExperiment`) the chromatograms could be empty. Would that be useful?

**Comment by lgatto** [comment]
Yes, as there is a link between spectra and chromatograms - there are just different dimensions of the same data. In some cases one uses only one, in others both (such as MS1 quantitation). I am not sure if the mega-class for both would be the best approach though, but my goal (although I don't know how yet), is to make sure we have foreign keys from one to the other - and these will be somehow different in proteomics and metabolomics.

**Comment by lgatto** [comment]
Let me clarify. I wouldn't see a point of having a class with spectra and chromatograms that each have their own independent feature metada. Hower, if we could define and implement a link  between these, and hence meaningful subsetting operation for example, then it might be very convenient.

**Comment by jotsetung** [comment]
I would also not put both into the same megaclass.

Regarding the link between both, that was also one reason for the `Spectra` class: I wanted to be able to link from the spectra back to the chromatographic peaks and features they belong to. This was added as an additional metadata column (with the chromatographic peak IDs or the feature IDs, respectively).
