### ISSUE TITLE
MSnExperiment feature metadata

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#438]
I would propose to rename `spectraData` to `featureData` in the [`MSnExperiment` class](https://github.com/lgatto/MSnbase/blob/backends/R/MSnExperiment-class.R#L232) so that we can have a consistent slot in `MSnExperiment`, `Chromatogram` and `MSnSet` classes, have a `featureData` accessor that returns the `DataFrame`, and overload it with `spectraData` for the `MSnExperiment` class.

See also #437.

Waiting for @jotsetung and @sgibb before sending the PR.

**Comment by jotsetung** [comment]
I was happy with `spectraData` because `featureData` can be misleading - I have `featureValues`, `featureDefinitions` in `xcms` and there *feature* refers to an m/z - retention time entity (ion). In the end I can live with it, just wanted to explain why I thought `spectraData` is actually *better*.

**Comment by lgatto** [comment]
Yes, you have features, which is the general term for peptides, scan, ions, proteins,... anything of interest.

**Comment by sgibb** [comment]
I also thought `spectraData` is easier to understand for the `Backend` class but of course for the `MSnExperiment` we could use `featureData` to be consistent with `MSnSet`. But then I would rename the `spectraData` arguments in the `backend*` methods into `featureData` as well.

**Comment by lgatto** [comment]
Yes, I would suggest to name the slots `featureData`, have a generic `featureData` accessor for all classes (`MsnExperiment`, `MSnSet`, `Chromatogram`), and overload these with class-specific accessors, such as `spectraData` of `MSnExperiment`s.

**Comment by jotsetung** [comment]
Note: in the *backends_jo* branch I did implement already the `featureData,MSnExperiment` and `featureData<-,MSnExperiment` methods. I will make a pull request soon.
