### ISSUE TITLE
Add a method that makes changes of the lazy processing queue permanent

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#440]
This picks up the discussion from issue #405. In summary, we agreed to use the lazy processing queue as standard for any data manipulations, i.e. `clean,MSnExperiment` adds the `clean` call to the object's lazy processing queue and applies it only (but each time) spectra data is retrieved.

To test this I've already implemented `removePeaks,MSnExperiment` and `clean,MSnExperiment` and it works nicely with all backends. `BackendMemory` and `BackendHdf5` would however allow to apply changes and write them back to the backend.

The worflow would be something like this:
```r
## Perform smoothing and peak picking
data <- smooth(data)
data <- pickPeaks(data)

## Both are in the lazy processing queue. If we're happy
## with both we could apply these changes to make them
## persistent
applyProcessingQueue(data)

## changes were written to the backend. The processing
## queue of `data` is now empty
```

Side note: we could even implement an `undo` method that removes the last processing step from the lazy processing queue - just an idea.

Name suggestions:
- `applyProcessingQueue`
- `consolidate`
- `force`

I wouldn't use `write...` because we have e.g. `writeMSData` to export the data to mzML (`exportMSData` would have been better).

@lgatto @sgibb other suggestions, preferences?

**Comment by sgibb** [comment]
I like the `applyProcessingQueue` because it tells exactly what is going on but I would prefer to use
`data <- applyProcessingQueue(data)`. In `R` nobody is expecting side effects from a function and `applyProcessingQueue` will modify the backend and/or metadata and clean the processing queue (= really changing the whole object).

**Comment by jotsetung** [comment]
I get your point @sgibb and agree. Only thing I wanted to avoid is that people use `data_2 <- applyProcessingQueue(data)`.

**Comment by jotsetung** [comment]
I've implemented the following function:
```r
applyProcessingQueue <- function(x, f = spectraData(x)$fileIdx,
                                 BPPARAM = bpparam()) {
    if (!inherits(x, "MSnExperiment"))
        stop("'x' is supposed to be an 'MSnExperiment' object")
    if (length(x@processingQueue)) {
        isOK <- validateFeatureDataForOnDiskMSnExp(x@spectraData)
        if (length(isOK))
            stop(isOK)
        if (length(f) != nrow(spectraData(x)))
            stop("Length of 'f' has to match 'nrow(spectraData(x))'")
        ## Does not work on BackendMemory!
        cnts <- bplapply(split(x@spectraData, f), function(z, backend, queue) {
            res <- backendWriteSpectra(backend,
                                       .apply_processing_queue(
                                           backendReadSpectra(backend, z),
                                           queue),
                                       z)
            res@modCount[z$fileIdx[1]]
        }, backend = x@backend, queue = x@processingQueue, BPPARAM = BPPARAM)
        x@backend@modCount <- unlist(cnts, use.names = FALSE)
        x@processingQueue <- list()
    }
    validObject(x)
    x
}
```

This does in theory all I want it to do: read the spectra, apply processing queue, write the spectra, increase the `@modCount`. What I didn't realize is that this obviously only works for the `BackendHdf5` as the data is written as it should to the external hdf5 files. For `BackendMemory` it simply doesn't work because the updated `backend` is not returned, but only the `modCount` value. 

So, presently I don't see another way than having to switch within the function depending on the backend (i.e. use a different code for `BackendHdf5`, `BackendMzR` and `BackendMemory`. @sgibb , @lgatto, do you eventually have another idea.

**Comment by jotsetung** [comment]
Or we add a

```r
setGeneric(
    "backendApplyProcessingQueue", 
    function(backend, spectraData, queue, ..., BPPARAM = bpparam())
        standardGeneric("backendApplyProcessingQueue"),
        valueClass = "Backend")
```
The default could be the one for the `BackendMemory`. I hesitant to add yet another method to the backend but at present that seems to be the cleanest approach to me.
