### ISSUE TITLE
Support Spectrum objects without MS level

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#452]
Thinking out loud here:
@stanstrup has a use case with UV data (spectrum like) but that has no MS level.
Also Michele Stravs has some use cases for spectrum data neither MS1 nor MS2. 

Should we either add a new `Spectrum0` object extending `Spectrum`? Or support MS level `0`? Any thoughts @lgatto @sgibb ?

**Comment by lgatto** [comment]
If there's no MS level, it should probably be set to `NA`, but I suspect that one can't instantiate a `Spectrum1` object and setting the MS level to `NA`. 

But what about the simplest solution to just use a `Spectrum1` object and ignore the MS level? Is everything else except the MS level relevant? Are there not other packages for Nuclear magnetic resonance or Raman spectroscopy  that would be a better fit? (See https://cran.r-project.org/web/views/ChemPhys.html)

My point here is that I don't think we should support other types of spectro-technology that measure spectra in `MSnbase`. We could start a new package that uses `MSnbase`'s infrastucture for non MS spectra, if that would be relevant.

**Comment by lgatto** [comment]
@stanstrup - I'm closing this issue for now, but please feel free to re-open it if needed and/or to document your solution here too.

**Comment by lgatto** [comment]
I think that with `Spectra`, we are bypassing this issue altogether. @stanstrup - did you ever get a chance to try it?

**Comment by stanstrup** [comment]
No, I have not dealt with UV/PDA data since before `Spectra`.
