### ISSUE TITLE
Next MSnbase dev call - 20190405

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#454]
We'll have our next call on Friday 5 April 2019 at 8h45. On the agenda so far:

## Current affairs
- `MSnExperiment` and assays.

## Misc news

- Jo to report from the metabolomics R hackathon

## Possible new developments

- Spectra annotation (see [this tweet](https://twitter.com/jotsetung/status/1112991463800008704))
- Spectra without MS level (see #452)
- MS schema (see [Emma's tweet](https://twitter.com/ESchymanski/status/1112987677656276993))

Anyone, and in particular @sgibb and @jorainer, feel free to add agenda items to this issue.

**Comment by jotsetung** [comment]
some notes re spectra annotation from the metaRbolomics hackathon:
https://docs.google.com/document/d/1zTTctc-M4jeqR2TCde27ytOP-YUxmPg53eW9bbphGws/edit#

**Comment by meowcat** [comment]
FYI, now in the works for the active use of the proposed "metadata" slot, by me, @treutler and @michaelwitting: http://github.com/meowcat/MSnio. Potentially some of it could be merged into MSnbase at some point, if there is sufficient interest and agreement.

**Comment by meowcat** [comment]
Also FYI, if the peaksAnnotation slot is adopted, RMassBank will have a big use case and a lot less replicated infrastructure.

**Comment by lgatto** [comment]
Minutes from today's call:

## Report from the metabolomics R hackathon                                                                                                     - It was fun.                                                                                                                                                                                               
- Genuine interest in `MSnbase`, resulting from the influence of MS2 in metabolomics and MS2 spectra databases 
         
## Spectra annotation 
Requestion for 2 slots fields to Spectrum 
- `metadata`: list() with names of fields of schema and values                                                                                                                                                
- `peakAnnotations`: DataFrame() with peak annotations, also needs index to peaks                                                                                                                                                                                            

While the fields are valuable are fit with other needs, there are some serious flaws in the design. More details and further discussion in #456.

## Spectra without MS level (see #452)                                                                                                                                                                                                                                                                                                                                                                               
Not MS data, so leaving this for now.                                                                                                                                                                       
                           
## MS schema 
- Compatibility between different MS2 databases                                                                                                                                                             
- MS schema R package (see [MSnio](https://github.com/meowcat/MSnio)), possibly rename to [msschemer](https://github.com/meowcat/MSnio/issues/3)
- CompoundDB backend is under development, will be a good use case for other spectral libraries, make use of `MSnio`/`msschemer` for re-use across dbs.

## Spectra                                                                                                                                                                                                   

Externalise the new `Spectra` infrastructure in its [own package](https://github.com/lgatto/Spectra) to (1) ease up development and (2) possibly compartmentalise different parts of `MSnbase` for easier re-use by other packages (such as metabolomics spectral libraries).

This followed also from the discussion whether we still need the `Spectum` object? And indeed, that class is there (1) for historical reasons and (2) as a means to have an in memory implementation for spectra. But, in the medium term, data and metadata for MS spectra will be implemented through backends (in `Spectra`), where both spectra data (i.e. intensities and M/Z values) and metadata (all the rest) can be either in memory or on disk.
