### ISSUE TITLE
CHECK report for MSnbase on tokay2

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#459]
I am unable to reproduce the errors shown below

https://master.bioconductor.org/checkResults/3.9/bioc-LATEST/MSnbase/malbec2-checksrc.html

This might be because I don't have R devel, which I can test tomorrow. But may be @sgibb or @jorainer have an idea?

**Comment by jorainer** [comment]
Yes, I'm currently fixing them. They are related to the update in `mzR`: we're now also reading the *isolationWindowTargetMZ*, *isolationWindowLowerOffset* and *isolationWindowUpperOffset* header data. I'll have a fix tomorrow.

**Comment by lgatto** [comment]
@jorainer - just ping me when I can push to Bioc.

**Comment by jorainer** [comment]
Made a pull request fixing the issue and adding some more methods.
