### ISSUE TITLE
Confusing description for fData() column

### ISSUE THREAD

**Issue by adder** [lgatto/MSnbase#46]
Hi

Not sure this the right place to ask but here I go.
In the feature dataframe  (from `fData()`), there are multiple semicolon separated values in the `accession` collumn. The MSnbase manual says that these are all the matches sorted by there rank values. I'm a bit confused by the meaning of this. Are these the highest scoring PSM, seccond highest PSM and so on? Or something else?
If so, how are shared peptides (same peptides occuring in different protein sequences) annotated?
The featuredata I use comes from msgfplus.

Greetz

**Comment by lgatto** [comment]
The relevant paragraph is:

> The column ‘nprot’ contains the number of members in the protein group; the columns ‘accession’ and ‘description’ contain a semicolon separated list of all matches sorted by their ‘rank’ values. The columns ‘npsm.prot’ and ‘npep.prot’ representing the number of PSMs and peptides that were matched to a particular protein group. The column ‘npsm.pep’ indicates how many PSMs were attributed to a peptide (as defined by its sequence ‘pepseq’).

Indeed, in case of multiple matches, all results are reported, ordered by rank and separated by `;`. Shared peptides are not filtered out; each row corresponds to a single PSM; if multiple accessions are listed, this means that that the corresponding peptide sequence occurs in these multiple proteins. 

Could you paste a couple of lines to clarify your example if the above does not answer your question.

**Comment by adder** [comment]
An example. Here are some entries from the accession collumn:  
First I only allowed 1 match in MSGFplus so all the entries below are from shared peptides (I verified this)
```
[1] "sp|P02788ups|TRFL_HUMAN_UPS;sp|P02788|TRFL_HUMAN;sp|TRFL_HUMAN_crap|"           
[2] "sp|P10145ups|IL8_HUMAN_UPS;sp|P10145|IL8_HUMAN;sp|IL8_HUMAN_crap|"                  
[3] "sp|P62937ups|PPIA_HUMAN_UPS;sp|P62988ups|UBIQ_HUMAN_UPS;sp|O76070ups|SYUG_HUMAN_UPS"
```
Then I allow 2 matches in MSGF plus. Next to the accessions I already had above, some new accessions get added from the rank 2 PSMs.
```
[1] "sp|P02788ups|TRFL_HUMAN_UPS;sp|P02788|TRFL_HUMAN;sp|TRFL_HUMAN_crap|;sp|Q9P2D1|CHD7_HUMAN"                
[2] "sp|P10145ups|IL8_HUMAN_UPS;sp|P10145|IL8_HUMAN;sp|IL8_HUMAN_crap|;XXX_sp|P17480|UBF1_HUMAN"               
[3] "sp|P62937ups|PPIA_HUMAN_UPS;sp|P62988ups|UBIQ_HUMAN_UPS;sp|O76070ups|SYUG_HUMAN_UPS;sp|O75526|RMXL2_HUMAN"

```
In the second example there is no way you can tell apart the accessions from proteins with shared peptides and the accesions from rank 1 and rank 2 PSMs. Or am I wrong here?

Greetz

**Comment by adder** [comment]
Maybe an additional question relate to the above. Is there a way to get information about 2nd rank hits, 3d rank hits ...? If I understand correctly, you only get complete information of the 1st rank hits currently.

Greets

**Comment by lgatto** [comment]
> In the second example there is no way you can tell apart the accessions from proteins with shared peptides and the accesions from rank 1 and rank 2 PSMs. Or am I wrong here?

I think you are right. 

> Maybe an additional question relate to the above. Is there a way to get information about 2nd rank hits, 3d rank hits ...? If I understand correctly, you only get complete information of the 1st rank hits currently.

Yes. Do do a more detailed analysis of the PSMs, you can access the identification data directly using the `mzID` or `mzR` packages.

@sgibb, do you have any additional comments on this?

**Comment by sgibb** [comment]
No, we decided to remove/lose these information to reduce the complexity of the identification data and to fit them into the feature data slot.

**Comment by adder** [comment]
Yes, thanks for the confirmation.
I started to play with `mzID` and `mzR` yersterday. They indeed seem to provide what I need. Allthough it's not very clear what the difference is between the two packages. They seem highly redundant in features. mzR seems to be a bit faster and maybe also better maintained.

Greetz

**Comment by lgatto** [comment]
> They seem highly redundant in features. mzR seems to be a bit faster and maybe also better maintained.

`mzR` is **much** faster, especially for big files. If you have 100+ files, `mzID` becomes prohibitive. Both are well maintained. `mzID` is a pure R implementation for mzid parsing while `mzR` makes use of C++ code and works for raw and id files.
