### ISSUE TITLE
XIC plotting errors, "figure margins too large"

### ISSUE THREAD

**Issue by rgov** [lgatto/MSnbase#473]
I'm following the vignette [here](https://bioconductor.org/packages/devel/bioc/vignettes/xcms/inst/doc/xcms.html#4_chromatographic_peak_detection) to generate the figure "Visualization of the raw MS data for one peak."

```r
raw_data %>%
    filterRt(rt = rtr) %>%
    filterMz(mz = mzr) %>%
    plot(type = "XIC")
```

Sometimes this fails with:

```
Error in plot.new() : figure margins too large
Calls: <Anonymous> ... .plotXIC -> plot -> plot -> plot.default -> plot.new
```

There are a lot of [proposed solutions](https://stackoverflow.com/questions/12766166/error-in-plot-new-figure-margins-too-large-in-r) on how to resolve this issue like shrinking the margins (does not work) or resizing the display window (I'm not using the RStudio GUI).

I've noticed that the error mostly occurs when I have "too many" input files, dying somewhere in the 41-50 range.

<details><summary>raw_data summary</summary>

```
## MSn experiment data ("OnDiskMSnExp")
## Object size in memory: 1.15 Mb
## - - - Spectra data - - -
##  MS level(s): 2 1 
##  Number of spectra: 3979 
##  MSn retention times: 4:20 - 4:30 minutes
## - - - Processing information - - -
## Data loaded [Mon Jun 24 16:11:03 2019] 
## Filter: select retention time [260-270] and MS level(s), 1 2 [Mon Jun 24 16:13:14 2019] 
## Filter: trim MZ [245..246] on MS level(s) 1. 
## Filter: trim MZ [245..246] on MS level(s) 2. 
##  MSnbase version: 2.10.0 
## - - - Lazy processing queue content  - - -
##  o  filterMz 
## - - - Meta data  - - -
## phenoData
##   rowNames: 12 13 ... 50 (39 total)
##   varLabels: Sample.Type File.Name ... FileWithExtension (13
##     total)
##   varMetadata: labelDescription
## Loaded from:
##   [1] mtab_webber_cuba_lumos_062018_uplc_12.mzML...  [39] mtab_webber_cuba_lumos_062018_uplc_50.mzML
##   Use 'fileNames(.)' to see all files.
## protocolData: none
## featureData
##   featureNames: F01.S2431 F01.S2432 ... F39.S2518 (3979 total)
##   fvarLabels: fileIdx spIdx ... spectrum (33 total)
##   fvarMetadata: labelDescription
## experimentData: use 'experimentData(object)'
```

</details>

I think the plot should work regardless of how many subfigures need to be drawn, but in the meantime, is there a way to split this up into separate figures so that I can avoid the error?

**Comment by lgatto** [comment]
I can't remember encountering this error outside of RStudio. Do you run this inside a loop? Do you plot to a file or on screen?

**Comment by rgov** [comment]
It's not in a loop. It is in a chunk of an Rmarkdown file, which I'm running from the command line with:

```Rscript -e 'library(rmarkdown); rmarkdown::render("simple_XCMS3.2019.05.08.Rmd", output_format = "html_document", output_file = "/output/simple_XCMS3.2019.05.08.html")'```

**Comment by lgatto** [comment]
And does it display when plotting it interactively?

Could you also confirm that isn't rendered as a margin figure of some sort. If you use the. BiocStyle template, you could use a wide figure.

I would also try to set all the outer margins to 0 with `par(oma = c(0, 0, 0, 0))`. I appreciate this isn't ideal, but might help to understand what's happening.

**Comment by rgov** [comment]
Unfortunately I'm not set up to plot interactively but I haven't heard of this error from the users who developed the Rmarkdown script I'm using. My system is headless.

I tried the outer margins as zero which did not work. However, I tried passing `plot(..., layout = NULL)` which seemed to work around the issue.

**Comment by lgatto** [comment]
Oh, interesting. I didn't even know that it was possible to pass `layout` to `plot` and can't even find any reference to it in the manual pages. How did you find this? Is there any call to `layout` elsewhere in the Rmd?

**Comment by rgov** [comment]
It is an argument to `plotXIC`:

https://github.com/lgatto/MSnbase/blob/70a9ec3f31b4a355af7ab4957dc4d1e0b73d17f2/R/functions-plotting.R#L26

I don't know the magic that makes `plot` call `plotXIC` but it seems to pass the arguments through.

@jorainer any thoughts on why the default `layout` setting would cause this error?

**Comment by lgatto** [comment]
Thank you, that makes sense now: you are using the `plot,MSnExp` method that indeed calls `.plotXIC`. If you set `layout = NULL`, you will be missing parts of the desired output. 

Have you tried setting [`fig.with` and `fig.height`](https://yihui.name/knitr/options/) to something > 7 in the code chunk?

**Comment by rgov** [comment]
Could you attach a screenshot of what it should look like with the default
layout?

**Comment by lgatto** [comment]
Here's what I get with the code from the vignette
![nolayout](https://user-images.githubusercontent.com/384198/60069877-df1ef980-9714-11e9-83f5-7e681af59993.png)

And I was apparently wrong above (or at least the output will depend is displayed on the current device) - setting `layout = NULL` with a new device produces 

![nulllayout](https://user-images.githubusercontent.com/384198/60069992-55bbf700-9715-11e9-85e1-d4aa6e8daeeb.png)

**Comment by rgov** [comment]
Thanks. I do see the same stacked intensity + m/z plot for each file, not just the m/z plot. How are you resetting the device?

I don't understand how the default `layout` argument produces a 4x3 grid of stacked plots.

**Comment by lgatto** [comment]
The `plot, MSnExp` method with `type = "XIC"` calls `plot_XIC`. Then see https://github.com/lgatto/MSnbase/blob/9e2d7032954b28c3d6e913f7ec2fdefcb53d7ed7/R/functions-MSnExp.R#L608

As for resetting, you close the devices with `dev.close` in an interactive session. I Rmd, a new one is created for each plot chunk.

**Comment by jorainer** [comment]
It's a little late but still want to provide some extra info. By default the `plot` with `type = "XIC"` produces these stacked plots. I suggest to not plot too many of them into the same plot/image as it becomes rather impossible to read then - and you'll get the `"figure margins too large"` error anyways.

What I'd suggest is the following: split your data object into pieces of, say 9 files and plot the data into separate images. Something like the code below could work:

```r
fls <- seq_along(fileNames(raw_data))
fls_split <- split(fls, ceiling(seq_along(fls) / 9))

lapply(fls_split, function(z) {
    png(paste0("plot", paste(z, collapse = "-"), ".png"), width = 16, height = 16, 
        units = "cm", res = 200, pointsize = 6)
    raw_data %>%
        filterFile(z) %>%
        filterRt(rt = rtr) %>%
        filterMz(mz = mzr) %>%
        plot(type = "XIC")
    dev.off()
})
```

It's not nice, but it should work

**Comment by rgov** [comment]
@jorainer When I place that in my Rmarkdown file, I get this output:

```
## $`1`
## png 
##   2
```

Or if I switch `png()` to `plot.new()`:

```
## $`1`
## null device 
##           1
```

Is there a way to do this without creating a file such that it will be rendered in Rmarkdown output? Sorry, I'm inexperienced with R.

**Comment by jorainer** [comment]
Firstly, you could assign the output of the `lapply` to some variable - that way you avoid the messages you see there (e.g. `tmp <- lapply( ...`). You could then try to just skip the `png` and `dev.off()` calls - if I'm not mistaken `rmarkdown` will include all created images in the final document.
