### ISSUE TITLE
Add parameter msLevel to pickPeaks

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#478]
For DDA data it might be helpful/better to use different settings for peak picking in MS1 and MSn levels (see http://www.metabolomics-forum.com/index.php?topic=1359.0).

We could add the `msLevel` parameter to perform peak picking specifically on a single MS level, or to use different settings for different MS levels.

**Comment by Tony-II** [comment]
Hello jorainer,

I tried this recent implementation for DDA with MSnbase 2.11.6 and Biocondunctor 3.10, here especially **without** the smoothing (http://www.metabolomics-forum.com/index.php?topic=1359.0)

cent_file <- pickPeaks(x = raw_file, refineMz = "descendPeak", signalPercentage = 33, msLevel. = 1, verbose = TRUE)

I get:

Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘pickPeaks’ for signature ‘"missing"’

the raw file is a DDA-sample.
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 2.67 Mb
- - - Spectra data - - -
 MS level(s): 1 2
 Number of spectra: 7205
 MSn retention times: 0:0 - 21:60 minutes
- - - Processing information - - -
Data loaded [Thu Sep 19 13:36:33 2019]
 MSnbase version: 2.11.6
- - - Meta data  - - -
phenoData
  rowNames:   xyz.mzML
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  xyz.mzML
protocolData: none
featureData
  featureNames: F1.S0001 F1.S0002 ... F1.S7205 (7205 total)
  fvarLabels: fileIdx spIdx ... spectrum (35 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'

**Comment by jorainer** [comment]
Would it be possible to share one of your files for me to try to reproduce? Unfortunately I don't have any profile-mode DDA files available.

**Comment by Tony-II** [comment]
yes, I suggest to provide one DDA-file via a wetranfer download link. Would that be okay?

**Comment by jorainer** [comment]
Whatever works for you is good for me.

**Comment by Tony-II** [comment]
ok, here comes the link for one Demo file. The link is only valid for 7 days.
https://we.tl/t-VBD9NQYcaj

**Comment by jorainer** [comment]
Actually, the error you get is because of `x = raw_file` in your function call above, but the `pickPeaks` method is defined for a parameter `object` (not `x`). Centroiding works actually well:

```r
library(MSnbase)

data <- readMSData("DemoFileDDA.mzML", mode = "onDisk")

cent_file <- pickPeaks(data, refineMz = "descendPeak",
                       signalPercentage = 33, msLevel. = 1, verbose = TRUE)

centroided(cent_file[[1]])
[1] TRUE
centroided(data[[1]])
[1] FALSE
peaksCount(cent_file[[1]])
[1] 4
peaksCount(data[[1]])
[1] 560
```

MS level 2 spectra don't get centroided. The only problem is that currently a `TRUE` is returned by `centroiding` even for (not centroided) MS2 spectra, but I'm working on a fix for that.

**Comment by Tony-II** [comment]
(maybe a misunderstanding? Actually I was doing as you mean)

raw_file <- readMSData("DemoFileDDA.mzML, mode = "onDisk")
cent_file <- pickPeaks(raw_file, refineMz = "descendPeak", signalPercentage = 33, msLevel. = 1, 
verbose = TRUE)

Thanks for the suggested fix. Will it than work with smooth(pickPeaks(..),..) also?

**Comment by jorainer** [comment]
Hm, `smooth` has no `msLevel.` parameter - could you please try?

**Comment by Tony-II** [comment]
can do so, if/once the fix is available ...

**Comment by Tony-II** [comment]
I could try in the meantime with Bioconductor 3.10 and MSnbase 2.11.13. Here the realyy not so bad news is:

pickPeaks(..., msLevel. = 1) throws the error: Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘pickPeaks’ for signature ‘"missing"’

but 

pickPeaks(smooth(..., msLevel. = 1), msLevel. = 1) works pretty fine.

The most important thing, is that a valid DDA (MS1 centroided, MS2 disregarded) mzML file is outputted, so this issue is (nearly) solved. 

What do you think?

**Comment by jorainer** [comment]
You get an error with `pickPeaks(..., msLevel. = 1)`? What did you use as input object (`...`)?

**Comment by Tony-II** [comment]
yes, the input MSnobject is:

 raw_file <- readMSData(files = "DemoData.xzML", pdata = NULL, centroided. = FALSE, smoothed. = FALSE., mode = "onDisk", msLevel. = NULL)

**Comment by jorainer** [comment]
This is strange. With the same version of `MSnbase` (2.11.13) it works for me:

```r
> dta <- readMSData("DemoFileDDA.mzML", mode = "onDisk")
> tmp <- pickPeaks(dta, msLevel. = 1L)
> table(centroided(tmp))

FALSE  TRUE 
 2931  4274 

```

**Comment by Tony-II** [comment]
ok, have you achieved also an output file with writeMSData() on the disk?

**Comment by Tony-II** [comment]
please feel free to close, will reopen if neccessary
