### ISSUE TITLE
not properly reading fdata on some MRM samples

### ISSUE THREAD

**Issue by jmbadia** [lgatto/MSnbase#486]
Hello, 
I am reading a mzML file (attached: [27076.1.zip](https://github.com/lgatto/MSnbase/files/3746607/27076.1.zip)) with MSnBase acquired by MRM from QqQ samples. There are some chromatograms with identical polarity, precursor and product m/z values on it, but with different collision energies

> <chromatogram index="3" id="SRM SIC Q1=380 Q3=263.996 start=2.002616667 end=6.492633333"...>...<...name="collision energy" value="15.0">
> <chromatogram index="4" id="SRM SIC Q1=380 Q3=263.996 start=2.0044 end=6.494416667" ....>...<...name="collision energy" value="7.0">
> <chromatogram index="5" id="SRM SIC Q1=380 Q3=263.996 start=2.005283333 end=6.495316667"...>...<...name="collision energy" value="25.0"> 

I cannot read their feature Data correctly. fData() returns the data from the first chromatogram repeated three times, so I'm not able to know the fData from the others chromatograms (I need their collision energy, specifically)
```
Chroms <- readSRMData("27076.1.mzML")
fData(Chroms)[5:7,c("chromatogramId","precursorCollisionEnergy")]
```
> chromatogramId
> 5 SRM SIC Q1=380 Q3=263.996 start=2.002616667 end=6.492633333
> 6 SRM SIC Q1=380 Q3=263.996 start=2.002616667 end=6.492633333
> 7 SRM SIC Q1=380 Q3=263.996 start=2.002616667 end=6.492633333
>   precursorCollisionEnergy
> 5                       15
> 6                       15
> 7                       15

Thanks in advance

**Comment by jorainer** [comment]
For this I have to dig a little deeper into the respective (C++) code in the `mzR` package. I guess there might be some problem in extracting an unique chromatogram ID from the *id* string in the chromatogram header in the mzML file.

**Comment by jorainer** [comment]
So, `mzR` is reading the files correctly:
```r
> head(mzR::chromatogramHeader(fd))
                                               chromatogramId chromatogramIndex
1                                                         TIC                 1
2 SRM SIC Q1=300 Q3=263.996 start=2.006183333 end=6.496216667                 2
3 SRM SIC Q1=300 Q3=281.996 start=2.006183333 end=6.496216667                 3
4 SRM SIC Q1=380 Q3=263.996 start=2.002616667 end=6.492633333                 4
5      SRM SIC Q1=380 Q3=263.996 start=2.0044 end=6.494416667                 5
6 SRM SIC Q1=380 Q3=263.996 start=2.005283333 end=6.495316667                 6
  polarity precursorIsolationWindowTargetMZ precursorIsolationWindowLowerOffset
1       -1                               NA                                  NA
2        1                              300                                  NA
3        1                              300                                  NA
4        1                              380                                  NA
5        1                              380                                  NA
6        1                              380                                  NA
  precursorIsolationWindowUpperOffset precursorCollisionEnergy
1                                  NA                       NA
2                                  NA                       15
3                                  NA                       15
4                                  NA                       15
5                                  NA                        7
6                                  NA                       25
  productIsolationWindowTargetMZ productIsolationWindowLowerOffset
1                             NA                                NA
2                        263.996                                NA
3                        281.996                                NA
4                        263.996                                NA
5                        263.996                                NA
6                        263.996                                NA
  productIsolationWindowUpperOffset
1                                NA
2                                NA
3                                NA
4                                NA
5                                NA
6                                NA
```

So, the problem is in fact in `MSnbase` function to generate the `Chromatograms` ... I will have a look into that.

**Comment by jmbadia** [comment]
something related with the warnings appearing when it creates the `chromatograms` object?
```
readSRMData("27062.1.mzML")
Warning messages:
1: file 27062.1.mzML contains multiple chromatograms with identical polarity, precursor and product m/z values 
```

**Comment by jorainer** [comment]
Exactly that is the problem. I was generating a *unique* identifier for chromatograms based on the available metadata, but forgot to consider the collision energy. Fixes for this are in https://github.com/lgatto/MSnbase/pull/487 - hope @lgatto finds the time to merge this and push it to bioconductor.

**Comment by jmbadia** [comment]
Thank you very much @jorainer, this definitely solves my problem. 

Just to contribute with something, I raise a rare case that could continue to give error. If someone made different SRMs with identical metadata (Q1,Q3, Pol and CE) but with different time ranges (very unusual I guess), the `chromatogramId` would be the same for all SRMs (with a misleading start/end time). Why don't you use an identifier for each chromatogram in a file instead of using its metadata to group them under a unique identifier?

**Comment by jmbadia** [comment]
Thanks for your detailed answer. No, it seems hardly possible in practice to have such working conditions. And I see your point, identifier is just an id, not a feature source. 
I will install your devel version and give you a proper feedback

**Comment by jorainer** [comment]
Thanks for the feedback! Any suggestions (or even better, contributions :) ) are highly welcome!

**Comment by jmbadia** [comment]
It works perfectly. Same Q1,Q3, polarity + different CE => Different chromatogramId & different characteristics. Thanks so much for your help & consideration, If I have any suggestion (or contribution !!) I'll let you know  
```
chromatogramId
5 SRM SIC Q1=380 Q3=263.996 start=2.002616667 end=6.492633333
6 SRM SIC Q1=380 Q3=263.996 start=2.005283333 end=6.495316667
7      SRM SIC Q1=380 Q3=263.996 start=2.0044 end=6.494416667
  chromatogramIndex polarity precursorIsolationWindowTargetMZ
5                 4        1                              380
6                 6        1                              380
7                 5        1                              380
  precursorIsolationWindowLowerOffset
5                                  NA
6                                  NA
7                                  NA
  precursorIsolationWindowUpperOffset precursorCollisionEnergy
5                                  NA                       15
6                                  NA                       25
7                                  NA                        7
  productIsolationWindowTargetMZ productIsolationWindowLowerOffset
5                        263.996                                NA
6                        263.996                                NA
7                        263.996                                NA
  productIsolationWindowUpperOffset
5                                NA
6                                NA
7                                NA
```
