### ISSUE TITLE
Rename `MSnbase::Spectra-class`

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#488]
To avoid clashes and confusion with `Spectra::Spectra` (from [this issue](https://github.com/rformassspectrometry/RforMassSpectrometry/issues/17))

**Comment by jorainer** [comment]
We have to be careful here to not break existing code (e.g. in `xcms`) -

**Comment by lgatto** [comment]
Closing this one for now. We'll see in the future if this becomes an issue to be addressed.
