### ISSUE TITLE
vsn normalization and glog transformation: mathematical question

### ISSUE THREAD

**Issue by aalvarezf** [lgatto/MSnbase#489]
Hi, 
After perform the vsn method implemented in the _normalise()_ function on psms, the data obtained is glog transformed.
Then,  to _combineFeatures_ via iPQF method, data should be log reversed previously, isn't it? And after medianPolish,  converted to log again. 

If we assume data is log2,  will be the transformation equivalent? (2^ to the glog matrix, and log2(iPQF result) )
If not, how do you perform the operation? Should I recover the hoffset parameter from the vsn2 fit, avoiding the use of normalise(), ... or any other  suggestion? 

Thank you!

**Comment by lgatto** [comment]
Indeed, I think you are correct. I haven't used this set of methods together, so can't suggest how to reverse-transform the `glog` transformation without looking into this.

My first (and quick) suggestion would be to try quantile normalisation, that doesn't transform you data. There will be numeric differences if you quantile-normalise your raw data, or quantile-normalise your log-transformed data and then reverse with 2^. So some care has to be taken here. 

Also, I don't remember if, or why, iPQF requires raw values. So may be there's something to be adjusted on that side.
