### ISSUE TITLE
How to reduce the cost memory using the function chromatogram?

### ISSUE THREAD

**Issue by 13479776** [lgatto/MSnbase#491]
When i use the chromatogram to extract the rt and mz of the peaks from large size samples, the chromatogram will cost lots of memory. Is there any possible to reduce the cost ?

Thanks

Best wishes,
Hemi

**Comment by lgatto** [comment]
No, unfortunately now. There is work as part of the [*RforMassSpectrometry*](https://www.rformassspectrometry.org/) project to improve on this.
