### ISSUE TITLE
featureChromatograms() - argument for sample subset selection

### ISSUE THREAD

**Issue by Tony-II** [lgatto/MSnbase#492]
Hi developers,

so far the function `featureChromatograms()` has an argument features which can be used to select a subset of features, which is very useful. Also the possibility of mz and rt selection via chromatogram is very useful, so in analogy:

```r
featureChromatograms(x, 
    expandRt = 0, aggregationFun = "max", 
    features, include = c("feature_only", "all"),
    filled = FALSE, ...)
```

Is it possible to add an argument "samples" or "files" to select a subset of samples?

Imagine an (`XCMSnExp`) object with several hundreds (or maybe thousands) of samples, where this argument could speed up `featureChromatograms()` tremendously, when passing a representative subset of samples (like some QC, selected biological samples, whatever ...)

The only alternative of using `filterFile()` on (`XCMSnExp`) object unfortunately looses its own features
```r
xdataSelected <- filterFile(object = xdata, file = 1:5, keepAdjustedRtime = TRUE)
# Correspondence results (features) removed.
```

thanks
Tony

**Comment by sgibb** [comment]
@jorainer I am not sure that we could address this in `MSnbase`. `featureChromatograms` is implemented in `xcms` so maybe it should be done there.

**Comment by jorainer** [comment]
@Tony-II , nice idea - and actually the only possible one, since `filterFile` on the object would remove the preprocessing results. But @sgibb is right, this issue should go to `xcms`.

**Comment by jorainer** [comment]
I cannot transfer the issue - could you please create this issue in `xcms` and close it here? Thanks!

**Comment by Tony-II** [comment]
ok
