### ISSUE TITLE
XCMS v.3 / MSnbase --> centroid --> IPO?

### ISSUE THREAD

**Issue by montmasis** [lgatto/MSnbase#493]
Dear lgatto and jorainer,

do you know if there is a way to use  MSnbase to convert (HRMS) mzXML files from profile to centroid, and give them as input to IPO? 

I mean, within the same pipeline as here: https://www.bioconductor.org/packages/release/bioc/vignettes/MSnbase/inst/doc/v03-MSnbase-centroiding.html

Thanks in advance

Best

Stefano

**Comment by lgatto** [comment]
I am not familiar with IPO - could you provide more details.

Have you tried what it described in the vignette, and if yes, what were the issues you encountered?

**Comment by montmasis** [comment]
Hi.
I can use succesfully the latest versions of XCMS v.3 and IPO for
optimization of XCMS parameters.
However, IPO (for high-res CentWave) parameters, works only on centroid
data.
Thus, I normally convert from profile to centroid using MSCovert, and load
the mzXML data into R.
Instead, I was wondering if there is a way to directly use Msnbase for
centroiding in R and then pipe it to IPO. Currently, the object (i.e. the
format of centroid mzXML data) produced using Msnbase doesnt seem to work
with IPO. I think it needs some transformation.

Stefano

**Comment by jorainer** [comment]
Hey Stefano,

for centroiding using `MSnbase` you can have a look [here](https://github.com/jorainer/metabolomics2018), but you would always have to export the centroided data to mzML/mzXML. Also, have you tried to export the files in mzML instead of mzXML format?
