### ISSUE TITLE
waters lockmass correction

### ISSUE THREAD

**Issue by cbroeckl** [lgatto/MSnbase#494]
I haven't seen it, but is there a lockmass correction implemented in MSnBase?  It would make sense for this to be part of the pickPeak family of functions.  It is possible I have missed it, and it is possible it isn't implemented.  Feedback welcomed!

**Comment by lgatto** [comment]
Hi @cbroeckl - no, there isn't in `MSnbase`.

@jorainer, do you have anything implemented directly in `xcms`?

**Comment by jorainer** [comment]
There was something in `xcms`'s old code base which we decided to not adapt/support anymore. I think a reason was that proteowizard allows to handle that properly.

**Comment by stanstrup** [comment]
There are two separate issues:
1) Getting the masses correct, i.e. calibrating using the lockmass. XCMS never did this.
2) Dealing with the "gap" left by the lockmass scan. This is what the stitch function did. The stitch function, though, makes assumptions that are not working in general: https://github.com/sneumann/xcms/issues/177

Discussion of dumping the stitch function: https://github.com/sneumann/xcms/issues/174


ProteoWizard handles (1) these days.
Implementing a working (2) would require a more reliable way to determine where the gaps really are. I think ProteoWizard might mark the scans in some way but so far the working strategy has been to make ProteoWizard remove the lockmass scans with the scanEvent filter.

**Comment by cbroeckl** [comment]
Thanks for the clarification all - I will plan to use PW for lockmass correction.   I have been ignoring the lockmass gap for quite some time now, and will continue to do so!
