### ISSUE TITLE
filterEmptySpectra for OnDiskMSnExp seems to be missing

### ISSUE THREAD

**Issue by antonwnk** [lgatto/MSnbase#495]
Getting some errors when trying to filter the empty spectra in my `OnDiskMSn` prompted me to look at the implementation of the method. I could only find an implementation for `MSnExp` objects however. Not sure why it's listed here https://rdrr.io/bioc/MSnbase/api/ as existing, but I also have no clue how rdrr.io works. 

In a more relaxed period I would take a shot at implementing it myself but for now, I'm just writing this issue.

**Comment by jorainer** [comment]
The `OnDiskMSnExp` extends the `MSnExp` class and thus also inherits all of its methods. Thus, if you call `filterEmptySpectra` on an `OnDiskMSnExp`, the implementation for `MSnExp` is invoked.

Could you please describe your error and provide ideally also the output of your `sessionInfo()`.

**Comment by antonwnk** [comment]
sorry, seems I was misunderstood -  I was underestimating the amount of memory needed to run the empty spectra filtering. it ran successfully giving the process more memory. 
The error was the very generic: 
```
Error in result[[njob]] <- value : 
  attempt to select less than one element in OneIndex
Calls: filterEmptySpectra ... .local -> bplapply -> bplapply -> bploop -> bploop.lapply
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
```
