### ISSUE TITLE
With or without extension

### ISSUE THREAD

**Issue by lecorguille** [lgatto/MSnbase#496]
Hi,
I meet a strange behaviour depending if the input file have or not extension.
Here is my script

```R
library(faahKO)
system.file("cdf", package = "faahKO")
faahKO_package_directory <- system.file("cdf", package = "faahKO")
file.copy(paste(faahKO_package_directory, "KO", "ko15.CDF", sep="/"), "ko15.CDF")
file.copy(paste(faahKO_package_directory, "KO", "ko15.CDF", sep="/"), "ko15")
raw_data_ext <- readMSData(files = "ko15.CDF", mode = "onDisk")
raw_data <- readMSData(files = "ko15", mode = "onDisk")
raw_data_ext@featureData@varMetadata
raw_data@featureData@varMetadata
```

As you can see, in `raw_data_ext@featureData@varMetadata`, there is a slot `polarity` that isn't in the `raw_data@featureData@varMetadata`.

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Catalina 10.15.2

Matrix products: default
BLAS/LAPACK: /Users/lecorguille/miniconda3/env/bioconductor-xcms-3.6.1/lib/libopenblasp-r0.3.7.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] faahKO_1.26.0       xcms_3.6.1          MSnbase_2.10.1
 [4] ProtGenerics_1.16.0 S4Vectors_0.22.0    mzR_2.18.0
 [7] Rcpp_1.0.3          BiocParallel_1.18.0 Biobase_2.44.0
[10] BiocGenerics_0.30.0
```

Maybe it's harmless but it was just to let you know :)

I detected that because in my functional tests, I check the `raw_data` display
```
> raw_data
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 0.46 Mb
- - - Spectra data - - -
 MS level(s): 1
 Number of spectra: 1278
 MSn retention times: 41:41 - 74:60 minutes
- - - Processing information - - -
Data loaded [Tue Feb  4 14:23:00 2020]
 MSnbase version: 2.10.1
- - - Meta data  - - -
phenoData
  rowNames: ko15.CDF
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  ko15.CDF
protocolData: none
featureData
  featureNames: F1.S0001 F1.S0002 ... F1.S1278 (1278 total)
  fvarLabels: fileIdx spIdx ... spectrum (31 total)
  fvarMetadata: labelDescription
```

`fvarLabels: fileIdx spIdx ... spectrum (31 total)` -> 31 if extension, 30 if not.

**Comment by lgatto** [comment]
There is a message that points to the reason why this is:
```r
> raw_data_ext <- readMSData(files = "ko15.CDF", mode = "onDisk")
Polarity can not be extracted from netCDF files, please set manually the polarity with the 'polarity' method.
```
In this case, the function is aware of the extension, knows that it can't get any polarity from netCDF files and then *fixes* this by setting it to `NA` (not available). In the absence of extension, this check and fix can't be applied.

**Comment by lgatto** [comment]
Closing the issue, but feel free to re-open it if necessary.

**Comment by lecorguille** [comment]
It would have been interesting to detect the type of the infile and get the same behaviour.
I don't know if there is any equivalent to `file` in Unix : 
```
$ file test-data/ko15*
test-data/ko15:     NetCDF Data Format data
test-data/ko15.CDF: NetCDF Data Format data
```

But I guess that it's not a real problem.
Thanks for your quick answer.

**Comment by jorainer** [comment]
Actually, in `mzR` we have ways to check the file content and decide based on that what backend to best use. This functions are invoked when you call `openMSfile` without specifying a `backend`. The function then first uses the file ending and if that fails reads the first few lines of the file to guess its content. The respective function is `mzR:::.mzRBackend` which takes a character string (length 1) with the file name and returns a `character` string with the backend name.

Could you please check the result of this function on your files? In your case it should return `"netCDF"`.

**Comment by lecorguille** [comment]
```R
> mzR:::.mzRBackend("ko15.CDF")
[1] "netCDF"
> mzR:::.mzRBackend("ko15")
[1] "netCDF"
```
👍
