### ISSUE TITLE
 "startTimeStamp"  in `MSnExp` objects

### ISSUE THREAD

**Issue by mvinaixa** [lgatto/MSnbase#499]
Dear @jorainer  and @lgatto. On working on `xcms` and downstream metabolomics analysis I notice the need to account for analytical drift. To this end, it is mandatory to know injection order (the order that samples were measured). To avoid relying on an external input (i.e., a .csv  file specifying worklist) , reading "startTimeStamp"  from mzML files as `mzR::openMSfile`  does and `mzR::runInfo()` outputs would be really helpful.  Despite `MSnbase::readMSData` seems to propagate all the information obtained from `mzR`, I have been unable to find the "startTimeStamp" field in the `MSnExp`object. I am wondering whether it would be possible  reading this  "startTimeStamp" using `MSnbase::readMSData` and further access it through `pData`. Is this functionality implemented?.

**Comment by lgatto** [comment]
Here's quick fix
```r
addStartTimeStamp <- function(x) {
    fs <- fileNames(x)    
    res <- character(length(fs))
    for (i in seq_along(res)) {
        ms <- mzR::openMSfile(fs[i])
        res[i] <- runInfo(ms)$startTimeStamp
        close(ms)
    }
    x$startTimeStamp <- res
    x
}
```

And here's how to use it:
```r
> library("MSnbase")
> library("msdata")
> basename(f <- proteomics(full.names = TRUE)[4:5])
[1] "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz"
[2] "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz"         
> x <- readMSData(f, mode = 'onDisk')
> x <- addStartTimeStamp(x)
> pData(x)
                                                                                                                                  sampleNames
TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz
TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz                   TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz
                                                                             startTimeStamp
TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz 2010-06-15T19:01:07Z
TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz          2010-06-15T19:01:07Z
```
I would also suggest to coerce these characters to a `Date` object (using for example the `lubridate` package):
```r
> lubridate::ymd_hms(x$startTimeStamp)
[1] "2010-06-15 19:01:07 UTC" "2010-06-15 19:01:07 UTC"
```

**Comment by mvinaixa** [comment]
Thanks @lgatto. Your help is much appreciated.  A small modification considering your suggestion to coerce these characters using R {base} instead,

`addStartTimeStamp <- function(x) {
  fs <- fileNames(x)    
  res <- character(length(fs))
  for (i in seq_along(res)) {
    ms <- mzR::openMSfile(fs[i])
    res[i] <- runInfo(ms)$startTimeStamp
    close(ms)
  }
  res1 <- as.POSIXct(res,format="%Y-%m-%dT%H:%M:%OS")
  x$startTimeStamp <- res1
  x
}`

**Comment by jorainer** [comment]
Sorry for the late reply - I've been pretty busy. Similar to @lgatto 's solution we have a similar one. You can find it [here](https://github.com/EuracBiomedicalResearch/CompMetaboTools/blob/master/R/ms_file_utils.R). In case, you can install our small package [CompMetaboTools](https://github.com/EuracBiomedicalResearch/CompMetaboTools) with common utility functions we use in our analyses.
