### ISSUE TITLE
filter by filterstring

### ISSUE THREAD

**Issue by tekitch** [lgatto/MSnbase#504]
Hi, 

I'm hoping to make a mzml file in which subsequent boxcar scans are summed into a single spectra - I have this part working ok, but mixed into the file I output is ms scan data which I would like to remove from the mzml (otherwise the scan and boxcar data is lumped together when extracting EICs). I would like to subset spectra in the msnexp object on the 'filterString' which distinguishes the two types of MS data but the there isn't an appropriate filter method that i can see. How can i achieve this?

very much appreciate your attention. 

Regards.

**Comment by tekitch** [comment]
not an issue after all.

**Comment by lgatto** [comment]
See https://github.com/lgatto/msnbase_boxcar
