### ISSUE TITLE
Rename Chromatograms?

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#515]
Along the line of issue #514 , should we also rename the `Chromatograms` class? Maybe into `ChromatogramMatrix` because in fact it is organizing `Chromatogram` objects in a  2-dimentional matrix (and is extending `matrix`).

**Comment by lgatto** [comment]
What about `MChromatograms` - the `M` for matrix of chromatograms and the leading M to stick to the same pattern and in #514.

**Comment by jorainer** [comment]
I'm OK with that. After that I'll have to update also `xcms` - guess there are not many more packages using/extending directly classes from `MSnbase`.

**Comment by lgatto** [comment]
I don't think so. But the good thing is that we are early in the release cycle, so plenty of time to brake dependencies.
