### ISSUE TITLE
intact protein - MW determination

### ISSUE THREAD

**Issue by cbroeckl** [lgatto/MSnbase#520]
Are there any tools within MSnbase that can perform spectrum deconvolution of charge state determination/isotope envelope deconvolution?   
i.e. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5838638/  

Thanks!
Corey

**Comment by lgatto** [comment]
No, and I can't think of any package that can do that. May be @jorainer or @sgibb know of any.

**Comment by cbroeckl** [comment]
@lgatto - thanks, and any suggestions are appreciated.  I can try to hack one together if need be but would rather not if it exists!

**Comment by jorainer** [comment]
We were playing around to identify and match isotopes in a MS spectrum - but never really finished that.

I would love to have an isotope envelope deconvolution algorithm implemented - maybe you could then contribute it to the `MsCoreUtils` (or `MetaboCoreUtils`) packages? That would be great 👍

**Comment by cbroeckl** [comment]
https://github.com/cbroeckl/RAMClustR/blob/master/R/assign.z.R

I had implemented a partial solution in RAMClustR for this.  given a spectrum of centroids, infer charge state of the ions.  Once charge is assigned, calcluate m.   I could see one additional step being of value - aggregation of similar masses (i.e. if we have charge state of 3 and 4, the produce nearly identical m values which we would want to merge).   I can try to work on this and document a function, but would probably need a bit of support on ensuring the function is up-to-standards.

**Comment by cbroeckl** [comment]
An isotope abundance check (averagine) would probably also be useful.

**Comment by sgibb** [comment]
Does this be of any value?

Based on poison distribution:
https://github.com/sgibb/MALDIquant/blob/master/R/monoisotopic-functions.R

Based on averagine:
https://github.com/sgibb/MALDIquantTools/blob/master/R/monoisotopic-methods.R

Both methods would need some work.
18.08.2020 16:43:30 Corey Broeckling <notifications@github.com>:
