### ISSUE TITLE
Clarification on acquisitionNum vs scanIndex

### ISSUE THREAD

**Issue by stanstrup** [lgatto/MSnbase#525]
I couldn't find a description of the difference between acquisitionNum, scanIndex and a few other scan variables.

In my file `spIdx`, `seqNum`, `acquisitionNum` and `spectrum` all appear to be the same and is just the number of the scan in the order recorded disregarding that they are different scanEvents (another matter is that there seems to be no easy way to distinguish scanEvents).

In the code it looks like `scanIndex` equals `spIdx`...

The documentation doesn't make it clearer in my mind...
```r
acquisitionNum integer(1): the index of acquisition of a spectrum during a MS run.
scanIndex integer(1): the index of a spectrum within a (raw) file.
```

Would it be possible to describe the differences more explicitly?

**Comment by sgibb** [comment]
This is indeed quite complicated and convoluted:

- `spectrumID` is a vendor specific field in the mzML file that contains some information about the run/spectrum, e.g.: `controllerType=0 controllerNumber=1 scan=5281 file=2`
- `acquisitionNum` is a more a less sanitize spectrum id generated from the `spectrumID` field by `mzR`: https://github.com/sneumann/mzR/blob/master/src/pwiz/data/msdata/MSData.cpp#L552-L580
- `scanIndex` is the `mzR` generated sequence number of the spectrum in the raw file (which doesn't have to be the same as the `acquisitionNum`)
- `seqNum` seems to be similar to `scanIndex` but an mzML field (@jorainer is that correct?)
- `spIdx`/`spectrum`: no idea

**Comment by lgatto** [comment]
Thanks @sgibb - you beat me to it. 

This is probably something we should add in the documentation, in `MSnbase` and `Spectra`.

**Comment by lgatto** [comment]
I have added a short description of this to the `Spectra` and `MSnExp` man pages.
