### ISSUE TITLE
Coerce Spectra to MSnExp

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#526]
This seem not to be possible with the new Spectra from the Spectra package.

```r
> as(spectras, "MSnExp")

Fejl i as(spectras, "MSnExp") : 
  no method or default for coercing "Spectra" to "MSnExp"
```

_Originally posted by @stanstrup in https://github.com/lgatto/MSnbase/issues/508#issuecomment-701261318_

**Comment by lgatto** [comment]
I think I understand what is happening here. The `Spectra` mentioned in that post isn't the class defined in the new `Spectra` package, but a first iteration thereof in the `MSnbase` package (that eventually triggered the development of new packages and the *R for Mass Spectrometry* initiative. 

That class in `MSnbase` has been renamed `MSpectra` (see this [commit](https://github.com/lgatto/MSnbase/commit/66f3661287cd64d7877a2701cefeabbac985aae9)). Sorry for the confusion.

**Comment by lgatto** [comment]
Closing now, but @stanstrup  feel free to follow up.

**Comment by stanstrup** [comment]
Isn't it still relevant? Or should there be another route to be able to make an mgf from a Spectra object?

**Comment by lgatto** [comment]
- If you mean `Spectra::Spectra`, there's the `export()` method. 
- If you mean `MSnbase::MSpectra`, then the previous code should work by using the new `MSpectra` name. If not, then feel free to follow up, as this would need to be investigated.

Another question is whether we want to be able to coerce `MSnbase::MSnExp` to `Spectra::Spectra`. Possible, but probably not a priority.

**Comment by stanstrup** [comment]
Ah, yes, right.
Then we are back to whether or not that is currently working as intended https://github.com/rformassspectrometry/MsBackendMgf/issues/4

**Comment by lgatto** [comment]
ok, thanks.
