### ISSUE TITLE
Error in addIdentificationData

### ISSUE THREAD

**Issue by InduKhatri** [lgatto/MSnbase#531]
Hello,

I have been trying to merge the quantification data with the feature data frame in a following way: 

**# Loading the peaks generated using Peptide Shaker from raw files**
rawms <- readMgfData("CRC_iTRAQ_24.mgf", centroided=FALSE, verbose = FALSE)
bp <- MulticoreParam(2L)
qntms <- quantify(rawms, reporters = iTRAQ4, method = "trap",  BPPARAM = bp)

**# Loading the identity file generated using Peptide Shaker**
mzidentity <- mzID("CRC_24_mz.mzid")
flatResults <- flatten(mzidentity)

**# Filtering the identity files with assignemnts of corresponding columns**
flatResults1 <- filterIdentificationDataFrame(flatResults,accession = "accession",  rank="rank", decoy ="isdecoy",spectrumID ="spectrumid")

**# Combining the data**
Combined <- addIdentificationData(object=qntms, id = flatResults1 )

**However, I get the following error:**
Error in filterIdentificationDataFrame(id, accession = accession, rank = rank,  : 
  argument "decoy" is missing, with no default

decoy is assigned in filterIdentificationDataFrame and the filtering was perfromed accordingly, but the error is still about decoy.

Please let me know if more information is required.

**Comment by lgatto** [comment]
I believe you need to specify `decoy = "isdecoy"` in `addIdentificationData`.

Note that you can also pass the mzid file name directly to `addIdentificationData()`, rather than loading, flattening and filtering yourself.

**Comment by InduKhatri** [comment]
I tried it in the format you mentioned but I still get an error. Can you suggest what to do in this case?

Combined <- addIdentificationData(object=qntms, id = mzidentity, decoy="isdecoy",accession = "accession", rank="rank",spectrumID ="spectrumid")

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'sapply': non-character argument

**Comment by lgatto** [comment]
Try `addIdentificationData(object = qntms, id = "CRC_24_mz.mzid")`. 

Note that this code will load your data with `mzR` instead of `mzID` - not sure if this will matter for you.

**Comment by InduKhatri** [comment]
"mzR" or "mzID" does not matter. I want to add the fData to the object

Using above suggestion, I still get the following error.

Error in (function (cond)  : 
  error in evaluating the argument 'X' in selecting a method for function 'lapply': bad lexical cast: source type value could not be interpreted as target

**Comment by lgatto** [comment]
Hmmm, no clue what that error means. Could you share the mgf and mzid files?

**Comment by InduKhatri** [comment]
I have put the file on WeTransfer as it was larger than the allowed file size.

https://we.tl/t-RzXdSrwOzn

**Comment by lgatto** [comment]
`mzR` isn't able to parse your mzid file (that what produces the error) - this sometimes happens with some software. So it does matter.


The following seems to work:

```r
addIdentificationData(object = qntms, id =  flatResults1,
                      spectrumID = "spectrumid",
                      decoy = NULL,
                      rank = NULL,
                      desc = "description",
                      pepseq = "pepseq",
                      acc = "accession",
                      fcol = "TITLE",
                      icol = "spectrum title")
```

**Comment by InduKhatri** [comment]
Thank you! This is helpful.
