### ISSUE TITLE
ProcessingStep error when importFrom Msnbase filterMz

### ISSUE THREAD

**Issue by ricardobachertdacunha** [lgatto/MSnbase#543]
I am currently bluiding a package where I use filterMz in a function. In the namespace I use importFrom MSnbase filterFile rtime filterRt filterMSLevel filterMz. After updating to R 4.1 and the newer MSnbase version (2.18.0), an error (below) started to occur. It seems that something is missing when I use importFrom MSnbase filterMz. Loading the entire MSnbase package solves the error but is undesired. Converting from OnDiskMSnExp to MSnExp also solves the error but I believe this is because the ProcessingStep class is not used.

Error in validObject(.Object) : 
  invalid class "ProcessingStep" object: Function 'filterMz' not found.

What would you recommend to load more from MSnbase to have the function filterMz working on OnDiskMSnExp?

**Comment by jorainer** [comment]
Could you please try to update all packages to the most recent Bioconductor version (e.g. with `BiocManager::install(version = "3.13")`? We moved the `ProcessingStep` class from `MSnbase` to `ProtGenerics` so maybe your error is related to that.

Note also that all these functions you list are *methods* not *functions*, so you would need to import them with `importMethodsFrom("MSnbase", "filterMz")` (or `@importMethodsFrom MSnbase filterMz` if you use roxygen).

I would only load the functions, methods and classes you actually need from `MSnbase`.

**Comment by ricardobachertdacunha** [comment]
Hi Johannes,
Thank you for the fast reply and advice on @importMethodsFrom, still learning. I use roxygen.
Checking versions of the packages was my first attempt to fix the error. Is TRUE when I run BiocManager::valid(version = "3.13").

Tried to add the @importClassesFrom PortGenerics ProcessingStep but the problem persists.

Besides converting from OnDiskMSnExp to MSnExp before applying filterMz, another fix is to load the package via devtools::load_all() which attaches the MSnbase package. Attaching the ProtGenerics via library() also solves the error. Loading my package via library() does not solve the error. So, I believe when I use MSnbase::filterMz() inside a function something is missing. Besides the imports listed below, what else should I add to apply MSnbase::filterMz() on OnDiskMSnExp objects? Or should I use a different namespace for filterMz?

importClassesFrom(MSnbase,MSnExp)
importClassesFrom(MSnbase,OnDiskMSnExp)
importClassesFrom(MSnbase,Spectrum)
importClassesFrom(ProtGenerics,ProcessingStep)
importFrom(MSnbase,readMSData)
importMethodsFrom(MSnbase,fileNames)
importMethodsFrom(MSnbase,filterEmptySpectra)
importMethodsFrom(MSnbase,filterFile)
importMethodsFrom(MSnbase,filterMsLevel)
importMethodsFrom(MSnbase,filterMz)
importMethodsFrom(MSnbase,filterRt)
importMethodsFrom(MSnbase,pickPeaks)
importMethodsFrom(MSnbase,rtime)
importMethodsFrom(MSnbase,smooth)
importMethodsFrom(MSnbase,writeMSData)

I appreciate the attention.

**Comment by jorainer** [comment]
Hm, that's strange. I would not import `trimMz` as that is deprecated. Maybe you can try to also import `filterMz` from `ProtGenerics`, but usually that should not be needed. 
Note that if you import a method you should not call it within your function with `MSnbase::filterMz` - simply use `filterMz`.

What exactly is the error message you get?

**Comment by ricardobachertdacunha** [comment]
I added trimMz as a trial but did not work. Also, tried your suggestion but still get the error.

The error is as follows:

Error in validObject(.Object) : 
  invalid class "ProcessingStep" object: Function 'filterMz' not found.

the actual call is filterMz(object = raw, mz = mzr, msLevel. = 1)

, where mzr is a vector of length 2 and raw is as below (I apply filterRt before filterMz, also tried as chain via %>% but the error comes up as well).

MSn experiment data ("OnDiskMSnExp")
Object size in memory: 1.06 Mb      
- - - Spectra data - - -
 MS level(s): 2 1
 Number of spectra: 3051
 MSn retention times: 13:00 - 16:60 minutes
- - - Processing information - - -
Data loaded [Tue Jun 01 13:39:38 2021]
Filter: select retention time [780-1020] and MS level(s), 1 2 [Tue Jun 01 13:39:38 2021]
Removed 0 empty spectra. [Tue Jun 01 13:39:55 2021]
Filter: select file(s) 4, 5. [Tue Jun 01 13:50:36 2021]
Filter: select retention time [780.04099999998-1019.89900000002] and MS level(s), 1 2 [Tue Jun 01 13:50:36 2021] 
 MSnbase version: 2.18.0
- - - Meta data  - - -
phenoData
  rowNames: 4 5
  varLabels: sample_name sample_group
  varMetadata: labelDescription
Loaded from:
  Sample01_cent.mzML,   Sample02_cent.mzML
protocolData: none
featureData
  featureNames: F4.S0001 F4.S0002 ... F5.S1518 (3051 total)
  fvarLabels: fileIdx spIdx ... spectrum (35 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'

**Comment by ricardobachertdacunha** [comment]
After some reading, I actually noticed that the "mz" argument in filterMz might be no longer valid but "mzlim".
Somehow, it was not clear. After changing, the function is recognised and added to the processing cue of the OnDiskMSnExp.
Only importMethodsFrom(MSnbase,filterMz) seems to be necessary.

I really appreciate the support. Interesting how much is there still to learn about best practices.

**Comment by ricardobachertdacunha** [comment]
I got it wrong. It did not work as I mentioned in the earlier comment. The filterMz is not added to the OnDiskMSnExp.
Something I miss in the namespace, because loading either MSnbase and ProtGenerics solves the problem.
The error persists. My solution for now is converting from OnDiskMSnExp to MSnExp but not desired.

**Comment by jorainer** [comment]
What happens if you move either `ProtGenerics` or `MSnbase` from *Imports* in your DESCRIPTION file to *Depends*? That way the respective package will be loaded by default.

**Comment by ricardobachertdacunha** [comment]
Thank you for the reply. That solves the problem as either packages are attached but then I get warnings, such as masking of smooth and others. I would prefer to avoid attaching entirely the packages. Still, I need to run `library(mypkg)` before running the function.

I read further and I found the comment "_Fails with un-exported functions_" on line 53 of the ProcessingStep.R file from `ProtGenerics`. I believe the error originates within the code below the comment but is just a guess. Could it be? I use other filter methods within my function and they work but they are applied directly not added to cue.

**Comment by jorainer** [comment]
You should always load your package before calling functions from it. That the preferred way how functionality from a package is supposed to be used and ensures that the namespace is correctly loaded. IMHO, calls like `somepackage::somefunction` should be avoided as much as possible and only be used when a function is masked by another loaded library. And if it's used you might even need to call `requireNamespace("mypkg")` before.

**Comment by jorainer** [comment]
And keeping `ProtGenerics` in Imports and loading your library with `library(mypkg)` and then calling your function instead of using directly `mypkg::myfun` does not work?

**Comment by ricardobachertdacunha** [comment]
That doesn't work. Works with either `MSnbase` or `ProtGenerics` in _Depends_ and loading the `library(mypkg)` so that either package is attached when the `myfunction` is called. Running `library(mypkg)` with both in Imports does not work. Adding `import(ProtGenerics)` in the NAMESPACE does not solve the problem either, as the same error occurs. Note that other filter methods (i.e., `filterFile`, `filterRt` and `filterMsLevel`) are also in the function and work fine with only `importMethodsFrom()` in the NAMESPACE. However, they do not need ProcessingStep as I understand from the documentation.

**Comment by jorainer** [comment]
This is all very strange - since both `ProcessingStep` and `filterMz` are defined (and exported) in `ProtGenerics`, so importing them into your package should solve the problem. Can you post the output of your `sessionInfo()`?

**Comment by ricardobachertdacunha** [comment]
sure, the session where I get the error

Error in validObject(.Object) : 
  invalid class "ProcessingStep" object: Function 'filterMz' not found.

, while loading `mypkg` via `library()` and having the `MSnbase` and `PortGenerics` in _Imports_, is as in the file:
[session.txt](https://github.com/lgatto/MSnbase/files/6586639/session.txt).

Is there something else I can share?

**Comment by jorainer** [comment]
Hm, could not spot anything strange in the session info. Could you maybe explain briefly your workflow?

I guess you will first read some MS data with `readMSData` from the MSnbase package and then call the function in your package, right? So, the R workflow would look somehow like this:

```r
library(MSnbase)
library(mypkg)
fls <- dir(".", pattern = "mzML")     # defining the files to read in
data <- readMSData(fls, mode = "onDisk")    # read the MS data
data <- myfunction(data)    # call your function
```

And you get the error when you do this? I'm just trying to replicate the error locally to better understand what's happening and how to fix it.

**Comment by ricardobachertdacunha** [comment]
As you wrote works. As long as MSnbase or ProtGenerics is attached. Also works if I add either to _Depends_ and only load `mypkg` via `library()`. The workflow is indeed with `readMSData`, which I add via `importFrom()`. I have `readMSData`, `filterRt` and `filterEmptySpectra` in a function to import the data into the project. It works by loading `library(mypkg)`. Then, I use `myfunction` for inspection by filtering further the _OnDiskMSnExp_ object, focusing on reference _m/z_. Afterwards, I continue with `xcms` for further peak picking and grouping. All was working before the update. For example, the error appears if you just run `MSnbase::filterMz(OnDiskMSnEpxObj, mz = c(200, 250))` without loading `MSnbase` or `ProtGenerics`. I believe a call to `MSnbase::filterMz` does not load required functionality by its own, since it works fine when `MSnbase` or `ProtGenerics` are attached. As you mentioned, the package should be attached before. Strange is that it was working before the update. Since I use `MSnbase` for pre-treatment and inspection of raw data, I was trying to avoid attach the entire package but maybe that is not a good practice. For now I keep the project private, as I am still build the basic structure but could invite you to have a closer look.

**Comment by jorainer** [comment]
With the recent update we moved the `ProcessingStep` function from (I guess it was) `MSnbase` to `ProtGenerics`. So that's maybe why you did not get the error before. As said above, I would almost never use `MSnbase::filterMz` instead of `library(MSnbase)` followed by `filterMz`. AFAIK only by loading the library (or calling `requireNamespace`) the NAMESPACE of the package is loaded which avoids the error you're getting. The `MSnbase::filterMz` call will not load anything on its own, it just directly calls the R function within the package (without loading any potentially additionally required things).

If you don't want to attach the package by default in your package, but you just need it in some few functions I guess you *could* use `requireNamespace("MSnbase")` in that particular functions... But I was wondering - in the example you mention to call `MSnbase::filterMz(OnDiskMSnExpObj, mz = c(200, 250))` - how can you have the `OnDiskMSnExpObj` without loading the `MSnbase` package? You would need to call `readMSData` before to read it and for that you should load `MSnbase` *via* `library`...

**Comment by ricardobachertdacunha** [comment]
As you suggested, I removed the `::` calls in the functions and I use now `importMethosFrom` and `importClassesFrom` for methods and classes, respectively. Something I was not aware of, thank you for that. Regarding the `readMSData`, I use `importFrom(MSnbase, readMSData)` in the namespace of `mypkg` (added via the roxygen heading of the function which I use to get the _OnDiskMsnExpObj_.) It works without loading the `MSnbase` package. That also works for all the filter methods I mentioned earlier but not for `filterMz`. Just tried to add `requireNamespace("MSnbase")` at the start of the function but still get the error with `filterMz`. As you say, loading `ProtGenerics` or `MSnbase` is ideal then as it seems `filterMz` does not load all it needs.
