### ISSUE TITLE
Peakpicking for Chromatogram instances

### ISSUE THREAD

**Issue by SumedhSankhe** [lgatto/MSnbase#544]
Hi Laurent,

I hope you are doing well, I am trying to automate the peak picking process and the data that I have is only chromatograms.
I was able to read the chromatograms in via readSRMData() but I am not sure if MSnbase has peak picking abilities for chromatogram instances. Is there a suggested workflow that might be useful for this use case?

Sumedh

**Comment by jorainer** [comment]
The chromatographic peak detection functionality is available in the `xcms` package. If you have a `MChromatograms` object from `MSnbase` you can simply use the `findChromPeaks` method on that with e.g. a `CentWaveParam` object to select centWave-based peak detection and pass the parameters to that algorithm along.

Maybe first have a look at the [xcms vignette](https://bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms.html) to get a first overview or see directly the help of the method on `MChromatograms` [here](http://sneumann.github.io/xcms/reference/findChromPeaks-Chromatogram-CentWaveParam.html).

**Comment by SumedhSankhe** [comment]
Thanks  Johannes! For pointing me to xcms, I had stumbled across is a few days back will definitely give it a more thorough look !
