### ISSUE TITLE
Dropping file(s) without any spectra

### ISSUE THREAD

**Issue by jmorim** [lgatto/MSnbase#547]
I have SIM data from a flow injection analysis. Trying to load it with
```
data = readMSData(file, mode = 'onDisk')
```
results in the error
```
Dropping 1 file(s) without any spectra: filename.mzML. They/it contain(s) chromatograms and can be read with `readSRMData()`.
```
It's MS1 level data so not sure why it thinks it's appropriate to use readSRMData()

**Comment by jmorim** [comment]
It might be worth mentioning the data is from a Chemstation acquisition software, converted to MassHunter .D files with Agilent's LC-SQ translator, then converted to mzML with proteowizard. I remember analyzing data like this before but it wasn't SIM.

**Comment by lgatto** [comment]
The file [doesn't contain any spectra](https://github.com/lgatto/MSnbase/blob/master/R/readMSData.R#L73-L77), hence the the first part of the message _Dropping 1 file(s) without any spectra: filename.mzML._
In addition, that file [contains chromatographic data](https://github.com/lgatto/MSnbase/blob/master/R/readMSData.R#L78-L79), here the second part _They/it contain(s) chromatograms and can be read with `readSRMData()`._, which you can ignore if you aren't interested in that data.

**Comment by jmorim** [comment]
It should contain spectra though. Not sure why mzr returns .hasspectra as otherwise

**Comment by lgatto** [comment]
What is `length(data)` ?

**Comment by jmorim** [comment]
0, with readMSData it doesn't load the data.

**Comment by lgatto** [comment]
You should have an object with `http://lgatto.github.io/MSnbase/reference/MChromatograms-class.html`. If you expected spectra, it guess that something went wrong during the initial export. If you are sure that spectra should be present in that file, I suggest to look directly into it and confirm that you them in the mzML file (which I very much doubt though).

**Comment by jmorim** [comment]
```bpi = chromatogram(dataSRM[[1]])``` returns ```Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘chromatogram’ for signature ‘"Chromatogram"’``` unless I'm subsetting it wrong.

**Comment by jmorim** [comment]
looking at the msconvert output it says input contains only chromatogram data so the problem must be there like you said

**Comment by lgatto** [comment]
Indeed, there's not such method for `Chromatogram` objects - `dataSRM[[1]]` is already a chromatogram and will be displayed as one. See ` ?MChromatograms` for details on these objects. 

The `chromatogram` method extract chomatograms from raw data containing specta.

**Comment by jmorim** [comment]
Just to update in case someone else searches this: I had to update proteowizard to convert SIM chemstation data with "SIM as spectra" checked off in MSConvert.
