### ISSUE TITLE
error writing mzML file

### ISSUE THREAD

**Issue by ricoderks** [lgatto/MSnbase#553]
Hi,

I'am try to write an mzML file, but get the error:
`Error in h(simpleError(msg, call)) : error in evaluating the argument 'args' in selecting a method for function 'do.call': subscript out of bounds`.

I already get this error when I read an mzML file and ,without doing anything with the `OnDiskMSnExp` object, I write it to a new file.

I'am using R 4.1.1, MSnbase 2.18.0

Cheers, Rico

**Comment by lgatto** [comment]
What type of data is it? How did you generate the mzML file?

**Comment by ricoderks** [comment]
It is LC-MSMS (DDA) data from a Sciex tripleTOF 6600 (qtof). The mzML file was created with msconvert version 3.0.19346.

Cheers, Rico

**Comment by ricoderks** [comment]
In #552 @jorainer suggested the package `Spectra`. I change my code and now also writing the mzML files works. :-) Thanks for the quick help!!

Cheers, Rico
