### ISSUE TITLE
General help quantitation

### ISSUE THREAD

**Issue by Lasseeli** [lgatto/MSnbase#555]
Hi,

I have a general question regarding quantitation of molecules from HPLC-tandemMS using MS1. I know this is not up to a chemist's standard, but as a biologist I just want to see if there is a general trend between the data and other variables i am measuring. I am very grateful for any reply or input, thanks!

Lets say i have 10min retention time and 10 samples (plus the standard, biological blanks and instrument blanks) and i extract the spectrum from each sample at the appropriate retention time based on the standard. lets say this was at exactly 5 min. I subset the mz axis of this spectrum for my molecule of interest, beta-carotene, which from the standard gets a mz of 537.440918.  
My plan was then to calculate the area under the curve from 357.3 to 357.5 (see matrix below). However, all my samples, including my blanks and the standard, all have a considerable peak at 537.49 - I do not know what this is...

Is this just very unfortunate for me? Does anyone have any tips? My interpretation is that I will not be able to quantify beta-carotene because of this unknown molecule which is overshadowing my molecule of interest...

Can I try just selecting the line where mz== 537.4409 and use the intensity value only, rather than area under curve calculation?

example from blank sample:
$KK_20210457_APCI_POS_Blank4.mzML
            mz intensity     rt
36168 537.3499         0 6.6164
36169 537.3600         5 6.6164
36170 537.3701        16 6.6164
36171 537.3802         9 6.6164
36172 537.3904        12 6.6164
36173 537.4005         0 6.6164
36174 537.4106         8 6.6164
36175 537.4207        26 6.6164
36176 537.4308        55 6.6164
36177 537.4409       181 6.6164       <-- this is the mass of my molecule of interest 
36178 537.4510       249 6.6164
36179 537.4612       450 6.6164
36180 537.4713      1031 6.6164
36181 537.4814      1572 6.6164
36182 537.4915      1889 6.6164 <--- something else (also in blanks and unrelated purified standards)
36183 537.5016      1391 6.6164
36184 537.5118       480 6.6164
36185 537.5219       188 6.6164
36186 537.5320       161 6.6164

Thank you so much for having a look at this!
Lasse

**Comment by lgatto** [comment]
It does indeed look like you have a peak of similar m/z co-eluting with beta-carotene. Note that your question is probably not a good fit for here, as I can't see any link with `MSnbase`. 

Closing for now.
