### ISSUE TITLE
Error in `sampleNames<-`(`*tmp*`, value = value)

### ISSUE THREAD

**Issue by Jasper472** [lgatto/MSnbase#559]
When trying to run the code according to [this page in bioconductor](https://www.bioconductor.org/packages/release/data/experiment/vignettes/RforProteomics/inst/doc/RProtVis.html#3_The_MA_plot_example)

I get an error when running the line: 
> > sampleNames(qnt) <- reporterNames(TMT6)
> Error in `sampleNames<-`(`*tmp*`, value = value) : 
>   number of new names (6) should equal number of rows in AnnotatedDataFrame (0)

I was able to read the data directly from the file using the code you provided. I tried running it as version 0.9 as well but it does not seem to help. What could be the problem?

The code I use now is:

> library(MSnbase)
> 
> qnt <- readMzTabData("F063721.dat-mztab.txt", what = "PEP")
> sampleNames(qnt) <- reporterNames(TMT6)

 
on the file:
[F063721.dat-mztab.txt](https://github.com/lgatto/MSnbase/files/7559354/F063721.dat-mztab.txt)

**Comment by Jasper472** [comment]
Here is the output of sessionInfo:
[sessionInfo_output.txt](https://github.com/lgatto/MSnbase/files/7559568/sessionInfo_output.txt)

**Comment by lgatto** [comment]
I didn't realise that mzTab file was from PXD000001. You need to use the following code:

```r
> readMzTabData_v0.9("F063721.dat-mztab.txt", what = "PEP")
MSnSet (storageMode: lockedEnvironment)
assayData: 1528 features, 6 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: sub[1] sub[2] ... sub[6] (6 total)
  varLabels: abundance
  varMetadata: labelDescription
featureData
  featureNames: 1 2 ... 1528 (1528 total)
  fvarLabels: sequence accession ... uri (14 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
Annotation:  
- - - Processing information - - -
mzTab read: Thu Nov 18 10:18:31 2021 
 MSnbase version: 2.20.1 
Warning message:
Version 0.9 is deprecated. Please see '?readMzTabData' and '?MzTab' for details. 
```

**Comment by Jasper472** [comment]
Thank you! It works. I think the warning message from version9 made me wrongly assume that it was not working with that before either.
