### ISSUE TITLE
pickPeaks error in release

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#56]
Using `MSnbase` version `1.16.0` (currently release): 

```r
library("MSnbase")
data(itraqdata)
  > pickPeaks(itraqdata)
  |=                                                                     |   2%Error in noise[, 2L] : incorrect number of dimensions
```
This however works fine with devel. The problem is in the `MSnbase:::pickPeaks_Spectrum`
```r
isAboveNoise <- object@intensity > (SNR * noise[, 2L])
```
which is 
```r
isAboveNoise <- object@intensity > (SNR * noise)
```
in `devel`.

@sgibb is this something that was not backported in release?

**Comment by sgibb** [comment]
Indeed. As I mentioned in #51 the output of the internal function `estimateNoise` has changed to `double` (was `matrix` before). Could you cherry-pick #51 to the release branch. That should fix it.

**Comment by lgatto** [comment]
Thanks! Will do immediately.
