### ISSUE TITLE
MSnbase Installation problems (R R 3.6.3)

### ISSUE THREAD

**Issue by dplazas** [lgatto/MSnbase#563]
Hi, 
I have tried to install MSnbase in my macbook (10.6.11, R 3.6.3) with no success. I installed Bioconductor version 3.10 (BiocManager 1.30.16) but the suggested steps (BiocManager::install("MSnbase")) and (BiocManager::install("lgatto/MSnbase")) don't work. 

first one gave: 

Error: package or namespace load failed for ‘MSnbase’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘MALDIquant’

second one:
ERROR: dependency ‘MALDIquant’ is not available for package ‘MSnbase’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/MSnbase’
Old packages: 'igraph', 'quantreg', 'rgl', 'systemfonts'
Update all/some/none? [a/s/n]: 
n
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/8r/kg9jgds561b3msqcjp3fw6dw0000gn/T//RtmpVeiofU/file7d0fa005bb8/MSnbase_2.21.3.tar.gz’ had non-zero exit status

What can I do?

Thank you in advance!

R 3.6.3

**Comment by lgatto** [comment]
You are missing some packages, that's all. But your R version, and thus the Bioconductor and MSnbase versions that you try to install, are way too old for this issues to be worth resolving, I'm sorry. Please update your R and post again if you still run into an issue.

**Comment by dplazas** [comment]
Hi, thanks for such a quick reply ! 
sadly, I can't go higher with my current Mac (Capitan), R 4.1.2 can't be installed :(

**Comment by lgatto** [comment]
All I can help you with is that you need to install `MALDIquant` with 

```
install.packages("MALDIquant")
```

But I see that you are trying to install the latest version of MSnbase from github - this isn't going to work because it itself relies on new versions of several dependencies. If you run into too many issues, you should install the old version of MSnbase (that fits your version of R) with 

```
BiocManager::install("MSnbase")
```
