### ISSUE TITLE
iPQF method

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#57]
iPQF is available in MSnbase version >= `1.17.8` (github and Bioconductor). There is a dedicated man page at `?iPQF`, that needs some updates. I have added unit tests, based on the code and data provided by @martifis. There are still a few thing to do though:
- [ ] Feature variable names: currently, `"sequence"`, `"accession"`,`"charge"`, `"modifications"`, `"mass_to_charge"`, `"search_engine_score"` are hard-coded. This should be customisable.
- [x] improve iPQF man page
- [x] Update reference to manuscript
- [x] Mention in vignette, or add a section

**Comment by martifis** [comment]
Thank you fo your work. The testing was successful?
- I try to improve the iPQF man page and send you a pull request then?
- What kind of description of iPQF are you expecting in the vignette (how long approximately? is it supposed to be placed somewhere close to the introduction of the combineFeatures function in the vignette?, so rather a short general note about using features/ feature-based-weighting of spectra?

**Comment by lgatto** [comment]
> Thank you fo your work. The testing was successful?

Yes, unit tests are (successfully) run every time the package is checked.

> - I try to improve the iPQF man page and send you a pull request then?

Yes, PR are the easiest, and they trace the origin of the changes, so that you get credit for your code/documentation contributions.

> - What kind of description of iPQF are you expecting in the vignette (how long approximately? is it supposed to be placed somewhere close to the introduction of the combineFeatures function in the vignette?, so rather a short general note about using features/ feature-based-weighting of spectra?

Let's start with the manual page and look into the vignette later. My suggestion would be to have a simple description of the method, i.e what it does and how it does it in the `?iPQF` manual page (rather that in `combineFeatures`). To update that documentation file, you need to update the [`roxygen` header](https://github.com/lgatto/MSnbase/blob/master/R/iPQF.R#L187-L220) in the `iPQF.R` file. You could add one or several new paragraphs after [line 193](https://github.com/lgatto/MSnbase/blob/master/R/iPQF.R#L193) (and before `@title`).

Such a documentation header is then converted into the R documentation file [iPQR.Rd](https://github.com/lgatto/MSnbase/blob/master/man/iPQF.Rd) using `roxygen`. We also use the [`maker`](https://github.com/computationalproteomicsunit/maker) `Makefile` to systematise the building/checking/documentation generation/... In this case 

```
make rd PKG=MSnbase
```
Would call
```
roxygen2::roxygenize("MSnbase", roclets="rd")
```
But don't worry too much about this for now, and don't hesitate to ask for details.

**Comment by lgatto** [comment]
Closing, although first item on TODO is not done (yet).
