### ISSUE TITLE
Change the unit of retention time from minute to second

### ISSUE THREAD

**Issue by MuyaoXi9271** [lgatto/MSnbase#572]
Hi expert,

I got the .mgf file of MS2 data in which the unit of retention time is minute, as shown in the image below
![image](https://user-images.githubusercontent.com/87710342/161220394-6ee576eb-7732-4748-bbdb-0aee344755ac.png)

My question is that is it possible to change the unit of retention time from minute to second and corresponding values by any function. Thanks in advance

Bests,
Muyao

**Comment by lgatto** [comment]
Once you have loaded your data into R (as an `MSnExp`, I assume), you could simply multiply the retention time values by 60 to get seconds.

**Comment by MuyaoXi9271** [comment]
Thanks for your quick answer. 

In the MSnExp object, I could actually add a new variable SECOND under "featureData" section. The actual problem is that the value of Retention time becomes 0:00 in the assayData, as shown below
![image](https://user-images.githubusercontent.com/87710342/161236630-5542b200-a75a-4417-b872-88b80a983c6e.png)

Therefore, even though I add the new variable "SECOND", I can not get the right value of retention time, if I write MSnExp as .mgf file. Do you have some ideas to deal with that? Thanks in advance.

Bests,
Muyao

**Comment by lgatto** [comment]
The retention time accessor will ignore your `SECOND` variable, and there's not way to tell it to do so. As I said, your best option would be to update the default `rtime` data.

**Comment by MuyaoXi9271** [comment]
It could be a stupid question, but I have no idea how to update the default `rtime` for MSnExp object by codes.

**Comment by lgatto** [comment]
This will depend on your `MSnExp` - if it's on-disk, this should do it:
```
fData(x)$retentionTime <- fData(x)$retentionTime * 60
```
In-memory would be rather difficult.

Also, I suggest you look at the [`Spectra`](https://rformassspectrometry.github.io/Spectra/) package, which is a considerable improvement to `MSnbase`.
