### ISSUE TITLE
readMSData function on mzXML file format

### ISSUE THREAD

**Issue by Marievlm** [lgatto/MSnbase#576]
Hello Laurent, 

Thank you for your great package MSnbase. 

Since the last version of MSnbase, I'm not able to load my mzXML file by the function `readMSData`. 
The error after executing the function is : `Error in FUN(X[[i]], ...) : inherits(x, "mzR") is not TRUE`

I have checked if the file exists and it is. It's surprising because it works with mzML format. 
I have tried with different R versions but I still have the same error. 

Thank you in advance for your help.

Marie

**Comment by Marievlm** [comment]
Ok Laurent, I have found the solution !
I have just to specify the entire local URL by `dir()`.

**Comment by Marievlm** [comment]
Ok Laurent, I have found the solution !
I have just to specify the entire local URL by dir().

**Comment by lgatto** [comment]
If you use MSnbase for raw data, I would suggest you take a look at [Spectra](https://rformassspectrometry.github.io/Spectra/). It builds on the principles of MSnbase + 30 years of cumulative development experience from the [R for Mass Spectrometry](https://www.rformassspectrometry.org/) team. See also [here](https://rformassspectrometry.github.io/docs/) for a book/tutorial.
