### ISSUE TITLE
‘MSnbase.so’ not found

### ISSUE THREAD

**Issue by cyan20200410** [lgatto/MSnbase#577]
Hi experts

I have the following error while trying to load MSnbase

> library(MSnbase)
Error: package or namespace load failed for ‘MSnbase’ in library.dynam(lib, package, package.lib):
 shared object ‘MSnbase.so’ not found
In addition: Warning message:
package ‘MSnbase’ was built under R version 4.1.2 

Could anyone help please?

**Comment by lgatto** [comment]
Please re-install the package with `BiocManager::install("MSnbase")`

**Comment by cyan20200410** [comment]
Thank you. It works!
