### ISSUE TITLE
Is it possible to split the chromatograms from multiple files

### ISSUE THREAD

**Issue by MuyaoXi9271** [lgatto/MSnbase#578]
Dear expert,

I tried to plot the extracted chromatograms from multiple files individually. I got the error when I split the chromatograms and I checked the lengths of two inputs are equal, as shown in the image below.

![image](https://user-images.githubusercontent.com/87710342/177329416-1ff0c96f-fc75-4c40-bd6c-aef87adf53a0.png)

Is it doable to split the chromatograms and plot them individually? Many thanks for considering my request.

Bests,
Muyao

**Comment by jorainer** [comment]
A `MChromatograms` is a two-dimensional data structure, thus `split` is not the best way to get the data by file.

If it's just for plotting purposes, I would suggest to instead loop over the columns (i.e. files):

```r
chrs <- chromatogram(aa, aggregationFun = "sum")
for (i in seq_len(ncol(chrs))) {
    plot(chrs[, i])
}
```

**Comment by MuyaoXi9271** [comment]
Yes, it is only for plotting purposes. Thanks😉

**Comment by MuyaoXi9271** [comment]
Hi Johannes,

It only works for extracting multiple columns when I select columns starting with the first column, as shown below. It is really weird.
![image](https://user-images.githubusercontent.com/87710342/177574760-a1a50541-c2d5-4cd2-947a-4dc821af77b8.png)

Thanks for taking care of this issue in advance

Bests,
Muyao

**Comment by jorainer** [comment]
This is strange. I can not reproduce this error:

```r
library(MSnbase)
fls <- c(system.file('cdf/KO/ko15.CDF', package = "faahKO"),
            system.file('cdf/KO/ko16.CDF', package = "faahKO"),
            system.file('cdf/KO/ko18.CDF', package = "faahKO"))
data <- readMSData(fls, mode = "onDisk")
chrs <- chromatogram(data, aggregationFun = "sum")
chrs[, 1:2]
MChromatograms with 1 row and 2 columns
           ko15.CDF       ko16.CDF
     <Chromatogram> <Chromatogram>
[1,]   length: 1278   length: 1278
phenoData with 1 variables
featureData with 1 variables

chrs[, 2:3]
MChromatograms with 1 row and 2 columns
           ko16.CDF       ko18.CDF
     <Chromatogram> <Chromatogram>
[1,]   length: 1278   length: 1278
phenoData with 1 variables
featureData with 1 variables
```

I've also tried with a *phenodata* provided:

```r
df <- data.frame(sample_id = 1:3, other_col = c("a", "b", "c"))
data <- readMSData(fls, pdata = as(df, "AnnotatedDataFrame"), mode = "onDisk")
chrs <- chromatogram(data, aggregationFun = "sum")
chrs[, 1:2]
MChromatograms with 1 row and 2 columns
                  1              2
     <Chromatogram> <Chromatogram>
[1,]   length: 1278   length: 1278
phenoData with 2 variables
featureData with 1 variables
chrs[, 2:3]
MChromatograms with 1 row and 2 columns
                  2              3
     <Chromatogram> <Chromatogram>
[1,]   length: 1278   length: 1278
phenoData with 2 variables
featureData with 1 variables
```

So, I guess this has to do with your specific data set or object? Can you provide some more information like how exactly you imported the data and also the output of your `sessionInfo()`?

**Comment by jorainer** [comment]
Can you maybe drop the `pdata = new("NAnnotatedDataFrame", .),` line in `readMSData` and try again?

**Comment by MuyaoXi9271** [comment]
Hi Johannes,

As you suggested, it works. But only the filenames are included when dropping `pdata = new("NAnnotatedDataFrame", .)`


Bests,
Muyao

**Comment by MuyaoXi9271** [comment]
Hi Johannes,

I found the problem is from the phenodata. The extracted phenodata always starts from the first file, as shown below

![image](https://user-images.githubusercontent.com/87710342/177743073-93cf0d91-1fc2-4942-8c66-e76f9475495b.png)


Bests,
Muyao
