### ISSUE TITLE
Problem with "too large halfWindowSize" with writeMSdata after centroiding MSe data

### ISSUE THREAD

**Issue by cwegler** [lgatto/MSnbase#587]
Hi,
I have MSe data acquired in profile (continuum) mode with a Waters Xevo G2 XS QToF instrument, converted to mzML with MSConvert from proteowizard, and imported using the readMSData(x, centroided = FALSE) function.

The profile data contains many data points:

![image](https://user-images.githubusercontent.com/124032415/215706185-6d7d284e-9b84-46c3-88b4-b2304b1244ec.png)
![image](https://user-images.githubusercontent.com/124032415/215706189-3db4e7df-9fae-4006-a184-683fa37791d8.png)

I then centroid the data with the pickPeaks function, after smooth and mz-refinement (see code below). My peaks are about 5-10 s wide, and I set the halfWindowSize to 2. When trying to save a mzML file (I need this file for other downstream analyses) with writeMSdata I get the error that the halfWindowSize is too big.
![image](https://user-images.githubusercontent.com/124032415/215702784-96297662-8a95-481e-aca1-c6709e137bcb.png)

However, It seems like the peak picking does work with those settings when I look at a XIC:

![image](https://user-images.githubusercontent.com/124032415/215705861-d6330ed9-4e19-4185-97fc-eb489bd2716b.png)
![image](https://user-images.githubusercontent.com/124032415/215705874-87653d81-2cd7-400a-b1cd-a9927fe0d2a8.png)

When plotting, I get the warnings:

![image](https://user-images.githubusercontent.com/124032415/215706493-f3eb00de-79d3-4dcf-81de-8521aa2abeed.png)

When I reduce the halfWindowSize to 1, I still get similar results in the XIC:

![image](https://user-images.githubusercontent.com/124032415/215706930-f147da68-c9b5-4242-9ca9-ba8e166b743c.png)

but I get another error when trying to save the file

![image](https://user-images.githubusercontent.com/124032415/215707169-08fad5f1-1770-42c2-8e95-2bb74b7a4022.png)

I have also tried to remove the smooth() function, but then I got another error:

![image](https://user-images.githubusercontent.com/124032415/215707342-19fea03c-0d53-4df3-8a6b-e826571cd1fe.png)

Does anyone have any ideas of how this can be fixed?

Cheers!

**Comment by jorainer** [comment]
Hm, maybe @sgibb has an idea?

**Comment by cwegler** [comment]
It seems like the problem was in that some of the spectra contained only zeros, the problem was resolved by adding the following line before the centroiding with smooth() and pickPeaks()

data_profile@featureData <- featureData(data_profile)[fData(data_profile)$totIonCurrent != 0,]
