### ISSUE TITLE
problem with loading mzml with a single MS1 spectrum

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/MSnbase#59]
I have a quite unusual application for MSnbase. To assess peptide purity I perform DI on orbitrap then I pull all MS1 spectra, perform charge state deconvolution (XTRACT algorithm) and export them as a single spectrum so I get mzML with only a single MS1 spectrum. When I try to plot it in MSnbase I get the following problem: 

> rawdata <- readMSData("C1_01.mzML", msLevel = 1, verbose = FALSE)
>     MSSpectrum <- rawdata[[1]]
>     MSSpectrum
Object of class "Spectrum1"
 Retention time: 5:0 
 MSn level: 1 
 Total ion count: 19567 
 Polarity:  
>     plot (MSSpectrum)
Error in (function (el, elname)  : 
  Element title must be a element_text object.

I understand smth is missing in this spectrum, but I do not know what. Perhaps you can have a look (sent the file by email)?

**Comment by lgatto** [comment]
Should be fixed in the latest version on github. To update

```r
library("BiocInstaller")
biocLite("lgatto/MSnbase")
```
