### ISSUE TITLE
Unable to import MRM mzML files

### ISSUE THREAD

**Issue by yeesherman** [lgatto/MSnbase#592]
Hi,

I recently started attempting to use R to analyze some MRM data acquired from a QQQ instrument. 

The data is generated from a PerkinElmer QSight 420, exported into mzML format. On attempting to import the data, i get the error below:
> readSRMData("PCC_Test.mzML")
Error in readSRMData("PCC_Test.mzML") : 
  file(s) '~mzml test\PCC_Test.mzML' do not contain SRM chromatogram data

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252    LC_MONETARY=English_Singapore.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Singapore.1252    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MSnbase_2.24.2      ProtGenerics_1.30.0 S4Vectors_0.36.2    mzR_2.32.0          Rcpp_1.0.10        
[6] Biobase_2.58.0      BiocGenerics_0.44.0

loaded via a namespace (and not attached):
 [1] plyr_1.8.8            compiler_4.2.1        pillar_1.9.0          BiocManager_1.30.20   iterators_1.0.14     
 [6] zlibbioc_1.44.0       tools_4.2.1           digest_0.6.31         MALDIquant_1.22.1     ncdf4_1.21           
[11] preprocessCore_1.60.2 lifecycle_1.0.3       tibble_3.2.1          gtable_0.3.3          lattice_0.21-8       
[16] clue_0.3-64           pkgconfig_2.0.3       rlang_1.1.1           foreach_1.5.2         DBI_1.1.3            
[21] cli_3.6.1             rstudioapi_0.14       parallel_4.2.1        dplyr_1.1.2           cluster_2.1.4        
[26] IRanges_2.32.0        generics_0.1.3        vctrs_0.6.2           MsCoreUtils_1.10.0    tidyselect_1.2.0     
[31] grid_4.2.1            glue_1.6.2            impute_1.72.3         R6_2.5.1              fansi_1.0.4          
[36] XML_3.99-0.14         BiocParallel_1.32.6   limma_3.54.2          ggplot2_3.4.2         magrittr_2.0.3       
[41] pcaMethods_1.90.0     scales_1.2.1          codetools_0.2-19      MASS_7.3-60           mzID_1.36.0          
[46] colorspace_2.1-0      utf8_1.2.3            affy_1.76.0           doParallel_1.0.17     munsell_0.5.0        
[51] vsn_3.66.0            affyio_1.68.0

**Comment by lgatto** [comment]
I have no experience with PE and how they export to mzML. I would suggest to open the mzML file and manually verify if it contains chromatographic data.

**Comment by yeesherman** [comment]
Hi Laurent,

Thanks for the quick reply. What is the best way to open the mzML file? I am not entirely familiar with the file format.

**Comment by lgatto** [comment]
It's an XML file, so a XML viewer/editor or text editor will do.  You should be looking for a Chromatogram tag (or something along these lines) in the file.

**Comment by yeesherman** [comment]
This is what I see in the file: 

<fileDescription>
    <fileContent>
      <cvParam cvRef="MS" accession="MS:1001473" name="selected reaction monitoring chromatogram" />
    </fileContent>
  </fileDescription>

<run id="Direct MS-220617 PCC_noG_08min_04ul (1)" defaultInstrumentConfigurationRef="QSight420">
    <spectrumList count="11385" defaultDataProcessingRef="PerkinElmer 3Q Data Converter">
      <spectrum id="Sample=1 Cycle=1 Experiment=1" index="0" defaultArrayLength="4">
        <cvParam cvRef="MS" accession="MS:1000796" value="Sample=1 Cycle=1 Experiment=1" name="spectrum title" />
        <cvParam cvRef="MS" accession="MS:1000511" value="1" name="ms level" />
        <cvParam cvRef="MS" accession="MS:1000129" name="negative scan" />
        <cvParam cvRef="MS" accession="MS:1000528" value="271.2" name="lowest observed m/z" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
        <cvParam cvRef="MS" accession="MS:1000527" value="274.2" name="highest observed m/z" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
        <cvParam cvRef="MS" accession="MS:1000285" value="440" name="total ion current" unitAccession="MS:1000131" unitName="number of detector counts" unitCvRef="MS" />
        <cvParam cvRef="MS" accession="MS:1000505" value="360" name="base peak intensity" unitAccession="MS:1000131" unitName="number of detector counts" unitCvRef="MS" />
        <cvParam cvRef="MS" accession="MS:1000504" value="271.2" name="base peak m/z" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
        <cvParam cvRef="MS" accession="MS:1000583" name="MRM spectrum" />
        <scanList count="1">
          <cvParam cvRef="MS" accession="MS:1000795" value="" name="no combination" />
          <scan>
            <cvParam cvRef="MS" accession="MS:1000016" value="0" name="scan start time" unitAccession="UO:0000031" unitName="minute" unitCvRef="UO" />
            <scanWindowList count="1">
              <scanWindow>
                <cvParam cvRef="MS" accession="MS:1000501" value="271.2" name="scan window lower limit" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
                <cvParam cvRef="MS" accession="MS:1000500" value="274.2" name="scan window upper limit" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
              </scanWindow>
            </scanWindowList>
          </scan>
        </scanList>
        <binaryDataArrayList count="2">
          <binaryDataArray encodedLength="44">
            <cvParam cvRef="MS" accession="MS:1000514" name="m/z array" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
            <cvParam cvRef="MS" accession="MS:1000576" name="no compression" />
            <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" />
            <binary>MzMzMzPzcEAzMzMzM/NwQDMzMzMzI3FAMzMzMzMjcUA=</binary>
          </binaryDataArray>
          <binaryDataArray encodedLength="44">
            <cvParam cvRef="MS" accession="MS:1000515" name="intensity array" unitAccession="MS:1000131" unitName="number of detector counts" unitCvRef="MS" />
            <cvParam cvRef="MS" accession="MS:1000576" name="no compression" />
            <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" />
            <binary>AAAAAACAdkAAAAAAAABUQAAAAAAAAAAAAAAAAAAAAAA=</binary>
          </binaryDataArray>
        </binaryDataArrayList>
      </spectrum>

It appears that the data has been extracted, but it might not be in the correct format?

**Comment by lgatto** [comment]
Indeed, it seems to be there. You could try with the latest version of mzR (version 2.34.0), as I believe there has been an update in the pwiz code that is shipped. @jorainer , any experience with these data?

**Comment by jorainer** [comment]
from the content above it seems to me the data is stored as spectrum and not chromatogram entries (i.e. you have 11385 entries in the `spectrumList` and the data for each entry is a m/z array and an intensity array. This type of data can be read with the `readMSData` function instead. If you want to use the `readSRMData` you need to store (convert?) the data as a mzML with a chromatogramList instead of a spectrumList.

**Comment by yeesherman** [comment]
When i tried to use the <readMSData> function, this is the output I get:

Error in readInMemMSData(files, pdata = pdata, msLevel. = msLevel., verbose = verbose,  : 
  No MS(n>1) spectra in fileC:\Users\Virtuedx\Desktop\Data Analysis\mzml test\PCC_Test.mzML

**Comment by yeesherman** [comment]
I am able to load the data into R using 

> sp <- Spectra("PCC_Test.mzML")
sp
MSn data (Spectra) with 11385 spectra in a MsBackendMzR backend:
        msLevel     rtime scanIndex
      <integer> <numeric> <integer>
1             1     0.000         1
2             1     0.222         2
3             1     0.656         3
4             1     0.869         4
5             1     1.091         5
...         ...       ...       ...
11381         1    46.286     11381
11382         1    46.720     11382
11383         1    46.933     11383
11384         1    47.155     11384
11385         1    47.589     11385
 ... 33 more variables/columns.

To follow up on this, how should I go about trying to analyze and quantify the peak?

**Comment by lgatto** [comment]
1. The `readMSData()` function failed because it looks (by default, based on your arguments) for MS levels > 1. You could parametrise it to return the MS 1 spectra.
2. I would suggest to use `Spectra()`, which is the new and improved infrastructure of MS data.

I'm closing this issue, given that the original issue has been solved.
