### ISSUE TITLE
Error in register(DoparParam(), default = TRUE) :    could not find function "register"

### ISSUE THREAD

**Issue by azUserGit** [lgatto/MSnbase#599]
I started working on MSnbase and getting this error after a lot of trials . Kindly let me know how to fix it

**Comment by lgatto** [comment]
I can't help you if you do not provide a minimum or information, such as the code you ran, and your session information. Also, be do format your issue properly.

**Comment by azUserGit** [comment]
files <- dir(system.file(package = "MSnbase", dir = "extdata"),
            full.names = TRUE, pattern = "my.mgf")

class(files)
print(class(files))
print(files)
rawdata <- readMgfData(files, verbose = FALSE)


While running the code I am getting this error 


"Error in readMgfData(files, verbose = FALSE) : Ion headers identical."

**Comment by lgatto** [comment]
As the error message says, there are two ion identical ion headers. 

I would advise you look into the [Spectra](https://rformassspectrometry.github.io/Spectra/) and [MsBackendMgf](https://rformassspectrometry.github.io/MsBackendMgf/) packages of you have mgf data. They are the new packages the team is working on.

**Comment by azUserGit** [comment]
Ok thanks for the clarification. I'll check it and let you know IA
