### ISSUE TITLE
Unable to open mzdata.xml 

### ISSUE THREAD

**Issue by XiaoleiOceano** [lgatto/MSnbase#601]
Hi MSnbase community;

I am recently learning to use R based pacakges for my un-targeted workflow. We are using agilent qtof and I use agilent qual to export mzdata.xml format LC-MS data. 
However, I was not able to use xcms/mzR/MSnbase to open the files, which is really bizarre. And same messages returned every time saying it "Could not determine file type". I was able to open the same files on python with pyopenms so I think the file should be ok.
Any suggestions? And pleease let me know if any other information would be helpful to debug. Thank you!

**Comment by lgatto** [comment]
- Support for mzData was dropped some time ago. I would recommend to convert/export your data to mzML.
- Please use the [R for Mass Spectrometry](https://rformassspectrometry.github.io/book/) infrastructure, that supersedes MSnbase.
