### ISSUE TITLE
mode = "inMemory" fails when msLevel. = 1:2

### ISSUE THREAD

**Issue by stanstrup** [lgatto/MSnbase#604]
Currently you cannot read in both ms1 and ms2 with mode = "inMemory":

It is the following check that fails because msLevel. is expected to be of length 1 in this check.
`Error in if (msLevel. == 1) cache. <- 0 : the condition has length > 1`

Not sure what the intention is here with the cache.

**Comment by lgatto** [comment]
If memory serves well, yes, I think this is expected. The [benchmarking vignette](http://lgatto.github.io/MSnbase/articles/v04-benchmarking.html) says:

> On-disk support multiple MS levels in one object, while in-memory only supports a single level. While support for multiple MS levels could be added to the in-memory back-end, memory constrains make this pretty-much useless and will most likely never happen.

Beyond this limitation. I would suggest to check the [Spectra](https://rformassspectrometry.github.io/Spectra/) package/class, that supersedes MSnbase's [OnDisk]MSnExp and offers more variety in backends.

**Comment by lgatto** [comment]
There are examples [here](https://rformassspectrometry.github.io/book/sec-raw.html#backends) and [here](https://rformassspectrometry.github.io/book/sec-id.html#summary-exercise), under the question 

> Extract the PSMs that have been matched to peptides from protein O43175 and compare and cluster the scans. Hint: once you have created the smaller Spectra object with the scans of interest, switch to an in-memory backend to seed up the calculations.

that illustrates changing Spectra backends.

**Comment by stanstrup** [comment]
OK. But a better warning might be good...
I know the new Spectra package well, but dealing with some  old code. I re-wrote it now to use Spectra instead.
