### ISSUE TITLE
Error in addIdentificationData

### ISSUE THREAD

**Issue by CSi-Ti** [lgatto/MSnbase#606]
Hi MSnbase team,

Many thanks for creating this useful package. I encounter a problem recently when I was trying to add identification data to my raw ms experiments. Please see the error message below:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function '%in%': argument "icol" is missing, with no default

I look forward to your reply and your help will be highly appreciated!

Best,
Ruimin

**Comment by lgatto** [comment]
The error message says that it `icol` argument is missing: see the [manual page](http://lgatto.github.io/MSnbase/reference/addIdentificationData-methods.html) for details as to what `icol` is. It can't be missing.

**Comment by CSi-Ti** [comment]
Apologies, I copied the wrong error message, should be the one below:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'sapply': non-character argument

**Comment by lgatto** [comment]
I cannot help with details, a reproducible example and a session info.
