### ISSUE TITLE
Not able to install MSnbase

### ISSUE THREAD

**Issue by bharathbhushandamodaran** [lgatto/MSnbase#62]
I tried to install MSnbase package in R (linux), but I couldn't do it. I did as follows

source("http://bioconductor.org/biocLite.R")
biocLite()

Then
biocLite("MSnbase")

I got following message at the end.

Warning messages:
1: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘mzR’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘MSnbase’ had non-zero exit status

When I tried 
library(MSnbase)

The library MSnbase package was not found.

Please help me to install this package ( I searched in google, but I couldn't find the solution).

Thanks

**Comment by sgibb** [comment]
Could you please provide the complete output of:
```r
source("http://bioconductor.org/biocLite.R")
biocLite("mzR")
```
and
```r
sessionInfo()
```

**Comment by bharathbhushandamodaran** [comment]
Thanks for your message. Please see the following

biocLite("mzR")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.19.14), R 3.2.2 (2015-08-14).
Installing package(s) ‘mzR’
essai de l'URL 'https://bioconductor.org/packages/3.2/bioc/src/contrib/mzR_2.3.2.tar.gz'
Content type 'application/x-gzip' length 14656653 bytes (14.0 MB)
==================================================
downloaded 14.0 MB

* installing *source* package ‘mzR’ ...
** libs
rm -f cramp.o ramp_base64.o ramp.o RcppRamp.o RcppRampModule.o rnetCDF.o RcppPwiz.o RcppPwizModule.o RcppIdent.o RcppIdentModule.o ./boost/system/src/error_code.o ./boost/regex/src/posix_api.o ./boost/regex/src/fileiter.o ./boost/regex/src/regex_raw_buffer.o ./boost/regex/src/cregex.o ./boost/regex/src/regex_debug.o ./boost/regex/src/instances.o ./boost/regex/src/icu.o ./boost/regex/src/usinstances.o ./boost/regex/src/regex.o ./boost/regex/src/wide_posix_api.o ./boost/regex/src/regex_traits_defaults.o ./boost/regex/src/winstances.o ./boost/regex/src/wc_regex_traits.o ./boost/regex/src/c_regex_traits.o ./boost/regex/src/cpp_regex_traits.o ./boost/regex/src/static_mutex.o ./boost/regex/src/w32_regex_traits.o ./boost/iostreams/src/zlib.o ./boost/iostreams/src/file_descriptor.o ./boost/thread/src/pthread/once.o ./boost/thread/src/pthread/thread.o ./boost/filesystem/src/operations.o ./boost/filesystem/src/path.o ./boost/filesystem/src/utf8_codecvt_facet.o ./pwiz/data/msdata/Version.o ./pwiz/data/common/MemoryIndex.o ./pwiz/data/common/CVTranslator.o ./pwiz/data/common/cv.o ./pwiz/data/common/ParamTypes.o ./pwiz/data/common/BinaryIndexStream.o ./pwiz/data/common/diff_std.o ./pwiz/data/common/Unimod.o ./pwiz/data/msdata/SpectrumList_MGF.o ./pwiz/data/msdata/DefaultReaderList.o ./pwiz/data/msdata/ChromatogramList_mzML.o ./pwiz/data/msdata/examples.o ./pwiz/data/msdata/Serializer_mzML.o ./pwiz/data/msdata/Serializer_MSn.o ./pwiz/data/msdata/Reader.o ./pwiz/data/msdata/Serializer_MGF.o ./pwiz/data/msdata/Serializer_mzXML.o ./pwiz/data/msdata/SpectrumList_mzML.o ./pwiz/data/msdata/SpectrumList_MSn.o ./pwiz/data/msdata/BinaryDataEncoder.o ./pwiz/data/msdata/Diff.o ./pwiz/data/msdata/MSData.o ./pwiz/data/msdata/References.o ./pwiz/data/msdata/SpectrumList_mzXML.o ./pwiz/data/msdata/IO.o ./pwiz/data/msdata/SpectrumList_BTDX.o ./pwiz/data/msdata/SpectrumInfo.o ./pwiz/data/msdata/RAMPAdapter.o ./pwiz/data/msdata/LegacyAdapter.o ./pwiz/data/msdata/SpectrumIterator.o ./pwiz/data/msdata/MSDataFile.o ./pwiz/data/msdata/MSNumpress.o ./pwiz/data/msdata/SpectrumListCache.o ./pwiz/data/msdata/Index_mzML.o ./pwiz/data/identdata/IdentDataFile.o ./pwiz/data/identdata/IdentData.o ./pwiz/data/identdata/DefaultReaderList.o ./pwiz/data/identdata/Reader.o ./pwiz/data/identdata/Serializer_protXML.o ./pwiz/data/identdata/Serializer_pepXML.o ./pwiz/data/identdata/Serializer_mzid.o ./pwiz/data/identdata/IO.o ./pwiz/data/identdata/Version.o ./pwiz/data/identdata/References.o ./pwiz/data/proteome/Modification.o ./pwiz/data/proteome/Digestion.o ./pwiz/data/proteome/Peptide.o ./pwiz/data/proteome/AminoAcid.o ./pwiz/utility/minimxml/XMLWriter.o ./pwiz/utility/minimxml/SAXParser.o ./pwiz/utility/chemistry/Chemistry.o ./pwiz/utility/chemistry/ChemistryData.o ./pwiz/utility/chemistry/MZTolerance.o ./pwiz/utility/misc/IntegerSet.o ./pwiz/utility/misc/Base64.o ./pwiz/utility/misc/IterationListener.o ./pwiz/utility/misc/MSIHandler.o ./pwiz/utility/misc/Filesystem.o ./pwiz/utility/misc/TabReader.o ./pwiz/utility/misc/random_access_compressed_ifstream.o ./pwiz/utility/misc/SHA1.o ./pwiz/utility/misc/SHA1Calculator.o ./pwiz/utility/misc/sha1calc.o ./random_access_gzFile.o rampR.o R_init_mzR.o
find . -name \*~ -exec rm {} \;   ## from cleanup
find . -name \*.o -exec rm {} \;  ## from cleanup
find . -name "#*#" -exec rm {} \; ## from cleanup
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I. -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags || /bin/true`  -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c cramp.cpp -o cramp.o
/bin/bash: nc-config : commande introuvable
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I. -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags || /bin/true`  -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c ramp_base64.cpp -o ramp_base64.o
/bin/bash: nc-config : commande introuvable
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I. -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags || /bin/true`  -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c ramp.cpp -o ramp.o
/bin/bash: nc-config : commande introuvable
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I. -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags || /bin/true`  -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppRamp.cpp -o RcppRamp.o
/bin/bash: nc-config : commande introuvable
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I. -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags || /bin/true`  -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppRampModule.cpp -o RcppRampModule.o
/bin/bash: nc-config : commande introuvable
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I. -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags || /bin/true`  -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c rnetCDF.c -o rnetCDF.o
/bin/bash: nc-config : commande introuvable
In file included from rnetCDF.c:2:0:
rnetCDF.h:1:20: fatal error: netcdf.h: Aucun fichier ou dossier de ce type
 #include <netcdf.h>
                    ^
compilation terminated.
/usr/lib/R/etc/Makeconf:134: recipe for target 'rnetCDF.o' failed
make: *** [rnetCDF.o] Error 1
ERROR: compilation failed for package ‘mzR’
* removing ‘/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/mzR’

The downloaded source packages are in
        ‘/tmp/Rtmpoe9gSB/downloaded_packages’
Old packages: 'abind', 'caTools', 'clue', 'deSolve', 'gdata', 'gplots',
  'gtools', 'kernlab', 'mvtnorm', 'permute', 'psych', 'quantmod',
  'randomForest', 'rJava', 'R.matlab', 'R.methodsS3', 'ROCR', 'R.oo',
  'R.utils', 'TTR', 'vegan', 'zoo', 'gdata', 'gplots', 'gtools', 'class',
  'foreign', 'MASS', 'nlme', 'nnet', 'spatial'
Update all/some/none? [a/s/n]: n
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘mzR’ had non-zero exit status

------------------------------------------------
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] BiocInstaller_1.19.14

loaded via a namespace (and not attached):
[1] tools_3.2.2

**Comment by bharathbhushandamodaran** [comment]
Kindly please see the following the information.

 biocLite("mzR")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.19.14), R 3.2.2 (2015-08-14).
Installing package(s) ‘mzR’
essai de l'URL '
https://bioconductor.org/packages/3.2/bioc/src/contrib/mzR_2.3.2.tar.gz'
Content type 'application/x-gzip' length 14656653 bytes (14.0 MB)
==================================================
downloaded 14.0 MB

* installing *source* package ‘mzR’ ...
** libs
rm -f cramp.o ramp_base64.o ramp.o RcppRamp.o RcppRampModule.o rnetCDF.o
RcppPwiz.o RcppPwizModule.o RcppIdent.o RcppIdentModule.o
./boost/system/src/error_code.o ./boost/regex/src/posix_api.o
./boost/regex/src/fileiter.o ./boost/regex/src/regex_raw_buffer.o
./boost/regex/src/cregex.o ./boost/regex/src/regex_debug.o
./boost/regex/src/instances.o ./boost/regex/src/icu.o
./boost/regex/src/usinstances.o ./boost/regex/src/regex.o
./boost/regex/src/wide_posix_api.o
./boost/regex/src/regex_traits_defaults.o ./boost/regex/src/winstances.o
./boost/regex/src/wc_regex_traits.o ./boost/regex/src/c_regex_traits.o
./boost/regex/src/cpp_regex_traits.o ./boost/regex/src/static_mutex.o
./boost/regex/src/w32_regex_traits.o ./boost/iostreams/src/zlib.o
./boost/iostreams/src/file_descriptor.o ./boost/thread/src/pthread/once.o
./boost/thread/src/pthread/thread.o ./boost/filesystem/src/operations.o
./boost/filesystem/src/path.o ./boost/filesystem/src/utf8_codecvt_facet.o
./pwiz/data/msdata/Version.o ./pwiz/data/common/MemoryIndex.o
./pwiz/data/common/CVTranslator.o ./pwiz/data/common/cv.o
./pwiz/data/common/ParamTypes.o ./pwiz/data/common/BinaryIndexStream.o
./pwiz/data/common/diff_std.o ./pwiz/data/common/Unimod.o
./pwiz/data/msdata/SpectrumList_MGF.o
./pwiz/data/msdata/DefaultReaderList.o
./pwiz/data/msdata/ChromatogramList_mzML.o ./pwiz/data/msdata/examples.o
./pwiz/data/msdata/Serializer_mzML.o ./pwiz/data/msdata/Serializer_MSn.o
./pwiz/data/msdata/Reader.o ./pwiz/data/msdata/Serializer_MGF.o
./pwiz/data/msdata/Serializer_mzXML.o
./pwiz/data/msdata/SpectrumList_mzML.o
./pwiz/data/msdata/SpectrumList_MSn.o
./pwiz/data/msdata/BinaryDataEncoder.o ./pwiz/data/msdata/Diff.o
./pwiz/data/msdata/MSData.o ./pwiz/data/msdata/References.o
./pwiz/data/msdata/SpectrumList_mzXML.o ./pwiz/data/msdata/IO.o
./pwiz/data/msdata/SpectrumList_BTDX.o ./pwiz/data/msdata/SpectrumInfo.o
./pwiz/data/msdata/RAMPAdapter.o ./pwiz/data/msdata/LegacyAdapter.o
./pwiz/data/msdata/SpectrumIterator.o ./pwiz/data/msdata/MSDataFile.o
./pwiz/data/msdata/MSNumpress.o ./pwiz/data/msdata/SpectrumListCache.o
./pwiz/data/msdata/Index_mzML.o ./pwiz/data/identdata/IdentDataFile.o
./pwiz/data/identdata/IdentData.o ./pwiz/data/identdata/DefaultReaderList.o
./pwiz/data/identdata/Reader.o ./pwiz/data/identdata/Serializer_protXML.o
./pwiz/data/identdata/Serializer_pepXML.o
./pwiz/data/identdata/Serializer_mzid.o ./pwiz/data/identdata/IO.o
./pwiz/data/identdata/Version.o ./pwiz/data/identdata/References.o
./pwiz/data/proteome/Modification.o ./pwiz/data/proteome/Digestion.o
./pwiz/data/proteome/Peptide.o ./pwiz/data/proteome/AminoAcid.o
./pwiz/utility/minimxml/XMLWriter.o ./pwiz/utility/minimxml/SAXParser.o
./pwiz/utility/chemistry/Chemistry.o
./pwiz/utility/chemistry/ChemistryData.o
./pwiz/utility/chemistry/MZTolerance.o ./pwiz/utility/misc/IntegerSet.o
./pwiz/utility/misc/Base64.o ./pwiz/utility/misc/IterationListener.o
./pwiz/utility/misc/MSIHandler.o ./pwiz/utility/misc/Filesystem.o
./pwiz/utility/misc/TabReader.o
./pwiz/utility/misc/random_access_compressed_ifstream.o
./pwiz/utility/misc/SHA1.o ./pwiz/utility/misc/SHA1Calculator.o
./pwiz/utility/misc/sha1calc.o ./random_access_gzFile.o rampR.o R_init_mzR.o
find . -name \*~ -exec rm {} \;   ## from cleanup
find . -name \*.o -exec rm {} \;  ## from cleanup
find . -name "#*#" -exec rm {} \; ## from cleanup
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I.
-DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags
|| /bin/true`
 -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"
-I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"
  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
-D_FORTIFY_SOURCE=2 -g  -c cramp.cpp -o cramp.o
/bin/bash: nc-config : commande introuvable
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I.
-DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags
|| /bin/true`
 -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"
-I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"
  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
-D_FORTIFY_SOURCE=2 -g  -c ramp_base64.cpp -o ramp_base64.o
/bin/bash: nc-config : commande introuvable
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I.
-DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags
|| /bin/true`
 -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"
-I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"
  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
-D_FORTIFY_SOURCE=2 -g  -c ramp.cpp -o ramp.o
/bin/bash: nc-config : commande introuvable
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I.
-DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags
|| /bin/true`
 -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"
-I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"
  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
-D_FORTIFY_SOURCE=2 -g  -c RcppRamp.cpp -o RcppRamp.o
/bin/bash: nc-config : commande introuvable
g++ -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I.
-DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags
|| /bin/true`
 -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"
-I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"
  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
-D_FORTIFY_SOURCE=2 -g  -c RcppRampModule.cpp -o RcppRampModule.o
/bin/bash: nc-config : commande introuvable
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -D_LARGEFILE_SOURCE
-I./boost_aux/ -I. -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost
`nc-config --cflags || /bin/true`
 -I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"
-I"/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/zlibbioc/include"
  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
-D_FORTIFY_SOURCE=2 -g  -c rnetCDF.c -o rnetCDF.o
/bin/bash: nc-config : commande introuvable
In file included from rnetCDF.c:2:0:
rnetCDF.h:1:20: fatal error: netcdf.h: Aucun fichier ou dossier de ce type
 #include <netcdf.h>
                    ^
compilation terminated.
/usr/lib/R/etc/Makeconf:134: recipe for target 'rnetCDF.o' failed
make: *** [rnetCDF.o] Error 1
ERROR: compilation failed for package ‘mzR’
* removing ‘/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/mzR’

The downloaded source packages are in
        ‘/tmp/Rtmpoe9gSB/downloaded_packages’
Old packages: 'abind', 'caTools', 'clue', 'deSolve', 'gdata', 'gplots',
  'gtools', 'kernlab', 'mvtnorm', 'permute', 'psych', 'quantmod',
  'randomForest', 'rJava', 'R.matlab', 'R.methodsS3', 'ROCR', 'R.oo',
  'R.utils', 'TTR', 'vegan', 'zoo', 'gdata', 'gplots', 'gtools', 'class',
  'foreign', 'MASS', 'nlme', 'nnet', 'spatial'
Update all/some/none? [a/s/n]: n
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘mzR’ had non-zero exit status

------------------------------------------------------------------------------------------------------------------------------------------
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] BiocInstaller_1.19.14

loaded via a namespace (and not attached):
[1] tools_3.2.2
>
ectrumList_mzML.o ./pwiz/data/msdata/SpectrumList_MSn.o
./pwiz/data/msdata/Bina



Thanks

Bharath Bhushan D
Post Doctoral Fellow
IRISA-UBS, Vannes
France

**Comment by sgibb** [comment]
I assume you are missing the NetCDF libraries. Try install the corresponding development files via `su -c "apt-get install libnetcdf-dev"` or `sudo apt-get install libnetcdf-dev`

**Comment by bharathbhushandamodaran** [comment]
Thank you for your information. After the installation of NetCDF libraries, I am able to install MSnbase package..

However, I have problem in installing "pRoloc" Package. Please see the below information for your reference

---------------------------------------------------
 biocLite("pRoloc")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.19.14), R 3.2.2 (2015-08-14).
Installing package(s) ‘pRoloc’
also installing the dependencies ‘rgl’, ‘RCurl’, ‘MLInterfaces’, ‘biomaRt’

essai de l'URL 'https://cran.rstudio.com/src/contrib/rgl_0.95.1337.tar.gz'
Content type 'application/x-gzip' length 2189241 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

essai de l'URL 'https://cran.rstudio.com/src/contrib/RCurl_1.95-4.7.tar.gz'
Content type 'application/x-gzip' length 916897 bytes (895 KB)
==================================================
downloaded 895 KB

essai de l'URL 'https://bioconductor.org/packages/3.2/bioc/src/contrib/MLInterfaces_1.49.13.tar.gz'
Content type 'application/x-gzip' length 1064898 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

essai de l'URL 'https://bioconductor.org/packages/3.2/bioc/src/contrib/biomaRt_2.25.3.tar.gz'
Content type 'application/x-gzip' length 278237 bytes (271 KB)
==================================================
downloaded 271 KB

essai de l'URL 'https://bioconductor.org/packages/3.2/bioc/src/contrib/pRoloc_1.9.6.tar.gz'
Content type 'application/x-gzip' length 4861660 bytes (4.6 MB)
==================================================
downloaded 4.6 MB

* installing *source* package ‘rgl’ ...
** package ‘rgl’ correctement décompressé et sommes MD5 vérifiées
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for gcc... (cached) gcc -std=gnu99
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc -std=gnu99 accepts -g... (cached) yes
checking for gcc -std=gnu99 option to accept ISO C89... (cached) none needed
checking whether __attribute__((visibility())) is supported... yes
checking whether gcc -std=gnu99 accepts -fvisibility... yes
checking whether  accepts -fvisibility... no
checking for libpng-config... yes
configure: using libpng-config
configure: using libpng dynamic linkage
checking for X... libraries , headers
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking GL/glu.h usability... no
checking GL/glu.h presence... no
checking for GL/glu.h... no
configure: error: missing required header GL/glu.h
ERROR: configuration failed for package ‘rgl’
* removing ‘/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/rgl’
* installing *source* package ‘RCurl’ ...
** package ‘RCurl’ correctement décompressé et sommes MD5 vérifiées
checking for curl-config... no
Cannot find curl-config
ERROR: configuration failed for package ‘RCurl’
* removing ‘/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/RCurl’
ERROR: dependency ‘rgl’ is not available for package ‘MLInterfaces’
* removing ‘/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/MLInterfaces’
ERROR: dependency ‘RCurl’ is not available for package ‘biomaRt’
* removing ‘/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/biomaRt’
ERROR: dependencies ‘MLInterfaces’, ‘biomaRt’ are not available for package ‘pRoloc’
* removing ‘/share/home/damodara/R/x86_64-pc-linux-gnu-library/3.2/pRoloc’

The downloaded source packages are in
        ‘/tmp/RtmpWJ70cf/downloaded_packages’
Old packages: 'abind', 'caTools', 'clue', 'deSolve', 'gdata', 'gplots',
  'gtools', 'kernlab', 'mvtnorm', 'permute', 'psych', 'quantmod',
  'randomForest', 'rJava', 'R.matlab', 'R.methodsS3', 'ROCR', 'R.oo',
  'R.utils', 'TTR', 'vegan', 'zoo', 'gdata', 'gplots', 'gtools', 'class',
  'foreign', 'MASS', 'nlme', 'nnet', 'spatial'
Update all/some/none? [a/s/n]: n
Warning messages:
1: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘rgl’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘RCurl’ had non-zero exit status
3: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘MLInterfaces’ had non-zero exit status
4: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘biomaRt’ had non-zero exit status
5: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘pRoloc’ had non-zero exit status

-----------------------------------------------------------------------------------------
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] BiocInstaller_1.19.14 MSnbase_1.17.14       ProtGenerics_1.1.0
[4] BiocParallel_1.3.52   mzR_2.3.2             Rcpp_0.12.1
[7] Biobase_2.29.1        BiocGenerics_0.15.6

loaded via a namespace (and not attached):
 [1] futile.logger_1.4.1   plyr_1.8.3            iterators_1.0.7
 [4] futile.options_1.0.0  tools_3.2.2           zlibbioc_1.15.0
 [7] MALDIquant_1.13       digest_0.6.8          preprocessCore_1.31.0
[10] gtable_0.1.2          lattice_0.20-33       foreach_1.4.2
[13] proto_0.3-10          stringr_1.0.0         S4Vectors_0.7.18
[16] IRanges_2.3.21        stats4_3.2.2          grid_3.2.2
[19] impute_1.43.0         XML_3.98-1.3          limma_3.25.16
[22] ggplot2_1.0.1         reshape2_1.4.1        lambda.r_1.1.7
[25] magrittr_1.5          scales_0.3.0          pcaMethods_1.59.0
[28] codetools_0.2-14      MASS_7.3-44           mzID_1.7.1
[31] colorspace_1.2-6      stringi_0.5-5         affy_1.47.1
[34] munsell_0.4.2         doParallel_1.0.8      vsn_3.37.3
[37] affyio_1.39.0
>
*** installing help indices
*

**Comment by lgatto** [comment]
Similar problem as previously, but for another external dependency. To address `configure: error: missing required header GL/glu.h`, I would look for `libglu1-mesa-dev`. You will also need `libcurl` to be able to install `RCurl`.

**Comment by bharathbhushandamodaran** [comment]
Thank you very much for your information. Finally it works now

**Comment by lgatto** [comment]
A few clarifications about the errors your observed.

The first dependency, `libnetcdf`, was required for the `mzR` package. `mzR` is a rather complex package, that provides access to various mass spectrometry data formats such as `mzXML`, `mzML`, `mzIdentML`, ... and `netCDF`. Being able to access data in these relies on (sometimes complex) external software. In your case, that software was a low-level library to parse `netCDF` files.

`libcurl` is used to send and receive message over the internet. The package that relies on it is `biomaRt`, a fantastic resource that allows us to query a great many biological repositories, called Biomarts.
