### ISSUE TITLE
writeMgfData doesn't work for MS1

### ISSUE THREAD

**Issue by meowcat** [lgatto/MSnbase#73]
Hi,

These lines in writeMgfContent make writeMgfData fail on MS1 spectra:
```R
  .cat("\nRTINSECONDS=", rtime(sp), "\nPEPMASS=", precursorMz(sp))

  if (length(precursorCharge(sp)) && !is.na(precursorCharge(sp))) {
    .cat("\nCHARGE=", precursorCharge(sp), "+")
  }
```

```
d> writeMgfData(cpds.tot[[1]]@parent)
Error in precursorMz(sp) : No precursor MZ value for MS1 spectra.
```

Admittedly my Spectrum1 objects are not created by MSnbase directly but by RMassBank, but I think this should still work...

**Comment by lgatto** [comment]
@meowcat - thanks for the report. Should be fixed in version 1.19.7 and available via `biocLite("MSnbase")` within 24 hours or immediately from github with `biocLite("lgatto/MSnbase")`.
