### ISSUE TITLE
the generic for "trimws" hides base::trimws

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#75]
Since MSnbase 1.19.9 the import of Spectrum.xml files in synapter isn't working anymore. That happens because MSnbase maskes `base::trimws` by defining a new generic.

To reproduce:
```r
Rdevel> R.version$version.str
[1] "R Under development (unstable) (2015-11-08 r69614)"
Rdevel> trimws(" xx ")
[1] "xx"
Rdevel> library("MSnbase"); packageVersion("MSnbase")
# ...
The following object is masked from ‘package:base’:

    trimws

[1] ‘1.19.9’
Rdevel> trimws(" xx ")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘trimws’ for signature ‘"character"’
```

IMHO there are two possible solutions:

- 1. Defining a generic that uses all arguments of `trimws`:

```r
# AllGenerics.R
setGeneric("trimws", function(x, which = c("both", "left", "right"))standardGeneric("trimws"))
# utils.R
setMethod("trimws", c("data.frame", "character"), function(x, which) { ... })
```

- 2. Or creating a new `trimws` that in contrast to the `base::trimws` accepts the `...` argument (as `BiocGenerics` does it for `is.unsorted`: https://github.com/Bioconductor-mirror/BiocGenerics/blob/master/R/is.unsorted.R)

**Comment by lgatto** [comment]
Thanks - fixed in 3c07de73f5195ae393c4a35312c196af7a9aebf5
