### ISSUE TITLE
Why is there no polarity in Spectrum2 objects?

### ISSUE THREAD

**Issue by meowcat** [lgatto/MSnbase#76]
Hi,

the Spectrum2 objects have no @polarity slot (as opposed to Spectrum1 objects). Is there a specific reason for this, and would you consider adding one? For me they would be useful, otherwise I have to carry the information somewhere else for downstream processing (or I might add it myself in my RmbSpectrum2 subclass, see https://github.com/MassBank/RMassBank/blob/master/R/SpectrumClasses.R ...)

**Comment by lgatto** [comment]
I would certainly consider adding adding that slot, or accept a pull request.

**Comment by lgatto** [comment]
Will give it a look tonight or tomorrow morning.

**Comment by lgatto** [comment]
@meowcat  Please test the latest github version (commit 69cbf523b693516b325e15684a3cc75f1a83b80c or later) and let me know how it works. There is a `updateObject` method to update `MSnExp` and `Spectrum2` objects, in case you have serialised instances that are not valid any more. 

I will close this issue, but please re-open it in case you run into issues.

**Comment by meowcat** [comment]
Thanks! Looks great so far, including the upgrade path.
