### ISSUE TITLE
bin_Spectrum bug

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#77]
The latest commit 77515b928542adc12a1b6fb8cced85f3f3ea2cd0 and ecaaa324505b17ee8c4855806f7e37f14f1b27b8 fix a bug report by Weibo Xie by email and add a unit test. 

@sgibb - could you check if you are fine with this before I commit to Bioc.

**Comment by sgibb** [comment]
seems to be OK, great catch
