### ISSUE TITLE
rt() does not work since there is a rt() in stats package

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/MSnbase#79]
Tried to use rt on a Spectrum1 object get the following error:

Error in rt(xx[[i]]) : argument "df" is missing, with no default

I imagine it is because rt() is present in stats package with df as argument.

Tried to use MSnbase::rt() syntax get an error that 

Error: 'rt' is not an exported object from 'namespace:MSnbase'

**Comment by lgatto** [comment]
What about `rtime`?

**Comment by pavel-shliaha** [comment]
Thanks! Help needs to be updated for ?Spectrum1

**Comment by lgatto** [comment]
Could  you point me where? I can't see anything wring in `?Spectrum1`.
