### ISSUE TITLE
combine samples in an MSnSet

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/MSnbase#81]
Working with synapter now I need to use correction of saturation on a combined MSnSet (after several synapter runs have been converted to MSnSet and combined into a single MSnSet).

The next step after saturation correction is to merge several replicas, but averageMSnSet works with a list of MSnSets.

Could you please modify averageMSnSet so that it takes an argument of the numbers of samples (i.e. numbers of columns in exprs(MSnSet), e.g. 1:5), so it can work with an MSnSet that has been combined?

**Comment by sgibb** [comment]
We could "misuse" `utils.applyColumnwiseByGroup` here, e.g.:

```r
data(msnset)
head(exprs(msnset))
#     iTRAQ4.114 iTRAQ4.115 iTRAQ4.116 iTRAQ4.117
# X1   1347.6158  2247.3097  3927.6931  7661.1463
# X10   739.9861   799.3501   712.5983   940.6793
# X11 27638.3582 33394.0252 32104.2879 26628.7278
# X12 31892.8928 33634.6980 37674.7272 37227.7119
# X13 26143.7542 29677.4781 29089.0593 27902.5608
# X14  6448.0829  6234.1957  6902.8903  6437.2303
groupBy <- c(1, 1, 2, 2)
e <- t(MSnbase:::utils.applyColumnwiseByGroup(t(exprs(msnset)), 
       groupBy=groupBy, FUN=colMeans))
head(e)
#              1          2
# X1   1797.4628  5794.4197
# X10   769.6681   826.6388
# X11 30516.1917 29366.5078
# X12 32763.7954 37451.2196
# X13 27910.6161 28495.8100
# X14  6341.1393  6670.0603
```

How to combine (no equal) featureData?

**Comment by lgatto** [comment]
Could `split`/`unsplit` help in converting `MSnSet` to/from `MSnSetList` instances to do what you need?
