### ISSUE TITLE
Error catching in utils.mergeSpectraAndIdentificationData

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#83]
I am systematically writing unit test and did (and then reverted) the following [modification](https://github.com/lgatto/MSnbase/commit/6c173ffbf3e54bd33edc2e50502abd7c4464b9fd) in the error catching at the beginning of `utils.mergeSpectraAndIdentificationData`. 

@sgibb - Could you clarify if you want at least one `fcol`/`icol` in `colnames(featureData)`/`colnames(id)` (rather than all, as I thought) - if so, I would suggest to change the error message to 
```r
stop("None of the column(s) ", sQuote(fcol), " are in the feature data.frame!")
```

**Comment by sgibb** [comment]
@lgatto this was indeed a bug. All `fcol`/`icol` have to be present in `colnames(featureData)`/`colnames(id)`. So your modification was correct. I rereverted it: https://github.com/lgatto/MSnbase/commit/2ee8a83cc923ee9651bd780f6018b32238d4f50f
