### ISSUE TITLE
Wondering about `removePeaks` and `peaksCount`

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#88]
I was wondering about the `removePeaks` method (on spectra); is it on purpose that the `peaksCount` in the spectra is not updated? I expected that, after changing a peak's intensity values below a threshold to `0` that these peaks (M/Z - intensity duples) are also removed from the spectrum and that this is then also reflected by a change to the value in the `peaksCount` slot. 

cheers, jo

**Comment by lgatto** [comment]
The name of `removePeaks` is misleading - it does not remove the (mz, intensity) pair, but rather just sets the intensity to zero. Hence, the number of peaks is unchanged. To remove the zero-intensity peaks, use `clean`. 

This is mentioned in the `removePeaks` man:
>  Note that the number of peaks is not changed; the peaks below the threshold are set to 0 and the object is not cleanded out (see ‘clean’). An illustrative example is shown below.

**Comment by jotsetung** [comment]
OK, thanks for the explanation; was just confused by the name.
