### ISSUE TITLE
Empty phenoData for new MSnExp objects

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#89]
If no phenoData is provided to the `readMSData` function than it creates a one-row `AnnotatedDataFrame`. I would suggest to change this to create a phenoData that has as many rows as there are data files, i.e. change the line
`.pd <- data.frame(sampleNames = 1)` in `readMSData` to `.pd <- data.frame(sampleNames = basename(files))`.

cheers, jo

**Comment by lgatto** [comment]
Yes, that's a good suggestion, thanks.

**Comment by lgatto** [comment]
Have you implemented this in `MSnbase2` and/or ported to `master`?

**Comment by jotsetung** [comment]
I've implemented it in MSnbase2. Actually realized that it might be even better to set the `rownames` of the `data.frame` to `basename(files)`. That way `sampleNames` would return the file names. I'll eventually add that to MSnbase2; didn't want to mess with the master repo.

**Comment by jotsetung** [comment]
I've now added the above mentioned little modification to the MSnbase2 branch.
