### ISSUE TITLE
OnDiskMSnExp class implemented

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#90]
Hi,
the `OnDiskMSnExp` class is now implemented along with all methods inherited from the `pSet` class. There are still some from the `MSnExp` class that should still be implemented, mostly for performance reasons; otherwise all should work fine.
Eventually you might have a look at it so we can discuss and eventually improve. I've added a section to the MSnbase-development.Rnw vignette describing the object and its principal functionality.

cheers, jo

**Comment by lgatto** [comment]
Fantastic. Let me do have a look at it beginning of next week. Cheers!
