### ISSUE TITLE
Check envrionments and bindings are locked

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#92]
- Check that all assay data environments and their bindings are locked
- Backport binding locking in MSnExp normalisation in `MSnbase2` branch

**Comment by jotsetung** [comment]
I'll always merging changes from master to `MSnbase2`, so no need to edit there. Also, the `OnDiskMSnExp` does not use the `assayData` slot (all related data is fetched on demand), so there shouldn't be any issue with that.

**Comment by lgatto** [comment]
I meant to review all the legacy code (not specifically what you added), to make sure that there are no other cases.
