### ISSUE TITLE
open/close MS file handle

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#97]
@jotsetung - quick question regarding the state of the raw file connection. Is it meant to be closed after creation of the `OnDiskMSnExp` and subsequently opened/closed, or does it stay opened for the duration of the session?

**Comment by lgatto** [comment]
Looking at `.applyFun2SpectraOfFile`, the file is opened and closed on exit. So I conclude that the raw data file handler is closed. Will amend `readMSData2` accordingly.

**Comment by jotsetung** [comment]
Apparently I was to slow to answer (well, was in the plane): yes, handles are closed. I think it's better to use file names and open/close connections to them on demand; filehandles could get problematic when it comes to save/load `OnDiskMSnExp` objects.

**Comment by lgatto** [comment]
Thanks for the clarification.
