### ISSUE TITLE
On the fly access for MS2 spectra

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#99]
@jotsetung - could you, when/if you have time, implement on the fly access to MS > 1 spectra? I will try do get it done at some point, but you might have time before me.

**Comment by jotsetung** [comment]
Yes, no prob. Should we go ahead and replace the `MSnExp` with the `OnDiskMSnExp` class at the same time, i.e. keep everything by default on disk?

**Comment by lgatto** [comment]
I have done a bit of work on `readMSData2` that reads different levels. It's not only about on disk or in memory, but also whether to support multiple levels in one experiment. Currently, I would favour yes. So let's continue developing on disk in parallel for now.

**Comment by lgatto** [comment]
See also related #103 issue.

**Comment by jotsetung** [comment]
OK, so let's keep the two objects separate for now; do you have a test file that contains both, MS 1 and 2 levels I could use for the unit tests? or is there one in the msdata package?

**Comment by lgatto** [comment]
I will add such a file in `msdata`.

**Comment by lgatto** [comment]
I have just added a test data containing MS1 and MS2 spectra in `msdata` (version `0.12.0`). 

```r
> msdata::proteomics(full.names = TRUE)
[1] "/home/lg390/R/x86_64-pc-linux-gnu-library/3.3rel/msdata/proteomics/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz"
```

**Comment by lgatto** [comment]
C-level constructor committed in abfe7c59a436cf7351f8b9643224569cdf67e856
